from __future__ import annotations

from song_agent.capabilities.model import CapabilitySpec, RuntimeVerificationSpec


def _program(
    capability_id: str,
    component_type: str,
    module: str,
    function: str,
    package_type: str,
    verification_package_type: str,
    *,
    defaults: tuple[tuple[str, object], ...],
    proofs: tuple[tuple[str, str], ...] = (),
    required: tuple[str, ...] = (),
    aliases: tuple[str, ...] = (),
) -> CapabilitySpec:
    return CapabilitySpec(
        capability_id=capability_id,
        component_type=component_type,
        bounded_context="program",
        application_service=f"{capability_id}.verify",
        runtime=RuntimeVerificationSpec(
            module=module,
            function=function,
            package_type=package_type,
            verification_package_type=verification_package_type,
            defaults=defaults,
            proof_arguments=proofs,
            required_proofs=required,
        ),
        gate_policies=("program.handoff", "program.continuity", "program.receiver_acceptance", "ga.standard", "ga.lts"),
        cli_commands=("unified-release-program",),
        api_routes=("/api/unified-release-programs",),
        web_panel="Program",
        release_checks=("v134.program_vertical_slice_smoke",),
        compatibility_aliases=aliases,
    )


PROGRAM_CAPABILITIES = (
    _program(
        "program.operations",
        "unified_release_program_operations",
        "song_agent.domains.program.unified_release_program_operations_verifier",
        "verify_unified_release_program_operations_package",
        "musicforge_unified_release_program_operations_archive",
        "musicforge_unified_release_program_operations_archive_verification",
        defaults=(("strict", True), ("require_current", True), ("require_signed_program", True)),
        proofs=(
            ("program_package", "program_zip_path"),
            ("program_verification_report", "program_verification_report_path"),
            ("program_signoff_binding", "program_signoff_binding_path"),
            ("external_evidence_manifest", "external_evidence_manifest_path"),
        ),
        required=("program_package", "program_verification_report", "program_signoff_binding", "external_evidence_manifest"),
    ),
    _program(
        "program.board",
        "unified_release_program",
        "song_agent.domains.program.unified_release_program_verifier",
        "verify_unified_release_program_package",
        "musicforge_unified_release_program",
        "musicforge_unified_release_program_verification",
        defaults=(("strict", True), ("require_current", True), ("require_signed", True)),
        proofs=(("external_evidence_manifest", "external_evidence_manifest_path"), ("signoff_binding", "program_signoff_binding_path")),
        required=("external_evidence_manifest", "signoff_binding"),
    ),
    _program(
        "program.handoff",
        "unified_release_program_handoff",
        "song_agent.domains.program.unified_release_program_handoff_verifier",
        "verify_unified_release_program_handoff_package",
        "musicforge_unified_release_program_handoff_archive",
        "musicforge_unified_release_program_handoff_verification",
        defaults=(("strict", True), ("require_current", True), ("require_accepted", True), ("require_signed", True)),
        proofs=(("external_evidence_manifest", "external_evidence_manifest_path"), ("signoff_binding", "handoff_signoff_binding_path")),
        required=("external_evidence_manifest", "signoff_binding"),
    ),
    _program(
        "program.vault",
        "unified_release_program_vault",
        "song_agent.domains.program.unified_release_program_vault_verifier",
        "verify_unified_release_program_vault_package",
        "musicforge_unified_release_program_evidence_vault",
        "musicforge_unified_release_program_evidence_vault_verification",
        defaults=(("strict", True), ("deep", True), ("require_anchor", True)),
        proofs=(("anchor", "vault_anchor_path"),),
        required=("anchor",),
    ),
    _program(
        "program.vault_operations",
        "unified_release_program_vault_operations",
        "song_agent.domains.program.unified_release_program_vault_operations_verifier",
        "verify_unified_release_program_vault_operations_package",
        "musicforge_unified_release_program_vault_operations_archive",
        "musicforge_unified_release_program_vault_operations_verification",
        defaults=(("strict", True), ("deep", True), ("require_signed", True), ("require_current_vault", True)),
        proofs=(("signoff_binding", "signoff_binding_path"),),
        required=("signoff_binding",),
    ),
    _program(
        "program.continuity",
        "unified_release_program_continuity",
        "song_agent.domains.program.unified_release_program_continuity_verifier",
        "verify_unified_release_program_continuity_package",
        "musicforge_unified_release_program_continuity_archive",
        "musicforge_unified_release_program_continuity_verification",
        defaults=(("strict", True), ("deep_restore", True), ("require_signed", True), ("require_current_vault_operations", True)),
        proofs=(
            ("signoff_binding", "signoff_binding_path"),
            ("vault_operations_package", "vault_operations_archive_path"),
            ("vault_operations_verification_report", "vault_operations_verification_report_path"),
            ("vault_operations_signoff_binding", "vault_operations_signoff_binding_path"),
        ),
        required=("signoff_binding", "vault_operations_package", "vault_operations_verification_report", "vault_operations_signoff_binding"),
    ),
    _program(
        "program.continuity_kit",
        "unified_release_program_continuity_kit",
        "song_agent.domains.program.unified_release_program_continuity_distribution_verifier",
        "verify_unified_release_program_continuity_distribution_package",
        "musicforge_unified_release_program_continuity_distribution_kit",
        "musicforge_unified_release_program_continuity_distribution_verification",
        defaults=(("strict", True), ("deep", True)),
    ),
    _program(
        "program.continuity_acceptance",
        "unified_release_program_continuity_acceptance",
        "song_agent.domains.program.unified_release_program_continuity_acceptance_verifier",
        "verify_unified_release_program_continuity_acceptance_package",
        "musicforge_unified_release_program_continuity_acceptance_archive",
        "musicforge_unified_release_program_continuity_acceptance_verification",
        defaults=(("strict", True), ("require_current_kit", True), ("require_signed", True), ("require_quorum", True)),
        proofs=(
            ("continuity_kit", "continuity_kit_path"),
            ("continuity_kit_verification_report", "continuity_kit_verification_report_path"),
            ("signoff_binding", "signoff_binding_path"),
        ),
        required=("continuity_kit", "continuity_kit_verification_report", "signoff_binding"),
    ),
    _program(
        "program.continuity_command_center",
        "unified_release_program_continuity_command_center",
        "song_agent.domains.program.unified_release_program_continuity_command_center_verifier",
        "verify_unified_release_program_continuity_command_center_package",
        "musicforge_unified_release_program_continuity_command_center",
        "musicforge_unified_release_program_continuity_command_center_verification",
        defaults=(("strict", True), ("deep", True), ("require_ready", True)),
        proofs=(("external_evidence_manifest", "evidence_manifest_path"),),
        required=("external_evidence_manifest",),
    ),
    _program(
        "program.continuity_acceptance_change",
        "unified_release_program_continuity_acceptance_change",
        "song_agent.domains.program.unified_release_program_continuity_acceptance_change_verifier",
        "verify_unified_release_program_continuity_acceptance_change_package",
        "musicforge_unified_release_program_continuity_acceptance_change_control_archive",
        "musicforge_unified_release_program_continuity_acceptance_change_control_verification",
        defaults=(("strict", True), ("require_current_acceptance", True)),
        proofs=(
            ("acceptance_package", "acceptance_archive_path"),
            ("acceptance_verification_report", "acceptance_verification_report_path"),
            ("acceptance_signoff_binding", "acceptance_signoff_binding_path"),
        ),
        required=("acceptance_package", "acceptance_verification_report", "acceptance_signoff_binding"),
    ),
    _program(
        "program.continuity_command_center_signoff",
        "unified_release_program_continuity_command_center_signoff",
        "song_agent.domains.program.unified_release_program_continuity_command_center_signoff_verifier",
        "verify_unified_release_program_continuity_command_center_signoff_package",
        "musicforge_unified_release_program_continuity_command_center_signoff_archive",
        "musicforge_unified_release_program_continuity_command_center_signoff_archive_verification",
        defaults=(("strict", True), ("require_signed", True)),
        proofs=(
            ("signoff_binding", "signoff_binding_path"),
            ("command_center_package", "command_center_zip_path"),
            ("command_center_verification_report", "command_center_verification_report_path"),
            ("external_evidence_manifest", "command_center_external_evidence_manifest_path"),
        ),
        required=("signoff_binding", "command_center_package", "command_center_verification_report", "external_evidence_manifest"),
    ),
    _program(
        "program.receiver_acceptance",
        "unified_release_program_receiver_acceptance",
        "song_agent.domains.program.unified_release_program_continuity_command_center_acceptance_verifier",
        "verify_unified_release_program_continuity_command_center_acceptance_package",
        "musicforge_unified_release_program_continuity_command_center_receiver_acceptance_archive",
        "musicforge_unified_release_program_continuity_command_center_receiver_acceptance_archive_verification",
        defaults=(("strict", True), ("require_signed", True)),
        proofs=(("signoff_binding", "signoff_binding_path"),),
        required=("signoff_binding",),
        aliases=("unified_release_program_continuity_command_center_acceptance",),
    ),
    _program(
        "program.receiver_acceptance_change",
        "unified_release_program_receiver_acceptance_change",
        "song_agent.domains.program.unified_release_program_continuity_command_center_acceptance_change_verifier",
        "verify_unified_release_program_continuity_command_center_acceptance_change_package",
        "musicforge_unified_release_program_continuity_command_center_acceptance_change_control_archive",
        "musicforge_unified_release_program_continuity_command_center_acceptance_change_control_verification",
        defaults=(("strict", True), ("require_current_acceptance", True), ("require_reset_proofs", True)),
        proofs=(
            ("acceptance_package", "acceptance_archive_path"),
            ("acceptance_verification_report", "acceptance_verification_report_path"),
            ("acceptance_signoff_binding", "acceptance_signoff_binding_path"),
            ("previous_acceptance_root", "previous_acceptance_root"),
        ),
        required=("acceptance_package", "acceptance_verification_report", "acceptance_signoff_binding", "previous_acceptance_root"),
        aliases=("unified_release_program_continuity_command_center_acceptance_change",),
    ),
)
