import './state.js';
import './panels/core.js';
import './panels/creation.js';
import './panels/quality.js';
import './panels/audio.js';
import './panels/delivery.js';
import './panels/trust.js';
import './panels/continuity.js';
import './panels/jobs.js';
import './panels/maintenance.js';
import './panels/program.js';
import './wiring-primary.js';
import './wiring-secondary.js';
export const studioPanels = globalThis.MusicForgePanels;
