from __future__ import annotations

from typing import Any


class CoreRouteContext:
    """Static inventory of members supplied by runtime composition."""

    _auth_required: Any
    _dispatch_portfolio_accepted_evidence: Any
    _dispatch_portfolio_acknowledgement: Any
    _dispatch_portfolio_attestation: Any
    _dispatch_portfolio_audit: Any
    _dispatch_portfolio_detail: Any
    _dispatch_portfolio_downloads: Any
    _dispatch_portfolio_final_actions: Any
    _dispatch_portfolio_final_board: Any
    _dispatch_portfolio_portal: Any
    _dispatch_portfolio_portal_review: Any
    _dispatch_portfolio_registry: Any
    _dispatch_portfolio_reviewer: Any
    _dispatch_portfolio_root: Any
    _dispatch_portfolio_transparency: Any
    _dispatch_portfolio_vault: Any
    _dispatch_ucc_boards: Any
    _dispatch_ucc_core: Any
    _dispatch_ucc_drifts: Any
    _dispatch_ucc_evidence_detail: Any
    _dispatch_ucc_evidence_root: Any
    _dispatch_ucc_handoff: Any
    _dispatch_ucc_reviews: Any
    _dispatch_ucc_root: Any
    _expand_context_pack_payload: Any
    _handle_project_acceptance_analytics: Any
    _handle_project_acceptance_analytics_refresh: Any
    _handle_project_add_to_release: Any
    _handle_project_audition_reviews: Any
    _handle_project_candidate_artifact: Any
    _handle_project_candidate_group_apply: Any
    _handle_project_candidate_group_delete: Any
    _handle_project_candidate_group_detail: Any
    _handle_project_candidate_group_render: Any
    _handle_project_candidate_group_usage: Any
    _handle_project_candidate_groups_list: Any
    _handle_project_delivery_qa: Any
    _handle_project_delivery_signoff: Any
    _handle_project_edit: Any
    _handle_project_edit_candidates: Any
    _handle_project_edit_preview: Any
    _handle_project_edit_preview_apply: Any
    _handle_project_edit_preview_delete: Any
    _handle_project_edit_targets: Any
    _handle_project_editor_audition_marker_route: Any
    _handle_project_editor_audition_route: Any
    _handle_project_editor_auditions_root: Any
    _handle_project_editor_clip_draft: Any
    _handle_project_editor_clips: Any
    _handle_project_editor_draft: Any
    _handle_project_editor_multitrack_clip_draft: Any
    _handle_project_editor_preview_create: Any
    _handle_project_editor_preview_root: Any
    _handle_project_editor_preview_route: Any
    _handle_project_editor_state: Any
    _handle_project_editor_template_mapping: Any
    _handle_project_editor_view: Any
    _handle_project_evaluate: Any
    _handle_project_evaluate_all: Any
    _handle_project_final_export: Any
    _handle_project_final_export_zip: Any
    _handle_project_final_export_zip_download: Any
    _handle_project_mix_route: Any
    _handle_project_prompt_ab_create: Any
    _handle_project_prompt_ab_delete: Any
    _handle_project_prompt_ab_detail: Any
    _handle_project_prompt_ab_list: Any
    _handle_project_provider_usage: Any
    _handle_project_provider_usage_report: Any
    _handle_project_quality_gate: Any
    _handle_project_reference_link: Any
    _handle_project_references: Any
    _handle_project_release_targets: Any
    _handle_project_review_metrics: Any
    _handle_project_review_sprint_route: Any
    _handle_project_review_sprints_root: Any
    _handle_project_review_task_candidate_route: Any
    _handle_project_review_task_route: Any
    _handle_project_review_tasks_root: Any
    _handle_project_route_part_01: Any
    _handle_project_route_part_02: Any
    _handle_project_route_part_03: Any
    _handle_project_route_part_04: Any
    _handle_project_route_part_05: Any
    _handle_project_route_part_06: Any
    _handle_project_route_part_07: Any
    _handle_project_section_template_create: Any
    _handle_project_track_template_create: Any
    _handle_project_variation: Any
    _handle_project_version_audio_route: Any
    _is_authorized: Any
    _optional_json_body: Any
    _read_json_body: Any
    _send_error: Any
    _send_file: Any
    _send_html: Any
    _send_javascript: Any
    _send_json: Any
    _send_unauthorized: Any
    _set_final_version_with_gate: Any
    _specs: Any
    auth_config: Any
    end_headers: Any
    matches: Any
    path: Any
    project_store: Any
    route_registry: Any
    send_header: Any
    send_response: Any
    server: Any
    store: Any
    wfile: Any
