from __future__ import annotations

from typing import Any


class CreationRouteContext:
    """Static inventory of members supplied by runtime composition."""

    _apply_review_task_candidate: Any
    _content_length_within: Any
    _create_assets_from_plan: Any
    _create_project_candidate_group: Any
    _create_project_candidate_group_part_01: Any
    _create_project_candidate_group_part_02: Any
    _create_review_edit_job: Any
    _create_review_task_follow_up: Any
    _ensure_recommendation_context_refs_current: Any
    _evaluate_project_version: Any
    _expand_context_pack_payload: Any
    _generate_review_sprint_local_candidates: Any
    _generate_review_sprint_provider_candidates: Any
    _get_or_refresh_delivery_qa: Any
    _get_or_refresh_project_review_metrics: Any
    _get_or_refresh_sprint_closeout: Any
    _get_or_refresh_sprint_judge_summary: Any
    _get_or_refresh_sprint_metrics: Any
    _handle_audition_context_pack: Any
    _handle_batch_route_part_01: Any
    _handle_batch_route_part_02: Any
    _handle_job_route_part_01: Any
    _handle_job_route_part_02: Any
    _handle_job_route_part_03: Any
    _handle_project_candidate_group_apply_part_01: Any
    _handle_project_candidate_group_apply_part_02: Any
    _handle_project_edit_part_01: Any
    _handle_project_edit_part_02: Any
    _handle_project_editor_audition_next_action: Any
    _handle_project_editor_preview_apply: Any
    _handle_project_editor_preview_apply_part_01: Any
    _handle_project_editor_preview_apply_part_02: Any
    _handle_project_mix_route_part_01: Any
    _handle_project_mix_route_part_02: Any
    _handle_project_review_sprint_route_part_01: Any
    _handle_project_review_sprint_route_part_02: Any
    _handle_project_review_sprint_route_part_03: Any
    _handle_project_review_sprint_route_part_04: Any
    _handle_project_review_sprint_route_part_05: Any
    _handle_project_review_task_create: Any
    _handle_project_review_task_route_part_01: Any
    _handle_project_review_task_route_part_02: Any
    _handle_project_review_task_route_part_03: Any
    _handle_provider_review_edit_preview: Any
    _handle_reference_route_part_01: Any
    _handle_reference_route_part_02: Any
    _handle_reference_slice_route: Any
    _job_audio_artifact_stale_reasons: Any
    _merge_editor_patch_metadata: Any
    _optional_json_body: Any
    _project_candidate_group_or_conflict: Any
    _project_edit_parent: Any
    _read_json_body: Any
    _read_review_task_judge_report: Any
    _refresh_review_sprint_judge_reports: Any
    _refresh_review_sprint_recommendations: Any
    _refresh_review_sprint_state: Any
    _refresh_review_task_judge_report: Any
    _render_editor_preview_audio: Any
    _renderer_profile_from_payload: Any
    _review_edit_context: Any
    _review_sprint_ordered_task_ids: Any
    _review_sprint_parent_plan_hashes: Any
    _review_sprint_public_payload: Any
    _review_sprint_response: Any
    _rollback_prompt_ab_groups: Any
    _run_review_sprint_action_queue: Any
    _save_review_sprint_recommendation_context_pack: Any
    _send_error: Any
    _send_file: Any
    _send_json: Any
    _send_node_retry: Any
    _send_node_route: Any
    _send_nodes_list: Any
    _send_runtime_view: Any
    _send_stem_file: Any
    asset_store: Any
    audio_profile_store: Any
    batch_runner: Any
    batch_store: Any
    context_pack_store: Any
    edit_preset_store: Any
    editor_template_store: Any
    library_index_store: Any
    path: Any
    project_store: Any
    prompt_template_store: Any
    reference_store: Any
    server: Any
    store: Any
