from __future__ import annotations

from http import HTTPStatus
from typing import TYPE_CHECKING, Protocol

from song_agent.application.jobs.ports import BatchStorePort, JobRuntimePort
from song_agent.application.program.http_context import ProgramServicePort
from song_agent.platform.contracts.documents import JsonDocument


class _StudioDispatchRouteContextTyping(Protocol):
    """Typed members supplied by API route composition."""

    def _expand_context_pack_payload(self, payload: JsonDocument) -> JsonDocument: ...

    def _handle_acceptance_analytics_recommendation(self, method: str, report_id: str, recommendation_id: str) -> None: ...

    def _handle_acceptance_analytics_refresh(self, method: str, query_string: str) -> None: ...

    def _handle_acceptance_analytics_report(self, method: str, report_id: str) -> None: ...

    def _handle_acceptance_analytics_root(self, method: str, query_string: str) -> None: ...

    def _handle_acceptance_fix_plan_review_route(self, method: str, route: tuple[str, str]) -> None: ...

    def _handle_acceptance_fix_plan_reviews_root(self, method: str, query_string: str) -> None: ...

    def _handle_acceptance_fix_plan_route(self, method: str, route: tuple[str, str]) -> None: ...

    def _handle_acceptance_fix_plans_recommend(self, method: str) -> None: ...

    def _handle_acceptance_fix_plans_root(self, method: str, query_string: str) -> None: ...

    def _handle_acceptance_fix_sprint_route(self, method: str, route: tuple[str, list[str]]) -> None: ...

    def _handle_acceptance_fix_sprints_root(self, method: str, query_string: str) -> None: ...

    def _handle_acceptance_kb_entries(self, method: str, query_string: str) -> None: ...

    def _handle_acceptance_kb_entry_route(self, method: str, route: tuple[str, str]) -> None: ...

    def _handle_acceptance_kb_recommend(self, method: str) -> None: ...

    def _handle_acceptance_kb_refresh(self, method: str) -> None: ...

    def _handle_acceptance_kb_report(self, method: str, report_id: str) -> None: ...

    def _handle_acceptance_kb_root(self, method: str) -> None: ...

    def _handle_acceptance_kb_search(self, method: str, query_string: str) -> None: ...

    def _handle_acceptance_route(self, method: str, suite_id: str, tail: str) -> None: ...

    def _handle_acceptance_suites_root(self, method: str, query_string: str) -> None: ...

    def _handle_asset_extract_from_candidate(self, method: str) -> None: ...

    def _handle_asset_extract_from_job(self, method: str) -> None: ...

    def _handle_asset_extract_from_project_version(self, method: str) -> None: ...

    def _handle_asset_route(self, method: str, asset_id: str, tail: str) -> None: ...

    def _handle_assets_root(self, method: str, query_string: str) -> None: ...

    def _handle_audio_baselines_route(self, method: str, path: str) -> None: ...

    def _handle_audio_campaign_route(self, method: str, path: str) -> None: ...

    def _handle_audio_encoding_route(self, method: str, path: str) -> None: ...

    def _handle_audio_fix_sprint_route(self, method: str, path: str) -> None: ...

    def _handle_audio_lab_route(self, method: str, path: str) -> None: ...

    def _handle_audio_profiles_route(self, method: str, path: str) -> None: ...

    def _handle_audio_quality_actions_route(self, method: str, path: str) -> None: ...

    def _handle_audio_quality_observatories_route(self, method: str, path: str) -> None: ...

    def _handle_batch_route(self, method: str, batch_id: str, tail: str) -> None: ...

    def _handle_context_pack_route(self, method: str, pack_id: str, tail: str) -> None: ...

    def _handle_context_packs_root(self, method: str, query_string: str) -> None: ...

    def _handle_distribution_profile_route(self, method: str, profile_id: str) -> None: ...

    def _handle_distribution_profiles_root(self, method: str) -> None: ...

    def _handle_distribution_template_import(self, method: str, query: str) -> None: ...

    def _handle_distribution_template_route(self, method: str, route: tuple[str, str]) -> None: ...

    def _handle_distribution_templates_root(self, method: str) -> None: ...

    def _handle_docs_index_route(self, method: str) -> None: ...

    def _handle_edit_preset_route(self, method: str, preset_id: str, tail: str) -> None: ...

    def _handle_edit_presets_reset(self, method: str) -> None: ...

    def _handle_edit_presets_root(self, method: str) -> None: ...

    def _handle_editor_template_route(self, method: str, template_type: str, template_id: str, tail: str) -> None: ...

    def _handle_editor_templates_root(self, method: str, query_string: str) -> None: ...

    def _handle_ga_check_route(self, method: str) -> None: ...

    def _handle_ga_route(self, method: str) -> None: ...

    def _handle_job_route(self, method: str, job_id: str, tail: str) -> None: ...

    def _handle_library_index(self, method: str) -> None: ...

    def _handle_library_rebuild(self, method: str) -> None: ...

    def _handle_library_recommend(self, method: str) -> None: ...

    def _handle_library_search(self, method: str) -> None: ...

    def _handle_maintenance_route(self, method: str, path: str) -> None: ...

    def _handle_mastering_profiles_route(self, method: str, path: str) -> None: ...

    def _handle_planning_rule_governance_active(self, method: str) -> None: ...

    def _handle_planning_rule_governance_events(self, method: str, query_string: str) -> None: ...

    def _handle_planning_rule_governance_promotion_route(self, method: str, route: tuple[str, str]) -> None: ...

    def _handle_planning_rule_governance_promotions(self, method: str, query_string: str) -> None: ...

    def _handle_planning_rule_governance_rollback(self, method: str) -> None: ...

    def _handle_planning_rule_governance_version_route(self, method: str, route: tuple[str, str]) -> None: ...

    def _handle_planning_rule_governance_versions(self, method: str, query_string: str) -> None: ...

    def _handle_planning_rule_impact_latest(self, method: str, query_string: str) -> None: ...

    def _handle_planning_rule_impact_report_route(self, method: str, route: tuple[str, str]) -> None: ...

    def _handle_planning_rule_impact_reports(self, method: str, query_string: str) -> None: ...

    def _handle_planning_ruleset_route(self, method: str, route: tuple[str, str]) -> None: ...

    def _handle_planning_rulesets_root(self, method: str, query_string: str) -> None: ...

    def _handle_planning_simulation_route(self, method: str, route: tuple[str, str]) -> None: ...

    def _handle_planning_simulations_root(self, method: str, query_string: str) -> None: ...

    def _handle_project_route(self, method: str, project_id: str, tail: str, query_string: str) -> None: ...

    def _handle_projects_root(self, method: str, query_string: str) -> None: ...

    def _handle_prompt_template_route(self, method: str, template_id: str, tail: str) -> None: ...

    def _handle_prompt_templates_reset(self, method: str) -> None: ...

    def _handle_prompt_templates_root(self, method: str) -> None: ...

    def _handle_provider_reset(self, method: str) -> None: ...

    def _handle_provider_route(self, method: str) -> None: ...

    def _handle_provider_test(self, method: str) -> None: ...

    def _handle_provider_usage_root(self, method: str) -> None: ...

    def _handle_public_trust_centers(self, method: str, path: str) -> None: ...

    def _handle_reference_import(self, method: str) -> None: ...

    def _handle_reference_route(self, method: str, reference_id: str, tail: str) -> None: ...

    def _handle_references_root(self, method: str, query_string: str) -> None: ...

    def _handle_release_portfolio_audits(self, method: str, path: str) -> None: ...

    def _handle_release_portfolio_governance_queues(self, method: str, path: str) -> None: ...

    def _handle_release_route(self, method: str, release_id: str, tail: str, query_string: str) -> None: ...

    def _handle_releases_root(self, method: str, query_string: str) -> None: ...

    def _handle_renderer_reset(self, method: str) -> None: ...

    def _handle_renderer_route(self, method: str) -> None: ...

    def _handle_renderer_test(self, method: str) -> None: ...

    def _handle_trust_operations(self, method: str, path: str) -> None: ...

    def _handle_unified_command_center_release_trains_route(self, method: str, path: str) -> None: ...

    def _handle_unified_command_centers_route(self, method: str, path: str) -> None: ...

    def _read_json_body(self) -> JsonDocument: ...

    def _send_error(self, status: HTTPStatus, message: str) -> None: ...

    def _send_json(self, data: JsonDocument, status: HTTPStatus = HTTPStatus.OK) -> None: ...

    @property
    def batch_store(self) -> BatchStorePort: ...

    @property
    def program_application(self) -> ProgramServicePort: ...

    @property
    def store(self) -> JobRuntimePort: ...


if TYPE_CHECKING:
    StudioDispatchRouteContext = _StudioDispatchRouteContextTyping
else:

    class StudioDispatchRouteContext:
        """Runtime marker for Studio dispatch mixins."""
