from __future__ import annotations

from typing import Any


class StudioDispatchRouteContext:
    """Static inventory of members supplied by runtime composition."""

    _expand_context_pack_payload: Any
    _handle_acceptance_analytics_recommendation: Any
    _handle_acceptance_analytics_refresh: Any
    _handle_acceptance_analytics_report: Any
    _handle_acceptance_analytics_root: Any
    _handle_acceptance_fix_plan_review_route: Any
    _handle_acceptance_fix_plan_reviews_root: Any
    _handle_acceptance_fix_plan_route: Any
    _handle_acceptance_fix_plans_recommend: Any
    _handle_acceptance_fix_plans_root: Any
    _handle_acceptance_fix_sprint_route: Any
    _handle_acceptance_fix_sprints_root: Any
    _handle_acceptance_kb_entries: Any
    _handle_acceptance_kb_entry_route: Any
    _handle_acceptance_kb_recommend: Any
    _handle_acceptance_kb_refresh: Any
    _handle_acceptance_kb_report: Any
    _handle_acceptance_kb_root: Any
    _handle_acceptance_kb_search: Any
    _handle_acceptance_route: Any
    _handle_acceptance_suites_root: Any
    _handle_asset_extract_from_candidate: Any
    _handle_asset_extract_from_job: Any
    _handle_asset_extract_from_project_version: Any
    _handle_asset_route: Any
    _handle_assets_root: Any
    _handle_audio_baselines_route: Any
    _handle_audio_campaign_route: Any
    _handle_audio_encoding_route: Any
    _handle_audio_fix_sprint_route: Any
    _handle_audio_lab_route: Any
    _handle_audio_profiles_route: Any
    _handle_audio_quality_actions_route: Any
    _handle_audio_quality_observatories_route: Any
    _handle_batch_route: Any
    _handle_context_pack_route: Any
    _handle_context_packs_root: Any
    _handle_distribution_profile_route: Any
    _handle_distribution_profiles_root: Any
    _handle_distribution_template_import: Any
    _handle_distribution_template_route: Any
    _handle_distribution_templates_root: Any
    _handle_docs_index_route: Any
    _handle_edit_preset_route: Any
    _handle_edit_presets_reset: Any
    _handle_edit_presets_root: Any
    _handle_editor_template_route: Any
    _handle_editor_templates_root: Any
    _handle_ga_check_route: Any
    _handle_ga_route: Any
    _handle_job_route: Any
    _handle_library_index: Any
    _handle_library_rebuild: Any
    _handle_library_recommend: Any
    _handle_library_search: Any
    _handle_maintenance_route: Any
    _handle_mastering_profiles_route: Any
    _handle_planning_rule_governance_active: Any
    _handle_planning_rule_governance_events: Any
    _handle_planning_rule_governance_promotion_route: Any
    _handle_planning_rule_governance_promotions: Any
    _handle_planning_rule_governance_rollback: Any
    _handle_planning_rule_governance_version_route: Any
    _handle_planning_rule_governance_versions: Any
    _handle_planning_rule_impact_latest: Any
    _handle_planning_rule_impact_report_route: Any
    _handle_planning_rule_impact_reports: Any
    _handle_planning_ruleset_route: Any
    _handle_planning_rulesets_root: Any
    _handle_planning_simulation_route: Any
    _handle_planning_simulations_root: Any
    _handle_project_route: Any
    _handle_projects_root: Any
    _handle_prompt_template_route: Any
    _handle_prompt_templates_reset: Any
    _handle_prompt_templates_root: Any
    _handle_provider_reset: Any
    _handle_provider_route: Any
    _handle_provider_test: Any
    _handle_provider_usage_root: Any
    _handle_public_trust_centers: Any
    _handle_reference_import: Any
    _handle_reference_route: Any
    _handle_references_root: Any
    _handle_release_portfolio_audits: Any
    _handle_release_portfolio_governance_queues: Any
    _handle_release_route: Any
    _handle_releases_root: Any
    _handle_renderer_reset: Any
    _handle_renderer_route: Any
    _handle_renderer_test: Any
    _handle_trust_operations: Any
    _handle_unified_command_center_release_trains_route: Any
    _handle_unified_command_centers_route: Any
    _read_json_body: Any
    _send_error: Any
    _send_json: Any
    batch_store: Any
    store: Any
