from __future__ import annotations

from typing import Any as _InferenceType


from . import dependencies as _commands_quality_parts_dependencies
AcceptanceAnalyticsStore, AcceptanceFixPlanReviewStore, AcceptanceFixPlanningStore, AcceptanceFixSprintStore, AcceptanceKnowledgeBaseStore, AcceptanceStore, AnalyticsScope, Any, AudioCampaignGovernanceStore, AudioCampaignPlannerStore, AudioCampaignRemediationStore, AudioCampaignStore, AudioEncodingProfileStore, AudioEncodingStore, AudioFixSprintStore, AudioLabStore, AudioProfileStore, AudioReviewEvidenceStore, CommandSpec, DistributionStore, EncodedAudioAcceptanceStore, FormatDecisionStore, Path, PlanningRuleGovernanceStore, PlanningRuleImpactStore, PlanningRuleSimulationStore, ProjectStore, ProviderConfig, ProviderError, ReleaseAudioBaselineGovernanceStore, ReleaseAudioCertificationStore, ReleaseAudioCommandCenterStore, ReleaseAudioQualityActionQueueSignoffStore, ReleaseAudioQualityActionQueueStore, ReleaseAudioQualityObservatoryStore, ReleaseAudioRegressionResponseStore, ReleaseAudioRegressionStore, ReleaseAudioTimelineStore, ReleaseStore, SongRequest, acceptance_analytics_summary, analyze_wav_health, argparse, audio_campaign_archive_verification_exit_code, audio_campaign_remediation_verification_exit_code, audio_campaign_verification_exit_code, audio_review_summary_public, build_acceptance_diff, build_acceptance_report, build_auth_config, default_acceptance_song_cases, encoded_audio_acceptance_summary_public, evidence_to_verifier_kwargs, fix_plan_review_summary, fix_plan_summary, fix_sprint_summary, generate_request, get_acceptance_profile, governance_summary, json, knowledge_entry_summary, knowledge_report_summary, load_provider_config, music_health_allows_review, normalize_required_profiles, os, planning_rule_impact_summary, planning_simulation_summary, promotion_summary, provider_configured, read_json, release_audio_baseline_registry_verification_exit_code, release_audio_certification_verification_exit_code, release_audio_command_center_verification_exit_code, release_audio_quality_action_queue_signoff_archive_verification_exit_code, release_audio_quality_action_queue_verification_exit_code, release_audio_quality_observatory_verification_exit_code, release_audio_regression_response_verification_exit_code, release_audio_regression_verification_exit_code, release_audio_timeline_verification_exit_code, ruleset_summary, sys, test_provider_config, unified_command_center_evidence_review_acceptance_verification_exit_code, unified_release_program_continuity_acceptance_change_verification_exit_code, unified_release_program_continuity_acceptance_verification_exit_code, unified_release_program_continuity_command_center_acceptance_change_verification_exit_code, verification_exit_code, verify_audio_campaign_archive_package, verify_audio_campaign_package, verify_audio_campaign_remediation_package, verify_release_audio_baseline_registry_package, verify_release_audio_certification_package, verify_release_audio_command_center_package, verify_release_audio_quality_action_queue_package, verify_release_audio_quality_action_queue_signoff_archive_package, verify_release_audio_quality_observatory_package, verify_release_audio_regression_package, verify_release_audio_regression_response_package, verify_release_audio_timeline_package, verify_unified_command_center_evidence_review_acceptance_package, verify_unified_release_program_continuity_acceptance_change_package, verify_unified_release_program_continuity_acceptance_package, verify_unified_release_program_continuity_command_center_acceptance_change_package, verify_unified_release_program_continuity_command_center_acceptance_package, write_audio_campaign_archive_verification_report, write_audio_campaign_remediation_verification_report, write_audio_campaign_verification_report, write_interface_document, write_json, write_release_audio_baseline_registry_verification_report, write_release_audio_certification_verification_report, write_release_audio_command_center_verification_report, write_release_audio_quality_action_queue_signoff_archive_verification_report, write_release_audio_quality_action_queue_verification_report, write_release_audio_quality_observatory_verification_report, write_release_audio_regression_response_verification_report, write_release_audio_regression_verification_report, write_release_audio_timeline_verification_report, write_unified_command_center_evidence_review_acceptance_verification_report, write_unified_release_program_continuity_acceptance_change_verification_report, write_unified_release_program_continuity_acceptance_verification_report, write_unified_release_program_continuity_command_center_acceptance_change_verification_report, write_verification_report = _commands_quality_parts_dependencies.AcceptanceAnalyticsStore, _commands_quality_parts_dependencies.AcceptanceFixPlanReviewStore, _commands_quality_parts_dependencies.AcceptanceFixPlanningStore, _commands_quality_parts_dependencies.AcceptanceFixSprintStore, _commands_quality_parts_dependencies.AcceptanceKnowledgeBaseStore, _commands_quality_parts_dependencies.AcceptanceStore, _commands_quality_parts_dependencies.AnalyticsScope, _commands_quality_parts_dependencies.Any, _commands_quality_parts_dependencies.AudioCampaignGovernanceStore, _commands_quality_parts_dependencies.AudioCampaignPlannerStore, _commands_quality_parts_dependencies.AudioCampaignRemediationStore, _commands_quality_parts_dependencies.AudioCampaignStore, _commands_quality_parts_dependencies.AudioEncodingProfileStore, _commands_quality_parts_dependencies.AudioEncodingStore, _commands_quality_parts_dependencies.AudioFixSprintStore, _commands_quality_parts_dependencies.AudioLabStore, _commands_quality_parts_dependencies.AudioProfileStore, _commands_quality_parts_dependencies.AudioReviewEvidenceStore, _commands_quality_parts_dependencies.CommandSpec, _commands_quality_parts_dependencies.DistributionStore, _commands_quality_parts_dependencies.EncodedAudioAcceptanceStore, _commands_quality_parts_dependencies.FormatDecisionStore, _commands_quality_parts_dependencies.Path, _commands_quality_parts_dependencies.PlanningRuleGovernanceStore, _commands_quality_parts_dependencies.PlanningRuleImpactStore, _commands_quality_parts_dependencies.PlanningRuleSimulationStore, _commands_quality_parts_dependencies.ProjectStore, _commands_quality_parts_dependencies.ProviderConfig, _commands_quality_parts_dependencies.ProviderError, _commands_quality_parts_dependencies.ReleaseAudioBaselineGovernanceStore, _commands_quality_parts_dependencies.ReleaseAudioCertificationStore, _commands_quality_parts_dependencies.ReleaseAudioCommandCenterStore, _commands_quality_parts_dependencies.ReleaseAudioQualityActionQueueSignoffStore, _commands_quality_parts_dependencies.ReleaseAudioQualityActionQueueStore, _commands_quality_parts_dependencies.ReleaseAudioQualityObservatoryStore, _commands_quality_parts_dependencies.ReleaseAudioRegressionResponseStore, _commands_quality_parts_dependencies.ReleaseAudioRegressionStore, _commands_quality_parts_dependencies.ReleaseAudioTimelineStore, _commands_quality_parts_dependencies.ReleaseStore, _commands_quality_parts_dependencies.SongRequest, _commands_quality_parts_dependencies.acceptance_analytics_summary, _commands_quality_parts_dependencies.analyze_wav_health, _commands_quality_parts_dependencies.argparse, _commands_quality_parts_dependencies.audio_campaign_archive_verification_exit_code, _commands_quality_parts_dependencies.audio_campaign_remediation_verification_exit_code, _commands_quality_parts_dependencies.audio_campaign_verification_exit_code, _commands_quality_parts_dependencies.audio_review_summary_public, _commands_quality_parts_dependencies.build_acceptance_diff, _commands_quality_parts_dependencies.build_acceptance_report, _commands_quality_parts_dependencies.build_auth_config, _commands_quality_parts_dependencies.default_acceptance_song_cases, _commands_quality_parts_dependencies.encoded_audio_acceptance_summary_public, _commands_quality_parts_dependencies.evidence_to_verifier_kwargs, _commands_quality_parts_dependencies.fix_plan_review_summary, _commands_quality_parts_dependencies.fix_plan_summary, _commands_quality_parts_dependencies.fix_sprint_summary, _commands_quality_parts_dependencies.generate_request, _commands_quality_parts_dependencies.get_acceptance_profile, _commands_quality_parts_dependencies.governance_summary, _commands_quality_parts_dependencies.json, _commands_quality_parts_dependencies.knowledge_entry_summary, _commands_quality_parts_dependencies.knowledge_report_summary, _commands_quality_parts_dependencies.load_provider_config, _commands_quality_parts_dependencies.music_health_allows_review, _commands_quality_parts_dependencies.normalize_required_profiles, _commands_quality_parts_dependencies.os, _commands_quality_parts_dependencies.planning_rule_impact_summary, _commands_quality_parts_dependencies.planning_simulation_summary, _commands_quality_parts_dependencies.promotion_summary, _commands_quality_parts_dependencies.provider_configured, _commands_quality_parts_dependencies.read_json, _commands_quality_parts_dependencies.release_audio_baseline_registry_verification_exit_code, _commands_quality_parts_dependencies.release_audio_certification_verification_exit_code, _commands_quality_parts_dependencies.release_audio_command_center_verification_exit_code, _commands_quality_parts_dependencies.release_audio_quality_action_queue_signoff_archive_verification_exit_code, _commands_quality_parts_dependencies.release_audio_quality_action_queue_verification_exit_code, _commands_quality_parts_dependencies.release_audio_quality_observatory_verification_exit_code, _commands_quality_parts_dependencies.release_audio_regression_response_verification_exit_code, _commands_quality_parts_dependencies.release_audio_regression_verification_exit_code, _commands_quality_parts_dependencies.release_audio_timeline_verification_exit_code, _commands_quality_parts_dependencies.ruleset_summary, _commands_quality_parts_dependencies.sys, _commands_quality_parts_dependencies.test_provider_config, _commands_quality_parts_dependencies.unified_command_center_evidence_review_acceptance_verification_exit_code, _commands_quality_parts_dependencies.unified_release_program_continuity_acceptance_change_verification_exit_code, _commands_quality_parts_dependencies.unified_release_program_continuity_acceptance_verification_exit_code, _commands_quality_parts_dependencies.unified_release_program_continuity_command_center_acceptance_change_verification_exit_code, _commands_quality_parts_dependencies.verification_exit_code, _commands_quality_parts_dependencies.verify_audio_campaign_archive_package, _commands_quality_parts_dependencies.verify_audio_campaign_package, _commands_quality_parts_dependencies.verify_audio_campaign_remediation_package, _commands_quality_parts_dependencies.verify_release_audio_baseline_registry_package, _commands_quality_parts_dependencies.verify_release_audio_certification_package, _commands_quality_parts_dependencies.verify_release_audio_command_center_package, _commands_quality_parts_dependencies.verify_release_audio_quality_action_queue_package, _commands_quality_parts_dependencies.verify_release_audio_quality_action_queue_signoff_archive_package, _commands_quality_parts_dependencies.verify_release_audio_quality_observatory_package, _commands_quality_parts_dependencies.verify_release_audio_regression_package, _commands_quality_parts_dependencies.verify_release_audio_regression_response_package, _commands_quality_parts_dependencies.verify_release_audio_timeline_package, _commands_quality_parts_dependencies.verify_unified_command_center_evidence_review_acceptance_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_acceptance_change_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_acceptance_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_command_center_acceptance_change_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_command_center_acceptance_package, _commands_quality_parts_dependencies.write_audio_campaign_archive_verification_report, _commands_quality_parts_dependencies.write_audio_campaign_remediation_verification_report, _commands_quality_parts_dependencies.write_audio_campaign_verification_report, _commands_quality_parts_dependencies.write_interface_document, _commands_quality_parts_dependencies.write_json, _commands_quality_parts_dependencies.write_release_audio_baseline_registry_verification_report, _commands_quality_parts_dependencies.write_release_audio_certification_verification_report, _commands_quality_parts_dependencies.write_release_audio_command_center_verification_report, _commands_quality_parts_dependencies.write_release_audio_quality_action_queue_signoff_archive_verification_report, _commands_quality_parts_dependencies.write_release_audio_quality_action_queue_verification_report, _commands_quality_parts_dependencies.write_release_audio_quality_observatory_verification_report, _commands_quality_parts_dependencies.write_release_audio_regression_response_verification_report, _commands_quality_parts_dependencies.write_release_audio_regression_verification_report, _commands_quality_parts_dependencies.write_release_audio_timeline_verification_report, _commands_quality_parts_dependencies.write_unified_command_center_evidence_review_acceptance_verification_report, _commands_quality_parts_dependencies.write_unified_release_program_continuity_acceptance_change_verification_report, _commands_quality_parts_dependencies.write_unified_release_program_continuity_acceptance_verification_report, _commands_quality_parts_dependencies.write_unified_release_program_continuity_command_center_acceptance_change_verification_report, _commands_quality_parts_dependencies.write_verification_report
def build_audio_fix_sprint_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage Audio Fix Sprints from Audio Lab needs_fix markers.")
    subparsers = parser.add_subparsers(dest="action", required=True)

    create = subparsers.add_parser("create", help="Create a sprint from one or more Audio Lab sessions.")
    create.add_argument("--from-session", "--session-id", dest="session_ids", action="append", required=True)
    create.add_argument("--name", default="")
    create.add_argument("--include-test-audio", action="store_true")
    create.add_argument("--json", action="store_true")

    listing = subparsers.add_parser("list", help="List Audio Fix Sprints.")
    listing.add_argument("--json", action="store_true")

    detail = subparsers.add_parser("detail", help="Show one Audio Fix Sprint.")
    detail.add_argument("sprint_id")
    detail.add_argument("--json", action="store_true")

    refresh = subparsers.add_parser("refresh", help="Refresh stale status for an Audio Fix Sprint.")
    refresh.add_argument("sprint_id")
    refresh.add_argument("--json", action="store_true")

    drafts = subparsers.add_parser("create-drafts", help="Create deterministic fix drafts for sprint items.")
    drafts.add_argument("sprint_id")
    drafts.add_argument("--draft-type", choices=["review_task", "audio_revision", "mix_patch"], default="review_task")
    drafts.add_argument("--item-id", dest="item_ids", action="append")
    drafts.add_argument("--json", action="store_true")

    candidates = subparsers.add_parser("generate-candidates", help="Generate local deterministic fix candidates.")
    candidates.add_argument("sprint_id")
    candidates.add_argument("--item-id", dest="item_ids", action="append")
    candidates.add_argument("--json", action="store_true")

    review = subparsers.add_parser("review-candidate", help="Write a manual A/B review for a candidate.")
    review.add_argument("sprint_id")
    review.add_argument("item_id")
    review.add_argument("candidate_id")
    review.add_argument("--preferred", choices=["left", "right", "same"], required=True)
    review.add_argument("--rating", type=int, default=4)
    review.add_argument("--rating-delta", type=int, default=0)
    review.add_argument("--reviewer", default="developer")
    review.add_argument("--role", default="developer")
    review.add_argument("--notes", default="")
    review.add_argument("--playback-confirmed", action="store_true")
    review.add_argument("--json", action="store_true")

    select = subparsers.add_parser("select-candidate", help="Select a manually reviewed candidate.")
    select.add_argument("sprint_id")
    select.add_argument("item_id")
    select.add_argument("candidate_id")
    select.add_argument("--selected-by", default="audio-fix-sprint")
    select.add_argument("--json", action="store_true")

    recheck = subparsers.add_parser("create-recheck-session", help="Create the manual recheck session from selected candidates.")
    recheck.add_argument("sprint_id")
    recheck.add_argument("--json", action="store_true")

    recheck_review = subparsers.add_parser("review-recheck", help="Review one recheck session item.")
    recheck_review.add_argument("sprint_id")
    recheck_review.add_argument("item_id")
    recheck_review.add_argument("--result", choices=["accepted", "needs_fix", "rejected"], required=True)
    recheck_review.add_argument("--rating", type=int, default=4)
    recheck_review.add_argument("--reviewer", default="developer")
    recheck_review.add_argument("--role", default="developer")
    recheck_review.add_argument("--notes", default="")
    recheck_review.add_argument("--playback-confirmed", action="store_true")
    recheck_review.add_argument("--json", action="store_true")

    closeout = subparsers.add_parser("closeout", help="Build and show the Audio Fix Sprint closeout report.")
    closeout.add_argument("sprint_id")
    closeout.add_argument("--json", action="store_true")

    close = subparsers.add_parser("close", help="Close a sprint after manual A/B and accepted recheck.")
    close.add_argument("sprint_id")
    close.add_argument("--closed-by", default="audio-fix-sprint")
    close.add_argument("--json", action="store_true")
    return parser

def _build_audio_campaign_parser_core(_split_state):
    _split_state['parser'] = argparse.ArgumentParser(description='Manage release candidate Audio Campaigns from Audio Lab sessions.')
    _split_state['subparsers'] = _split_state['parser'].add_subparsers(dest='action', required=True)
    create = _split_state['subparsers'].add_parser('create', help='Create an Audio Campaign from one or more Audio Lab sessions.')
    create.add_argument('--from-session', '--session-id', dest='session_ids', action='append', required=True)
    create.add_argument('--name', default='')
    create.add_argument('--profile', default='release_candidate')
    create.add_argument('--allow-test-audio', action='store_true')
    create.add_argument('--allow-synthetic-review', action='store_true')
    create.add_argument('--minimum-rating', type=int, default=4)
    create.add_argument('--json', action='store_true')
    listing = _split_state['subparsers'].add_parser('list', help='List Audio Campaigns.')
    listing.add_argument('--json', action='store_true')
    detail = _split_state['subparsers'].add_parser('detail', help='Show one Audio Campaign.')
    detail.add_argument('campaign_id')
    detail.add_argument('--json', action='store_true')
    refresh = _split_state['subparsers'].add_parser('refresh', help='Refresh Audio Campaign source snapshots.')
    refresh.add_argument('campaign_id')
    refresh.add_argument('--json', action='store_true')
    link_session = _split_state['subparsers'].add_parser('link-session', help='Add another Audio Lab listening session to a campaign.')
    link_session.add_argument('campaign_id')
    link_session.add_argument('--session-id', required=True)
    link_session.add_argument('--json', action='store_true')
    fix_sprints = _split_state['subparsers'].add_parser('create-fix-sprints', help='Create Audio Fix Sprints for campaign issues.')
    fix_sprints.add_argument('campaign_id')
    fix_sprints.add_argument('--json', action='store_true')
    report = _split_state['subparsers'].add_parser('report', help='Build and show the Audio Campaign report.')
    report.add_argument('campaign_id')
    report.add_argument('--json', action='store_true')
    signoff = _split_state['subparsers'].add_parser('signoff', help='Sign off a passed Audio Campaign.')
    signoff.add_argument('campaign_id')
    signoff.add_argument('--signed-by', required=True)
    signoff.add_argument('--role', default='audio-reviewer')
    signoff.add_argument('--reason', default='')
    signoff.add_argument('--json', action='store_true')
    export = _split_state['subparsers'].add_parser('export', help='Export the Audio Campaign evidence package directory.')
    export.add_argument('campaign_id')
    export.add_argument('--json', action='store_true')
    zip_cmd = _split_state['subparsers'].add_parser('zip', help='Build the Audio Campaign ZIP.')
    zip_cmd.add_argument('campaign_id')
    zip_cmd.add_argument('--json', action='store_true')
    verify = _split_state['subparsers'].add_parser('verify', help='Verify the Audio Campaign ZIP.')
    verify.add_argument('campaign_id')
    verify.add_argument('--strict', action='store_true')
    verify.add_argument('--require-real-audio', action='store_true')
    verify.add_argument('--require-manual-review', action='store_true')
    verify.add_argument('--require-fix-sprints-closed', action='store_true')
    verify.add_argument('--require-signed', action='store_true')
    verify.add_argument('--json', action='store_true')
    verify.add_argument('--report-out', type=Path, default=None)
    governance = _split_state['subparsers'].add_parser('governance', help='Refresh the Audio Campaign governance report.')
    governance.add_argument('campaign_id')
    governance.add_argument('--json', action='store_true')
    return None

def _build_audio_campaign_parser_governance(_split_state):
    analytics = _split_state['subparsers'].add_parser('analytics', help='Refresh the Audio Campaign analytics summary.')
    analytics.add_argument('campaign_id')
    analytics.add_argument('--json', action='store_true')
    archive = _split_state['subparsers'].add_parser('archive', help='Export signed Audio Campaign governance archive files.')
    archive.add_argument('campaign_id')
    archive.add_argument('--json', action='store_true')
    archive_zip = _split_state['subparsers'].add_parser('archive-zip', help='Build the signed Audio Campaign governance archive ZIP.')
    archive_zip.add_argument('campaign_id')
    archive_zip.add_argument('--json', action='store_true')
    verify_archive = _split_state['subparsers'].add_parser('verify-archive', help='Verify the signed Audio Campaign governance archive ZIP.')
    verify_archive.add_argument('campaign_id')
    verify_archive.add_argument('--strict', action='store_true')
    verify_archive.add_argument('--json', action='store_true')
    verify_archive.add_argument('--report-out', type=Path, default=None)
    remediation_plan = _split_state['subparsers'].add_parser('remediation-plan', help='Refresh Release Audio Campaign remediation plan.')
    remediation_plan.add_argument('release_id')
    remediation_plan.add_argument('--json', action='store_true')
    remediation_status = _split_state['subparsers'].add_parser('remediation-status', help='Show Release Audio Campaign remediation status.')
    remediation_status.add_argument('release_id')
    remediation_status.add_argument('--json', action='store_true')
    remediation_run = _split_state['subparsers'].add_parser('remediation-run-safe', help='Run safe remediation actions.')
    remediation_run.add_argument('release_id')
    remediation_run.add_argument('--closed-by', default='audio-campaign-remediation')
    remediation_run.add_argument('--json', action='store_true')
    remediation_closeout = _split_state['subparsers'].add_parser('remediation-closeout', help='Build Release Audio Campaign remediation closeout report.')
    remediation_closeout.add_argument('release_id')
    remediation_closeout.add_argument('--json', action='store_true')
    remediation_signoff = _split_state['subparsers'].add_parser('remediation-signoff', help='Sign off passed Release Audio Campaign remediation evidence.')
    remediation_signoff.add_argument('release_id')
    remediation_signoff.add_argument('--signed-by', required=True)
    remediation_signoff.add_argument('--role', default='audio-remediation-reviewer')
    remediation_signoff.add_argument('--reason', default='')
    remediation_signoff.add_argument('--json', action='store_true')
    remediation_export = _split_state['subparsers'].add_parser('remediation-export', help='Export Release Audio Campaign remediation evidence.')
    remediation_export.add_argument('release_id')
    remediation_export.add_argument('--json', action='store_true')
    _split_state['remediation_zip'] = _split_state['subparsers'].add_parser('remediation-zip', help='Build Release Audio Campaign remediation ZIP.')
    _split_state['remediation_zip'].add_argument('release_id')
    return None

def _build_audio_campaign_parser_part_01(_split_state):
    _build_audio_campaign_parser_core(_split_state)
    _build_audio_campaign_parser_governance(_split_state)
    return (False, None)

def _build_audio_campaign_parser_part_02(_split_state):
    _split_state['remediation_zip'].add_argument('--json', action='store_true')
    remediation_verify = _split_state['subparsers'].add_parser('remediation-verify', help='Verify Release Audio Campaign remediation ZIP.')
    remediation_verify.add_argument('release_id')
    remediation_verify.add_argument('--strict', action='store_true')
    remediation_verify.add_argument('--require-passed', action='store_true')
    remediation_verify.add_argument('--require-signed', action='store_true')
    remediation_verify.add_argument('--json', action='store_true')
    remediation_verify.add_argument('--report-out', type=Path, default=None)
    cr_create = _split_state['subparsers'].add_parser('change-request-create', help='Create an Audio Campaign signoff reset Change Request.')
    cr_create.add_argument('campaign_id')
    cr_create.add_argument('--created-by', default='developer')
    cr_create.add_argument('--reason', required=True)
    cr_create.add_argument('--risk', default='medium')
    cr_create.add_argument('--json', action='store_true')
    cr_approve = _split_state['subparsers'].add_parser('change-request-approve', help='Approve an Audio Campaign signoff reset Change Request.')
    cr_approve.add_argument('campaign_id')
    cr_approve.add_argument('change_request_id')
    cr_approve.add_argument('--approved-by', default='reviewer')
    cr_approve.add_argument('--reason', default='')
    cr_approve.add_argument('--json', action='store_true')
    reset = _split_state['subparsers'].add_parser('signoff-reset', help='Reset Audio Campaign signoff with an approved Change Request.')
    reset.add_argument('campaign_id')
    reset.add_argument('--change-request-id', required=True)
    reset.add_argument('--reason', required=True)
    reset.add_argument('--json', action='store_true')
    plan_release = _split_state['subparsers'].add_parser('plan-release', help='Create or refresh a release-bound Audio Campaign plan.')
    plan_release.add_argument('release_id')
    plan_release.add_argument('--json', action='store_true')
    preflight_release = _split_state['subparsers'].add_parser('preflight-release', help='Run Release Audio Campaign preflight.')
    preflight_release.add_argument('release_id')
    preflight_release.add_argument('--json', action='store_true')
    create_from_release = _split_state['subparsers'].add_parser('create-from-release', help='Create Audio Lab session and Audio Campaign from Release tracks.')
    create_from_release.add_argument('release_id')
    create_from_release.add_argument('--name', default='')
    create_from_release.add_argument('--minimum-rating', type=int, default=4)
    create_from_release.add_argument('--allow-failed-preflight', action='store_true')
    create_from_release.add_argument('--json', action='store_true')
    release_status = _split_state['subparsers'].add_parser('release-status', help='Show Release Audio Campaign plan status.')
    release_status.add_argument('release_id')
    release_status.add_argument('--json', action='store_true')
    release_link = _split_state['subparsers'].add_parser('release-link', help='Link an existing Audio Campaign to a Release plan.')
    release_link.add_argument('release_id')
    release_link.add_argument('--campaign-id', required=True)
    release_link.add_argument('--json', action='store_true')
    return (True, _split_state['parser'])
    return (False, None)

def build_audio_campaign_parser() -> argparse.ArgumentParser:
    _split_state: dict[str, _InferenceType] = {}
    _split_result = _build_audio_campaign_parser_part_01(_split_state)
    if _split_result[0]:
        return _split_result[1]
    _split_result = _build_audio_campaign_parser_part_02(_split_state)
    if _split_result[0]:
        return _split_result[1]
    raise RuntimeError("build_audio_campaign_parser did not produce a result.")

def build_verify_audio_campaign_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify a MusicForge Audio Campaign ZIP.")
    parser.add_argument("zip_path", type=Path)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--report-out", type=Path, default=None)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--require-real-audio", action="store_true")
    parser.add_argument("--require-manual-review", action="store_true")
    parser.add_argument("--require-fix-sprints-closed", action="store_true")
    parser.add_argument("--require-signed", action="store_true")
    parser.add_argument("--require-no-open-high", action="store_true")
    parser.add_argument("--require-no-open-critical", action="store_true")
    parser.add_argument("--max-zip-size-mb", type=int, default=256)
    parser.add_argument("--max-uncompressed-size-mb", type=int, default=512)
    parser.add_argument("--max-entry-count", type=int, default=5000)
    return parser

def build_verify_audio_campaign_archive_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify a MusicForge Audio Campaign Archive ZIP.")
    parser.add_argument("zip_path", type=Path)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--report-out", type=Path, default=None)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--require-signed", action="store_true")
    parser.add_argument("--require-verification-passed", action="store_true")
    parser.add_argument("--max-zip-size-mb", type=int, default=256)
    parser.add_argument("--max-uncompressed-size-mb", type=int, default=512)
    parser.add_argument("--max-entry-count", type=int, default=5000)
    return parser

def build_verify_audio_campaign_remediation_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify a MusicForge Audio Campaign Remediation ZIP.")
    parser.add_argument("zip_path", type=Path)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--report-out", type=Path, default=None)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--require-passed", action="store_true")
    parser.add_argument("--require-signed", action="store_true")
    parser.add_argument("--max-zip-size-mb", type=int, default=128)
    parser.add_argument("--max-uncompressed-size-mb", type=int, default=512)
    parser.add_argument("--max-entry-count", type=int, default=1000)
    return parser

def build_release_audio_certification_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage Release Audio Certification evidence.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    subparsers = parser.add_subparsers(dest="action", required=True)
    refresh = subparsers.add_parser("refresh", help="Refresh Release Audio Certification report.")
    refresh.add_argument("release_id")
    status = subparsers.add_parser("status", help="Show Release Audio Certification status.")
    status.add_argument("release_id")
    signoff = subparsers.add_parser("signoff", help="Sign off a passed Release Audio Certification.")
    signoff.add_argument("release_id")
    signoff.add_argument("--signed-by", default="audio-certification")
    signoff.add_argument("--role", default="audio-certification-reviewer")
    signoff.add_argument("--reason", default="Release audio certification accepted.")
    export = subparsers.add_parser("export", help="Export Release Audio Certification package files.")
    export.add_argument("release_id")
    zip_cmd = subparsers.add_parser("zip", help="Build Release Audio Certification ZIP.")
    zip_cmd.add_argument("release_id")
    verify = subparsers.add_parser("verify", help="Verify Release Audio Certification ZIP.")
    verify.add_argument("release_id")
    verify.add_argument("--strict", action="store_true")
    verify.add_argument("--require-passed", action="store_true")
    verify.add_argument("--require-signed", action="store_true")
    verify.add_argument("--require-real-audio", action="store_true")
    verify.add_argument("--require-manual-review", action="store_true")
    verify.add_argument("--require-remediation-when-needed", action="store_true")
    verify.add_argument("--report-out", type=Path, default=None)
    return parser

__all__ = ('build_audio_fix_sprint_parser', 'build_audio_campaign_parser', 'build_verify_audio_campaign_parser', 'build_verify_audio_campaign_archive_parser', 'build_verify_audio_campaign_remediation_parser', 'build_release_audio_certification_parser')
