from __future__ import annotations


from song_agent.interfaces.cli.bindings import BINDINGS as CLI_BINDINGS

from . import dependencies as _commands_quality_parts_dependencies
AcceptanceAnalyticsStore, AcceptanceFixPlanReviewStore, AcceptanceFixPlanningStore, AcceptanceFixSprintStore, AcceptanceKnowledgeBaseStore, AcceptanceStore, AnalyticsScope, Any, AudioCampaignGovernanceStore, AudioCampaignPlannerStore, AudioCampaignRemediationStore, AudioCampaignStore, AudioEncodingProfileStore, AudioEncodingStore, AudioFixSprintStore, AudioLabStore, AudioProfileStore, AudioReviewEvidenceStore, CommandSpec, DistributionStore, EncodedAudioAcceptanceStore, FormatDecisionStore, Path, PlanningRuleGovernanceStore, PlanningRuleImpactStore, PlanningRuleSimulationStore, ProjectStore, ProviderConfig, ProviderError, ReleaseAudioBaselineGovernanceStore, ReleaseAudioCertificationStore, ReleaseAudioCommandCenterStore, ReleaseAudioQualityActionQueueSignoffStore, ReleaseAudioQualityActionQueueStore, ReleaseAudioQualityObservatoryStore, ReleaseAudioRegressionResponseStore, ReleaseAudioRegressionStore, ReleaseAudioTimelineStore, ReleaseStore, SongRequest, acceptance_analytics_summary, analyze_wav_health, argparse, audio_campaign_archive_verification_exit_code, audio_campaign_remediation_verification_exit_code, audio_campaign_verification_exit_code, audio_review_summary_public, build_acceptance_diff, build_acceptance_report, build_auth_config, default_acceptance_song_cases, encoded_audio_acceptance_summary_public, evidence_to_verifier_kwargs, fix_plan_review_summary, fix_plan_summary, fix_sprint_summary, generate_request, get_acceptance_profile, governance_summary, json, knowledge_entry_summary, knowledge_report_summary, load_provider_config, music_health_allows_review, normalize_required_profiles, os, planning_rule_impact_summary, planning_simulation_summary, promotion_summary, provider_configured, read_json, release_audio_baseline_registry_verification_exit_code, release_audio_certification_verification_exit_code, release_audio_command_center_verification_exit_code, release_audio_quality_action_queue_signoff_archive_verification_exit_code, release_audio_quality_action_queue_verification_exit_code, release_audio_quality_observatory_verification_exit_code, release_audio_regression_response_verification_exit_code, release_audio_regression_verification_exit_code, release_audio_timeline_verification_exit_code, ruleset_summary, sys, test_provider_config, unified_command_center_evidence_review_acceptance_verification_exit_code, unified_release_program_continuity_acceptance_change_verification_exit_code, unified_release_program_continuity_acceptance_verification_exit_code, unified_release_program_continuity_command_center_acceptance_change_verification_exit_code, verification_exit_code, verify_audio_campaign_archive_package, verify_audio_campaign_package, verify_audio_campaign_remediation_package, verify_release_audio_baseline_registry_package, verify_release_audio_certification_package, verify_release_audio_command_center_package, verify_release_audio_quality_action_queue_package, verify_release_audio_quality_action_queue_signoff_archive_package, verify_release_audio_quality_observatory_package, verify_release_audio_regression_package, verify_release_audio_regression_response_package, verify_release_audio_timeline_package, verify_unified_command_center_evidence_review_acceptance_package, verify_unified_release_program_continuity_acceptance_change_package, verify_unified_release_program_continuity_acceptance_package, verify_unified_release_program_continuity_command_center_acceptance_change_package, verify_unified_release_program_continuity_command_center_acceptance_package, write_audio_campaign_archive_verification_report, write_audio_campaign_remediation_verification_report, write_audio_campaign_verification_report, write_interface_document, write_json, write_release_audio_baseline_registry_verification_report, write_release_audio_certification_verification_report, write_release_audio_command_center_verification_report, write_release_audio_quality_action_queue_signoff_archive_verification_report, write_release_audio_quality_action_queue_verification_report, write_release_audio_quality_observatory_verification_report, write_release_audio_regression_response_verification_report, write_release_audio_regression_verification_report, write_release_audio_timeline_verification_report, write_unified_command_center_evidence_review_acceptance_verification_report, write_unified_release_program_continuity_acceptance_change_verification_report, write_unified_release_program_continuity_acceptance_verification_report, write_unified_release_program_continuity_command_center_acceptance_change_verification_report, write_verification_report = _commands_quality_parts_dependencies.AcceptanceAnalyticsStore, _commands_quality_parts_dependencies.AcceptanceFixPlanReviewStore, _commands_quality_parts_dependencies.AcceptanceFixPlanningStore, _commands_quality_parts_dependencies.AcceptanceFixSprintStore, _commands_quality_parts_dependencies.AcceptanceKnowledgeBaseStore, _commands_quality_parts_dependencies.AcceptanceStore, _commands_quality_parts_dependencies.AnalyticsScope, _commands_quality_parts_dependencies.Any, _commands_quality_parts_dependencies.AudioCampaignGovernanceStore, _commands_quality_parts_dependencies.AudioCampaignPlannerStore, _commands_quality_parts_dependencies.AudioCampaignRemediationStore, _commands_quality_parts_dependencies.AudioCampaignStore, _commands_quality_parts_dependencies.AudioEncodingProfileStore, _commands_quality_parts_dependencies.AudioEncodingStore, _commands_quality_parts_dependencies.AudioFixSprintStore, _commands_quality_parts_dependencies.AudioLabStore, _commands_quality_parts_dependencies.AudioProfileStore, _commands_quality_parts_dependencies.AudioReviewEvidenceStore, _commands_quality_parts_dependencies.CommandSpec, _commands_quality_parts_dependencies.DistributionStore, _commands_quality_parts_dependencies.EncodedAudioAcceptanceStore, _commands_quality_parts_dependencies.FormatDecisionStore, _commands_quality_parts_dependencies.Path, _commands_quality_parts_dependencies.PlanningRuleGovernanceStore, _commands_quality_parts_dependencies.PlanningRuleImpactStore, _commands_quality_parts_dependencies.PlanningRuleSimulationStore, _commands_quality_parts_dependencies.ProjectStore, _commands_quality_parts_dependencies.ProviderConfig, _commands_quality_parts_dependencies.ProviderError, _commands_quality_parts_dependencies.ReleaseAudioBaselineGovernanceStore, _commands_quality_parts_dependencies.ReleaseAudioCertificationStore, _commands_quality_parts_dependencies.ReleaseAudioCommandCenterStore, _commands_quality_parts_dependencies.ReleaseAudioQualityActionQueueSignoffStore, _commands_quality_parts_dependencies.ReleaseAudioQualityActionQueueStore, _commands_quality_parts_dependencies.ReleaseAudioQualityObservatoryStore, _commands_quality_parts_dependencies.ReleaseAudioRegressionResponseStore, _commands_quality_parts_dependencies.ReleaseAudioRegressionStore, _commands_quality_parts_dependencies.ReleaseAudioTimelineStore, _commands_quality_parts_dependencies.ReleaseStore, _commands_quality_parts_dependencies.SongRequest, _commands_quality_parts_dependencies.acceptance_analytics_summary, _commands_quality_parts_dependencies.analyze_wav_health, _commands_quality_parts_dependencies.argparse, _commands_quality_parts_dependencies.audio_campaign_archive_verification_exit_code, _commands_quality_parts_dependencies.audio_campaign_remediation_verification_exit_code, _commands_quality_parts_dependencies.audio_campaign_verification_exit_code, _commands_quality_parts_dependencies.audio_review_summary_public, _commands_quality_parts_dependencies.build_acceptance_diff, _commands_quality_parts_dependencies.build_acceptance_report, _commands_quality_parts_dependencies.build_auth_config, _commands_quality_parts_dependencies.default_acceptance_song_cases, _commands_quality_parts_dependencies.encoded_audio_acceptance_summary_public, _commands_quality_parts_dependencies.evidence_to_verifier_kwargs, _commands_quality_parts_dependencies.fix_plan_review_summary, _commands_quality_parts_dependencies.fix_plan_summary, _commands_quality_parts_dependencies.fix_sprint_summary, _commands_quality_parts_dependencies.generate_request, _commands_quality_parts_dependencies.get_acceptance_profile, _commands_quality_parts_dependencies.governance_summary, _commands_quality_parts_dependencies.json, _commands_quality_parts_dependencies.knowledge_entry_summary, _commands_quality_parts_dependencies.knowledge_report_summary, _commands_quality_parts_dependencies.load_provider_config, _commands_quality_parts_dependencies.music_health_allows_review, _commands_quality_parts_dependencies.normalize_required_profiles, _commands_quality_parts_dependencies.os, _commands_quality_parts_dependencies.planning_rule_impact_summary, _commands_quality_parts_dependencies.planning_simulation_summary, _commands_quality_parts_dependencies.promotion_summary, _commands_quality_parts_dependencies.provider_configured, _commands_quality_parts_dependencies.read_json, _commands_quality_parts_dependencies.release_audio_baseline_registry_verification_exit_code, _commands_quality_parts_dependencies.release_audio_certification_verification_exit_code, _commands_quality_parts_dependencies.release_audio_command_center_verification_exit_code, _commands_quality_parts_dependencies.release_audio_quality_action_queue_signoff_archive_verification_exit_code, _commands_quality_parts_dependencies.release_audio_quality_action_queue_verification_exit_code, _commands_quality_parts_dependencies.release_audio_quality_observatory_verification_exit_code, _commands_quality_parts_dependencies.release_audio_regression_response_verification_exit_code, _commands_quality_parts_dependencies.release_audio_regression_verification_exit_code, _commands_quality_parts_dependencies.release_audio_timeline_verification_exit_code, _commands_quality_parts_dependencies.ruleset_summary, _commands_quality_parts_dependencies.sys, _commands_quality_parts_dependencies.test_provider_config, _commands_quality_parts_dependencies.unified_command_center_evidence_review_acceptance_verification_exit_code, _commands_quality_parts_dependencies.unified_release_program_continuity_acceptance_change_verification_exit_code, _commands_quality_parts_dependencies.unified_release_program_continuity_acceptance_verification_exit_code, _commands_quality_parts_dependencies.unified_release_program_continuity_command_center_acceptance_change_verification_exit_code, _commands_quality_parts_dependencies.verification_exit_code, _commands_quality_parts_dependencies.verify_audio_campaign_archive_package, _commands_quality_parts_dependencies.verify_audio_campaign_package, _commands_quality_parts_dependencies.verify_audio_campaign_remediation_package, _commands_quality_parts_dependencies.verify_release_audio_baseline_registry_package, _commands_quality_parts_dependencies.verify_release_audio_certification_package, _commands_quality_parts_dependencies.verify_release_audio_command_center_package, _commands_quality_parts_dependencies.verify_release_audio_quality_action_queue_package, _commands_quality_parts_dependencies.verify_release_audio_quality_action_queue_signoff_archive_package, _commands_quality_parts_dependencies.verify_release_audio_quality_observatory_package, _commands_quality_parts_dependencies.verify_release_audio_regression_package, _commands_quality_parts_dependencies.verify_release_audio_regression_response_package, _commands_quality_parts_dependencies.verify_release_audio_timeline_package, _commands_quality_parts_dependencies.verify_unified_command_center_evidence_review_acceptance_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_acceptance_change_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_acceptance_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_command_center_acceptance_change_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_command_center_acceptance_package, _commands_quality_parts_dependencies.write_audio_campaign_archive_verification_report, _commands_quality_parts_dependencies.write_audio_campaign_remediation_verification_report, _commands_quality_parts_dependencies.write_audio_campaign_verification_report, _commands_quality_parts_dependencies.write_interface_document, _commands_quality_parts_dependencies.write_json, _commands_quality_parts_dependencies.write_release_audio_baseline_registry_verification_report, _commands_quality_parts_dependencies.write_release_audio_certification_verification_report, _commands_quality_parts_dependencies.write_release_audio_command_center_verification_report, _commands_quality_parts_dependencies.write_release_audio_quality_action_queue_signoff_archive_verification_report, _commands_quality_parts_dependencies.write_release_audio_quality_action_queue_verification_report, _commands_quality_parts_dependencies.write_release_audio_quality_observatory_verification_report, _commands_quality_parts_dependencies.write_release_audio_regression_response_verification_report, _commands_quality_parts_dependencies.write_release_audio_regression_verification_report, _commands_quality_parts_dependencies.write_release_audio_timeline_verification_report, _commands_quality_parts_dependencies.write_unified_command_center_evidence_review_acceptance_verification_report, _commands_quality_parts_dependencies.write_unified_release_program_continuity_acceptance_change_verification_report, _commands_quality_parts_dependencies.write_unified_release_program_continuity_acceptance_verification_report, _commands_quality_parts_dependencies.write_unified_release_program_continuity_command_center_acceptance_change_verification_report, _commands_quality_parts_dependencies.write_verification_report
build_verify_release_portfolio_governance_attestation_portal_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_attestation_portal_parser

build_verify_release_portfolio_governance_attestation_portal_response_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_attestation_portal_response_parser

build_verify_release_portfolio_governance_attestation_portal_review_pack_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_attestation_portal_review_pack_parser

build_verify_release_portfolio_governance_attestation_registry_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_attestation_registry_parser

build_verify_release_portfolio_governance_attestation_transparency_acknowledgement_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_attestation_transparency_acknowledgement_parser

build_verify_release_portfolio_governance_attestation_transparency_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_attestation_transparency_parser

build_verify_release_portfolio_governance_audit_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_audit_parser

build_verify_release_portfolio_governance_evidence_vault_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_evidence_vault_parser

build_verify_release_portfolio_governance_final_board_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_final_board_parser

build_verify_release_portfolio_governance_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_parser

build_verify_release_portfolio_governance_reviewer_pack_parser = CLI_BINDINGS.trust.build_verify_release_portfolio_governance_reviewer_pack_parser

build_verify_submission_evidence_parser = CLI_BINDINGS.delivery.build_verify_submission_evidence_parser

build_verify_submission_parser = CLI_BINDINGS.delivery.build_verify_submission_parser

build_verify_trust_operations_assurance_parser = CLI_BINDINGS.trust.build_verify_trust_operations_assurance_parser

build_verify_trust_operations_assurance_watch_parser = CLI_BINDINGS.trust.build_verify_trust_operations_assurance_watch_parser

build_verify_trust_operations_assurance_watch_signoff_parser = CLI_BINDINGS.trust.build_verify_trust_operations_assurance_watch_signoff_parser

build_verify_trust_operations_control_parser = CLI_BINDINGS.trust.build_verify_trust_operations_control_parser

build_verify_trust_operations_control_signoff_parser = CLI_BINDINGS.trust.build_verify_trust_operations_control_signoff_parser

build_verify_trust_operations_final_handoff_parser = CLI_BINDINGS.trust.build_verify_trust_operations_final_handoff_parser

build_verify_trust_operations_hub_incident_parser = CLI_BINDINGS.trust.build_verify_trust_operations_hub_incident_parser

build_verify_trust_operations_hub_parser = CLI_BINDINGS.trust.build_verify_trust_operations_hub_parser

build_verify_trust_operations_hub_runbook_parser = CLI_BINDINGS.trust.build_verify_trust_operations_hub_runbook_parser

build_verify_trust_operations_incident_knowledge_parser = CLI_BINDINGS.trust.build_verify_trust_operations_incident_knowledge_parser

build_verify_unified_command_center_archive_parser = CLI_BINDINGS.program.build_verify_unified_command_center_archive_parser

build_verify_unified_command_center_continuous_review_parser = CLI_BINDINGS.program.build_verify_unified_command_center_continuous_review_parser

build_verify_unified_command_center_drift_response_parser = CLI_BINDINGS.program.build_verify_unified_command_center_drift_response_parser

build_verify_unified_command_center_evidence_review_acceptance_parser = CLI_BINDINGS.program.build_verify_unified_command_center_evidence_review_acceptance_parser

build_verify_unified_command_center_evidence_review_parser = CLI_BINDINGS.program.build_verify_unified_command_center_evidence_review_parser

build_verify_unified_command_center_handoff_parser = CLI_BINDINGS.program.build_verify_unified_command_center_handoff_parser

build_verify_unified_command_center_parser = CLI_BINDINGS.program.build_verify_unified_command_center_parser

build_verify_unified_command_center_release_train_change_control_parser = CLI_BINDINGS.program.build_verify_unified_command_center_release_train_change_control_parser

build_verify_unified_command_center_release_train_handoff_parser = CLI_BINDINGS.program.build_verify_unified_command_center_release_train_handoff_parser

build_verify_unified_command_center_release_train_lifecycle_parser = CLI_BINDINGS.program.build_verify_unified_command_center_release_train_lifecycle_parser

build_verify_unified_command_center_release_train_parser = CLI_BINDINGS.program.build_verify_unified_command_center_release_train_parser

build_verify_unified_command_center_reviewer_decision_board_parser = CLI_BINDINGS.program.build_verify_unified_command_center_reviewer_decision_board_parser

build_verify_unified_release_program_continuity_acceptance_change_parser = CLI_BINDINGS.program.build_verify_unified_release_program_continuity_acceptance_change_parser

build_verify_unified_release_program_continuity_acceptance_parser = CLI_BINDINGS.program.build_verify_unified_release_program_continuity_acceptance_parser

build_verify_unified_release_program_continuity_command_center_acceptance_change_parser = CLI_BINDINGS.program.build_verify_unified_release_program_continuity_command_center_acceptance_change_parser

build_verify_unified_release_program_continuity_command_center_acceptance_parser = CLI_BINDINGS.program.build_verify_unified_release_program_continuity_command_center_acceptance_parser

build_verify_unified_release_program_continuity_command_center_handoff_parser = CLI_BINDINGS.program.build_verify_unified_release_program_continuity_command_center_handoff_parser

build_verify_unified_release_program_continuity_command_center_parser = CLI_BINDINGS.program.build_verify_unified_release_program_continuity_command_center_parser

build_verify_unified_release_program_continuity_command_center_signoff_parser = CLI_BINDINGS.program.build_verify_unified_release_program_continuity_command_center_signoff_parser

build_verify_unified_release_program_continuity_distribution_parser = CLI_BINDINGS.program.build_verify_unified_release_program_continuity_distribution_parser

build_verify_unified_release_program_continuity_parser = CLI_BINDINGS.program.build_verify_unified_release_program_continuity_parser

build_verify_unified_release_program_handoff_parser = CLI_BINDINGS.program.build_verify_unified_release_program_handoff_parser

build_verify_unified_release_program_operations_parser = CLI_BINDINGS.program.build_verify_unified_release_program_operations_parser

build_verify_unified_release_program_parser = CLI_BINDINGS.program.build_verify_unified_release_program_parser

build_verify_unified_release_program_vault_operations_parser = CLI_BINDINGS.program.build_verify_unified_release_program_vault_operations_parser

build_verify_unified_release_program_vault_parser = CLI_BINDINGS.program.build_verify_unified_release_program_vault_parser

print_public_trust_center_result = CLI_BINDINGS.trust.print_public_trust_center_result

print_release_operations_archive_result = CLI_BINDINGS.delivery.print_release_operations_archive_result

print_release_operations_audit_result = CLI_BINDINGS.delivery.print_release_operations_audit_result

print_release_operations_result = CLI_BINDINGS.delivery.print_release_operations_result

print_release_operations_reviewer_pack_result = CLI_BINDINGS.delivery.print_release_operations_reviewer_pack_result

print_release_operations_runbook_result = CLI_BINDINGS.delivery.print_release_operations_runbook_result

print_release_operations_signoff_result = CLI_BINDINGS.delivery.print_release_operations_signoff_result

print_release_portfolio_audit_result = CLI_BINDINGS.trust.print_release_portfolio_audit_result

print_release_portfolio_governance_attestation_accepted_evidence_result = CLI_BINDINGS.trust.print_release_portfolio_governance_attestation_accepted_evidence_result

print_release_portfolio_governance_attestation_portal_result = CLI_BINDINGS.trust.print_release_portfolio_governance_attestation_portal_result

print_release_portfolio_governance_attestation_portal_review_result = CLI_BINDINGS.trust.print_release_portfolio_governance_attestation_portal_review_result

print_release_portfolio_governance_attestation_registry_result = CLI_BINDINGS.trust.print_release_portfolio_governance_attestation_registry_result

print_release_portfolio_governance_attestation_result = CLI_BINDINGS.trust.print_release_portfolio_governance_attestation_result

print_release_portfolio_governance_attestation_transparency_acknowledgement_result = CLI_BINDINGS.trust.print_release_portfolio_governance_attestation_transparency_acknowledgement_result

print_release_portfolio_governance_attestation_transparency_result = CLI_BINDINGS.trust.print_release_portfolio_governance_attestation_transparency_result

print_release_portfolio_governance_audit_result = CLI_BINDINGS.trust.print_release_portfolio_governance_audit_result

print_release_portfolio_governance_evidence_vault_result = CLI_BINDINGS.trust.print_release_portfolio_governance_evidence_vault_result

print_release_portfolio_governance_final_board_result = CLI_BINDINGS.trust.print_release_portfolio_governance_final_board_result

print_release_portfolio_governance_result = CLI_BINDINGS.trust.print_release_portfolio_governance_result

print_release_portfolio_governance_reviewer_pack_result = CLI_BINDINGS.trust.print_release_portfolio_governance_reviewer_pack_result

print_release_portfolio_governance_signoff_result = CLI_BINDINGS.trust.print_release_portfolio_governance_signoff_result

def build_audio_lab_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run MusicForge Audio Lab environment, smoke, listening, and A/B checks.")
    subparsers = parser.add_subparsers(dest="section", required=True)

    status = subparsers.add_parser("status", help="Show Audio Lab environment status.")
    status.add_argument("--json", action="store_true")

    detect = subparsers.add_parser("detect", help="Detect local Audio Lab renderer readiness.")
    detect.add_argument("--json", action="store_true")

    test_profile = subparsers.add_parser("test-profile", help="Test the configured renderer profile.")
    test_profile.add_argument("--profile", "--profile-id", dest="profile_id", default=None)
    test_profile.add_argument("--json", action="store_true")

    setup_report = subparsers.add_parser("setup-report", help="Write and show the Audio Lab setup report.")
    setup_report.add_argument("--json", action="store_true")
    setup_report.add_argument("--report-out", type=Path, default=None)

    smoke = subparsers.add_parser("smoke", help="Create an Audio Lab smoke run.")
    smoke.add_argument("--cases", type=int, default=1)
    smoke.add_argument("--render-audio", choices=["auto", "required", "require", "never"], default="auto")
    smoke.add_argument("--profile", "--profile-id", dest="profile_id", default=None)
    smoke.add_argument("--json", action="store_true")
    smoke.add_argument("--report-out", type=Path, default=None)

    smoke_report = subparsers.add_parser("smoke-report", help="Show an Audio Lab smoke run report.")
    smoke_report.add_argument("smoke_run_id")
    smoke_report.add_argument("--json", action="store_true")
    smoke_report.add_argument("--report-out", type=Path, default=None)

    session = subparsers.add_parser("session", help="Manage Audio Lab listening sessions.")
    session_sub = session.add_subparsers(dest="session_action", required=True)
    session_create = session_sub.add_parser("create", help="Create a listening session from a smoke run.")
    session_create.add_argument("--from-smoke", required=True)
    session_create.add_argument("--json", action="store_true")
    session_list = session_sub.add_parser("list", help="List listening sessions.")
    session_list.add_argument("--json", action="store_true")
    session_detail = session_sub.add_parser("detail", help="Show a listening session.")
    session_detail.add_argument("session_id")
    session_detail.add_argument("--json", action="store_true")
    session_review = session_sub.add_parser("review", help="Write a manual listening review.")
    session_review.add_argument("session_id")
    session_review.add_argument("item_id")
    session_review.add_argument("--result", choices=["accepted", "needs_fix", "rejected"], required=True)
    session_review.add_argument("--rating", type=int, required=True)
    session_review.add_argument("--reviewer", default="developer")
    session_review.add_argument("--role", default="developer")
    session_review.add_argument("--notes", default="")
    session_review.add_argument("--playback-confirmed", action="store_true")
    session_review.add_argument("--json", action="store_true")
    session_marker = session_sub.add_parser("marker", help="Add an issue marker to a listening item.")
    session_marker.add_argument("session_id")
    session_marker.add_argument("item_id")
    session_marker.add_argument("--time-seconds", type=float, default=0.0)
    session_marker.add_argument("--category", default="other")
    session_marker.add_argument("--severity", default="medium")
    session_marker.add_argument("--message", default="")
    session_marker.add_argument("--json", action="store_true")
    session_task = session_sub.add_parser("create-review-task", help="Create a draft ReviewTask from a marker.")
    session_task.add_argument("session_id")
    session_task.add_argument("marker_id")
    session_task.add_argument("--title", default="")
    session_task.add_argument("--instruction", default="")
    session_task.add_argument("--json", action="store_true")
    session_revision = session_sub.add_parser("create-audio-revision-draft", help="Create an Audio Revision draft from a marker.")
    session_revision.add_argument("session_id")
    session_revision.add_argument("marker_id")
    session_revision.add_argument("--title", default="")
    session_revision.add_argument("--instruction", default="")
    session_revision.add_argument("--json", action="store_true")
    session_mix = session_sub.add_parser("create-mix-patch-draft", help="Create a Mix Patch draft from a marker.")
    session_mix.add_argument("session_id")
    session_mix.add_argument("marker_id")
    session_mix.add_argument("--title", default="")
    session_mix.add_argument("--instruction", default="")
    session_mix.add_argument("--json", action="store_true")
    session_report = session_sub.add_parser("report", help="Write and show a listening session report.")
    session_report.add_argument("session_id")
    session_report.add_argument("--json", action="store_true")
    session_close = session_sub.add_parser("close", help="Close a reviewed listening session.")
    session_close.add_argument("session_id")
    session_close.add_argument("--closed-by", default="audio-lab")
    session_close.add_argument("--json", action="store_true")

    compare = subparsers.add_parser("compare", help="Manage Audio Lab A/B comparisons.")
    compare_sub = compare.add_subparsers(dest="compare_action", required=True)
    compare_create = compare_sub.add_parser("create", help="Create an A/B comparison.")
    compare_create.add_argument("--left", required=True)
    compare_create.add_argument("--right", required=True)
    compare_create.add_argument("--json", action="store_true")
    compare_review = compare_sub.add_parser("review", help="Review an A/B comparison.")
    compare_review.add_argument("comparison_id")
    compare_review.add_argument("--preferred", choices=["left", "right", "same"], required=True)
    compare_review.add_argument("--rating", type=int, default=4)
    compare_review.add_argument("--rating-delta", type=int, default=0)
    compare_review.add_argument("--reviewer", default="developer")
    compare_review.add_argument("--role", default="developer")
    compare_review.add_argument("--notes", default="")
    compare_review.add_argument("--playback-confirmed", action="store_true")
    compare_review.add_argument("--json", action="store_true")
    compare_report = compare_sub.add_parser("report", help="Write and show an A/B comparison report.")
    compare_report.add_argument("comparison_id")
    compare_report.add_argument("--json", action="store_true")
    return parser

__all__ = ('build_verify_release_portfolio_governance_attestation_portal_parser', 'build_verify_release_portfolio_governance_attestation_portal_response_parser', 'build_verify_release_portfolio_governance_attestation_portal_review_pack_parser', 'build_verify_release_portfolio_governance_attestation_registry_parser', 'build_verify_release_portfolio_governance_attestation_transparency_acknowledgement_parser', 'build_verify_release_portfolio_governance_attestation_transparency_parser', 'build_verify_release_portfolio_governance_audit_parser', 'build_verify_release_portfolio_governance_evidence_vault_parser', 'build_verify_release_portfolio_governance_final_board_parser', 'build_verify_release_portfolio_governance_parser', 'build_verify_release_portfolio_governance_reviewer_pack_parser', 'build_verify_submission_evidence_parser', 'build_verify_submission_parser', 'build_verify_trust_operations_assurance_parser', 'build_verify_trust_operations_assurance_watch_parser', 'build_verify_trust_operations_assurance_watch_signoff_parser', 'build_verify_trust_operations_control_parser', 'build_verify_trust_operations_control_signoff_parser', 'build_verify_trust_operations_final_handoff_parser', 'build_verify_trust_operations_hub_incident_parser', 'build_verify_trust_operations_hub_parser', 'build_verify_trust_operations_hub_runbook_parser', 'build_verify_trust_operations_incident_knowledge_parser', 'build_verify_unified_command_center_archive_parser', 'build_verify_unified_command_center_continuous_review_parser', 'build_verify_unified_command_center_drift_response_parser', 'build_verify_unified_command_center_evidence_review_acceptance_parser', 'build_verify_unified_command_center_evidence_review_parser', 'build_verify_unified_command_center_handoff_parser', 'build_verify_unified_command_center_parser', 'build_verify_unified_command_center_release_train_change_control_parser', 'build_verify_unified_command_center_release_train_handoff_parser', 'build_verify_unified_command_center_release_train_lifecycle_parser', 'build_verify_unified_command_center_release_train_parser', 'build_verify_unified_command_center_reviewer_decision_board_parser', 'build_verify_unified_release_program_continuity_acceptance_change_parser', 'build_verify_unified_release_program_continuity_acceptance_parser', 'build_verify_unified_release_program_continuity_command_center_acceptance_change_parser', 'build_verify_unified_release_program_continuity_command_center_acceptance_parser', 'build_verify_unified_release_program_continuity_command_center_handoff_parser', 'build_verify_unified_release_program_continuity_command_center_parser', 'build_verify_unified_release_program_continuity_command_center_signoff_parser', 'build_verify_unified_release_program_continuity_distribution_parser', 'build_verify_unified_release_program_continuity_parser', 'build_verify_unified_release_program_handoff_parser', 'build_verify_unified_release_program_operations_parser', 'build_verify_unified_release_program_parser', 'build_verify_unified_release_program_vault_operations_parser', 'build_verify_unified_release_program_vault_parser', 'print_public_trust_center_result', 'print_release_operations_archive_result', 'print_release_operations_audit_result', 'print_release_operations_result', 'print_release_operations_reviewer_pack_result', 'print_release_operations_runbook_result', 'print_release_operations_signoff_result', 'print_release_portfolio_audit_result', 'print_release_portfolio_governance_attestation_accepted_evidence_result', 'print_release_portfolio_governance_attestation_portal_result', 'print_release_portfolio_governance_attestation_portal_review_result', 'print_release_portfolio_governance_attestation_registry_result', 'print_release_portfolio_governance_attestation_result', 'print_release_portfolio_governance_attestation_transparency_acknowledgement_result', 'print_release_portfolio_governance_attestation_transparency_result', 'print_release_portfolio_governance_audit_result', 'print_release_portfolio_governance_evidence_vault_result', 'print_release_portfolio_governance_final_board_result', 'print_release_portfolio_governance_result', 'print_release_portfolio_governance_reviewer_pack_result', 'print_release_portfolio_governance_signoff_result', 'build_audio_lab_parser')
