from __future__ import annotations


from . import dependencies as _commands_quality_parts_dependencies
AcceptanceAnalyticsStore, AcceptanceFixPlanReviewStore, AcceptanceFixPlanningStore, AcceptanceFixSprintStore, AcceptanceKnowledgeBaseStore, AcceptanceStore, AnalyticsScope, Any, AudioCampaignGovernanceStore, AudioCampaignPlannerStore, AudioCampaignRemediationStore, AudioCampaignStore, AudioEncodingProfileStore, AudioEncodingStore, AudioFixSprintStore, AudioLabStore, AudioProfileStore, AudioReviewEvidenceStore, CommandSpec, DistributionStore, EncodedAudioAcceptanceStore, FormatDecisionStore, Path, PlanningRuleGovernanceStore, PlanningRuleImpactStore, PlanningRuleSimulationStore, ProjectStore, ProviderConfig, ProviderError, ReleaseAudioBaselineGovernanceStore, ReleaseAudioCertificationStore, ReleaseAudioCommandCenterStore, ReleaseAudioQualityActionQueueSignoffStore, ReleaseAudioQualityActionQueueStore, ReleaseAudioQualityObservatoryStore, ReleaseAudioRegressionResponseStore, ReleaseAudioRegressionStore, ReleaseAudioTimelineStore, ReleaseStore, SongRequest, acceptance_analytics_summary, analyze_wav_health, argparse, audio_campaign_archive_verification_exit_code, audio_campaign_remediation_verification_exit_code, audio_campaign_verification_exit_code, audio_review_summary_public, build_acceptance_diff, build_acceptance_report, build_auth_config, default_acceptance_song_cases, encoded_audio_acceptance_summary_public, evidence_to_verifier_kwargs, fix_plan_review_summary, fix_plan_summary, fix_sprint_summary, generate_request, get_acceptance_profile, governance_summary, json, knowledge_entry_summary, knowledge_report_summary, load_provider_config, music_health_allows_review, normalize_required_profiles, os, planning_rule_impact_summary, planning_simulation_summary, promotion_summary, provider_configured, read_json, release_audio_baseline_registry_verification_exit_code, release_audio_certification_verification_exit_code, release_audio_command_center_verification_exit_code, release_audio_quality_action_queue_signoff_archive_verification_exit_code, release_audio_quality_action_queue_verification_exit_code, release_audio_quality_observatory_verification_exit_code, release_audio_regression_response_verification_exit_code, release_audio_regression_verification_exit_code, release_audio_timeline_verification_exit_code, ruleset_summary, sys, test_provider_config, unified_command_center_evidence_review_acceptance_verification_exit_code, unified_release_program_continuity_acceptance_change_verification_exit_code, unified_release_program_continuity_acceptance_verification_exit_code, unified_release_program_continuity_command_center_acceptance_change_verification_exit_code, verification_exit_code, verify_audio_campaign_archive_package, verify_audio_campaign_package, verify_audio_campaign_remediation_package, verify_release_audio_baseline_registry_package, verify_release_audio_certification_package, verify_release_audio_command_center_package, verify_release_audio_quality_action_queue_package, verify_release_audio_quality_action_queue_signoff_archive_package, verify_release_audio_quality_observatory_package, verify_release_audio_regression_package, verify_release_audio_regression_response_package, verify_release_audio_timeline_package, verify_unified_command_center_evidence_review_acceptance_package, verify_unified_release_program_continuity_acceptance_change_package, verify_unified_release_program_continuity_acceptance_package, verify_unified_release_program_continuity_command_center_acceptance_change_package, verify_unified_release_program_continuity_command_center_acceptance_package, write_audio_campaign_archive_verification_report, write_audio_campaign_remediation_verification_report, write_audio_campaign_verification_report, write_interface_document, write_json, write_release_audio_baseline_registry_verification_report, write_release_audio_certification_verification_report, write_release_audio_command_center_verification_report, write_release_audio_quality_action_queue_signoff_archive_verification_report, write_release_audio_quality_action_queue_verification_report, write_release_audio_quality_observatory_verification_report, write_release_audio_regression_response_verification_report, write_release_audio_regression_verification_report, write_release_audio_timeline_verification_report, write_unified_command_center_evidence_review_acceptance_verification_report, write_unified_release_program_continuity_acceptance_change_verification_report, write_unified_release_program_continuity_acceptance_verification_report, write_unified_release_program_continuity_command_center_acceptance_change_verification_report, write_verification_report = _commands_quality_parts_dependencies.AcceptanceAnalyticsStore, _commands_quality_parts_dependencies.AcceptanceFixPlanReviewStore, _commands_quality_parts_dependencies.AcceptanceFixPlanningStore, _commands_quality_parts_dependencies.AcceptanceFixSprintStore, _commands_quality_parts_dependencies.AcceptanceKnowledgeBaseStore, _commands_quality_parts_dependencies.AcceptanceStore, _commands_quality_parts_dependencies.AnalyticsScope, _commands_quality_parts_dependencies.Any, _commands_quality_parts_dependencies.AudioCampaignGovernanceStore, _commands_quality_parts_dependencies.AudioCampaignPlannerStore, _commands_quality_parts_dependencies.AudioCampaignRemediationStore, _commands_quality_parts_dependencies.AudioCampaignStore, _commands_quality_parts_dependencies.AudioEncodingProfileStore, _commands_quality_parts_dependencies.AudioEncodingStore, _commands_quality_parts_dependencies.AudioFixSprintStore, _commands_quality_parts_dependencies.AudioLabStore, _commands_quality_parts_dependencies.AudioProfileStore, _commands_quality_parts_dependencies.AudioReviewEvidenceStore, _commands_quality_parts_dependencies.CommandSpec, _commands_quality_parts_dependencies.DistributionStore, _commands_quality_parts_dependencies.EncodedAudioAcceptanceStore, _commands_quality_parts_dependencies.FormatDecisionStore, _commands_quality_parts_dependencies.Path, _commands_quality_parts_dependencies.PlanningRuleGovernanceStore, _commands_quality_parts_dependencies.PlanningRuleImpactStore, _commands_quality_parts_dependencies.PlanningRuleSimulationStore, _commands_quality_parts_dependencies.ProjectStore, _commands_quality_parts_dependencies.ProviderConfig, _commands_quality_parts_dependencies.ProviderError, _commands_quality_parts_dependencies.ReleaseAudioBaselineGovernanceStore, _commands_quality_parts_dependencies.ReleaseAudioCertificationStore, _commands_quality_parts_dependencies.ReleaseAudioCommandCenterStore, _commands_quality_parts_dependencies.ReleaseAudioQualityActionQueueSignoffStore, _commands_quality_parts_dependencies.ReleaseAudioQualityActionQueueStore, _commands_quality_parts_dependencies.ReleaseAudioQualityObservatoryStore, _commands_quality_parts_dependencies.ReleaseAudioRegressionResponseStore, _commands_quality_parts_dependencies.ReleaseAudioRegressionStore, _commands_quality_parts_dependencies.ReleaseAudioTimelineStore, _commands_quality_parts_dependencies.ReleaseStore, _commands_quality_parts_dependencies.SongRequest, _commands_quality_parts_dependencies.acceptance_analytics_summary, _commands_quality_parts_dependencies.analyze_wav_health, _commands_quality_parts_dependencies.argparse, _commands_quality_parts_dependencies.audio_campaign_archive_verification_exit_code, _commands_quality_parts_dependencies.audio_campaign_remediation_verification_exit_code, _commands_quality_parts_dependencies.audio_campaign_verification_exit_code, _commands_quality_parts_dependencies.audio_review_summary_public, _commands_quality_parts_dependencies.build_acceptance_diff, _commands_quality_parts_dependencies.build_acceptance_report, _commands_quality_parts_dependencies.build_auth_config, _commands_quality_parts_dependencies.default_acceptance_song_cases, _commands_quality_parts_dependencies.encoded_audio_acceptance_summary_public, _commands_quality_parts_dependencies.evidence_to_verifier_kwargs, _commands_quality_parts_dependencies.fix_plan_review_summary, _commands_quality_parts_dependencies.fix_plan_summary, _commands_quality_parts_dependencies.fix_sprint_summary, _commands_quality_parts_dependencies.generate_request, _commands_quality_parts_dependencies.get_acceptance_profile, _commands_quality_parts_dependencies.governance_summary, _commands_quality_parts_dependencies.json, _commands_quality_parts_dependencies.knowledge_entry_summary, _commands_quality_parts_dependencies.knowledge_report_summary, _commands_quality_parts_dependencies.load_provider_config, _commands_quality_parts_dependencies.music_health_allows_review, _commands_quality_parts_dependencies.normalize_required_profiles, _commands_quality_parts_dependencies.os, _commands_quality_parts_dependencies.planning_rule_impact_summary, _commands_quality_parts_dependencies.planning_simulation_summary, _commands_quality_parts_dependencies.promotion_summary, _commands_quality_parts_dependencies.provider_configured, _commands_quality_parts_dependencies.read_json, _commands_quality_parts_dependencies.release_audio_baseline_registry_verification_exit_code, _commands_quality_parts_dependencies.release_audio_certification_verification_exit_code, _commands_quality_parts_dependencies.release_audio_command_center_verification_exit_code, _commands_quality_parts_dependencies.release_audio_quality_action_queue_signoff_archive_verification_exit_code, _commands_quality_parts_dependencies.release_audio_quality_action_queue_verification_exit_code, _commands_quality_parts_dependencies.release_audio_quality_observatory_verification_exit_code, _commands_quality_parts_dependencies.release_audio_regression_response_verification_exit_code, _commands_quality_parts_dependencies.release_audio_regression_verification_exit_code, _commands_quality_parts_dependencies.release_audio_timeline_verification_exit_code, _commands_quality_parts_dependencies.ruleset_summary, _commands_quality_parts_dependencies.sys, _commands_quality_parts_dependencies.test_provider_config, _commands_quality_parts_dependencies.unified_command_center_evidence_review_acceptance_verification_exit_code, _commands_quality_parts_dependencies.unified_release_program_continuity_acceptance_change_verification_exit_code, _commands_quality_parts_dependencies.unified_release_program_continuity_acceptance_verification_exit_code, _commands_quality_parts_dependencies.unified_release_program_continuity_command_center_acceptance_change_verification_exit_code, _commands_quality_parts_dependencies.verification_exit_code, _commands_quality_parts_dependencies.verify_audio_campaign_archive_package, _commands_quality_parts_dependencies.verify_audio_campaign_package, _commands_quality_parts_dependencies.verify_audio_campaign_remediation_package, _commands_quality_parts_dependencies.verify_release_audio_baseline_registry_package, _commands_quality_parts_dependencies.verify_release_audio_certification_package, _commands_quality_parts_dependencies.verify_release_audio_command_center_package, _commands_quality_parts_dependencies.verify_release_audio_quality_action_queue_package, _commands_quality_parts_dependencies.verify_release_audio_quality_action_queue_signoff_archive_package, _commands_quality_parts_dependencies.verify_release_audio_quality_observatory_package, _commands_quality_parts_dependencies.verify_release_audio_regression_package, _commands_quality_parts_dependencies.verify_release_audio_regression_response_package, _commands_quality_parts_dependencies.verify_release_audio_timeline_package, _commands_quality_parts_dependencies.verify_unified_command_center_evidence_review_acceptance_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_acceptance_change_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_acceptance_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_command_center_acceptance_change_package, _commands_quality_parts_dependencies.verify_unified_release_program_continuity_command_center_acceptance_package, _commands_quality_parts_dependencies.write_audio_campaign_archive_verification_report, _commands_quality_parts_dependencies.write_audio_campaign_remediation_verification_report, _commands_quality_parts_dependencies.write_audio_campaign_verification_report, _commands_quality_parts_dependencies.write_interface_document, _commands_quality_parts_dependencies.write_json, _commands_quality_parts_dependencies.write_release_audio_baseline_registry_verification_report, _commands_quality_parts_dependencies.write_release_audio_certification_verification_report, _commands_quality_parts_dependencies.write_release_audio_command_center_verification_report, _commands_quality_parts_dependencies.write_release_audio_quality_action_queue_signoff_archive_verification_report, _commands_quality_parts_dependencies.write_release_audio_quality_action_queue_verification_report, _commands_quality_parts_dependencies.write_release_audio_quality_observatory_verification_report, _commands_quality_parts_dependencies.write_release_audio_regression_response_verification_report, _commands_quality_parts_dependencies.write_release_audio_regression_verification_report, _commands_quality_parts_dependencies.write_release_audio_timeline_verification_report, _commands_quality_parts_dependencies.write_unified_command_center_evidence_review_acceptance_verification_report, _commands_quality_parts_dependencies.write_unified_release_program_continuity_acceptance_change_verification_report, _commands_quality_parts_dependencies.write_unified_release_program_continuity_acceptance_verification_report, _commands_quality_parts_dependencies.write_unified_release_program_continuity_command_center_acceptance_change_verification_report, _commands_quality_parts_dependencies.write_verification_report
def build_verify_release_audio_certification_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify a MusicForge Release Audio Certification ZIP.")
    parser.add_argument("zip_path", type=Path)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--report-out", type=Path, default=None)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--require-passed", action="store_true")
    parser.add_argument("--require-signed", action="store_true")
    parser.add_argument("--require-real-audio", action="store_true")
    parser.add_argument("--require-manual-review", action="store_true")
    parser.add_argument("--require-remediation-when-needed", action="store_true")
    parser.add_argument("--max-zip-size-mb", type=int, default=128)
    parser.add_argument("--max-uncompressed-size-mb", type=int, default=512)
    parser.add_argument("--max-entry-count", type=int, default=1000)
    return parser

def build_release_audio_timeline_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage Release Audio Certification Timeline evidence.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    subparsers = parser.add_subparsers(dest="action", required=True)
    refresh = subparsers.add_parser("refresh", help="Refresh or create a Release Audio Timeline.")
    refresh.add_argument("release_id")
    refresh.add_argument("--force-new", action="store_true")
    status = subparsers.add_parser("status", help="Show Release Audio Timeline status.")
    status.add_argument("release_id")
    status.add_argument("--timeline-id", default=None)
    events = subparsers.add_parser("events", help="Show Release Audio Timeline event ledger.")
    events.add_argument("release_id")
    events.add_argument("--timeline-id", default=None)
    signoff = subparsers.add_parser("signoff", help="Sign off a passed Release Audio Timeline.")
    signoff.add_argument("release_id")
    signoff.add_argument("--timeline-id", default=None)
    signoff.add_argument("--signed-by", default="audio-timeline")
    signoff.add_argument("--role", default="audio-timeline-reviewer")
    signoff.add_argument("--reason", default="Release audio timeline accepted.")
    export = subparsers.add_parser("export", help="Export Release Audio Timeline package files.")
    export.add_argument("release_id")
    export.add_argument("--timeline-id", default=None)
    zip_cmd = subparsers.add_parser("zip", help="Build Release Audio Timeline ZIP.")
    zip_cmd.add_argument("release_id")
    zip_cmd.add_argument("--timeline-id", default=None)
    verify = subparsers.add_parser("verify", help="Verify Release Audio Timeline ZIP.")
    verify.add_argument("release_id")
    verify.add_argument("--timeline-id", default=None)
    verify.add_argument("--strict", action="store_true")
    verify.add_argument("--require-passed", action="store_true")
    verify.add_argument("--require-signed", action="store_true")
    verify.add_argument("--require-real-audio", action="store_true")
    verify.add_argument("--require-manual-review", action="store_true")
    verify.add_argument("--require-current-certification", action="store_true")
    verify.add_argument("--report-out", type=Path, default=None)
    return parser

def build_verify_release_audio_timeline_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify a MusicForge Release Audio Timeline ZIP.")
    parser.add_argument("zip_path", type=Path)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--report-out", type=Path, default=None)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--require-passed", action="store_true")
    parser.add_argument("--require-signed", action="store_true")
    parser.add_argument("--require-real-audio", action="store_true")
    parser.add_argument("--require-manual-review", action="store_true")
    parser.add_argument("--require-current-certification", action="store_true")
    parser.add_argument("--release-audio-certification", type=Path, default=None)
    parser.add_argument("--release-audio-certification-verification-report", type=Path, default=None)
    parser.add_argument("--max-zip-size-mb", type=int, default=128)
    parser.add_argument("--max-uncompressed-size-mb", type=int, default=512)
    parser.add_argument("--max-entry-count", type=int, default=1000)
    return parser

def _add_release_audio_regression_external_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--baseline-timeline", type=Path, default=None)
    parser.add_argument("--baseline-timeline-verification-report", type=Path, default=None)
    parser.add_argument("--baseline-certification", type=Path, default=None)
    parser.add_argument("--baseline-certification-verification-report", type=Path, default=None)
    parser.add_argument("--current-timeline", type=Path, default=None)
    parser.add_argument("--current-timeline-verification-report", type=Path, default=None)
    parser.add_argument("--current-certification", type=Path, default=None)
    parser.add_argument("--current-certification-verification-report", type=Path, default=None)

def build_release_audio_regression_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage Release Audio Regression Guard evidence.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    subparsers = parser.add_subparsers(dest="action", required=True)
    configure = subparsers.add_parser("configure", help="Configure a baseline/current audio regression comparison.")
    configure.add_argument("release_id")
    configure.add_argument("--baseline-release-id", default=None)
    _add_release_audio_regression_external_args(configure)
    configure.add_argument("--identity-mode", choices=["release_track_lineage", "same_artifact_repeat_check"], default=None)
    refresh = subparsers.add_parser("refresh", help="Refresh Release Audio Regression report.")
    refresh.add_argument("release_id")
    status = subparsers.add_parser("status", help="Show Release Audio Regression status.")
    status.add_argument("release_id")
    signoff = subparsers.add_parser("signoff", help="Sign off a passed Release Audio Regression report.")
    signoff.add_argument("release_id")
    signoff.add_argument("--signed-by", default="audio-regression")
    signoff.add_argument("--role", default="audio-regression-reviewer")
    signoff.add_argument("--reason", default="Release audio regression guard accepted.")
    export = subparsers.add_parser("export", help="Export Release Audio Regression package files.")
    export.add_argument("release_id")
    zip_cmd = subparsers.add_parser("zip", help="Build Release Audio Regression ZIP.")
    zip_cmd.add_argument("release_id")
    verify = subparsers.add_parser("verify", help="Verify Release Audio Regression ZIP.")
    verify.add_argument("release_id")
    verify.add_argument("--strict", action="store_true")
    verify.add_argument("--require-passed", action="store_true")
    verify.add_argument("--require-signed", action="store_true")
    verify.add_argument("--require-current", action="store_true")
    verify.add_argument("--require-baseline-current", action="store_true")
    _add_release_audio_regression_external_args(verify)
    verify.add_argument("--report-out", type=Path, default=None)
    return parser

def build_verify_release_audio_regression_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify a MusicForge Release Audio Regression ZIP.")
    parser.add_argument("zip_path", type=Path)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--report-out", type=Path, default=None)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--require-passed", action="store_true")
    parser.add_argument("--require-signed", action="store_true")
    parser.add_argument("--require-current", action="store_true")
    parser.add_argument("--require-baseline-current", action="store_true")
    _add_release_audio_regression_external_args(parser)
    parser.add_argument("--max-zip-size-mb", type=int, default=128)
    parser.add_argument("--max-uncompressed-size-mb", type=int, default=512)
    parser.add_argument("--max-entry-count", type=int, default=1000)
    return parser

def _add_release_audio_baseline_external_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--timeline", type=Path, default=None)
    parser.add_argument("--timeline-verification-report", type=Path, default=None)
    parser.add_argument("--certification", type=Path, default=None)
    parser.add_argument("--certification-verification-report", type=Path, default=None)

def build_release_audio_baseline_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage Release Audio Baseline Governance.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    subparsers = parser.add_subparsers(dest="action", required=True)
    create = subparsers.add_parser("from-release", help="Create a baseline candidate from signed Release Audio evidence.")
    create.add_argument("release_id")
    _add_release_audio_baseline_external_args(create)
    create.add_argument("--scope-type", default="release_line")
    create.add_argument("--release-line-id", default="default")
    approve = subparsers.add_parser("approve", help="Approve a baseline candidate.")
    approve.add_argument("baseline_id")
    approve.add_argument("--approved-by", default="audio-lead")
    approve.add_argument("--role", default="audio-lead")
    approve.add_argument("--reason", default="Release audio baseline approved.")
    activate = subparsers.add_parser("activate", help="Activate an approved baseline.")
    activate.add_argument("baseline_id")
    activate.add_argument("--supersede-existing", action="store_true")
    revoke = subparsers.add_parser("revoke", help="Revoke a baseline.")
    revoke.add_argument("baseline_id")
    revoke.add_argument("--reason", default="Release audio baseline revoked.")
    subparsers.add_parser("list", help="List baselines.")
    subparsers.add_parser("export", help="Export baseline registry.")
    subparsers.add_parser("zip", help="Build baseline registry ZIP.")
    verify = subparsers.add_parser("verify", help="Verify baseline registry ZIP.")
    verify.add_argument("--strict", action="store_true")
    verify.add_argument("--require-active", action="store_true")
    verify.add_argument("--report-out", type=Path, default=None)
    preflight = subparsers.add_parser("preflight-release", help="Preflight a release against a baseline.")
    preflight.add_argument("release_id")
    preflight.add_argument("baseline_id")
    _add_release_audio_baseline_external_args(preflight)
    return parser

def build_verify_release_audio_baseline_registry_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify a MusicForge Release Audio Baseline Registry ZIP.")
    parser.add_argument("zip_path", type=Path)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--require-active", action="store_true")
    parser.add_argument("--report-out", type=Path, default=None)
    return parser

def build_release_audio_regression_response_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage Release Audio Regression Response evidence.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    subparsers = parser.add_subparsers(dest="action", required=True)
    create = subparsers.add_parser("create", help="Create a regression response plan.")
    create.add_argument("release_id")
    waiver = subparsers.add_parser("waive", help="Add a warning-level waiver.")
    waiver.add_argument("release_id")
    waiver.add_argument("--action-id", required=True)
    waiver.add_argument("--reason", required=True)
    waiver.add_argument("--waived-by", default="audio-lead")
    run = subparsers.add_parser("run-safe", help="Prepare draft-only safe actions.")
    run.add_argument("release_id")
    closeout = subparsers.add_parser("closeout", help="Close response after passed Regression recheck.")
    closeout.add_argument("release_id")
    closeout.add_argument("--closed-by", default="audio-lead")
    closeout.add_argument("--reason", default="Regression response recheck passed.")
    signoff = subparsers.add_parser("signoff", help="Sign off closed response evidence.")
    signoff.add_argument("release_id")
    signoff.add_argument("--signed-by", default="audio-lead")
    signoff.add_argument("--role", default="audio-response-reviewer")
    signoff.add_argument("--reason", default="Release audio regression response accepted.")
    status = subparsers.add_parser("status", help="Show response status.")
    status.add_argument("release_id")
    export = subparsers.add_parser("export", help="Export response package files.")
    export.add_argument("release_id")
    zip_cmd = subparsers.add_parser("zip", help="Build response ZIP.")
    zip_cmd.add_argument("release_id")
    verify = subparsers.add_parser("verify", help="Verify response ZIP.")
    verify.add_argument("release_id")
    verify.add_argument("--strict", action="store_true")
    verify.add_argument("--require-closed", action="store_true")
    verify.add_argument("--require-signed", action="store_true")
    verify.add_argument("--require-regression-current", action="store_true")
    verify.add_argument("--report-out", type=Path, default=None)
    return parser

def build_verify_release_audio_regression_response_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify a MusicForge Release Audio Regression Response ZIP.")
    parser.add_argument("zip_path", type=Path)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--require-closed", action="store_true")
    parser.add_argument("--require-signed", action="store_true")
    parser.add_argument("--require-regression-current", action="store_true")
    parser.add_argument("--release-audio-regression", type=Path, default=None)
    parser.add_argument("--release-audio-regression-verification-report", type=Path, default=None)
    _add_release_audio_regression_external_args(parser)
    parser.add_argument("--report-out", type=Path, default=None)
    return parser

def build_release_audio_quality_observatory_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage Release Audio Quality Observatory evidence.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    subparsers = parser.add_subparsers(dest="action", required=True)
    create = subparsers.add_parser("create", help="Create an audio quality observatory.")
    create.add_argument("--name", default="Release Audio Quality Observatory")
    create.add_argument("--release-id", action="append", default=[], help="Release id to include. Can be repeated.")
    list_cmd = subparsers.add_parser("list", help="List observatories.")
    del list_cmd
    refresh = subparsers.add_parser("refresh", help="Refresh observatory reports from current audio evidence.")
    refresh.add_argument("observatory_id")
    status = subparsers.add_parser("status", help="Show observatory status.")
    status.add_argument("observatory_id")
    export = subparsers.add_parser("export", help="Export observatory package files.")
    export.add_argument("observatory_id")
    zip_cmd = subparsers.add_parser("zip", help="Build observatory ZIP.")
    zip_cmd.add_argument("observatory_id")
    verify = subparsers.add_parser("verify", help="Verify observatory ZIP.")
    verify.add_argument("observatory_id")
    verify.add_argument("--strict", action="store_true")
    verify.add_argument("--require-current-evidence", action="store_true")
    verify.add_argument("--require-no-critical-risk", action="store_true")
    verify.add_argument("--evidence-root", type=Path, default=None)
    verify.add_argument("--report-out", type=Path, default=None)
    return parser

def build_verify_release_audio_quality_observatory_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify a MusicForge Release Audio Quality Observatory ZIP.")
    parser.add_argument("zip_path", type=Path)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--report-out", type=Path, default=None)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--require-current-evidence", action="store_true")
    parser.add_argument("--evidence-root", type=Path, default=None)
    parser.add_argument("--require-no-critical-risk", action="store_true")
    parser.add_argument("--max-zip-size-mb", type=int, default=128)
    parser.add_argument("--max-uncompressed-size-mb", type=int, default=512)
    parser.add_argument("--max-entry-count", type=int, default=1000)
    return parser

__all__ = ('build_verify_release_audio_certification_parser', 'build_release_audio_timeline_parser', 'build_verify_release_audio_timeline_parser', '_add_release_audio_regression_external_args', 'build_release_audio_regression_parser', 'build_verify_release_audio_regression_parser', '_add_release_audio_baseline_external_args', 'build_release_audio_baseline_parser', 'build_verify_release_audio_baseline_registry_parser', 'build_release_audio_regression_response_parser', 'build_verify_release_audio_regression_response_parser', 'build_release_audio_quality_observatory_parser', 'build_verify_release_audio_quality_observatory_parser')
