from __future__ import annotations

from song_agent.interfaces.cli.bindings import BINDINGS

from song_agent.interfaces.cli.commands.delivery_parts.release_train_handoff_payload_from_args import _release_train_handoff_payload_from_args as _delivery_private_release_train_handoff_payload_from_args
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import _release_train_lifecycle_payload_from_args as _delivery_private_release_train_lifecycle_payload_from_args
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_release_encode_parser as _delivery_build_release_encode_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_release_operations_archive_parser as _delivery_build_release_operations_archive_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_release_operations_audit_parser as _delivery_build_release_operations_audit_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_release_operations_parser as _delivery_build_release_operations_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_release_operations_reviewer_pack_parser as _delivery_build_release_operations_reviewer_pack_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_release_operations_runbook_parser as _delivery_build_release_operations_runbook_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_release_operations_signoff_parser as _delivery_build_release_operations_signoff_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_verify_distribution_parser as _delivery_build_verify_distribution_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_verify_release_operations_archive_parser as _delivery_build_verify_release_operations_archive_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_verify_release_operations_audit_parser as _delivery_build_verify_release_operations_audit_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_verify_release_operations_parser as _delivery_build_verify_release_operations_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_verify_release_operations_reviewer_pack_parser as _delivery_build_verify_release_operations_reviewer_pack_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_verify_release_operations_runbook_parser as _delivery_build_verify_release_operations_runbook_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_verify_release_parser as _delivery_build_verify_release_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_verify_submission_evidence_parser as _delivery_build_verify_submission_evidence_parser
from song_agent.interfaces.cli.commands.delivery_parts.verify_release_and_adapters import build_verify_submission_parser as _delivery_build_verify_submission_parser
from song_agent.interfaces.cli.commands.delivery_parts.release_train_handoff_payload_from_args import print_release_operations_archive_result as _delivery_print_release_operations_archive_result
from song_agent.interfaces.cli.commands.delivery_parts.release_train_handoff_payload_from_args import print_release_operations_audit_result as _delivery_print_release_operations_audit_result
from song_agent.interfaces.cli.commands.delivery_parts.release_train_handoff_payload_from_args import print_release_operations_result as _delivery_print_release_operations_result
from song_agent.interfaces.cli.commands.delivery_parts.release_train_handoff_payload_from_args import print_release_operations_reviewer_pack_result as _delivery_print_release_operations_reviewer_pack_result
from song_agent.interfaces.cli.commands.delivery_parts.release_train_handoff_payload_from_args import print_release_operations_runbook_result as _delivery_print_release_operations_runbook_result
from song_agent.interfaces.cli.commands.delivery_parts.release_train_handoff_payload_from_args import print_release_operations_signoff_result as _delivery_print_release_operations_signoff_result

BINDINGS.delivery._release_train_handoff_payload_from_args = _delivery_private_release_train_handoff_payload_from_args
BINDINGS.delivery._release_train_lifecycle_payload_from_args = _delivery_private_release_train_lifecycle_payload_from_args
BINDINGS.delivery.build_release_encode_parser = _delivery_build_release_encode_parser
BINDINGS.delivery.build_release_operations_archive_parser = _delivery_build_release_operations_archive_parser
BINDINGS.delivery.build_release_operations_audit_parser = _delivery_build_release_operations_audit_parser
BINDINGS.delivery.build_release_operations_parser = _delivery_build_release_operations_parser
BINDINGS.delivery.build_release_operations_reviewer_pack_parser = _delivery_build_release_operations_reviewer_pack_parser
BINDINGS.delivery.build_release_operations_runbook_parser = _delivery_build_release_operations_runbook_parser
BINDINGS.delivery.build_release_operations_signoff_parser = _delivery_build_release_operations_signoff_parser
BINDINGS.delivery.build_verify_distribution_parser = _delivery_build_verify_distribution_parser
BINDINGS.delivery.build_verify_release_operations_archive_parser = _delivery_build_verify_release_operations_archive_parser
BINDINGS.delivery.build_verify_release_operations_audit_parser = _delivery_build_verify_release_operations_audit_parser
BINDINGS.delivery.build_verify_release_operations_parser = _delivery_build_verify_release_operations_parser
BINDINGS.delivery.build_verify_release_operations_reviewer_pack_parser = _delivery_build_verify_release_operations_reviewer_pack_parser
BINDINGS.delivery.build_verify_release_operations_runbook_parser = _delivery_build_verify_release_operations_runbook_parser
BINDINGS.delivery.build_verify_release_parser = _delivery_build_verify_release_parser
BINDINGS.delivery.build_verify_submission_evidence_parser = _delivery_build_verify_submission_evidence_parser
BINDINGS.delivery.build_verify_submission_parser = _delivery_build_verify_submission_parser
BINDINGS.delivery.print_release_operations_archive_result = _delivery_print_release_operations_archive_result
BINDINGS.delivery.print_release_operations_audit_result = _delivery_print_release_operations_audit_result
BINDINGS.delivery.print_release_operations_result = _delivery_print_release_operations_result
BINDINGS.delivery.print_release_operations_reviewer_pack_result = _delivery_print_release_operations_reviewer_pack_result
BINDINGS.delivery.print_release_operations_runbook_result = _delivery_print_release_operations_runbook_result
BINDINGS.delivery.print_release_operations_signoff_result = _delivery_print_release_operations_signoff_result
