from __future__ import annotations

from song_agent.interfaces.cli.bindings import BINDINGS

from song_agent.interfaces.cli.commands.maintenance_parts.maintenance_commands_and_presenter_adapters import _print_maintenance_result as _maintenance_private_print_maintenance_result
from song_agent.interfaces.cli.commands.maintenance_parts.maintenance_commands_and_presenter_adapters import _run_maintenance_command as _maintenance_private_run_maintenance_command
from song_agent.interfaces.cli.commands.maintenance_parts.maintenance_commands_and_presenter_adapters import build_doctor_parser as _maintenance_build_doctor_parser
from song_agent.interfaces.cli.commands.maintenance_parts.maintenance_commands_and_presenter_adapters import build_maintenance_parser as _maintenance_build_maintenance_parser
from song_agent.interfaces.cli.commands.maintenance_parts.maintenance_commands_and_presenter_adapters import build_verify_maintenance_backup_parser as _maintenance_build_verify_maintenance_backup_parser
from song_agent.interfaces.cli.commands.maintenance_parts.maintenance_commands_and_presenter_adapters import run_doctor as _maintenance_run_doctor

BINDINGS.maintenance._print_maintenance_result = _maintenance_private_print_maintenance_result
BINDINGS.maintenance._run_maintenance_command = _maintenance_private_run_maintenance_command
BINDINGS.maintenance.build_doctor_parser = _maintenance_build_doctor_parser
BINDINGS.maintenance.build_maintenance_parser = _maintenance_build_maintenance_parser
BINDINGS.maintenance.build_verify_maintenance_backup_parser = _maintenance_build_verify_maintenance_backup_parser
BINDINGS.maintenance.run_doctor = _maintenance_run_doctor
