from __future__ import annotations

from song_agent.interfaces.cli.bindings import BINDINGS

from song_agent.interfaces.cli.commands.quality_parts.planning_ruleset import _acceptance_analytics_fail_on as _quality_private_acceptance_analytics_fail_on
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import _add_command_center_acceptance_source_args as _quality_private_add_command_center_acceptance_source_args
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import _command_center_acceptance_payload as _quality_private_command_center_acceptance_payload
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import _print_audio_campaign_result as _quality_private_print_audio_campaign_result
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import _print_audio_fix_sprint_result as _quality_private_print_audio_fix_sprint_result
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import _print_audio_lab_result as _quality_private_print_audio_lab_result
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import _print_release_audio_certification_result as _quality_private_print_release_audio_certification_result
from song_agent.interfaces.cli.commands.quality_parts.release_audio_regression_command import _release_audio_command_center_evidence_from_args as _quality_private_release_audio_command_center_evidence_from_args
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint_command import _run_audio_campaign_command as _quality_private_run_audio_campaign_command
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint_command import _run_audio_fix_sprint_command as _quality_private_run_audio_fix_sprint_command
from song_agent.interfaces.cli.commands.quality_parts.acceptance_fix_plan import _run_audio_lab_command as _quality_private_run_audio_lab_command
from song_agent.interfaces.cli.commands.quality_parts.release_audio_regression_command import _run_release_audio_baseline_command as _quality_private_run_release_audio_baseline_command
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint_command import _run_release_audio_certification_command as _quality_private_run_release_audio_certification_command
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import _run_release_audio_command_center_command as _quality_private_run_release_audio_command_center_command
from song_agent.interfaces.cli.commands.quality_parts.release_audio_regression_command import _run_release_audio_quality_actions_command as _quality_private_run_release_audio_quality_actions_command
from song_agent.interfaces.cli.commands.quality_parts.release_audio_regression_command import _run_release_audio_quality_observatory_command as _quality_private_run_release_audio_quality_observatory_command
from song_agent.interfaces.cli.commands.quality_parts.release_audio_regression_command import _run_release_audio_regression_command as _quality_private_run_release_audio_regression_command
from song_agent.interfaces.cli.commands.quality_parts.release_audio_regression_command import _run_release_audio_regression_response_command as _quality_private_run_release_audio_regression_response_command
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint_command import _run_release_audio_timeline_command as _quality_private_run_release_audio_timeline_command
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_acceptance_analytics_parser as _quality_build_acceptance_analytics_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_acceptance_check_parser as _quality_build_acceptance_check_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_acceptance_diff_parser as _quality_build_acceptance_diff_parser
from song_agent.interfaces.cli.commands.quality_parts.acceptance_fix_plan import build_acceptance_fix_plan_parser as _quality_build_acceptance_fix_plan_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_acceptance_fix_sprint_parser as _quality_build_acceptance_fix_sprint_parser
from song_agent.interfaces.cli.commands.quality_parts.acceptance_fix_plan import build_acceptance_kb_parser as _quality_build_acceptance_kb_parser
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint import build_audio_campaign_parser as _quality_build_audio_campaign_parser
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint import build_audio_fix_sprint_parser as _quality_build_audio_fix_sprint_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_audio_health_parser as _quality_build_audio_health_parser
from song_agent.interfaces.cli.commands.quality_parts.audio_lab_parser_and_adapters import build_audio_lab_parser as _quality_build_audio_lab_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_audio_profile_parser as _quality_build_audio_profile_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_encoded_audio_acceptance_parser as _quality_build_encoded_audio_acceptance_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_format_decision_parser as _quality_build_format_decision_parser
from song_agent.interfaces.cli.commands.quality_parts.acceptance_fix_plan import build_planning_rule_governance_parser as _quality_build_planning_rule_governance_parser
from song_agent.interfaces.cli.commands.quality_parts.acceptance_fix_plan import build_planning_rule_impact_parser as _quality_build_planning_rule_impact_parser
from song_agent.interfaces.cli.commands.quality_parts.acceptance_fix_plan import build_planning_ruleset_parser as _quality_build_planning_ruleset_parser
from song_agent.interfaces.cli.commands.quality_parts.acceptance_fix_plan import build_planning_simulation_parser as _quality_build_planning_simulation_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_release_audio_baseline_parser as _quality_build_release_audio_baseline_parser
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint import build_release_audio_certification_parser as _quality_build_release_audio_certification_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_release_audio_command_center_parser as _quality_build_release_audio_command_center_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_release_audio_quality_actions_parser as _quality_build_release_audio_quality_actions_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_release_audio_quality_observatory_parser as _quality_build_release_audio_quality_observatory_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_release_audio_regression_parser as _quality_build_release_audio_regression_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_release_audio_regression_response_parser as _quality_build_release_audio_regression_response_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_release_audio_review_parser as _quality_build_release_audio_review_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_release_audio_timeline_parser as _quality_build_release_audio_timeline_parser
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint import build_verify_audio_campaign_archive_parser as _quality_build_verify_audio_campaign_archive_parser
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint import build_verify_audio_campaign_parser as _quality_build_verify_audio_campaign_parser
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint import build_verify_audio_campaign_remediation_parser as _quality_build_verify_audio_campaign_remediation_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_verify_release_audio_baseline_registry_parser as _quality_build_verify_release_audio_baseline_registry_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_verify_release_audio_certification_parser as _quality_build_verify_release_audio_certification_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_verify_release_audio_command_center_parser as _quality_build_verify_release_audio_command_center_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_verify_release_audio_quality_action_queue_parser as _quality_build_verify_release_audio_quality_action_queue_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import build_verify_release_audio_quality_action_queue_signoff_archive_parser as _quality_build_verify_release_audio_quality_action_queue_signoff_archive_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_verify_release_audio_quality_observatory_parser as _quality_build_verify_release_audio_quality_observatory_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_verify_release_audio_regression_parser as _quality_build_verify_release_audio_regression_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_verify_release_audio_regression_response_parser as _quality_build_verify_release_audio_regression_response_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import build_verify_release_audio_timeline_parser as _quality_build_verify_release_audio_timeline_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import print_acceptance_analytics_report as _quality_print_acceptance_analytics_report
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import print_acceptance_check_report as _quality_print_acceptance_check_report
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import print_acceptance_diff_report as _quality_print_acceptance_diff_report
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import print_acceptance_fix_plan_result as _quality_print_acceptance_fix_plan_result
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import print_acceptance_fix_sprint_result as _quality_print_acceptance_fix_sprint_result
from song_agent.interfaces.cli.commands.quality_parts.planning_ruleset import print_acceptance_kb_result as _quality_print_acceptance_kb_result
from song_agent.interfaces.cli.commands.quality_parts.planning_ruleset import print_planning_rule_governance_result as _quality_print_planning_rule_governance_result
from song_agent.interfaces.cli.commands.quality_parts.planning_ruleset import print_planning_rule_impact_result as _quality_print_planning_rule_impact_result
from song_agent.interfaces.cli.commands.quality_parts.planning_ruleset import print_planning_ruleset_result as _quality_print_planning_ruleset_result
from song_agent.interfaces.cli.commands.quality_parts.planning_ruleset import print_planning_simulation_result as _quality_print_planning_simulation_result
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import print_release_audio_review_result as _quality_print_release_audio_review_result
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import run_acceptance_check as _quality_run_acceptance_check

BINDINGS.quality._acceptance_analytics_fail_on = _quality_private_acceptance_analytics_fail_on
BINDINGS.quality._add_command_center_acceptance_source_args = _quality_private_add_command_center_acceptance_source_args
BINDINGS.quality._command_center_acceptance_payload = _quality_private_command_center_acceptance_payload
BINDINGS.quality._print_audio_campaign_result = _quality_private_print_audio_campaign_result
BINDINGS.quality._print_audio_fix_sprint_result = _quality_private_print_audio_fix_sprint_result
BINDINGS.quality._print_audio_lab_result = _quality_private_print_audio_lab_result
BINDINGS.quality._print_release_audio_certification_result = _quality_private_print_release_audio_certification_result
BINDINGS.quality._release_audio_command_center_evidence_from_args = _quality_private_release_audio_command_center_evidence_from_args
BINDINGS.quality._run_audio_campaign_command = _quality_private_run_audio_campaign_command
BINDINGS.quality._run_audio_fix_sprint_command = _quality_private_run_audio_fix_sprint_command
BINDINGS.quality._run_audio_lab_command = _quality_private_run_audio_lab_command
BINDINGS.quality._run_release_audio_baseline_command = _quality_private_run_release_audio_baseline_command
BINDINGS.quality._run_release_audio_certification_command = _quality_private_run_release_audio_certification_command
BINDINGS.quality._run_release_audio_command_center_command = _quality_private_run_release_audio_command_center_command
BINDINGS.quality._run_release_audio_quality_actions_command = _quality_private_run_release_audio_quality_actions_command
BINDINGS.quality._run_release_audio_quality_observatory_command = _quality_private_run_release_audio_quality_observatory_command
BINDINGS.quality._run_release_audio_regression_command = _quality_private_run_release_audio_regression_command
BINDINGS.quality._run_release_audio_regression_response_command = _quality_private_run_release_audio_regression_response_command
BINDINGS.quality._run_release_audio_timeline_command = _quality_private_run_release_audio_timeline_command
BINDINGS.quality.build_acceptance_analytics_parser = _quality_build_acceptance_analytics_parser
BINDINGS.quality.build_acceptance_check_parser = _quality_build_acceptance_check_parser
BINDINGS.quality.build_acceptance_diff_parser = _quality_build_acceptance_diff_parser
BINDINGS.quality.build_acceptance_fix_plan_parser = _quality_build_acceptance_fix_plan_parser
BINDINGS.quality.build_acceptance_fix_sprint_parser = _quality_build_acceptance_fix_sprint_parser
BINDINGS.quality.build_acceptance_kb_parser = _quality_build_acceptance_kb_parser
BINDINGS.quality.build_audio_campaign_parser = _quality_build_audio_campaign_parser
BINDINGS.quality.build_audio_fix_sprint_parser = _quality_build_audio_fix_sprint_parser
BINDINGS.quality.build_audio_health_parser = _quality_build_audio_health_parser
BINDINGS.quality.build_audio_lab_parser = _quality_build_audio_lab_parser
BINDINGS.quality.build_audio_profile_parser = _quality_build_audio_profile_parser
BINDINGS.quality.build_encoded_audio_acceptance_parser = _quality_build_encoded_audio_acceptance_parser
BINDINGS.quality.build_format_decision_parser = _quality_build_format_decision_parser
BINDINGS.quality.build_planning_rule_governance_parser = _quality_build_planning_rule_governance_parser
BINDINGS.quality.build_planning_rule_impact_parser = _quality_build_planning_rule_impact_parser
BINDINGS.quality.build_planning_ruleset_parser = _quality_build_planning_ruleset_parser
BINDINGS.quality.build_planning_simulation_parser = _quality_build_planning_simulation_parser
BINDINGS.quality.build_release_audio_baseline_parser = _quality_build_release_audio_baseline_parser
BINDINGS.quality.build_release_audio_certification_parser = _quality_build_release_audio_certification_parser
BINDINGS.quality.build_release_audio_command_center_parser = _quality_build_release_audio_command_center_parser
BINDINGS.quality.build_release_audio_quality_actions_parser = _quality_build_release_audio_quality_actions_parser
BINDINGS.quality.build_release_audio_quality_observatory_parser = _quality_build_release_audio_quality_observatory_parser
BINDINGS.quality.build_release_audio_regression_parser = _quality_build_release_audio_regression_parser
BINDINGS.quality.build_release_audio_regression_response_parser = _quality_build_release_audio_regression_response_parser
BINDINGS.quality.build_release_audio_review_parser = _quality_build_release_audio_review_parser
BINDINGS.quality.build_release_audio_timeline_parser = _quality_build_release_audio_timeline_parser
BINDINGS.quality.build_verify_audio_campaign_archive_parser = _quality_build_verify_audio_campaign_archive_parser
BINDINGS.quality.build_verify_audio_campaign_parser = _quality_build_verify_audio_campaign_parser
BINDINGS.quality.build_verify_audio_campaign_remediation_parser = _quality_build_verify_audio_campaign_remediation_parser
BINDINGS.quality.build_verify_release_audio_baseline_registry_parser = _quality_build_verify_release_audio_baseline_registry_parser
BINDINGS.quality.build_verify_release_audio_certification_parser = _quality_build_verify_release_audio_certification_parser
BINDINGS.quality.build_verify_release_audio_command_center_parser = _quality_build_verify_release_audio_command_center_parser
BINDINGS.quality.build_verify_release_audio_quality_action_queue_parser = _quality_build_verify_release_audio_quality_action_queue_parser
BINDINGS.quality.build_verify_release_audio_quality_action_queue_signoff_archive_parser = _quality_build_verify_release_audio_quality_action_queue_signoff_archive_parser
BINDINGS.quality.build_verify_release_audio_quality_observatory_parser = _quality_build_verify_release_audio_quality_observatory_parser
BINDINGS.quality.build_verify_release_audio_regression_parser = _quality_build_verify_release_audio_regression_parser
BINDINGS.quality.build_verify_release_audio_regression_response_parser = _quality_build_verify_release_audio_regression_response_parser
BINDINGS.quality.build_verify_release_audio_timeline_parser = _quality_build_verify_release_audio_timeline_parser
BINDINGS.quality.print_acceptance_analytics_report = _quality_print_acceptance_analytics_report
BINDINGS.quality.print_acceptance_check_report = _quality_print_acceptance_check_report
BINDINGS.quality.print_acceptance_diff_report = _quality_print_acceptance_diff_report
BINDINGS.quality.print_acceptance_fix_plan_result = _quality_print_acceptance_fix_plan_result
BINDINGS.quality.print_acceptance_fix_sprint_result = _quality_print_acceptance_fix_sprint_result
BINDINGS.quality.print_acceptance_kb_result = _quality_print_acceptance_kb_result
BINDINGS.quality.print_planning_rule_governance_result = _quality_print_planning_rule_governance_result
BINDINGS.quality.print_planning_rule_impact_result = _quality_print_planning_rule_impact_result
BINDINGS.quality.print_planning_ruleset_result = _quality_print_planning_ruleset_result
BINDINGS.quality.print_planning_simulation_result = _quality_print_planning_simulation_result
BINDINGS.quality.print_release_audio_review_result = _quality_print_release_audio_review_result
BINDINGS.quality.run_acceptance_check = _quality_run_acceptance_check
