from __future__ import annotations

from song_agent.interfaces.cli.bindings import BINDINGS

from song_agent.interfaces.cli.commands.release_check_parts.release_check_commands_and_presenter_adapters import build_ga_check_parser as _release_check_build_ga_check_parser
from song_agent.interfaces.cli.commands.release_check_parts.release_check_commands_and_presenter_adapters import build_release_check_parser as _release_check_build_release_check_parser
from song_agent.interfaces.cli.commands.release_check_parts.release_check_commands_and_presenter_adapters import build_verify_ga_readiness_parser as _release_check_build_verify_ga_readiness_parser
from song_agent.interfaces.cli.commands.release_check_parts.release_check_commands_and_presenter_adapters import print_ga_readiness_report as _release_check_print_ga_readiness_report

BINDINGS.release_check.build_ga_check_parser = _release_check_build_ga_check_parser
BINDINGS.release_check.build_release_check_parser = _release_check_build_release_check_parser
BINDINGS.release_check.build_verify_ga_readiness_parser = _release_check_build_verify_ga_readiness_parser
BINDINGS.release_check.print_ga_readiness_report = _release_check_print_ga_readiness_report
