from __future__ import annotations

from song_agent.interfaces.cli.bindings import BINDINGS

from song_agent.interfaces.cli.commands.trust_parts.public_trust_center_publication_store import _build_public_trust_center_publication_store as _trust_private_build_public_trust_center_publication_store
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import _build_public_trust_center_store as _trust_private_build_public_trust_center_store
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import _build_release_portfolio_governance_attestation_portal_store as _trust_private_build_release_portfolio_governance_attestation_portal_store
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import _trust_operations_assurance_source_payload as _trust_private_trust_operations_assurance_source_payload
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import _trust_operations_assurance_watch_source_payload as _trust_private_trust_operations_assurance_watch_source_payload
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import _trust_operations_final_readiness_source_payload as _trust_private_trust_operations_final_readiness_source_payload
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import build_public_trust_center_parser as _trust_build_public_trust_center_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_public_trust_center_publication_monitor_parser as _trust_build_public_trust_center_publication_monitor_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_public_trust_center_publication_parser as _trust_build_public_trust_center_publication_parser
from song_agent.interfaces.cli.commands.trust_parts.portfolio_parsers_and_cross_domain_adapters import build_release_portfolio_audit_parser as _trust_build_release_portfolio_audit_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_release_portfolio_governance_attestation_accepted_evidence_parser as _trust_build_release_portfolio_governance_attestation_accepted_evidence_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_release_portfolio_governance_attestation_parser as _trust_build_release_portfolio_governance_attestation_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_release_portfolio_governance_attestation_portal_parser as _trust_build_release_portfolio_governance_attestation_portal_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_release_portfolio_governance_attestation_portal_review_parser as _trust_build_release_portfolio_governance_attestation_portal_review_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_release_portfolio_governance_attestation_registry_parser as _trust_build_release_portfolio_governance_attestation_registry_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_release_portfolio_governance_attestation_transparency_acknowledgement_parser as _trust_build_release_portfolio_governance_attestation_transparency_acknowledgement_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_release_portfolio_governance_attestation_transparency_parser as _trust_build_release_portfolio_governance_attestation_transparency_parser
from song_agent.interfaces.cli.commands.trust_parts.portfolio_parsers_and_cross_domain_adapters import build_release_portfolio_governance_audit_parser as _trust_build_release_portfolio_governance_audit_parser
from song_agent.interfaces.cli.commands.trust_parts.portfolio_parsers_and_cross_domain_adapters import build_release_portfolio_governance_evidence_vault_parser as _trust_build_release_portfolio_governance_evidence_vault_parser
from song_agent.interfaces.cli.commands.trust_parts.portfolio_parsers_and_cross_domain_adapters import build_release_portfolio_governance_final_board_parser as _trust_build_release_portfolio_governance_final_board_parser
from song_agent.interfaces.cli.commands.trust_parts.portfolio_parsers_and_cross_domain_adapters import build_release_portfolio_governance_queue_parser as _trust_build_release_portfolio_governance_queue_parser
from song_agent.interfaces.cli.commands.trust_parts.portfolio_parsers_and_cross_domain_adapters import build_release_portfolio_governance_reviewer_pack_parser as _trust_build_release_portfolio_governance_reviewer_pack_parser
from song_agent.interfaces.cli.commands.trust_parts.portfolio_parsers_and_cross_domain_adapters import build_release_portfolio_governance_signoff_parser as _trust_build_release_portfolio_governance_signoff_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_trust_operations_assurance_parser as _trust_build_trust_operations_assurance_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_trust_operations_assurance_watch_parser as _trust_build_trust_operations_assurance_watch_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_trust_operations_assurance_watch_signoff_parser as _trust_build_trust_operations_assurance_watch_signoff_parser
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import build_trust_operations_control_signoff_parser as _trust_build_trust_operations_control_signoff_parser
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import build_trust_operations_controls_parser as _trust_build_trust_operations_controls_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_trust_operations_final_readiness_parser as _trust_build_trust_operations_final_readiness_parser
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import build_trust_operations_hub_incidents_parser as _trust_build_trust_operations_hub_incidents_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_trust_operations_hub_parser as _trust_build_trust_operations_hub_parser
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import build_trust_operations_hub_runbook_parser as _trust_build_trust_operations_hub_runbook_parser
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import build_trust_operations_incident_knowledge_parser as _trust_build_trust_operations_incident_knowledge_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_public_trust_center_acceptance_board_parser as _trust_build_verify_public_trust_center_acceptance_board_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_public_trust_center_acceptance_board_signoff_archive_parser as _trust_build_verify_public_trust_center_acceptance_board_signoff_archive_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_public_trust_center_anchor_registry_parser as _trust_build_verify_public_trust_center_anchor_registry_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_public_trust_center_anchor_transparency_parser as _trust_build_verify_public_trust_center_anchor_transparency_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_public_trust_center_distribution_kit_accepted_evidence_parser as _trust_build_verify_public_trust_center_distribution_kit_accepted_evidence_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_public_trust_center_distribution_kit_parser as _trust_build_verify_public_trust_center_distribution_kit_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_public_trust_center_parser as _trust_build_verify_public_trust_center_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_public_trust_center_publication_mirror_parser as _trust_build_verify_public_trust_center_publication_mirror_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_public_trust_center_publication_monitoring_parser as _trust_build_verify_public_trust_center_publication_monitoring_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_public_trust_center_publication_parser as _trust_build_verify_public_trust_center_publication_parser
from song_agent.interfaces.cli.commands.trust_parts.portfolio_parsers_and_cross_domain_adapters import build_verify_release_portfolio_audit_parser as _trust_build_verify_release_portfolio_audit_parser
from song_agent.interfaces.cli.commands.trust_parts.portfolio_parsers_and_cross_domain_adapters import build_verify_release_portfolio_governance_archive_parser as _trust_build_verify_release_portfolio_governance_archive_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_attestation_accepted_evidence_parser as _trust_build_verify_release_portfolio_governance_attestation_accepted_evidence_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_attestation_parser as _trust_build_verify_release_portfolio_governance_attestation_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_attestation_portal_parser as _trust_build_verify_release_portfolio_governance_attestation_portal_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_attestation_portal_response_parser as _trust_build_verify_release_portfolio_governance_attestation_portal_response_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_attestation_portal_review_pack_parser as _trust_build_verify_release_portfolio_governance_attestation_portal_review_pack_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_attestation_registry_parser as _trust_build_verify_release_portfolio_governance_attestation_registry_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_attestation_transparency_acknowledgement_parser as _trust_build_verify_release_portfolio_governance_attestation_transparency_acknowledgement_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_attestation_transparency_parser as _trust_build_verify_release_portfolio_governance_attestation_transparency_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_audit_parser as _trust_build_verify_release_portfolio_governance_audit_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_evidence_vault_parser as _trust_build_verify_release_portfolio_governance_evidence_vault_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_final_board_parser as _trust_build_verify_release_portfolio_governance_final_board_parser
from song_agent.interfaces.cli.commands.trust_parts.portfolio_parsers_and_cross_domain_adapters import build_verify_release_portfolio_governance_parser as _trust_build_verify_release_portfolio_governance_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_attestation import build_verify_release_portfolio_governance_reviewer_pack_parser as _trust_build_verify_release_portfolio_governance_reviewer_pack_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_verify_trust_operations_assurance_parser as _trust_build_verify_trust_operations_assurance_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_trust_operations_assurance_watch_parser as _trust_build_verify_trust_operations_assurance_watch_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_trust_operations_assurance_watch_signoff_parser as _trust_build_verify_trust_operations_assurance_watch_signoff_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_verify_trust_operations_control_parser as _trust_build_verify_trust_operations_control_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_verify_trust_operations_control_signoff_parser as _trust_build_verify_trust_operations_control_signoff_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_trust_operations_final_handoff_parser as _trust_build_verify_trust_operations_final_handoff_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_verify_trust_operations_hub_incident_parser as _trust_build_verify_trust_operations_hub_incident_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_public_trust_center import build_verify_trust_operations_hub_parser as _trust_build_verify_trust_operations_hub_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_verify_trust_operations_hub_runbook_parser as _trust_build_verify_trust_operations_hub_runbook_parser
from song_agent.interfaces.cli.commands.trust_parts.verify_trust_operations_assurance import build_verify_trust_operations_incident_knowledge_parser as _trust_build_verify_trust_operations_incident_knowledge_parser
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_public_trust_center_result as _trust_print_public_trust_center_result
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import print_release_portfolio_audit_result as _trust_print_release_portfolio_audit_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_attestation_accepted_evidence_result as _trust_print_release_portfolio_governance_attestation_accepted_evidence_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_attestation_portal_result as _trust_print_release_portfolio_governance_attestation_portal_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_attestation_portal_review_result as _trust_print_release_portfolio_governance_attestation_portal_review_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_attestation_registry_result as _trust_print_release_portfolio_governance_attestation_registry_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_attestation_result as _trust_print_release_portfolio_governance_attestation_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_attestation_transparency_acknowledgement_result as _trust_print_release_portfolio_governance_attestation_transparency_acknowledgement_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_attestation_transparency_result as _trust_print_release_portfolio_governance_attestation_transparency_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_audit_result as _trust_print_release_portfolio_governance_audit_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_evidence_vault_result as _trust_print_release_portfolio_governance_evidence_vault_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_final_board_result as _trust_print_release_portfolio_governance_final_board_result
from song_agent.interfaces.cli.commands.trust_parts.trust_operations_control_signoff import print_release_portfolio_governance_result as _trust_print_release_portfolio_governance_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_reviewer_pack_result as _trust_print_release_portfolio_governance_reviewer_pack_result
from song_agent.interfaces.cli.commands.trust_parts.release_portfolio_governance_signoff import print_release_portfolio_governance_signoff_result as _trust_print_release_portfolio_governance_signoff_result

BINDINGS.trust._build_public_trust_center_publication_store = _trust_private_build_public_trust_center_publication_store
BINDINGS.trust._build_public_trust_center_store = _trust_private_build_public_trust_center_store
BINDINGS.trust._build_release_portfolio_governance_attestation_portal_store = _trust_private_build_release_portfolio_governance_attestation_portal_store
BINDINGS.trust._trust_operations_assurance_source_payload = _trust_private_trust_operations_assurance_source_payload
BINDINGS.trust._trust_operations_assurance_watch_source_payload = _trust_private_trust_operations_assurance_watch_source_payload
BINDINGS.trust._trust_operations_final_readiness_source_payload = _trust_private_trust_operations_final_readiness_source_payload
BINDINGS.trust.build_public_trust_center_parser = _trust_build_public_trust_center_parser
BINDINGS.trust.build_public_trust_center_publication_monitor_parser = _trust_build_public_trust_center_publication_monitor_parser
BINDINGS.trust.build_public_trust_center_publication_parser = _trust_build_public_trust_center_publication_parser
BINDINGS.trust.build_release_portfolio_audit_parser = _trust_build_release_portfolio_audit_parser
BINDINGS.trust.build_release_portfolio_governance_attestation_accepted_evidence_parser = _trust_build_release_portfolio_governance_attestation_accepted_evidence_parser
BINDINGS.trust.build_release_portfolio_governance_attestation_parser = _trust_build_release_portfolio_governance_attestation_parser
BINDINGS.trust.build_release_portfolio_governance_attestation_portal_parser = _trust_build_release_portfolio_governance_attestation_portal_parser
BINDINGS.trust.build_release_portfolio_governance_attestation_portal_review_parser = _trust_build_release_portfolio_governance_attestation_portal_review_parser
BINDINGS.trust.build_release_portfolio_governance_attestation_registry_parser = _trust_build_release_portfolio_governance_attestation_registry_parser
BINDINGS.trust.build_release_portfolio_governance_attestation_transparency_acknowledgement_parser = _trust_build_release_portfolio_governance_attestation_transparency_acknowledgement_parser
BINDINGS.trust.build_release_portfolio_governance_attestation_transparency_parser = _trust_build_release_portfolio_governance_attestation_transparency_parser
BINDINGS.trust.build_release_portfolio_governance_audit_parser = _trust_build_release_portfolio_governance_audit_parser
BINDINGS.trust.build_release_portfolio_governance_evidence_vault_parser = _trust_build_release_portfolio_governance_evidence_vault_parser
BINDINGS.trust.build_release_portfolio_governance_final_board_parser = _trust_build_release_portfolio_governance_final_board_parser
BINDINGS.trust.build_release_portfolio_governance_queue_parser = _trust_build_release_portfolio_governance_queue_parser
BINDINGS.trust.build_release_portfolio_governance_reviewer_pack_parser = _trust_build_release_portfolio_governance_reviewer_pack_parser
BINDINGS.trust.build_release_portfolio_governance_signoff_parser = _trust_build_release_portfolio_governance_signoff_parser
BINDINGS.trust.build_trust_operations_assurance_parser = _trust_build_trust_operations_assurance_parser
BINDINGS.trust.build_trust_operations_assurance_watch_parser = _trust_build_trust_operations_assurance_watch_parser
BINDINGS.trust.build_trust_operations_assurance_watch_signoff_parser = _trust_build_trust_operations_assurance_watch_signoff_parser
BINDINGS.trust.build_trust_operations_control_signoff_parser = _trust_build_trust_operations_control_signoff_parser
BINDINGS.trust.build_trust_operations_controls_parser = _trust_build_trust_operations_controls_parser
BINDINGS.trust.build_trust_operations_final_readiness_parser = _trust_build_trust_operations_final_readiness_parser
BINDINGS.trust.build_trust_operations_hub_incidents_parser = _trust_build_trust_operations_hub_incidents_parser
BINDINGS.trust.build_trust_operations_hub_parser = _trust_build_trust_operations_hub_parser
BINDINGS.trust.build_trust_operations_hub_runbook_parser = _trust_build_trust_operations_hub_runbook_parser
BINDINGS.trust.build_trust_operations_incident_knowledge_parser = _trust_build_trust_operations_incident_knowledge_parser
BINDINGS.trust.build_verify_public_trust_center_acceptance_board_parser = _trust_build_verify_public_trust_center_acceptance_board_parser
BINDINGS.trust.build_verify_public_trust_center_acceptance_board_signoff_archive_parser = _trust_build_verify_public_trust_center_acceptance_board_signoff_archive_parser
BINDINGS.trust.build_verify_public_trust_center_anchor_registry_parser = _trust_build_verify_public_trust_center_anchor_registry_parser
BINDINGS.trust.build_verify_public_trust_center_anchor_transparency_parser = _trust_build_verify_public_trust_center_anchor_transparency_parser
BINDINGS.trust.build_verify_public_trust_center_distribution_kit_accepted_evidence_parser = _trust_build_verify_public_trust_center_distribution_kit_accepted_evidence_parser
BINDINGS.trust.build_verify_public_trust_center_distribution_kit_parser = _trust_build_verify_public_trust_center_distribution_kit_parser
BINDINGS.trust.build_verify_public_trust_center_parser = _trust_build_verify_public_trust_center_parser
BINDINGS.trust.build_verify_public_trust_center_publication_mirror_parser = _trust_build_verify_public_trust_center_publication_mirror_parser
BINDINGS.trust.build_verify_public_trust_center_publication_monitoring_parser = _trust_build_verify_public_trust_center_publication_monitoring_parser
BINDINGS.trust.build_verify_public_trust_center_publication_parser = _trust_build_verify_public_trust_center_publication_parser
BINDINGS.trust.build_verify_release_portfolio_audit_parser = _trust_build_verify_release_portfolio_audit_parser
BINDINGS.trust.build_verify_release_portfolio_governance_archive_parser = _trust_build_verify_release_portfolio_governance_archive_parser
BINDINGS.trust.build_verify_release_portfolio_governance_attestation_accepted_evidence_parser = _trust_build_verify_release_portfolio_governance_attestation_accepted_evidence_parser
BINDINGS.trust.build_verify_release_portfolio_governance_attestation_parser = _trust_build_verify_release_portfolio_governance_attestation_parser
BINDINGS.trust.build_verify_release_portfolio_governance_attestation_portal_parser = _trust_build_verify_release_portfolio_governance_attestation_portal_parser
BINDINGS.trust.build_verify_release_portfolio_governance_attestation_portal_response_parser = _trust_build_verify_release_portfolio_governance_attestation_portal_response_parser
BINDINGS.trust.build_verify_release_portfolio_governance_attestation_portal_review_pack_parser = _trust_build_verify_release_portfolio_governance_attestation_portal_review_pack_parser
BINDINGS.trust.build_verify_release_portfolio_governance_attestation_registry_parser = _trust_build_verify_release_portfolio_governance_attestation_registry_parser
BINDINGS.trust.build_verify_release_portfolio_governance_attestation_transparency_acknowledgement_parser = _trust_build_verify_release_portfolio_governance_attestation_transparency_acknowledgement_parser
BINDINGS.trust.build_verify_release_portfolio_governance_attestation_transparency_parser = _trust_build_verify_release_portfolio_governance_attestation_transparency_parser
BINDINGS.trust.build_verify_release_portfolio_governance_audit_parser = _trust_build_verify_release_portfolio_governance_audit_parser
BINDINGS.trust.build_verify_release_portfolio_governance_evidence_vault_parser = _trust_build_verify_release_portfolio_governance_evidence_vault_parser
BINDINGS.trust.build_verify_release_portfolio_governance_final_board_parser = _trust_build_verify_release_portfolio_governance_final_board_parser
BINDINGS.trust.build_verify_release_portfolio_governance_parser = _trust_build_verify_release_portfolio_governance_parser
BINDINGS.trust.build_verify_release_portfolio_governance_reviewer_pack_parser = _trust_build_verify_release_portfolio_governance_reviewer_pack_parser
BINDINGS.trust.build_verify_trust_operations_assurance_parser = _trust_build_verify_trust_operations_assurance_parser
BINDINGS.trust.build_verify_trust_operations_assurance_watch_parser = _trust_build_verify_trust_operations_assurance_watch_parser
BINDINGS.trust.build_verify_trust_operations_assurance_watch_signoff_parser = _trust_build_verify_trust_operations_assurance_watch_signoff_parser
BINDINGS.trust.build_verify_trust_operations_control_parser = _trust_build_verify_trust_operations_control_parser
BINDINGS.trust.build_verify_trust_operations_control_signoff_parser = _trust_build_verify_trust_operations_control_signoff_parser
BINDINGS.trust.build_verify_trust_operations_final_handoff_parser = _trust_build_verify_trust_operations_final_handoff_parser
BINDINGS.trust.build_verify_trust_operations_hub_incident_parser = _trust_build_verify_trust_operations_hub_incident_parser
BINDINGS.trust.build_verify_trust_operations_hub_parser = _trust_build_verify_trust_operations_hub_parser
BINDINGS.trust.build_verify_trust_operations_hub_runbook_parser = _trust_build_verify_trust_operations_hub_runbook_parser
BINDINGS.trust.build_verify_trust_operations_incident_knowledge_parser = _trust_build_verify_trust_operations_incident_knowledge_parser
BINDINGS.trust.print_public_trust_center_result = _trust_print_public_trust_center_result
BINDINGS.trust.print_release_portfolio_audit_result = _trust_print_release_portfolio_audit_result
BINDINGS.trust.print_release_portfolio_governance_attestation_accepted_evidence_result = _trust_print_release_portfolio_governance_attestation_accepted_evidence_result
BINDINGS.trust.print_release_portfolio_governance_attestation_portal_result = _trust_print_release_portfolio_governance_attestation_portal_result
BINDINGS.trust.print_release_portfolio_governance_attestation_portal_review_result = _trust_print_release_portfolio_governance_attestation_portal_review_result
BINDINGS.trust.print_release_portfolio_governance_attestation_registry_result = _trust_print_release_portfolio_governance_attestation_registry_result
BINDINGS.trust.print_release_portfolio_governance_attestation_result = _trust_print_release_portfolio_governance_attestation_result
BINDINGS.trust.print_release_portfolio_governance_attestation_transparency_acknowledgement_result = _trust_print_release_portfolio_governance_attestation_transparency_acknowledgement_result
BINDINGS.trust.print_release_portfolio_governance_attestation_transparency_result = _trust_print_release_portfolio_governance_attestation_transparency_result
BINDINGS.trust.print_release_portfolio_governance_audit_result = _trust_print_release_portfolio_governance_audit_result
BINDINGS.trust.print_release_portfolio_governance_evidence_vault_result = _trust_print_release_portfolio_governance_evidence_vault_result
BINDINGS.trust.print_release_portfolio_governance_final_board_result = _trust_print_release_portfolio_governance_final_board_result
BINDINGS.trust.print_release_portfolio_governance_result = _trust_print_release_portfolio_governance_result
BINDINGS.trust.print_release_portfolio_governance_reviewer_pack_result = _trust_print_release_portfolio_governance_reviewer_pack_result
BINDINGS.trust.print_release_portfolio_governance_signoff_result = _trust_print_release_portfolio_governance_signoff_result
