from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class LLMMessage:
    role: str
    content: str


class LLMProvider(Protocol):
    def complete_json(self, messages: list[LLMMessage]) -> dict:
        """Return a JSON object generated by the provider."""
        ...

