from __future__ import annotations

from . import dependencies as _commands_trust_parts_dependencies; Any, CommandSpec, DistributionStore, Path, ProviderConfig, ProviderError, PublicTrustCenterAcceptanceBoardStore, PublicTrustCenterAnchorRegistryStore, PublicTrustCenterAnchorTransparencyStore, PublicTrustCenterDistributionKitAcceptanceStore, PublicTrustCenterDistributionKitStore, PublicTrustCenterPublicationMonitoringStore, PublicTrustCenterPublicationStore, PublicTrustCenterStore, ReleaseOperationsAuditStore, ReleaseOperationsReviewerPackStore, ReleaseOperationsRunbookStore, ReleaseOperationsSignoffStore, ReleaseOperationsStore, ReleasePortfolioAuditStore, ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, ReleasePortfolioGovernanceAttestationPortalReviewStore, ReleasePortfolioGovernanceAttestationPortalStore, ReleasePortfolioGovernanceAttestationRegistryStore, ReleasePortfolioGovernanceAttestationStore, ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore, ReleasePortfolioGovernanceAttestationTransparencyStore, ReleasePortfolioGovernanceAuditStore, ReleasePortfolioGovernanceEvidenceVaultStore, ReleasePortfolioGovernanceFinalBoardStore, ReleasePortfolioGovernanceReviewerPackStore, ReleasePortfolioGovernanceSignoffStore, ReleasePortfolioGovernanceStore, ReleaseStore, SongRequest, SubmissionEvidenceStore, SubmissionStore, TrustOperationsAssuranceStore, TrustOperationsAssuranceWatchSignoffStore, TrustOperationsAssuranceWatchStore, TrustOperationsControlSignoffStore, TrustOperationsControlStore, TrustOperationsFinalReadinessStore, TrustOperationsHubRunbookStore, TrustOperationsHubStore, TrustOperationsIncidentKnowledgeStore, TrustOperationsIncidentStore, acknowledgement_summary, anchor_registry_summary, anchor_transparency_summary, argparse, base64, build_auth_config, distribution_kit_summary, generate_request, json, load_provider_config, monitoring_summary, os, portfolio_audit_summary, portfolio_governance_attestation_registry_summary, portfolio_governance_attestation_summary, portfolio_governance_audit_summary, portfolio_governance_evidence_vault_summary, portfolio_governance_final_board_summary, portfolio_governance_reviewer_pack_summary, print_public_trust_center_acceptance_board_signoff_archive_verification_report, print_public_trust_center_acceptance_board_verification_report, print_public_trust_center_anchor_registry_verification_report, print_public_trust_center_anchor_transparency_verification_report, print_public_trust_center_distribution_kit_accepted_evidence_verification_report, print_public_trust_center_distribution_kit_verification_report, print_public_trust_center_publication_monitoring_verification_report, print_public_trust_center_publication_verification_report, print_public_trust_center_verification_report, print_release_portfolio_audit_verification_report, print_release_portfolio_governance_archive_verification_report, print_release_portfolio_governance_attestation_accepted_evidence_verification_report, print_release_portfolio_governance_attestation_portal_response_verification_report, print_release_portfolio_governance_attestation_portal_review_pack_verification_report, print_release_portfolio_governance_attestation_portal_verification_report, print_release_portfolio_governance_attestation_registry_verification_report, print_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, print_release_portfolio_governance_attestation_transparency_verification_report, print_release_portfolio_governance_attestation_verification_report, print_release_portfolio_governance_audit_verification_report, print_release_portfolio_governance_evidence_vault_verification_report, print_release_portfolio_governance_final_board_verification_report, print_release_portfolio_governance_reviewer_pack_verification_report, print_release_portfolio_governance_verification_report, print_trust_operations_assurance_verification_report, print_trust_operations_assurance_watch_signoff_verification_report, print_trust_operations_assurance_watch_verification_report, print_trust_operations_control_signoff_verification_report, print_trust_operations_control_verification_report, print_trust_operations_final_handoff_verification_report, print_trust_operations_hub_incident_verification_report, print_trust_operations_hub_runbook_verification_report, print_trust_operations_hub_verification_report, print_trust_operations_incident_knowledge_verification_report, provider_configured, public_trust_center_acceptance_board_signoff_archive_verification_exit_code, public_trust_center_acceptance_board_verification_exit_code, public_trust_center_anchor_registry_verification_exit_code, public_trust_center_anchor_transparency_verification_exit_code, public_trust_center_distribution_kit_accepted_evidence_verification_exit_code, public_trust_center_distribution_kit_verification_exit_code, public_trust_center_publication_monitoring_verification_exit_code, public_trust_center_publication_verification_exit_code, public_trust_center_summary, public_trust_center_verification_exit_code, publication_summary, queue_summary, read_json, release_portfolio_audit_verification_exit_code, release_portfolio_audit_verification_summary, release_portfolio_governance_archive_verification_exit_code, release_portfolio_governance_archive_verification_summary, release_portfolio_governance_attestation_accepted_evidence_verification_exit_code, release_portfolio_governance_attestation_portal_response_summary, release_portfolio_governance_attestation_portal_review_pack_summary, release_portfolio_governance_attestation_portal_review_verification_exit_code, release_portfolio_governance_attestation_portal_summary, release_portfolio_governance_attestation_portal_verification_exit_code, release_portfolio_governance_attestation_portal_verification_summary, release_portfolio_governance_attestation_registry_verification_exit_code, release_portfolio_governance_attestation_registry_verification_summary, release_portfolio_governance_attestation_transparency_acknowledgement_verification_exit_code, release_portfolio_governance_attestation_transparency_verification_exit_code, release_portfolio_governance_attestation_verification_exit_code, release_portfolio_governance_attestation_verification_summary, release_portfolio_governance_audit_verification_exit_code, release_portfolio_governance_audit_verification_summary, release_portfolio_governance_evidence_vault_verification_exit_code, release_portfolio_governance_evidence_vault_verification_summary, release_portfolio_governance_final_board_verification_exit_code, release_portfolio_governance_final_board_verification_summary, release_portfolio_governance_reviewer_pack_verification_exit_code, release_portfolio_governance_reviewer_pack_verification_summary, release_portfolio_governance_verification_exit_code, release_portfolio_governance_verification_summary, sys, test_provider_config, transparency_summary, trust_operations_assurance_verification_exit_code, trust_operations_assurance_watch_signoff_verification_exit_code, trust_operations_assurance_watch_verification_exit_code, trust_operations_control_signoff_verification_exit_code, trust_operations_control_verification_exit_code, trust_operations_final_handoff_verification_exit_code, trust_operations_hub_incident_verification_exit_code, trust_operations_hub_runbook_verification_exit_code, trust_operations_hub_verification_exit_code, trust_operations_incident_knowledge_verification_exit_code, verify_public_trust_center_acceptance_board_package, verify_public_trust_center_acceptance_board_signoff_archive_package, verify_public_trust_center_anchor_registry_package, verify_public_trust_center_anchor_transparency_package, verify_public_trust_center_distribution_kit_accepted_evidence_package, verify_public_trust_center_distribution_kit_package, verify_public_trust_center_package, verify_public_trust_center_publication_mirror, verify_public_trust_center_publication_monitoring_package, verify_public_trust_center_publication_package, verify_release_portfolio_audit_package, verify_release_portfolio_governance_archive_package, verify_release_portfolio_governance_attestation, verify_release_portfolio_governance_attestation_accepted_evidence, verify_release_portfolio_governance_attestation_portal, verify_release_portfolio_governance_attestation_portal_response, verify_release_portfolio_governance_attestation_portal_review_pack, verify_release_portfolio_governance_attestation_registry, verify_release_portfolio_governance_attestation_transparency, verify_release_portfolio_governance_attestation_transparency_acknowledgement_package, verify_release_portfolio_governance_audit_package, verify_release_portfolio_governance_evidence_vault_package, verify_release_portfolio_governance_final_board_package, verify_release_portfolio_governance_package, verify_release_portfolio_governance_reviewer_pack, verify_trust_operations_assurance_package, verify_trust_operations_assurance_watch_package, verify_trust_operations_assurance_watch_signoff_archive_package, verify_trust_operations_control_package, verify_trust_operations_control_signoff_archive_package, verify_trust_operations_final_handoff_package, verify_trust_operations_hub_incident_package, verify_trust_operations_hub_package, verify_trust_operations_hub_runbook_package, verify_trust_operations_incident_knowledge_package, write_interface_document, write_json, write_public_trust_center_acceptance_board_signoff_archive_verification_report, write_public_trust_center_acceptance_board_verification_report, write_public_trust_center_anchor_registry_verification_report, write_public_trust_center_anchor_transparency_verification_report, write_public_trust_center_distribution_kit_accepted_evidence_verification_report, write_public_trust_center_distribution_kit_verification_report, write_public_trust_center_publication_monitoring_verification_report, write_public_trust_center_publication_verification_report, write_public_trust_center_verification_report, write_release_portfolio_audit_verification_report, write_release_portfolio_governance_archive_verification_report, write_release_portfolio_governance_attestation_accepted_evidence_verification_report, write_release_portfolio_governance_attestation_portal_response_verification_report, write_release_portfolio_governance_attestation_portal_review_pack_verification_report, write_release_portfolio_governance_attestation_portal_verification_report, write_release_portfolio_governance_attestation_registry_verification_report, write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, write_release_portfolio_governance_attestation_transparency_verification_report, write_release_portfolio_governance_attestation_verification_report, write_release_portfolio_governance_audit_verification_report, write_release_portfolio_governance_evidence_vault_verification_report, write_release_portfolio_governance_final_board_verification_report, write_release_portfolio_governance_reviewer_pack_verification_report, write_release_portfolio_governance_verification_report, write_trust_operations_assurance_verification_report, write_trust_operations_assurance_watch_signoff_verification_report, write_trust_operations_assurance_watch_verification_report, write_trust_operations_control_signoff_verification_report, write_trust_operations_control_verification_report, write_trust_operations_final_handoff_verification_report, write_trust_operations_hub_incident_verification_report, write_trust_operations_hub_runbook_verification_report, write_trust_operations_hub_verification_report, write_trust_operations_incident_knowledge_verification_report = (_commands_trust_parts_dependencies.Any, _commands_trust_parts_dependencies.CommandSpec, _commands_trust_parts_dependencies.DistributionStore, _commands_trust_parts_dependencies.Path, _commands_trust_parts_dependencies.ProviderConfig, _commands_trust_parts_dependencies.ProviderError, _commands_trust_parts_dependencies.PublicTrustCenterAcceptanceBoardStore, _commands_trust_parts_dependencies.PublicTrustCenterAnchorRegistryStore, _commands_trust_parts_dependencies.PublicTrustCenterAnchorTransparencyStore, _commands_trust_parts_dependencies.PublicTrustCenterDistributionKitAcceptanceStore, _commands_trust_parts_dependencies.PublicTrustCenterDistributionKitStore, _commands_trust_parts_dependencies.PublicTrustCenterPublicationMonitoringStore, _commands_trust_parts_dependencies.PublicTrustCenterPublicationStore, _commands_trust_parts_dependencies.PublicTrustCenterStore, _commands_trust_parts_dependencies.ReleaseOperationsAuditStore, _commands_trust_parts_dependencies.ReleaseOperationsReviewerPackStore, _commands_trust_parts_dependencies.ReleaseOperationsRunbookStore, _commands_trust_parts_dependencies.ReleaseOperationsSignoffStore, _commands_trust_parts_dependencies.ReleaseOperationsStore, _commands_trust_parts_dependencies.ReleasePortfolioAuditStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationPortalReviewStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationPortalStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationRegistryStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationTransparencyStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAuditStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceEvidenceVaultStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceFinalBoardStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceReviewerPackStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceSignoffStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceStore, _commands_trust_parts_dependencies.ReleaseStore, _commands_trust_parts_dependencies.SongRequest, _commands_trust_parts_dependencies.SubmissionEvidenceStore, _commands_trust_parts_dependencies.SubmissionStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceWatchSignoffStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceWatchStore, _commands_trust_parts_dependencies.TrustOperationsControlSignoffStore, _commands_trust_parts_dependencies.TrustOperationsControlStore, _commands_trust_parts_dependencies.TrustOperationsFinalReadinessStore, _commands_trust_parts_dependencies.TrustOperationsHubRunbookStore, _commands_trust_parts_dependencies.TrustOperationsHubStore, _commands_trust_parts_dependencies.TrustOperationsIncidentKnowledgeStore, _commands_trust_parts_dependencies.TrustOperationsIncidentStore, _commands_trust_parts_dependencies.acknowledgement_summary, _commands_trust_parts_dependencies.anchor_registry_summary, _commands_trust_parts_dependencies.anchor_transparency_summary, _commands_trust_parts_dependencies.argparse, _commands_trust_parts_dependencies.base64, _commands_trust_parts_dependencies.build_auth_config, _commands_trust_parts_dependencies.distribution_kit_summary, _commands_trust_parts_dependencies.generate_request, _commands_trust_parts_dependencies.json, _commands_trust_parts_dependencies.load_provider_config, _commands_trust_parts_dependencies.monitoring_summary, _commands_trust_parts_dependencies.os, _commands_trust_parts_dependencies.portfolio_audit_summary, _commands_trust_parts_dependencies.portfolio_governance_attestation_registry_summary, _commands_trust_parts_dependencies.portfolio_governance_attestation_summary, _commands_trust_parts_dependencies.portfolio_governance_audit_summary, _commands_trust_parts_dependencies.portfolio_governance_evidence_vault_summary, _commands_trust_parts_dependencies.portfolio_governance_final_board_summary, _commands_trust_parts_dependencies.portfolio_governance_reviewer_pack_summary, _commands_trust_parts_dependencies.print_public_trust_center_acceptance_board_signoff_archive_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_acceptance_board_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_anchor_registry_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_anchor_transparency_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_distribution_kit_accepted_evidence_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_distribution_kit_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_publication_monitoring_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_publication_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_audit_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_archive_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_accepted_evidence_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_response_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_review_pack_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_registry_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_transparency_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_audit_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_evidence_vault_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_final_board_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_reviewer_pack_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_watch_signoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_watch_verification_report, _commands_trust_parts_dependencies.print_trust_operations_control_signoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_control_verification_report, _commands_trust_parts_dependencies.print_trust_operations_final_handoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_incident_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_runbook_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_verification_report, _commands_trust_parts_dependencies.print_trust_operations_incident_knowledge_verification_report, _commands_trust_parts_dependencies.provider_configured, _commands_trust_parts_dependencies.public_trust_center_acceptance_board_signoff_archive_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_acceptance_board_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_anchor_registry_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_anchor_transparency_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_distribution_kit_accepted_evidence_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_distribution_kit_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_publication_monitoring_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_publication_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_summary, _commands_trust_parts_dependencies.public_trust_center_verification_exit_code, _commands_trust_parts_dependencies.publication_summary, _commands_trust_parts_dependencies.queue_summary, _commands_trust_parts_dependencies.read_json, _commands_trust_parts_dependencies.release_portfolio_audit_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_audit_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_archive_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_archive_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_accepted_evidence_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_response_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_review_pack_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_review_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_registry_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_registry_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_transparency_acknowledgement_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_transparency_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_audit_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_audit_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_evidence_vault_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_evidence_vault_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_final_board_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_final_board_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_reviewer_pack_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_reviewer_pack_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_verification_summary, _commands_trust_parts_dependencies.sys, _commands_trust_parts_dependencies.test_provider_config, _commands_trust_parts_dependencies.transparency_summary, _commands_trust_parts_dependencies.trust_operations_assurance_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_assurance_watch_signoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_assurance_watch_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_control_signoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_control_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_final_handoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_incident_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_runbook_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_incident_knowledge_verification_exit_code, _commands_trust_parts_dependencies.verify_public_trust_center_acceptance_board_package, _commands_trust_parts_dependencies.verify_public_trust_center_acceptance_board_signoff_archive_package, _commands_trust_parts_dependencies.verify_public_trust_center_anchor_registry_package, _commands_trust_parts_dependencies.verify_public_trust_center_anchor_transparency_package, _commands_trust_parts_dependencies.verify_public_trust_center_distribution_kit_accepted_evidence_package, _commands_trust_parts_dependencies.verify_public_trust_center_distribution_kit_package, _commands_trust_parts_dependencies.verify_public_trust_center_package, _commands_trust_parts_dependencies.verify_public_trust_center_publication_mirror, _commands_trust_parts_dependencies.verify_public_trust_center_publication_monitoring_package, _commands_trust_parts_dependencies.verify_public_trust_center_publication_package, _commands_trust_parts_dependencies.verify_release_portfolio_audit_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_archive_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_accepted_evidence, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal_response, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal_review_pack, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_registry, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_transparency, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_transparency_acknowledgement_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_audit_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_evidence_vault_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_final_board_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_reviewer_pack, _commands_trust_parts_dependencies.verify_trust_operations_assurance_package, _commands_trust_parts_dependencies.verify_trust_operations_assurance_watch_package, _commands_trust_parts_dependencies.verify_trust_operations_assurance_watch_signoff_archive_package, _commands_trust_parts_dependencies.verify_trust_operations_control_package, _commands_trust_parts_dependencies.verify_trust_operations_control_signoff_archive_package, _commands_trust_parts_dependencies.verify_trust_operations_final_handoff_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_incident_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_runbook_package, _commands_trust_parts_dependencies.verify_trust_operations_incident_knowledge_package, _commands_trust_parts_dependencies.write_interface_document, _commands_trust_parts_dependencies.write_json, _commands_trust_parts_dependencies.write_public_trust_center_acceptance_board_signoff_archive_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_acceptance_board_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_anchor_registry_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_anchor_transparency_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_distribution_kit_accepted_evidence_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_distribution_kit_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_publication_monitoring_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_publication_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_audit_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_archive_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_accepted_evidence_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_response_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_review_pack_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_registry_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_transparency_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_audit_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_evidence_vault_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_final_board_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_reviewer_pack_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_watch_signoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_watch_verification_report, _commands_trust_parts_dependencies.write_trust_operations_control_signoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_control_verification_report, _commands_trust_parts_dependencies.write_trust_operations_final_handoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_incident_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_runbook_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_verification_report, _commands_trust_parts_dependencies.write_trust_operations_incident_knowledge_verification_report)

from .release_portfolio_governance_attestation import build_release_portfolio_governance_attestation_parser, build_release_portfolio_governance_attestation_portal_parser, build_release_portfolio_governance_attestation_portal_review_parser, build_release_portfolio_governance_attestation_registry_parser

from .release_portfolio_governance_signoff import _build_release_portfolio_governance_attestation_portal_store, print_release_portfolio_governance_attestation_portal_result, print_release_portfolio_governance_attestation_portal_review_result, print_release_portfolio_governance_attestation_registry_result, print_release_portfolio_governance_attestation_result

def _execute_release_portfolio_governance_attestation(argv: list[str]) -> None:
    raw_args = ['release-portfolio-governance-attestation', *argv]
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    parser = build_release_portfolio_governance_attestation_parser()
    args = parser.parse_args(raw_args[1:])
    release_store = ReleaseStore()
    distribution_store = DistributionStore(release_store)
    submission_store = SubmissionStore(release_store, distribution_store)
    evidence_store = SubmissionEvidenceStore(submission_store)
    operations_store = ReleaseOperationsStore(release_store=release_store, distribution_store=distribution_store, submission_store=submission_store, submission_evidence_store=evidence_store)
    runbook_store = ReleaseOperationsRunbookStore(operations_store=operations_store, release_store=release_store, distribution_store=distribution_store, submission_store=submission_store, submission_evidence_store=evidence_store)
    operations_signoff_store = ReleaseOperationsSignoffStore(operations_store=operations_store, runbook_store=runbook_store, release_store=release_store)
    operations_audit_store = ReleaseOperationsAuditStore(operations_store=operations_store, runbook_store=runbook_store, signoff_store=operations_signoff_store, release_store=release_store)
    operations_reviewer_store = ReleaseOperationsReviewerPackStore(audit_store=operations_audit_store, signoff_store=operations_signoff_store, release_store=release_store)
    portfolio_store = ReleasePortfolioAuditStore(release_store=release_store, operations_store=operations_store, runbook_store=runbook_store, signoff_store=operations_signoff_store, audit_store=operations_audit_store, reviewer_pack_store=operations_reviewer_store)
    governance_store = ReleasePortfolioGovernanceStore(portfolio_store=portfolio_store, reviewer_pack_store=operations_reviewer_store, audit_store=operations_audit_store, signoff_store=operations_signoff_store)
    governance_signoff_store = ReleasePortfolioGovernanceSignoffStore(governance_store=governance_store)
    governance_audit_store = ReleasePortfolioGovernanceAuditStore(portfolio_store=portfolio_store, governance_store=governance_store, signoff_store=governance_signoff_store)
    governance_reviewer_store = ReleasePortfolioGovernanceReviewerPackStore(audit_store=governance_audit_store)
    final_board_store = ReleasePortfolioGovernanceFinalBoardStore(portfolio_store=portfolio_store, audit_store=governance_audit_store, reviewer_pack_store=governance_reviewer_store)
    vault_store = ReleasePortfolioGovernanceEvidenceVaultStore(
        portfolio_store=portfolio_store,
        governance_store=governance_store,
        signoff_store=governance_signoff_store,
        audit_store=governance_audit_store,
        reviewer_pack_store=governance_reviewer_store,
        final_board_store=final_board_store,
    )
    store = ReleasePortfolioGovernanceAttestationStore(portfolio_store=portfolio_store, final_board_store=final_board_store, evidence_vault_store=vault_store)
    portfolio_id = args.portfolio_id
    payload = {"profile": args.profile, "require_no_force": args.require_no_force}
    result: dict[str, Any] = {"ok": True, "portfolio_id": portfolio_id, "profile": args.profile}
    if args.refresh:
        report = store.refresh_report(portfolio_id, payload)
        result.update({"report": report, "summary": portfolio_governance_attestation_summary(report), "stale": store.report_is_stale(portfolio_id, report, profile=args.profile)})
    else:
        report = store.read_report(portfolio_id, profile=args.profile, default={})
        summary = portfolio_governance_attestation_summary(report) if report else {"status": "missing", "profile": args.profile}
        if report:
            summary["stale"] = store.report_is_stale(portfolio_id, report, profile=args.profile)
        result.update({"report": report, "summary": summary, "stale": summary.get("stale", False)})
    certificate = store.read_certificate(portfolio_id, profile=args.profile, default={})
    if certificate:
        result["certificate"] = certificate
    if args.export:
        manifest = store.export_attestation(portfolio_id, payload)
        result.update({"manifest": manifest})
    if args.zip:
        zip_info = store.build_zip(portfolio_id, payload)
        result.update({"zip": zip_info})
    if args.verify:
        verification = verify_release_portfolio_governance_attestation(store.zip_path(portfolio_id, args.profile), strict=args.strict, require_vault=args.require_vault, require_final_board=args.require_final_board)
        write_release_portfolio_governance_attestation_verification_report(verification, store.verification_report_path(portfolio_id, args.profile))
        result.update({"verification": verification, "verification_summary": release_portfolio_governance_attestation_verification_summary(verification)})
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print_release_portfolio_governance_attestation_result(result)
    raise SystemExit(0)

def handle_release_portfolio_governance_attestation(argv: list[str]) -> None:
    _execute_release_portfolio_governance_attestation(argv)

def _execute_release_portfolio_governance_attestation_registry(argv: list[str]) -> None:
    raw_args = ['release-portfolio-governance-attestation-registry', *argv]
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    parser = build_release_portfolio_governance_attestation_registry_parser()
    args = parser.parse_args(raw_args[1:])
    release_store = ReleaseStore()
    distribution_store = DistributionStore(release_store)
    submission_store = SubmissionStore(release_store, distribution_store)
    evidence_store = SubmissionEvidenceStore(submission_store)
    operations_store = ReleaseOperationsStore(release_store=release_store, distribution_store=distribution_store, submission_store=submission_store, submission_evidence_store=evidence_store)
    runbook_store = ReleaseOperationsRunbookStore(operations_store=operations_store, release_store=release_store, distribution_store=distribution_store, submission_store=submission_store, submission_evidence_store=evidence_store)
    operations_signoff_store = ReleaseOperationsSignoffStore(operations_store=operations_store, runbook_store=runbook_store, release_store=release_store)
    operations_audit_store = ReleaseOperationsAuditStore(operations_store=operations_store, runbook_store=runbook_store, signoff_store=operations_signoff_store, release_store=release_store)
    operations_reviewer_store = ReleaseOperationsReviewerPackStore(audit_store=operations_audit_store, signoff_store=operations_signoff_store, release_store=release_store)
    portfolio_store = ReleasePortfolioAuditStore(release_store=release_store, operations_store=operations_store, runbook_store=runbook_store, signoff_store=operations_signoff_store, audit_store=operations_audit_store, reviewer_pack_store=operations_reviewer_store)
    governance_store = ReleasePortfolioGovernanceStore(portfolio_store=portfolio_store, reviewer_pack_store=operations_reviewer_store, audit_store=operations_audit_store, signoff_store=operations_signoff_store)
    governance_signoff_store = ReleasePortfolioGovernanceSignoffStore(governance_store=governance_store)
    governance_audit_store = ReleasePortfolioGovernanceAuditStore(portfolio_store=portfolio_store, governance_store=governance_store, signoff_store=governance_signoff_store)
    governance_reviewer_store = ReleasePortfolioGovernanceReviewerPackStore(audit_store=governance_audit_store)
    final_board_store = ReleasePortfolioGovernanceFinalBoardStore(portfolio_store=portfolio_store, audit_store=governance_audit_store, reviewer_pack_store=governance_reviewer_store)
    vault_store = ReleasePortfolioGovernanceEvidenceVaultStore(
        portfolio_store=portfolio_store,
        governance_store=governance_store,
        signoff_store=governance_signoff_store,
        audit_store=governance_audit_store,
        reviewer_pack_store=governance_reviewer_store,
        final_board_store=final_board_store,
    )
    attestation_store = ReleasePortfolioGovernanceAttestationStore(portfolio_store=portfolio_store, final_board_store=final_board_store, evidence_vault_store=vault_store)
    store = ReleasePortfolioGovernanceAttestationRegistryStore(attestation_store=attestation_store)
    portfolio_id = args.portfolio_id
    payload = {"profile": args.profile}
    result: dict[str, Any] = {"ok": True, "portfolio_id": portfolio_id, "profile": args.profile}
    if args.register_current:
        registered = store.register_current_attestation(portfolio_id, {**payload, "public_url": args.public_url, "distribution_note": args.distribution_note})
        result.update({"entry": registered.get("entry"), "registry": registered.get("registry"), "existing": bool(registered.get("existing"))})
    if args.publish:
        published = store.publish_entry(portfolio_id, args.publish, {**payload, "supersede_current": args.supersede_current, "public_url": args.public_url, "distribution_note": args.distribution_note, "published_by": "cli"})
        result.update({"entry": published.get("entry"), "registry": published.get("registry")})
    if args.revoke:
        revoked = store.revoke_entry(portfolio_id, args.revoke, {**payload, "reason": args.reason, "revoked_by": "cli"})
        result.update({"entry": revoked.get("entry"), "registry": revoked.get("registry")})
    if args.refresh:
        report = store.refresh_report(portfolio_id, payload)
        result.update({"report": report})
    else:
        report = store.read_report(portfolio_id, profile=args.profile, default={})
        if report:
            result["report"] = report
    registry = result.get("registry") if isinstance(result.get("registry"), dict) else store.read_registry(portfolio_id, profile=args.profile, default={})
    result["registry"] = registry
    result["summary"] = portfolio_governance_attestation_registry_summary(registry) if registry else {"status": "missing", "profile": args.profile}
    if args.export:
        manifest = store.export_registry(portfolio_id, payload)
        result.update({"manifest": manifest})
    if args.zip:
        zip_info = store.build_zip(portfolio_id, payload)
        result.update({"zip": zip_info})
    if args.verify:
        verification = verify_release_portfolio_governance_attestation_registry(store.zip_path(portfolio_id, args.profile), strict=args.strict, require_current=args.require_current, require_published=args.require_published, require_no_revoked_current=args.require_no_revoked_current, require_accepted_evidence=args.require_accepted_evidence)
        write_release_portfolio_governance_attestation_registry_verification_report(verification, store.verification_report_path(portfolio_id, args.profile))
        result.update({"verification": verification, "verification_summary": release_portfolio_governance_attestation_registry_verification_summary(verification)})
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print_release_portfolio_governance_attestation_registry_result(result)
    raise SystemExit(0)

def handle_release_portfolio_governance_attestation_registry(argv: list[str]) -> None:
    _execute_release_portfolio_governance_attestation_registry(argv)

def _execute_release_portfolio_governance_attestation_portal(argv: list[str]) -> None:
    raw_args = ['release-portfolio-governance-attestation-portal', *argv]
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    pass
    parser = build_release_portfolio_governance_attestation_portal_parser()
    args = parser.parse_args(raw_args[1:])
    release_store = ReleaseStore()
    distribution_store = DistributionStore(release_store)
    submission_store = SubmissionStore(release_store, distribution_store)
    evidence_store = SubmissionEvidenceStore(submission_store)
    operations_store = ReleaseOperationsStore(release_store=release_store, distribution_store=distribution_store, submission_store=submission_store, submission_evidence_store=evidence_store)
    runbook_store = ReleaseOperationsRunbookStore(operations_store=operations_store, release_store=release_store, distribution_store=distribution_store, submission_store=submission_store, submission_evidence_store=evidence_store)
    operations_signoff_store = ReleaseOperationsSignoffStore(operations_store=operations_store, runbook_store=runbook_store, release_store=release_store)
    operations_audit_store = ReleaseOperationsAuditStore(operations_store=operations_store, runbook_store=runbook_store, signoff_store=operations_signoff_store, release_store=release_store)
    operations_reviewer_store = ReleaseOperationsReviewerPackStore(audit_store=operations_audit_store, signoff_store=operations_signoff_store, release_store=release_store)
    portfolio_store = ReleasePortfolioAuditStore(release_store=release_store, operations_store=operations_store, runbook_store=runbook_store, signoff_store=operations_signoff_store, audit_store=operations_audit_store, reviewer_pack_store=operations_reviewer_store)
    governance_store = ReleasePortfolioGovernanceStore(portfolio_store=portfolio_store, reviewer_pack_store=operations_reviewer_store, audit_store=operations_audit_store, signoff_store=operations_signoff_store)
    governance_signoff_store = ReleasePortfolioGovernanceSignoffStore(governance_store=governance_store)
    governance_audit_store = ReleasePortfolioGovernanceAuditStore(portfolio_store=portfolio_store, governance_store=governance_store, signoff_store=governance_signoff_store)
    governance_reviewer_store = ReleasePortfolioGovernanceReviewerPackStore(audit_store=governance_audit_store)
    final_board_store = ReleasePortfolioGovernanceFinalBoardStore(portfolio_store=portfolio_store, audit_store=governance_audit_store, reviewer_pack_store=governance_reviewer_store)
    vault_store = ReleasePortfolioGovernanceEvidenceVaultStore(
        portfolio_store=portfolio_store,
        governance_store=governance_store,
        signoff_store=governance_signoff_store,
        audit_store=governance_audit_store,
        reviewer_pack_store=governance_reviewer_store,
        final_board_store=final_board_store,
    )
    attestation_store = ReleasePortfolioGovernanceAttestationStore(portfolio_store=portfolio_store, final_board_store=final_board_store, evidence_vault_store=vault_store)
    registry_store = ReleasePortfolioGovernanceAttestationRegistryStore(attestation_store=attestation_store)
    store = ReleasePortfolioGovernanceAttestationPortalStore(registry_store=registry_store, attestation_store=attestation_store)
    portfolio_id = args.portfolio_id
    payload = {"profile": args.profile}
    result: dict[str, Any] = {"ok": True, "portfolio_id": portfolio_id, "profile": args.profile}
    if args.refresh:
        report = store.refresh_report(portfolio_id, payload)
        result.update({"report": report, "summary": release_portfolio_governance_attestation_portal_summary(report), "stale": False})
    else:
        report = store.read_report(portfolio_id, profile=args.profile, default={})
        summary = release_portfolio_governance_attestation_portal_summary(report) if report else {"status": "missing", "profile": args.profile}
        if report:
            summary["stale"] = store.report_is_stale(portfolio_id, report, profile=args.profile)
        result.update({"report": report, "summary": summary, "stale": summary.get("stale", False)})
    if args.export:
        manifest = store.export_portal(portfolio_id, payload)
        result.update({"manifest": manifest})
    if args.zip:
        zip_info = store.build_zip(portfolio_id, payload)
        result.update({"zip": zip_info})
    if args.verify:
        verification = verify_release_portfolio_governance_attestation_portal(store.zip_path(portfolio_id, args.profile), strict=args.strict, require_current=args.require_current, require_registry=args.require_registry, require_attestation=args.require_attestation, require_accepted_evidence=args.require_accepted_evidence)
        write_release_portfolio_governance_attestation_portal_verification_report(verification, store.verification_report_path(portfolio_id, args.profile))
        result.update({"verification": verification, "verification_summary": release_portfolio_governance_attestation_portal_verification_summary(verification)})
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print_release_portfolio_governance_attestation_portal_result(result)
    raise SystemExit(0)

def handle_release_portfolio_governance_attestation_portal(argv: list[str]) -> None:
    _execute_release_portfolio_governance_attestation_portal(argv)

def _execute_release_portfolio_governance_attestation_portal_review(argv: list[str]) -> None:
    raw_args = ['release-portfolio-governance-attestation-portal-review', *argv]
    pass




    pass



    parser = build_release_portfolio_governance_attestation_portal_review_parser()
    args = parser.parse_args(raw_args[1:])
    portal_store = _build_release_portfolio_governance_attestation_portal_store()
    store = ReleasePortfolioGovernanceAttestationPortalReviewStore(portal_store=portal_store)
    portfolio_id = args.portfolio_id
    result: dict[str, Any] = {"ok": True, "portfolio_id": portfolio_id, "profile": args.profile}
    if args.refresh_pack:
        pack = store.refresh_pack(portfolio_id, {"profile": args.profile})
        result.update({"review_pack": pack, "summary": release_portfolio_governance_attestation_portal_review_pack_summary(pack), "stale": False})
    else:
        pack = store.read_pack(portfolio_id, profile=args.profile, default={})
        summary = release_portfolio_governance_attestation_portal_review_pack_summary(pack) if pack else {"status": "missing", "profile": args.profile}
        if pack:
            summary["stale"] = store.pack_is_stale(portfolio_id, pack, profile=args.profile)
        result.update({"review_pack": pack, "summary": summary, "stale": summary.get("stale", False)})
    if args.export_pack:
        manifest = store.export_pack(portfolio_id, {"profile": args.profile})
        result.update({"manifest": manifest})
    if args.zip_pack:
        zip_info = store.build_pack_zip(portfolio_id, {"profile": args.profile})
        result.update({"zip": zip_info})
    if args.verify_pack:
        verification = verify_release_portfolio_governance_attestation_portal_review_pack(
            store.pack_zip_path(portfolio_id, args.profile),
            strict=args.strict,
            require_current=args.require_current,
        )
        write_release_portfolio_governance_attestation_portal_review_pack_verification_report(verification, store.pack_verification_report_path(portfolio_id, args.profile))
        result.update({"verification": verification})
    if args.import_response:
        imported = store.import_response(portfolio_id, {"profile": args.profile, "content_base64": args.content_base64})
        result.update(imported)
    if args.responses:
        result.update({"responses": store.list_responses(portfolio_id, profile=args.profile)})
    if args.response_id and not args.verify_response and not args.create_change_request:
        response = store.get_response(portfolio_id, args.response_id, profile=args.profile)
        result.update({"response": response, "response_summary": release_portfolio_governance_attestation_portal_response_summary(response)})
    if args.verify_response:
        if not args.response_id:
            parser.error("--verify-response requires --response-id")
        verification = store.verify_response(portfolio_id, args.response_id, profile=args.profile)
        result.update({"response_verification": verification})
    if args.create_change_request:
        if not args.response_id:
            parser.error("--create-change-request requires --response-id")
        change = store.create_change_request(portfolio_id, args.response_id, {"created_by": "cli"}, profile=args.profile)
        result.update(change)
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print_release_portfolio_governance_attestation_portal_review_result(result)
    raise SystemExit(0)

def handle_release_portfolio_governance_attestation_portal_review(argv: list[str]) -> None:
    _execute_release_portfolio_governance_attestation_portal_review(argv)

__all__ = ('_execute_release_portfolio_governance_attestation', 'handle_release_portfolio_governance_attestation', '_execute_release_portfolio_governance_attestation_registry', 'handle_release_portfolio_governance_attestation_registry', '_execute_release_portfolio_governance_attestation_portal', 'handle_release_portfolio_governance_attestation_portal', '_execute_release_portfolio_governance_attestation_portal_review', 'handle_release_portfolio_governance_attestation_portal_review')
