from __future__ import annotations

from .dependencies import *

from .part_003 import _add_trust_operations_assurance_source_args, _add_trust_operations_assurance_watch_source_args, _add_trust_operations_final_readiness_source_args

def build_verify_trust_operations_assurance_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a MusicForge Trust Operations Continuous Assurance Archive ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Trust Operations Assurance archive ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat strict package checks as failures.")
    verify_parser.add_argument("--require-passed", action="store_true", help="Require Assurance status to be passed.")
    verify_parser.add_argument("--require-current", action="store_true", help="Require current external source evidence.")
    _add_trust_operations_assurance_source_args(verify_parser)
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=32, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=64, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=64, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_trust_operations_hub_runbook_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a MusicForge Trust Operations Hub Runbook ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Trust Operations Hub Runbook ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat strict package checks as failures.")
    verify_parser.add_argument("--require-completed", action="store_true", help="Require safe runbook actions to have run.")
    verify_parser.add_argument("--require-no-blocked", action="store_true", help="Require no blocked safe action results.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=64, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_trust_operations_hub_incident_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a MusicForge Trust Operations Incident Board ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Trust Operations Incident Board ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat strict package checks as failures.")
    verify_parser.add_argument("--require-no-open-critical", action="store_true", help="Require no open critical incidents.")
    verify_parser.add_argument("--require-no-open-blocking", action="store_true", help="Require no open blocking incidents.")
    verify_parser.add_argument("--require-current-hub", action="store_true", help="Require external current Hub verification evidence.")
    verify_parser.add_argument("--hub-verification-report", type=Path, default=None, help="External Trust Operations Hub verification report.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=64, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_trust_operations_incident_knowledge_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a MusicForge Trust Operations Incident Knowledge ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Trust Operations Incident Knowledge ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat strict package checks as failures.")
    verify_parser.add_argument("--require-guards-passed", action="store_true", help="Require regression guards to have passed runs.")
    verify_parser.add_argument("--require-no-open-recurrence", action="store_true", help="Require no open incident recurrence.")
    verify_parser.add_argument("--incident-board-package", type=Path, default=None, help="External Trust Operations Incident Board ZIP.")
    verify_parser.add_argument("--incident-board-verification-report", type=Path, default=None, help="External Trust Operations Incident Board verification report.")
    verify_parser.add_argument("--hub-verification-report", type=Path, default=None, help="External Trust Operations Hub verification report.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=64, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_trust_operations_control_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a MusicForge Trust Operations Control ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Trust Operations Control ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat strict package checks as failures.")
    verify_parser.add_argument("--require-policy-passed", action="store_true", help="Require the control policy assessment to pass.")
    verify_parser.add_argument("--hub-package", type=Path, default=None, help="External Trust Operations Hub ZIP.")
    verify_parser.add_argument("--hub-verification-report", type=Path, default=None, help="External Trust Operations Hub verification report.")
    verify_parser.add_argument("--incident-board-package", type=Path, default=None, help="External Trust Operations Incident Board ZIP.")
    verify_parser.add_argument("--incident-board-verification-report", type=Path, default=None, help="External Trust Operations Incident Board verification report.")
    verify_parser.add_argument("--incident-knowledge-package", type=Path, default=None, help="External Trust Operations Incident Knowledge ZIP.")
    verify_parser.add_argument("--incident-knowledge-verification-report", type=Path, default=None, help="External Trust Operations Incident Knowledge verification report.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=64, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_trust_operations_control_signoff_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a MusicForge Trust Operations Control Signoff Archive ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Trust Operations Control Signoff archive ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat strict package checks as failures.")
    verify_parser.add_argument("--require-signed", action="store_true", help="Require signed Control Signoff evidence.")
    verify_parser.add_argument("--require-current", action="store_true", help="Require current external Control/Hub/Incident/Knowledge evidence.")
    verify_parser.add_argument("--control-package", type=Path, default=None, help="External Trust Operations Control ZIP.")
    verify_parser.add_argument("--control-verification-report", type=Path, default=None, help="External Trust Operations Control verification report.")
    verify_parser.add_argument("--hub-package", type=Path, default=None, help="External Trust Operations Hub ZIP.")
    verify_parser.add_argument("--hub-verification-report", type=Path, default=None, help="External Trust Operations Hub verification report.")
    verify_parser.add_argument("--incident-board-package", type=Path, default=None, help="External Trust Operations Incident Board ZIP.")
    verify_parser.add_argument("--incident-board-verification-report", type=Path, default=None, help="External Trust Operations Incident Board verification report.")
    verify_parser.add_argument("--incident-knowledge-package", type=Path, default=None, help="External Trust Operations Incident Knowledge ZIP.")
    verify_parser.add_argument("--incident-knowledge-verification-report", type=Path, default=None, help="External Trust Operations Incident Knowledge verification report.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=32, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=64, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=64, help="Maximum number of ZIP entries.")
    return verify_parser

def build_public_trust_center_publication_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build and verify MusicForge Public Trust Center Publication channels.")
    parser.add_argument("--center-id", default="ptc-default", help="Public Trust Center id.")
    parser.add_argument("--channel-id", default="public-release", help="Publication channel id.")
    parser.add_argument("--channel-name", default="Public Release Channel", help="Publication channel name.")
    parser.add_argument("--channel-type", default="public_release", help="Publication channel type.")
    parser.add_argument("--create-channel", action="store_true", help="Create the publication channel if needed.")
    parser.add_argument("--refresh", action="store_true", help="Refresh the current publication report.")
    parser.add_argument("--export", action="store_true", help="Export the publication mirror directory.")
    parser.add_argument("--zip", action="store_true", help="Build the publication ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the publication ZIP.")
    parser.add_argument("--verify-mirror", action="store_true", help="Verify the publication mirror directory.")
    parser.add_argument("--mirror-dir", type=Path, default=None, help="External mirror directory to verify. Defaults to current export.")
    parser.add_argument("--publication-id", default=None, help="Publication id. Defaults to the current publication.")
    parser.add_argument("--revoke", action="store_true", help="Revoke the publication snapshot.")
    parser.add_argument("--supersede", action="store_true", help="Create a new publication and mark the previous current one superseded.")
    parser.add_argument("--reason", default="Public Trust Center publication operation.", help="Reason for revoke/supersede operations.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--deep", action="store_true", help="Run nested package verification.")
    parser.add_argument("--require-ready", action="store_true", default=True, help="Verifier requires ready publication state.")
    parser.add_argument("--no-require-ready", dest="require_ready", action="store_false", help="Do not require ready publication state.")
    parser.add_argument("--require-acceptance-board-signoff", action="store_true", default=True, help="Verifier requires Acceptance Board signoff.")
    parser.add_argument("--no-require-acceptance-board-signoff", dest="require_acceptance_board_signoff", action="store_false", help="Do not require Acceptance Board signoff.")
    parser.add_argument("--require-anchor-current", action="store_true", default=True, help="Verifier requires current anchor evidence.")
    parser.add_argument("--no-require-anchor-current", dest="require_anchor_current", action="store_false", help="Do not require current anchor evidence.")
    parser.add_argument("--require-no-revoked", action="store_true", help="Verifier fails revoked snapshots.")
    parser.add_argument("--publication-channel-state", type=Path, default=None, help="External publication-channel-state.json used for revoke/supersede checks.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_public_trust_center_publication_monitor_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run and export MusicForge Public Trust Center Publication monitoring.")
    parser.add_argument("--center-id", default="ptc-default", help="Public Trust Center id.")
    parser.add_argument("--channel-id", default="public-release", help="Publication channel id.")
    parser.add_argument("--monitor-id", default=None, help="Publication monitor id.")
    parser.add_argument("--run-id", default=None, help="Monitoring run id.")
    parser.add_argument("--create-monitor", action="store_true", help="Create a monitor if needed.")
    parser.add_argument("--monitor-name", default="Public Release Monitor", help="Monitor display name.")
    parser.add_argument("--publication-id", default=None, help="Publication id, or current.")
    parser.add_argument("--mirror-dir", type=Path, default=None, help="Mirror directory to monitor. Defaults to publication export dir.")
    parser.add_argument("--run", action="store_true", help="Run the monitor.")
    parser.add_argument("--export", action="store_true", help="Export the monitoring package directory.")
    parser.add_argument("--zip", action="store_true", help="Build the monitoring ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the monitoring ZIP.")
    parser.add_argument("--ack-incident", default=None, help="Acknowledge an incident id.")
    parser.add_argument("--resolve-incident", default=None, help="Resolve an incident id.")
    parser.add_argument("--waive-incident", default=None, help="Waive an incident id.")
    parser.add_argument("--reopen-incident", default=None, help="Reopen an incident id.")
    parser.add_argument("--reason", default="Publication monitoring operation.", help="Reason for incident transitions.")
    parser.add_argument("--publication-channel-state", type=Path, default=None, help="External publication-channel-state.json used for current/revoke checks.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-current", action="store_true", help="Verifier requires current external channel state.")
    parser.add_argument("--require-no-revoked", action="store_true", help="Verifier fails revoked/superseded monitored publications.")
    parser.add_argument("--require-ready", action="store_true", help="Verifier requires a passed monitoring run.")
    parser.add_argument("--require-no-drift", action="store_true", help="Verifier requires no critical/high drift.")
    parser.add_argument("--require-no-open-critical-incidents", action="store_true", help="Verifier requires no open critical incident.")
    parser.add_argument("--allow-waived-incidents", action="store_true", help="Allow waived high/critical incidents as warnings.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_trust_operations_hub_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build, sign, and verify MusicForge Trust Operations Hub packages.")
    parser.add_argument("--hub-id", default=None, help="Trust Operations Hub id.")
    parser.add_argument("--name", default="Default Trust Operations Hub", help="Hub display name.")
    parser.add_argument("--create", action="store_true", help="Create the Hub if it does not exist.")
    parser.add_argument("--refresh", action="store_true", help="Refresh the Hub report.")
    parser.add_argument("--report-id", default=None, help="Hub report id. Defaults to current report when possible.")
    parser.add_argument("--export", action="store_true", help="Export the Hub package directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Hub ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the Hub ZIP.")
    parser.add_argument("--signoff", action="store_true", help="Sign off the verified Hub ZIP.")
    parser.add_argument("--signed-by", default="local-reviewer", help="Signer name for Hub signoff.")
    parser.add_argument("--reason", default="Trust Operations Hub operation.", help="Reason for signoff/change request/reset.")
    parser.add_argument("--force", action="store_true", help="Force signoff when allowed.")
    parser.add_argument("--override-reason", default="", help="Required reason for forced signoff.")
    parser.add_argument("--create-change-request", action="store_true", help="Create a Hub change request.")
    parser.add_argument("--approve-change-request", default=None, help="Approve a Hub change request id.")
    parser.add_argument("--reset-signoff", action="store_true", help="Reset Hub signoff with an approved change request.")
    parser.add_argument("--change-request-id", default=None, help="Change request id for reset.")
    parser.add_argument("--publication-channel-state", type=Path, default=None, help="External publication-channel-state.json.")
    parser.add_argument("--public-trust-center-verification", type=Path, default=None, help="External Public Trust Center verification report.")
    parser.add_argument("--publication-monitoring-verification", type=Path, default=None, help="External Publication Monitoring verification report.")
    parser.add_argument("--release-verification", type=Path, action="append", default=[], help="External Release ZIP verification report. Can be repeated.")
    parser.add_argument("--distribution-verification", type=Path, action="append", default=[], help="External Distribution package verification report. Can be repeated.")
    parser.add_argument("--submission-verification", type=Path, action="append", default=[], help="External Submission package verification report. Can be repeated.")
    parser.add_argument("--submission-evidence-verification", type=Path, action="append", default=[], help="External Submission Evidence verification report. Can be repeated.")
    parser.add_argument("--release-operations-verification", type=Path, action="append", default=[], help="External Release Operations verification report. Can be repeated.")
    parser.add_argument("--hub-signoff", type=Path, default=None, help="External Trust Operations Hub signoff sidecar JSON.")
    parser.add_argument("--hub-verification-report", type=Path, default=None, help="External Trust Operations Hub verification report used for signoff.")
    parser.add_argument("--incident-board-package", type=Path, default=None, help="External Trust Operations Incident Board ZIP.")
    parser.add_argument("--incident-board-verification-report", type=Path, default=None, help="External Trust Operations Incident Board verification report.")
    parser.add_argument("--incident-knowledge-package", type=Path, default=None, help="External Trust Operations Incident Knowledge ZIP.")
    parser.add_argument("--incident-knowledge-verification-report", type=Path, default=None, help="External Trust Operations Incident Knowledge verification report.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-ready", action="store_true", help="Verifier requires ready Hub.")
    parser.add_argument("--require-signed", action="store_true", help="Verifier requires Hub signoff summary.")
    parser.add_argument("--require-current", action="store_true", help="Verifier requires current external source evidence.")
    parser.add_argument("--require-no-critical-blockers", action="store_true", help="Verifier requires no critical blockers.")
    parser.add_argument("--require-publication-monitoring-clean", action="store_true", help="Verifier requires clean publication monitoring evidence.")
    parser.add_argument("--require-delivery-ready", action="store_true", help="Verifier requires full delivery-chain verification evidence.")
    parser.add_argument("--require-incident-closeout", action="store_true", help="Verifier requires Trust Operations Incident closeout evidence.")
    parser.add_argument("--require-incident-regression-guards", action="store_true", help="Verifier requires Trust Operations Incident Knowledge regression guard evidence.")
    parser.add_argument("--require-trust-controls", action="store_true", help="Verifier requires Trust Operations Control policy evidence.")
    parser.add_argument("--trust-control-package", type=Path, default=None, help="External Trust Operations Control ZIP.")
    parser.add_argument("--trust-control-verification-report", type=Path, default=None, help="External Trust Operations Control verification report.")
    parser.add_argument("--require-trust-control-signoff", action="store_true", help="Verifier requires Trust Operations Control Signoff archive evidence.")
    parser.add_argument("--trust-control-signoff-archive", type=Path, default=None, help="External Trust Operations Control Signoff Archive ZIP.")
    parser.add_argument("--trust-control-signoff-verification-report", type=Path, default=None, help="External Trust Operations Control Signoff verification report.")
    parser.add_argument("--require-continuous-assurance", action="store_true", help="Verifier requires Trust Operations Continuous Assurance evidence.")
    parser.add_argument("--continuous-assurance-archive", type=Path, default=None, help="External Trust Operations Continuous Assurance Archive ZIP.")
    parser.add_argument("--continuous-assurance-verification-report", type=Path, default=None, help="External Trust Operations Continuous Assurance verification report.")
    parser.add_argument("--require-assurance-watch-clear", action="store_true", help="Verifier requires Trust Operations Assurance Watch clear evidence.")
    parser.add_argument("--assurance-watch-package", type=Path, default=None, help="External Trust Operations Assurance Watch ZIP.")
    parser.add_argument("--assurance-watch-verification-report", type=Path, default=None, help="External Trust Operations Assurance Watch verification report.")
    parser.add_argument("--require-assurance-watch-signoff", action="store_true", help="Verifier requires Trust Operations Assurance Watch Signoff archive evidence.")
    parser.add_argument("--assurance-watch-signoff-archive", type=Path, default=None, help="External Trust Operations Assurance Watch Signoff Archive ZIP.")
    parser.add_argument("--assurance-watch-signoff-verification-report", type=Path, default=None, help="External Trust Operations Assurance Watch Signoff verification report.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_trust_operations_assurance_watch_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build and verify Trust Operations Assurance Watch queues.")
    parser.add_argument("--schedule-id", default="default", help="Assurance Watch schedule id.")
    parser.add_argument("--queue-id", default=None, help="Assurance Watch queue id.")
    parser.add_argument("--hub-id", default=None, help="Trust Operations Hub id.")
    parser.add_argument("--write-schedule", action="store_true", help="Create or update the Assurance Watch schedule.")
    parser.add_argument("--interval-days", type=int, default=None, help="Schedule interval in days.")
    parser.add_argument("--grace-days", type=int, default=None, help="Schedule grace window in days.")
    parser.add_argument("--refresh", action="store_true", help="Refresh the Watch queue.")
    parser.add_argument("--list", action="store_true", help="List Watch queues.")
    parser.add_argument("--export", action="store_true", help="Export the Watch archive directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Watch ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the Watch ZIP.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-clear", action="store_true", default=True, help="Verifier requires the Watch queue to be clear.")
    parser.add_argument("--no-require-clear", dest="require_clear", action="store_false", help="Do not require the Watch queue to be clear.")
    parser.add_argument("--require-current", action="store_true", default=True, help="Verifier requires current external evidence.")
    parser.add_argument("--no-require-current", dest="require_current", action="store_false", help="Do not require current external evidence.")
    _add_trust_operations_assurance_watch_source_args(parser)
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_trust_operations_assurance_watch_signoff_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Sign, archive, and verify Trust Operations Assurance Watch closeout evidence.")
    parser.add_argument("--queue-id", required=True, help="Assurance Watch queue id.")
    parser.add_argument("--refresh-closeout", action="store_true", help="Refresh the Assurance Watch closeout.")
    parser.add_argument("--sign", action="store_true", help="Sign the current passed closeout.")
    parser.add_argument("--signed-by", default="local-reviewer", help="Signer name.")
    parser.add_argument("--role", default="owner", help="Signer role.")
    parser.add_argument("--reason", default="Assurance Watch queue clear and verified.", help="Signoff/change request reason.")
    parser.add_argument("--create-change-request", action="store_true", help="Create a signoff reset change request.")
    parser.add_argument("--approve-change-request", default=None, help="Approve a change request id.")
    parser.add_argument("--reset-signoff", default=None, help="Reset signoff with an approved change request id.")
    parser.add_argument("--export", action="store_true", help="Export the signoff archive directory.")
    parser.add_argument("--zip", action="store_true", help="Build the signoff archive ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the signoff archive ZIP.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-signed", action="store_true", default=True, help="Verifier requires signed evidence.")
    parser.add_argument("--no-require-signed", dest="require_signed", action="store_false", help="Do not require signed evidence.")
    parser.add_argument("--require-current", action="store_true", default=True, help="Verifier requires current external evidence.")
    parser.add_argument("--no-require-current", dest="require_current", action="store_false", help="Do not require current external evidence.")
    parser.add_argument("--watch-package", type=Path, default=None, help="External Trust Operations Assurance Watch ZIP.")
    parser.add_argument("--watch-verification-report", type=Path, default=None, help="External Trust Operations Assurance Watch verification report.")
    parser.add_argument("--hub-package", type=Path, default=None, help="External Trust Operations Hub ZIP.")
    parser.add_argument("--hub-verification-report", type=Path, default=None, help="External Trust Operations Hub verification report.")
    parser.add_argument("--continuous-assurance-report", type=Path, default=None, help="External Trust Operations Continuous Assurance verification report.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_trust_operations_final_readiness_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create, sign, archive, and verify Trust Operations Final Readiness handoff evidence.")
    parser.add_argument("--refresh-report", action="store_true", help="Refresh the Final Readiness report.")
    parser.add_argument("--create-certificate", action="store_true", help="Create the Final Readiness certificate.")
    parser.add_argument("--sign", action="store_true", help="Sign the Final Handoff.")
    parser.add_argument("--signed-by", default="local-reviewer", help="Signer name.")
    parser.add_argument("--role", default="owner", help="Signer role.")
    parser.add_argument("--reason", default="Trust Operations final readiness accepted.", help="Signoff/change request reason.")
    parser.add_argument("--create-change-request", action="store_true", help="Create a Final Handoff reset change request.")
    parser.add_argument("--approve-change-request", default=None, help="Approve a change request id.")
    parser.add_argument("--reset-signoff", default=None, help="Reset Final Handoff with an approved change request id.")
    parser.add_argument("--export", action="store_true", help="Export the Final Handoff directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Final Handoff ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the Final Handoff ZIP.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-signed", action="store_true", default=True, help="Verifier requires signed evidence.")
    parser.add_argument("--no-require-signed", dest="require_signed", action="store_false", help="Do not require signed evidence.")
    parser.add_argument("--require-current", action="store_true", default=True, help="Verifier requires current external evidence.")
    parser.add_argument("--no-require-current", dest="require_current", action="store_false", help="Do not require current external evidence.")
    _add_trust_operations_final_readiness_source_args(parser)
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_trust_operations_assurance_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build and verify Trust Operations Continuous Assurance archives.")
    parser.add_argument("--hub-id", default="hub", help="Trust Operations Hub id.")
    parser.add_argument("--run-id", default=None, help="Assurance run id.")
    parser.add_argument("--policy-id", default="default", help="Assurance policy id.")
    parser.add_argument("--refresh", action="store_true", help="Refresh and persist an Assurance run.")
    parser.add_argument("--list", action="store_true", help="List Assurance runs.")
    parser.add_argument("--export", action="store_true", help="Export the Assurance archive directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Assurance ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the Assurance ZIP.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-passed", action="store_true", default=True, help="Verifier requires passed Assurance.")
    parser.add_argument("--no-require-passed", dest="require_passed", action="store_false", help="Do not require passed Assurance.")
    parser.add_argument("--require-current", action="store_true", default=True, help="Verifier requires current external evidence.")
    parser.add_argument("--no-require-current", dest="require_current", action="store_false", help="Do not require current external evidence.")
    _add_trust_operations_assurance_source_args(parser)
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

__all__ = ('build_verify_trust_operations_assurance_parser', 'build_verify_trust_operations_hub_runbook_parser', 'build_verify_trust_operations_hub_incident_parser', 'build_verify_trust_operations_incident_knowledge_parser', 'build_verify_trust_operations_control_parser', 'build_verify_trust_operations_control_signoff_parser', 'build_public_trust_center_publication_parser', 'build_public_trust_center_publication_monitor_parser', 'build_trust_operations_hub_parser', 'build_trust_operations_assurance_watch_parser', 'build_trust_operations_assurance_watch_signoff_parser', 'build_trust_operations_final_readiness_parser', 'build_trust_operations_assurance_parser')
