from __future__ import annotations

from .dependencies import *

def build_release_portfolio_governance_attestation_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build and verify local MusicForge Release Portfolio Governance Public Attestation packages.")
    parser.add_argument("--portfolio-id", required=True, help="Release Portfolio Audit id.")
    parser.add_argument("--profile", default="public_summary", help="Attestation profile: public_summary, partner_due_diligence, or internal_public_preview.")
    parser.add_argument("--refresh", action="store_true", help="Refresh the Public Attestation Report.")
    parser.add_argument("--export", action="store_true", help="Build the Public Attestation export directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Public Attestation ZIP package.")
    parser.add_argument("--verify", action="store_true", help="Verify the Public Attestation ZIP package.")
    parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    parser.add_argument("--require-vault", action="store_true", help="Require passed deep Evidence Vault verification.")
    parser.add_argument("--require-final-board", action="store_true", help="Require Final Board signoff evidence.")
    parser.add_argument("--require-no-force", action="store_true", help="Fail when force-signed governance evidence is present.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_release_portfolio_governance_attestation_registry_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage local MusicForge Release Portfolio Governance Public Attestation registries.")
    parser.add_argument("--portfolio-id", required=True, help="Release Portfolio Audit id.")
    parser.add_argument("--profile", default="public_summary", help="Attestation profile.")
    parser.add_argument("--register-current", action="store_true", help="Register the current verified Public Attestation ZIP.")
    parser.add_argument("--publish", metavar="ENTRY_ID", default=None, help="Publish a registry entry.")
    parser.add_argument("--supersede-current", action="store_true", help="Allow publish to supersede the current entry.")
    parser.add_argument("--revoke", metavar="ENTRY_ID", default=None, help="Revoke a published or superseded registry entry.")
    parser.add_argument("--reason", default="", help="Revocation reason.")
    parser.add_argument("--public-url", default="", help="Optional public URL for the published entry.")
    parser.add_argument("--distribution-note", default="", help="Optional public distribution note.")
    parser.add_argument("--refresh", action="store_true", help="Refresh the registry report.")
    parser.add_argument("--export", action="store_true", help="Build the registry export directory.")
    parser.add_argument("--zip", action="store_true", help="Build the registry ZIP package.")
    parser.add_argument("--verify", action="store_true", help="Verify the registry ZIP package.")
    parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    parser.add_argument("--require-current", action="store_true", help="Require a current published registry entry.")
    parser.add_argument("--require-published", action="store_true", help="Require at least one published registry entry.")
    parser.add_argument("--require-no-revoked-current", action="store_true", help="Fail when the current registry entry is revoked.")
    parser.add_argument("--require-accepted-evidence", action="store_true", help="Require current accepted external review evidence.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_release_portfolio_governance_attestation_portal_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build and verify local MusicForge Release Portfolio Governance Public Attestation Portal snapshots.")
    parser.add_argument("--portfolio-id", required=True, help="Release Portfolio Audit id.")
    parser.add_argument("--profile", default="public_summary", help="Attestation profile.")
    parser.add_argument("--refresh", action="store_true", help="Refresh the Attestation Portal Report.")
    parser.add_argument("--export", action="store_true", help="Build the Attestation Portal export directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Attestation Portal ZIP package.")
    parser.add_argument("--verify", action="store_true", help="Verify the Attestation Portal ZIP package.")
    parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    parser.add_argument("--require-current", action="store_true", help="Require a current published portal entry.")
    parser.add_argument("--require-registry", action="store_true", help="Require passed Attestation Registry evidence.")
    parser.add_argument("--require-attestation", action="store_true", help="Require passed Public Attestation evidence.")
    parser.add_argument("--require-accepted-evidence", action="store_true", help="Require current accepted external review evidence.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_release_portfolio_governance_attestation_portal_review_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build local MusicForge Public Attestation Portal review packs and import external responses.")
    parser.add_argument("--portfolio-id", required=True, help="Release Portfolio Audit id.")
    parser.add_argument("--profile", default="public_summary", help="Attestation profile.")
    parser.add_argument("--refresh-pack", action="store_true", help="Refresh the Portal Review Pack.")
    parser.add_argument("--export-pack", action="store_true", help="Build the Portal Review Pack export directory.")
    parser.add_argument("--zip-pack", action="store_true", help="Build the Portal Review Pack ZIP.")
    parser.add_argument("--verify-pack", action="store_true", help="Verify the Portal Review Pack ZIP.")
    parser.add_argument("--import-response", action="store_true", help="Import an external Portal Review Response from content_base64.")
    parser.add_argument("--content-base64", default="", help="Base64 JSON or ZIP response payload for --import-response.")
    parser.add_argument("--response-id", default="", help="Response id for detail, verify, or Change Request creation.")
    parser.add_argument("--responses", action="store_true", help="List imported responses.")
    parser.add_argument("--verify-response", action="store_true", help="Verify an imported response.")
    parser.add_argument("--create-change-request", action="store_true", help="Create a Change Request draft from a needs_changes/rejected response.")
    parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    parser.add_argument("--require-current", action="store_true", help="Require current source evidence when verifying.")
    parser.add_argument("--require-pack", action="store_true", help="Require response to bind to a Review Pack source.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_release_portfolio_governance_attestation_accepted_evidence_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage local MusicForge Public Attestation Accepted Evidence packages.")
    parser.add_argument("--portfolio-id", required=True, help="Release Portfolio Audit id.")
    parser.add_argument("--profile", default="public_summary", help="Attestation profile.")
    parser.add_argument("--refresh", action="store_true", help="Refresh Accepted Evidence from an accepted Portal Review Response.")
    parser.add_argument("--response-id", default="", help="Accepted Portal Review Response id.")
    parser.add_argument("--export", action="store_true", help="Build the Accepted Evidence export directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Accepted Evidence ZIP package.")
    parser.add_argument("--verify", action="store_true", help="Verify the Accepted Evidence ZIP package.")
    parser.add_argument("--archive", action="store_true", help="Archive current Accepted Evidence.")
    parser.add_argument("--reason", default="", help="Archive reason.")
    parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    parser.add_argument("--require-current", action="store_true", help="Require current accepted evidence when verifying.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_release_portfolio_governance_attestation_transparency_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage local MusicForge Public Attestation Transparency Feed packages.")
    parser.add_argument("--portfolio-id", required=True, help="Release Portfolio Audit id.")
    parser.add_argument("--profile", default="public_summary", help="Attestation profile.")
    parser.add_argument("--refresh", action="store_true", help="Refresh the Transparency Feed.")
    parser.add_argument("--export", action="store_true", help="Build the Transparency export directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Transparency ZIP package.")
    parser.add_argument("--verify", action="store_true", help="Verify the Transparency ZIP package.")
    parser.add_argument("--notices", action="store_true", help="List current change notices.")
    parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    parser.add_argument("--require-current", action="store_true", help="Require a current published registry entry.")
    parser.add_argument("--require-accepted-evidence", action="store_true", help="Require current accepted external review evidence.")
    parser.add_argument("--require-no-revoked-current", action="store_true", help="Fail when the current registry entry is revoked.")
    parser.add_argument("--require-contiguous-chain", action="store_true", help="Require a valid contiguous transparency event chain.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_release_portfolio_governance_attestation_transparency_acknowledgement_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage local MusicForge Public Attestation Transparency Acknowledgement packages.")
    parser.add_argument("--portfolio-id", required=True, help="Release Portfolio Audit id.")
    parser.add_argument("--profile", default="public_summary", help="Attestation profile.")
    parser.add_argument("--refresh-pack", action="store_true", help="Refresh the Transparency Acknowledgement Pack.")
    parser.add_argument("--export-pack", action="store_true", help="Build the Acknowledgement Pack export directory.")
    parser.add_argument("--zip-pack", action="store_true", help="Build the Acknowledgement Pack ZIP package.")
    parser.add_argument("--verify-pack", action="store_true", help="Verify the Acknowledgement Pack ZIP package.")
    parser.add_argument("--import-response", action="store_true", help="Import an uploaded acknowledgement response.")
    parser.add_argument("--content-base64", default="", help="Base64-encoded acknowledgement response JSON or ZIP.")
    parser.add_argument("--response-id", default="", help="Acknowledgement response id.")
    parser.add_argument("--refresh-evidence", action="store_true", help="Refresh accepted acknowledgement evidence.")
    parser.add_argument("--export-evidence", action="store_true", help="Build the Acknowledgement Evidence export directory.")
    parser.add_argument("--zip-evidence", action="store_true", help="Build the Acknowledgement Evidence ZIP package.")
    parser.add_argument("--verify-evidence", action="store_true", help="Verify the Acknowledgement Evidence ZIP package.")
    parser.add_argument("--create-change-request", action="store_true", help="Create a Change Request draft from a needs_changes/rejected response.")
    parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    parser.add_argument("--require-pack", action="store_true", help="Require an Acknowledgement Pack package when verifying.")
    parser.add_argument("--require-response", action="store_true", help="Require Acknowledgement Evidence when verifying.")
    parser.add_argument("--require-accepted", action="store_true", help="Require accepted acknowledgement evidence when verifying.")
    parser.add_argument("--require-transparency", action="store_true", help="Require passed Transparency verification and semantics.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_verify_release_portfolio_governance_audit_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Release Portfolio Governance Audit ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Release Portfolio Governance Audit ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-signed", action="store_true", help="Require every Governance Queue in the audit to be signed.")
    verify_parser.add_argument("--require-archives", action="store_true", help="Require signed queues to have verified Governance Archives.")
    verify_parser.add_argument("--require-no-force", action="store_true", help="Fail when force-signed governance evidence is present.")
    verify_parser.add_argument("--require-reset-cr-causality", action="store_true", help="Require signoff reset events to be bound to applied Change Requests.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=128, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=512, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=5000, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_reviewer_pack_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Release Portfolio Governance Reviewer Pack ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Release Portfolio Governance Reviewer Pack ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-audit", action="store_true", help="Require passed Governance Audit evidence.")
    verify_parser.add_argument("--require-signed", action="store_true", help="Require every Governance Queue in the pack to be signed.")
    verify_parser.add_argument("--require-archives", action="store_true", help="Require signed queues to have verified Governance Archives.")
    verify_parser.add_argument("--require-no-force", action="store_true", help="Fail when force-signed governance evidence is present.")
    verify_parser.add_argument("--require-reset-cr-causality", action="store_true", help="Require signoff reset events to be bound to applied Change Requests.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=128, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=512, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=5000, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_final_board_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Release Portfolio Governance Final Board Archive ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Release Portfolio Governance Final Board Archive ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-signed", action="store_true", help="Require signed Final Board Signoff.")
    verify_parser.add_argument("--require-reviewer-pack", action="store_true", help="Require passed Governance Reviewer Pack evidence.")
    verify_parser.add_argument("--require-audit", action="store_true", help="Require passed Governance Audit evidence.")
    verify_parser.add_argument("--require-archives", action="store_true", help="Require verified Governance Archive coverage.")
    verify_parser.add_argument("--require-reviewer-response", action="store_true", help="Require accepted external reviewer response.")
    verify_parser.add_argument("--require-no-force", action="store_true", help="Fail when force-signed governance evidence is present.")
    verify_parser.add_argument("--require-reset-cr-causality", action="store_true", help="Require signoff reset events to be bound to applied Change Requests.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=128, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=512, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=5000, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_evidence_vault_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Release Portfolio Governance Evidence Vault ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Release Portfolio Governance Evidence Vault ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--deep", action="store_true", help="Run nested package verifiers.")
    verify_parser.add_argument("--require-final-board", action="store_true", help="Require passed Final Board Archive evidence.")
    verify_parser.add_argument("--require-reviewer-pack", action="store_true", help="Require passed Governance Reviewer Pack evidence.")
    verify_parser.add_argument("--require-audit", action="store_true", help="Require passed Governance Audit evidence.")
    verify_parser.add_argument("--require-archives", action="store_true", help="Require signed queue Governance Archive evidence.")
    verify_parser.add_argument("--require-queue-packages", action="store_true", help="Require Governance Queue ZIP evidence.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=1024, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=4096, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=20000, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_attestation_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Release Portfolio Governance Public Attestation ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Release Portfolio Governance Public Attestation ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-vault", action="store_true", help="Require passed deep Evidence Vault verification.")
    verify_parser.add_argument("--require-final-board", action="store_true", help="Require Final Board signoff evidence.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=200, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_attestation_registry_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Release Portfolio Governance Public Attestation Registry ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Release Portfolio Governance Public Attestation Registry ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-current", action="store_true", help="Require a current published registry entry.")
    verify_parser.add_argument("--require-published", action="store_true", help="Require at least one published registry entry.")
    verify_parser.add_argument("--require-no-revoked-current", action="store_true", help="Fail when the current registry entry is revoked.")
    verify_parser.add_argument("--require-accepted-evidence", action="store_true", help="Require current accepted external review evidence.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=200, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_attestation_portal_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Release Portfolio Governance Public Attestation Portal ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Release Portfolio Governance Public Attestation Portal ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-current", action="store_true", help="Require a current published portal entry.")
    verify_parser.add_argument("--require-registry", action="store_true", help="Require passed Attestation Registry evidence.")
    verify_parser.add_argument("--require-attestation", action="store_true", help="Require passed Public Attestation evidence.")
    verify_parser.add_argument("--require-accepted-evidence", action="store_true", help="Require current accepted external review evidence.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=200, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_attestation_portal_review_pack_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Public Attestation Portal Review Pack ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Portal Review Pack ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-current", action="store_true", help="Require current verified Portal evidence.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=200, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_attestation_portal_response_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Public Attestation Portal Review Response ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Portal Review Response ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-current", action="store_true", help="Require current response source evidence.")
    verify_parser.add_argument("--require-pack", action="store_true", help="Require response to bind to a Review Pack source.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=200, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_attestation_accepted_evidence_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Public Attestation Accepted Evidence ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Accepted Evidence ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-current", action="store_true", help="Require current accepted external review evidence.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=200, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_attestation_transparency_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Public Attestation Transparency ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Attestation Transparency ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-current", action="store_true", help="Require a current published registry entry.")
    verify_parser.add_argument("--require-accepted-evidence", action="store_true", help="Require current accepted external review evidence.")
    verify_parser.add_argument("--require-no-revoked-current", action="store_true", help="Fail when the current registry entry is revoked.")
    verify_parser.add_argument("--require-contiguous-chain", action="store_true", help="Require a valid contiguous transparency event chain.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=300, help="Maximum number of ZIP entries.")
    return verify_parser

def build_verify_release_portfolio_governance_attestation_transparency_acknowledgement_parser() -> argparse.ArgumentParser:
    verify_parser = argparse.ArgumentParser(description="Verify a portable MusicForge Public Attestation Transparency Acknowledgement ZIP.")
    verify_parser.add_argument("zip_path", type=Path, help="Path to the Transparency Acknowledgement Pack/Evidence ZIP to verify.")
    verify_parser.add_argument("--json", action="store_true", help="Print the full verification report as JSON.")
    verify_parser.add_argument("--report-out", type=Path, default=None, help="Write the verification report to this JSON file.")
    verify_parser.add_argument("--strict", action="store_true", help="Treat extra ZIP entries and strict warnings as failures.")
    verify_parser.add_argument("--require-pack", action="store_true", help="Require an Acknowledgement Pack package.")
    verify_parser.add_argument("--require-response", action="store_true", help="Require Acknowledgement Evidence.")
    verify_parser.add_argument("--require-accepted", action="store_true", help="Require accepted acknowledgement evidence.")
    verify_parser.add_argument("--require-transparency", action="store_true", help="Require passed Transparency verification and semantics.")
    verify_parser.add_argument("--max-zip-size-mb", type=int, default=64, help="Maximum compressed ZIP size in MiB.")
    verify_parser.add_argument("--max-uncompressed-size-mb", type=int, default=128, help="Maximum total uncompressed entry size in MiB.")
    verify_parser.add_argument("--max-entry-count", type=int, default=300, help="Maximum number of ZIP entries.")
    return verify_parser

__all__ = ('build_release_portfolio_governance_attestation_parser', 'build_release_portfolio_governance_attestation_registry_parser', 'build_release_portfolio_governance_attestation_portal_parser', 'build_release_portfolio_governance_attestation_portal_review_parser', 'build_release_portfolio_governance_attestation_accepted_evidence_parser', 'build_release_portfolio_governance_attestation_transparency_parser', 'build_release_portfolio_governance_attestation_transparency_acknowledgement_parser', 'build_verify_release_portfolio_governance_audit_parser', 'build_verify_release_portfolio_governance_reviewer_pack_parser', 'build_verify_release_portfolio_governance_final_board_parser', 'build_verify_release_portfolio_governance_evidence_vault_parser', 'build_verify_release_portfolio_governance_attestation_parser', 'build_verify_release_portfolio_governance_attestation_registry_parser', 'build_verify_release_portfolio_governance_attestation_portal_parser', 'build_verify_release_portfolio_governance_attestation_portal_review_pack_parser', 'build_verify_release_portfolio_governance_attestation_portal_response_parser', 'build_verify_release_portfolio_governance_attestation_accepted_evidence_parser', 'build_verify_release_portfolio_governance_attestation_transparency_parser', 'build_verify_release_portfolio_governance_attestation_transparency_acknowledgement_parser')
