from __future__ import annotations

from . import dependencies as _commands_trust_parts_dependencies; Any, CommandSpec, DistributionStore, Path, ProviderConfig, ProviderError, PublicTrustCenterAcceptanceBoardStore, PublicTrustCenterAnchorRegistryStore, PublicTrustCenterAnchorTransparencyStore, PublicTrustCenterDistributionKitAcceptanceStore, PublicTrustCenterDistributionKitStore, PublicTrustCenterPublicationMonitoringStore, PublicTrustCenterPublicationStore, PublicTrustCenterStore, ReleaseOperationsAuditStore, ReleaseOperationsReviewerPackStore, ReleaseOperationsRunbookStore, ReleaseOperationsSignoffStore, ReleaseOperationsStore, ReleasePortfolioAuditStore, ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, ReleasePortfolioGovernanceAttestationPortalReviewStore, ReleasePortfolioGovernanceAttestationPortalStore, ReleasePortfolioGovernanceAttestationRegistryStore, ReleasePortfolioGovernanceAttestationStore, ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore, ReleasePortfolioGovernanceAttestationTransparencyStore, ReleasePortfolioGovernanceAuditStore, ReleasePortfolioGovernanceEvidenceVaultStore, ReleasePortfolioGovernanceFinalBoardStore, ReleasePortfolioGovernanceReviewerPackStore, ReleasePortfolioGovernanceSignoffStore, ReleasePortfolioGovernanceStore, ReleaseStore, SongRequest, SubmissionEvidenceStore, SubmissionStore, TrustOperationsAssuranceStore, TrustOperationsAssuranceWatchSignoffStore, TrustOperationsAssuranceWatchStore, TrustOperationsControlSignoffStore, TrustOperationsControlStore, TrustOperationsFinalReadinessStore, TrustOperationsHubRunbookStore, TrustOperationsHubStore, TrustOperationsIncidentKnowledgeStore, TrustOperationsIncidentStore, acknowledgement_summary, anchor_registry_summary, anchor_transparency_summary, argparse, base64, build_auth_config, distribution_kit_summary, generate_request, json, load_provider_config, monitoring_summary, os, portfolio_audit_summary, portfolio_governance_attestation_registry_summary, portfolio_governance_attestation_summary, portfolio_governance_audit_summary, portfolio_governance_evidence_vault_summary, portfolio_governance_final_board_summary, portfolio_governance_reviewer_pack_summary, print_public_trust_center_acceptance_board_signoff_archive_verification_report, print_public_trust_center_acceptance_board_verification_report, print_public_trust_center_anchor_registry_verification_report, print_public_trust_center_anchor_transparency_verification_report, print_public_trust_center_distribution_kit_accepted_evidence_verification_report, print_public_trust_center_distribution_kit_verification_report, print_public_trust_center_publication_monitoring_verification_report, print_public_trust_center_publication_verification_report, print_public_trust_center_verification_report, print_release_portfolio_audit_verification_report, print_release_portfolio_governance_archive_verification_report, print_release_portfolio_governance_attestation_accepted_evidence_verification_report, print_release_portfolio_governance_attestation_portal_response_verification_report, print_release_portfolio_governance_attestation_portal_review_pack_verification_report, print_release_portfolio_governance_attestation_portal_verification_report, print_release_portfolio_governance_attestation_registry_verification_report, print_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, print_release_portfolio_governance_attestation_transparency_verification_report, print_release_portfolio_governance_attestation_verification_report, print_release_portfolio_governance_audit_verification_report, print_release_portfolio_governance_evidence_vault_verification_report, print_release_portfolio_governance_final_board_verification_report, print_release_portfolio_governance_reviewer_pack_verification_report, print_release_portfolio_governance_verification_report, print_trust_operations_assurance_verification_report, print_trust_operations_assurance_watch_signoff_verification_report, print_trust_operations_assurance_watch_verification_report, print_trust_operations_control_signoff_verification_report, print_trust_operations_control_verification_report, print_trust_operations_final_handoff_verification_report, print_trust_operations_hub_incident_verification_report, print_trust_operations_hub_runbook_verification_report, print_trust_operations_hub_verification_report, print_trust_operations_incident_knowledge_verification_report, provider_configured, public_trust_center_acceptance_board_signoff_archive_verification_exit_code, public_trust_center_acceptance_board_verification_exit_code, public_trust_center_anchor_registry_verification_exit_code, public_trust_center_anchor_transparency_verification_exit_code, public_trust_center_distribution_kit_accepted_evidence_verification_exit_code, public_trust_center_distribution_kit_verification_exit_code, public_trust_center_publication_monitoring_verification_exit_code, public_trust_center_publication_verification_exit_code, public_trust_center_summary, public_trust_center_verification_exit_code, publication_summary, queue_summary, read_json, release_portfolio_audit_verification_exit_code, release_portfolio_audit_verification_summary, release_portfolio_governance_archive_verification_exit_code, release_portfolio_governance_archive_verification_summary, release_portfolio_governance_attestation_accepted_evidence_verification_exit_code, release_portfolio_governance_attestation_portal_response_summary, release_portfolio_governance_attestation_portal_review_pack_summary, release_portfolio_governance_attestation_portal_review_verification_exit_code, release_portfolio_governance_attestation_portal_summary, release_portfolio_governance_attestation_portal_verification_exit_code, release_portfolio_governance_attestation_portal_verification_summary, release_portfolio_governance_attestation_registry_verification_exit_code, release_portfolio_governance_attestation_registry_verification_summary, release_portfolio_governance_attestation_transparency_acknowledgement_verification_exit_code, release_portfolio_governance_attestation_transparency_verification_exit_code, release_portfolio_governance_attestation_verification_exit_code, release_portfolio_governance_attestation_verification_summary, release_portfolio_governance_audit_verification_exit_code, release_portfolio_governance_audit_verification_summary, release_portfolio_governance_evidence_vault_verification_exit_code, release_portfolio_governance_evidence_vault_verification_summary, release_portfolio_governance_final_board_verification_exit_code, release_portfolio_governance_final_board_verification_summary, release_portfolio_governance_reviewer_pack_verification_exit_code, release_portfolio_governance_reviewer_pack_verification_summary, release_portfolio_governance_verification_exit_code, release_portfolio_governance_verification_summary, sys, test_provider_config, transparency_summary, trust_operations_assurance_verification_exit_code, trust_operations_assurance_watch_signoff_verification_exit_code, trust_operations_assurance_watch_verification_exit_code, trust_operations_control_signoff_verification_exit_code, trust_operations_control_verification_exit_code, trust_operations_final_handoff_verification_exit_code, trust_operations_hub_incident_verification_exit_code, trust_operations_hub_runbook_verification_exit_code, trust_operations_hub_verification_exit_code, trust_operations_incident_knowledge_verification_exit_code, verify_public_trust_center_acceptance_board_package, verify_public_trust_center_acceptance_board_signoff_archive_package, verify_public_trust_center_anchor_registry_package, verify_public_trust_center_anchor_transparency_package, verify_public_trust_center_distribution_kit_accepted_evidence_package, verify_public_trust_center_distribution_kit_package, verify_public_trust_center_package, verify_public_trust_center_publication_mirror, verify_public_trust_center_publication_monitoring_package, verify_public_trust_center_publication_package, verify_release_portfolio_audit_package, verify_release_portfolio_governance_archive_package, verify_release_portfolio_governance_attestation, verify_release_portfolio_governance_attestation_accepted_evidence, verify_release_portfolio_governance_attestation_portal, verify_release_portfolio_governance_attestation_portal_response, verify_release_portfolio_governance_attestation_portal_review_pack, verify_release_portfolio_governance_attestation_registry, verify_release_portfolio_governance_attestation_transparency, verify_release_portfolio_governance_attestation_transparency_acknowledgement_package, verify_release_portfolio_governance_audit_package, verify_release_portfolio_governance_evidence_vault_package, verify_release_portfolio_governance_final_board_package, verify_release_portfolio_governance_package, verify_release_portfolio_governance_reviewer_pack, verify_trust_operations_assurance_package, verify_trust_operations_assurance_watch_package, verify_trust_operations_assurance_watch_signoff_archive_package, verify_trust_operations_control_package, verify_trust_operations_control_signoff_archive_package, verify_trust_operations_final_handoff_package, verify_trust_operations_hub_incident_package, verify_trust_operations_hub_package, verify_trust_operations_hub_runbook_package, verify_trust_operations_incident_knowledge_package, write_interface_document, write_json, write_public_trust_center_acceptance_board_signoff_archive_verification_report, write_public_trust_center_acceptance_board_verification_report, write_public_trust_center_anchor_registry_verification_report, write_public_trust_center_anchor_transparency_verification_report, write_public_trust_center_distribution_kit_accepted_evidence_verification_report, write_public_trust_center_distribution_kit_verification_report, write_public_trust_center_publication_monitoring_verification_report, write_public_trust_center_publication_verification_report, write_public_trust_center_verification_report, write_release_portfolio_audit_verification_report, write_release_portfolio_governance_archive_verification_report, write_release_portfolio_governance_attestation_accepted_evidence_verification_report, write_release_portfolio_governance_attestation_portal_response_verification_report, write_release_portfolio_governance_attestation_portal_review_pack_verification_report, write_release_portfolio_governance_attestation_portal_verification_report, write_release_portfolio_governance_attestation_registry_verification_report, write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, write_release_portfolio_governance_attestation_transparency_verification_report, write_release_portfolio_governance_attestation_verification_report, write_release_portfolio_governance_audit_verification_report, write_release_portfolio_governance_evidence_vault_verification_report, write_release_portfolio_governance_final_board_verification_report, write_release_portfolio_governance_reviewer_pack_verification_report, write_release_portfolio_governance_verification_report, write_trust_operations_assurance_verification_report, write_trust_operations_assurance_watch_signoff_verification_report, write_trust_operations_assurance_watch_verification_report, write_trust_operations_control_signoff_verification_report, write_trust_operations_control_verification_report, write_trust_operations_final_handoff_verification_report, write_trust_operations_hub_incident_verification_report, write_trust_operations_hub_runbook_verification_report, write_trust_operations_hub_verification_report, write_trust_operations_incident_knowledge_verification_report = (_commands_trust_parts_dependencies.Any, _commands_trust_parts_dependencies.CommandSpec, _commands_trust_parts_dependencies.DistributionStore, _commands_trust_parts_dependencies.Path, _commands_trust_parts_dependencies.ProviderConfig, _commands_trust_parts_dependencies.ProviderError, _commands_trust_parts_dependencies.PublicTrustCenterAcceptanceBoardStore, _commands_trust_parts_dependencies.PublicTrustCenterAnchorRegistryStore, _commands_trust_parts_dependencies.PublicTrustCenterAnchorTransparencyStore, _commands_trust_parts_dependencies.PublicTrustCenterDistributionKitAcceptanceStore, _commands_trust_parts_dependencies.PublicTrustCenterDistributionKitStore, _commands_trust_parts_dependencies.PublicTrustCenterPublicationMonitoringStore, _commands_trust_parts_dependencies.PublicTrustCenterPublicationStore, _commands_trust_parts_dependencies.PublicTrustCenterStore, _commands_trust_parts_dependencies.ReleaseOperationsAuditStore, _commands_trust_parts_dependencies.ReleaseOperationsReviewerPackStore, _commands_trust_parts_dependencies.ReleaseOperationsRunbookStore, _commands_trust_parts_dependencies.ReleaseOperationsSignoffStore, _commands_trust_parts_dependencies.ReleaseOperationsStore, _commands_trust_parts_dependencies.ReleasePortfolioAuditStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationPortalReviewStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationPortalStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationRegistryStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationTransparencyStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAuditStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceEvidenceVaultStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceFinalBoardStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceReviewerPackStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceSignoffStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceStore, _commands_trust_parts_dependencies.ReleaseStore, _commands_trust_parts_dependencies.SongRequest, _commands_trust_parts_dependencies.SubmissionEvidenceStore, _commands_trust_parts_dependencies.SubmissionStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceWatchSignoffStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceWatchStore, _commands_trust_parts_dependencies.TrustOperationsControlSignoffStore, _commands_trust_parts_dependencies.TrustOperationsControlStore, _commands_trust_parts_dependencies.TrustOperationsFinalReadinessStore, _commands_trust_parts_dependencies.TrustOperationsHubRunbookStore, _commands_trust_parts_dependencies.TrustOperationsHubStore, _commands_trust_parts_dependencies.TrustOperationsIncidentKnowledgeStore, _commands_trust_parts_dependencies.TrustOperationsIncidentStore, _commands_trust_parts_dependencies.acknowledgement_summary, _commands_trust_parts_dependencies.anchor_registry_summary, _commands_trust_parts_dependencies.anchor_transparency_summary, _commands_trust_parts_dependencies.argparse, _commands_trust_parts_dependencies.base64, _commands_trust_parts_dependencies.build_auth_config, _commands_trust_parts_dependencies.distribution_kit_summary, _commands_trust_parts_dependencies.generate_request, _commands_trust_parts_dependencies.json, _commands_trust_parts_dependencies.load_provider_config, _commands_trust_parts_dependencies.monitoring_summary, _commands_trust_parts_dependencies.os, _commands_trust_parts_dependencies.portfolio_audit_summary, _commands_trust_parts_dependencies.portfolio_governance_attestation_registry_summary, _commands_trust_parts_dependencies.portfolio_governance_attestation_summary, _commands_trust_parts_dependencies.portfolio_governance_audit_summary, _commands_trust_parts_dependencies.portfolio_governance_evidence_vault_summary, _commands_trust_parts_dependencies.portfolio_governance_final_board_summary, _commands_trust_parts_dependencies.portfolio_governance_reviewer_pack_summary, _commands_trust_parts_dependencies.print_public_trust_center_acceptance_board_signoff_archive_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_acceptance_board_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_anchor_registry_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_anchor_transparency_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_distribution_kit_accepted_evidence_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_distribution_kit_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_publication_monitoring_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_publication_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_audit_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_archive_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_accepted_evidence_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_response_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_review_pack_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_registry_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_transparency_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_audit_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_evidence_vault_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_final_board_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_reviewer_pack_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_watch_signoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_watch_verification_report, _commands_trust_parts_dependencies.print_trust_operations_control_signoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_control_verification_report, _commands_trust_parts_dependencies.print_trust_operations_final_handoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_incident_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_runbook_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_verification_report, _commands_trust_parts_dependencies.print_trust_operations_incident_knowledge_verification_report, _commands_trust_parts_dependencies.provider_configured, _commands_trust_parts_dependencies.public_trust_center_acceptance_board_signoff_archive_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_acceptance_board_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_anchor_registry_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_anchor_transparency_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_distribution_kit_accepted_evidence_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_distribution_kit_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_publication_monitoring_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_publication_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_summary, _commands_trust_parts_dependencies.public_trust_center_verification_exit_code, _commands_trust_parts_dependencies.publication_summary, _commands_trust_parts_dependencies.queue_summary, _commands_trust_parts_dependencies.read_json, _commands_trust_parts_dependencies.release_portfolio_audit_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_audit_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_archive_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_archive_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_accepted_evidence_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_response_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_review_pack_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_review_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_registry_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_registry_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_transparency_acknowledgement_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_transparency_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_audit_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_audit_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_evidence_vault_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_evidence_vault_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_final_board_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_final_board_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_reviewer_pack_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_reviewer_pack_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_verification_summary, _commands_trust_parts_dependencies.sys, _commands_trust_parts_dependencies.test_provider_config, _commands_trust_parts_dependencies.transparency_summary, _commands_trust_parts_dependencies.trust_operations_assurance_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_assurance_watch_signoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_assurance_watch_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_control_signoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_control_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_final_handoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_incident_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_runbook_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_incident_knowledge_verification_exit_code, _commands_trust_parts_dependencies.verify_public_trust_center_acceptance_board_package, _commands_trust_parts_dependencies.verify_public_trust_center_acceptance_board_signoff_archive_package, _commands_trust_parts_dependencies.verify_public_trust_center_anchor_registry_package, _commands_trust_parts_dependencies.verify_public_trust_center_anchor_transparency_package, _commands_trust_parts_dependencies.verify_public_trust_center_distribution_kit_accepted_evidence_package, _commands_trust_parts_dependencies.verify_public_trust_center_distribution_kit_package, _commands_trust_parts_dependencies.verify_public_trust_center_package, _commands_trust_parts_dependencies.verify_public_trust_center_publication_mirror, _commands_trust_parts_dependencies.verify_public_trust_center_publication_monitoring_package, _commands_trust_parts_dependencies.verify_public_trust_center_publication_package, _commands_trust_parts_dependencies.verify_release_portfolio_audit_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_archive_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_accepted_evidence, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal_response, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal_review_pack, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_registry, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_transparency, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_transparency_acknowledgement_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_audit_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_evidence_vault_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_final_board_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_reviewer_pack, _commands_trust_parts_dependencies.verify_trust_operations_assurance_package, _commands_trust_parts_dependencies.verify_trust_operations_assurance_watch_package, _commands_trust_parts_dependencies.verify_trust_operations_assurance_watch_signoff_archive_package, _commands_trust_parts_dependencies.verify_trust_operations_control_package, _commands_trust_parts_dependencies.verify_trust_operations_control_signoff_archive_package, _commands_trust_parts_dependencies.verify_trust_operations_final_handoff_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_incident_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_runbook_package, _commands_trust_parts_dependencies.verify_trust_operations_incident_knowledge_package, _commands_trust_parts_dependencies.write_interface_document, _commands_trust_parts_dependencies.write_json, _commands_trust_parts_dependencies.write_public_trust_center_acceptance_board_signoff_archive_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_acceptance_board_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_anchor_registry_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_anchor_transparency_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_distribution_kit_accepted_evidence_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_distribution_kit_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_publication_monitoring_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_publication_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_audit_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_archive_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_accepted_evidence_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_response_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_review_pack_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_registry_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_transparency_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_audit_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_evidence_vault_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_final_board_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_reviewer_pack_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_watch_signoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_watch_verification_report, _commands_trust_parts_dependencies.write_trust_operations_control_signoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_control_verification_report, _commands_trust_parts_dependencies.write_trust_operations_final_handoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_incident_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_runbook_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_verification_report, _commands_trust_parts_dependencies.write_trust_operations_incident_knowledge_verification_report)

from .trust_operations_control_signoff import build_public_trust_center_parser

from .release_portfolio_governance_signoff import _build_public_trust_center_store, print_public_trust_center_result

def _execute_public_trust_center(argv: list[str]) -> None:
    raw_args = ['public-trust-center', *argv]
    pass
    pass
    pass



    pass
    pass



    pass
    from song_agent.domains.trust.public_trust_center_distribution_kit_acceptance import PublicTrustCenterDistributionKitAcceptanceStore, accepted_evidence_summary
    pass
    parser = build_public_trust_center_parser()
    args = parser.parse_args(raw_args[1:])
    store = _build_public_trust_center_store()
    anchor_store = PublicTrustCenterAnchorRegistryStore(trust_center_store=store)
    anchor_transparency_store = PublicTrustCenterAnchorTransparencyStore(anchor_registry_store=anchor_store)
    distribution_kit_store = PublicTrustCenterDistributionKitStore(
        trust_center_store=store,
        anchor_registry_store=anchor_store,
        anchor_transparency_store=anchor_transparency_store,
    )
    distribution_kit_acceptance_store = PublicTrustCenterDistributionKitAcceptanceStore(distribution_kit_store=distribution_kit_store)
    acceptance_board_store = PublicTrustCenterAcceptanceBoardStore(acceptance_store=distribution_kit_acceptance_store)
    payload: dict[str, Any] = {
        "center_id": args.center_id,
        "attestation_profile": args.profile,
        "release_ids": args.release_ids,
        "portfolio_ids": args.portfolio_ids,
        "include_all_releases": not bool(args.release_ids),
        "include_all_portfolios": not bool(args.portfolio_ids),
        "require_registry_current": True,
        "require_portal_current": True,
        "require_transparency_current": True,
        "require_acknowledgement_current": args.require_acknowledgement_current,
        "include_delivery": args.include_delivery,
        "include_distribution": args.include_delivery and args.include_distribution,
        "include_submission": args.include_delivery and args.include_submission,
        "include_submission_evidence": args.include_delivery and args.include_submission_evidence,
        "include_operations": args.include_delivery and args.include_operations,
        "require_release_signoff": args.require_release_signoff,
        "require_distribution_signed": args.require_distribution_signed,
        "require_submission_accepted": args.require_submission_accepted,
        "require_submission_evidence_signed": args.require_submission_evidence_signed,
        "require_operations_signed": args.require_operations_signed,
        "require_operations_audit_verified": args.require_operations_audit_verified,
        "require_operations_reviewer_pack_verified": args.require_operations_reviewer_pack_verified,
    }
    if args.name:
        payload["name"] = args.name
    result: dict[str, Any] = {"ok": True, "center_id": args.center_id}
    if args.refresh:
        report = store.refresh_report(args.center_id, payload)
        result.update({"report": report, "summary": public_trust_center_summary(report), "stale": False})
    else:
        config = store.read_config(args.center_id, default={}) or store.create_or_update_center(payload)
        report = store.read_report(args.center_id, default={})
        summary = public_trust_center_summary(report) if report else {"status": "missing", "center_id": args.center_id}
        if report:
            summary["stale"] = store.report_is_stale(args.center_id, report)
        result.update({"config": config, "report": report, "summary": summary, "stale": summary.get("stale", False)})
    if args.export:
        result["manifest"] = store.export_center(args.center_id)
    if args.zip:
        result["zip"] = store.build_zip(args.center_id)
    if args.verify:
        verify_payload = {
            "strict": args.strict,
            "require_registry_current": args.require_registry_current,
            "require_portal_current": args.require_portal_current,
            "require_transparency_current": args.require_transparency_current,
            "require_acknowledgement_current": args.require_acknowledgement_current,
            "require_release_readiness": args.require_release_readiness,
            "require_delivery_readiness": args.require_delivery_readiness,
            "require_distribution_ready": args.require_distribution_ready,
            "require_submission_accepted": args.require_submission_accepted,
            "require_submission_evidence": args.require_submission_evidence,
            "require_operations_signed": args.require_operations_signed,
            "require_operations_audit": args.require_operations_audit,
            "require_operations_reviewer_pack": args.require_operations_reviewer_pack,
            "require_anchor_registry_current": args.require_anchor_registry_current,
            "require_anchor_published": args.require_anchor_published,
            "require_anchor_not_revoked": args.require_anchor_not_revoked,
            "require_anchor_transparency_current": args.require_anchor_transparency_current,
            "require_anchor_checkpoint": args.require_anchor_checkpoint,
        }
        if args.require_anchor_registry_current or args.require_anchor_published or args.require_anchor_not_revoked:
            verify_payload["anchor_registry_path"] = anchor_store.zip_path(args.center_id)
        if args.require_anchor_transparency_current or args.require_anchor_checkpoint:
            verify_payload["anchor_transparency_path"] = anchor_transparency_store.zip_path(args.center_id)
        if args.require_anchor_checkpoint:
            verify_payload["anchor_checkpoint_path"] = anchor_transparency_store.current_checkpoint_path(args.center_id)
        verification = store.verify_zip(args.center_id, verify_payload)
        result["verification"] = verification
        result["verification_summary"] = verification.get("summary", {})
    if args.archive:
        result["archive"] = store.archive_snapshot(args.center_id)
    if args.anchor_register:
        registered = anchor_store.register_current_anchor(args.center_id, {"reason": args.anchor_reason})
        result["anchor_registry"] = registered
        result["anchor_summary"] = anchor_registry_summary(registered.get("registry") if isinstance(registered.get("registry"), dict) else {})
    if args.anchor_publish:
        registry = anchor_store.read_registry(args.center_id, default={})
        entry_id = str(registry.get("current_entry_id") or "")
        if not entry_id:
            registered = anchor_store.register_current_anchor(args.center_id, {"reason": args.anchor_reason})
            entry_id = str((registered.get("entry") if isinstance(registered.get("entry"), dict) else {}).get("entry_id") or "")
        published = anchor_store.publish_entry(args.center_id, entry_id, {"reason": args.anchor_reason, "supersede_current": True})
        result["anchor_publish"] = published
        result["anchor_summary"] = anchor_registry_summary(published.get("registry") if isinstance(published.get("registry"), dict) else {})
    if args.anchor_revoke:
        revoked = anchor_store.revoke_entry(args.center_id, args.anchor_revoke, {"reason": args.anchor_reason})
        result["anchor_revoke"] = revoked
        result["anchor_summary"] = anchor_registry_summary(revoked.get("registry") if isinstance(revoked.get("registry"), dict) else {})
    if args.anchor_export:
        result["anchor_manifest"] = anchor_store.export_registry(args.center_id)
    if args.anchor_zip:
        result["anchor_zip"] = anchor_store.build_zip(args.center_id)
    if args.anchor_verify:
        anchor_verification = verify_public_trust_center_anchor_registry_package(
            anchor_store.zip_path(args.center_id),
            strict=args.strict,
            require_current=args.require_anchor_registry_current,
            require_anchor_published=args.require_anchor_published,
            require_anchor_not_revoked=args.require_anchor_not_revoked,
        )
        write_public_trust_center_anchor_registry_verification_report(anchor_verification, anchor_store.verification_report_path(args.center_id))
        result["anchor_verification"] = anchor_verification
        result["anchor_verification_summary"] = anchor_verification.get("summary", {})
    if args.anchor_transparency_refresh:
        report = anchor_transparency_store.refresh_report(args.center_id, {"reason": args.anchor_reason})
        result["anchor_transparency"] = report
        result["anchor_transparency_summary"] = anchor_transparency_summary(report)
    if args.anchor_checkpoint_create:
        checkpoint = anchor_transparency_store.create_checkpoint(args.center_id, {"reason": args.anchor_reason})
        result["anchor_checkpoint"] = checkpoint
    if args.anchor_transparency_export:
        result["anchor_transparency_manifest"] = anchor_transparency_store.export_transparency(args.center_id)
    if args.anchor_transparency_zip:
        result["anchor_transparency_zip"] = anchor_transparency_store.build_zip(args.center_id)
    if args.anchor_transparency_verify:
        transparency_verification = verify_public_trust_center_anchor_transparency_package(
            anchor_transparency_store.zip_path(args.center_id),
            strict=args.strict,
            checkpoint_path=anchor_transparency_store.current_checkpoint_path(args.center_id),
            anchor_registry_path=anchor_store.zip_path(args.center_id),
            require_current_checkpoint=args.require_anchor_transparency_current or args.require_anchor_checkpoint,
            require_published_anchor=args.require_anchor_published or args.require_anchor_registry_current,
            require_not_revoked=args.require_anchor_not_revoked,
        )
        write_public_trust_center_anchor_transparency_verification_report(transparency_verification, anchor_transparency_store.verification_report_path(args.center_id))
        result["anchor_transparency_verification"] = transparency_verification
        result["anchor_transparency_verification_summary"] = transparency_verification.get("summary", {})
    if args.distribution_kit_refresh:
        kit_report = distribution_kit_store.refresh_report(args.center_id)
        result["distribution_kit"] = kit_report
        result["distribution_kit_summary"] = distribution_kit_summary(kit_report)
    if args.distribution_kit_export:
        result["distribution_kit_manifest"] = distribution_kit_store.export_kit(args.center_id)
    if args.distribution_kit_zip:
        result["distribution_kit_zip"] = distribution_kit_store.build_zip(args.center_id)
    if args.distribution_kit_verify:
        kit_verification = distribution_kit_store.verify_zip(
            args.center_id,
            {
                "strict": args.strict,
                "deep": True,
                "require_current": True,
                "require_delivery_readiness": args.require_delivery_readiness,
                "require_anchor_registry_current": True,
                "require_anchor_published": True,
                "require_anchor_not_revoked": True,
                "require_anchor_transparency_current": True,
                "require_anchor_checkpoint": True,
            },
        )
        result["distribution_kit_verification"] = kit_verification
        result["distribution_kit_verification_summary"] = kit_verification.get("summary", {})
    if args.distribution_kit_acceptance_template:
        template = distribution_kit_acceptance_store.create_response_template(args.center_id)
        result["distribution_kit_acceptance_template"] = template
    if args.distribution_kit_acceptance_response_file is not None or args.distribution_kit_acceptance_response_base64:
        import_payload: dict[str, Any] = {}
        if args.distribution_kit_acceptance_response_file is not None:
            import_payload["content"] = args.distribution_kit_acceptance_response_file.read_text(encoding="utf-8")
        if args.distribution_kit_acceptance_response_base64:
            import_payload["content_base64"] = args.distribution_kit_acceptance_response_base64
        imported = distribution_kit_acceptance_store.import_response(args.center_id, import_payload)
        result["distribution_kit_acceptance_import"] = imported
        result["distribution_kit_acceptance_summary"] = imported.get("response", {})
    if args.distribution_kit_acceptance_verify_response:
        if not args.distribution_kit_acceptance_response_id:
            raise SystemExit("--distribution-kit-acceptance-response-id is required with --distribution-kit-acceptance-verify-response")
        verification = distribution_kit_acceptance_store.verify_response(args.center_id, args.distribution_kit_acceptance_response_id)
        result["distribution_kit_acceptance_response_verification"] = verification
    if args.distribution_kit_accepted_evidence_export:
        manifest = distribution_kit_acceptance_store.export_accepted_evidence(args.center_id, args.distribution_kit_acceptance_response_id)
        result["distribution_kit_accepted_evidence_manifest"] = manifest
    if args.distribution_kit_accepted_evidence_zip:
        zip_info = distribution_kit_acceptance_store.build_accepted_evidence_zip(args.center_id, args.distribution_kit_acceptance_response_id)
        result["distribution_kit_accepted_evidence_zip"] = zip_info
        evidence = distribution_kit_acceptance_store.read_evidence(args.center_id, zip_info.get("evidence_id"), default={})
        result["distribution_kit_accepted_evidence_summary"] = accepted_evidence_summary(evidence)
    if args.distribution_kit_accepted_evidence_verify:
        evidence_id = None
        if args.distribution_kit_acceptance_response_id:
            evidence = distribution_kit_acceptance_store.refresh_accepted_evidence(args.center_id, {"response_id": args.distribution_kit_acceptance_response_id})
            evidence_id = str(evidence.get("evidence_id") or "")
        verification = distribution_kit_acceptance_store.verify_accepted_evidence_zip(args.center_id, evidence_id, {"strict": args.strict, "require_current": True})
        result["distribution_kit_accepted_evidence_verification"] = verification
        result["distribution_kit_accepted_evidence_verification_summary"] = verification.get("summary", {})
    if args.distribution_kit_acceptance_change_request:
        if not args.distribution_kit_acceptance_response_id:
            raise SystemExit("--distribution-kit-acceptance-response-id is required with --distribution-kit-acceptance-change-request")
        result["distribution_kit_acceptance_change_request"] = distribution_kit_acceptance_store.create_change_request_draft(args.center_id, args.distribution_kit_acceptance_response_id, {"source": "cli"})
    if args.acceptance_board_policy_save is not None:
        result["acceptance_board_policy"] = acceptance_board_store.save_policy(args.center_id, read_json(args.acceptance_board_policy_save))
    if args.acceptance_board_refresh:
        board = acceptance_board_store.refresh_report(args.center_id)
        result["acceptance_board"] = board
        result["acceptance_board_summary"] = acceptance_board_store.summary(args.center_id)
    if args.acceptance_board_export:
        result["acceptance_board_manifest"] = acceptance_board_store.export_board(args.center_id)
    if args.acceptance_board_zip:
        result["acceptance_board_zip"] = acceptance_board_store.build_zip(args.center_id)
    if args.acceptance_board_verify:
        board_verification = acceptance_board_store.verify_zip(
            args.center_id,
            {
                "strict": args.strict,
                "require_ready": args.require_ready,
                "require_quorum": args.require_quorum,
                "require_no_conflicts": args.require_no_conflicts,
                "min_accepted_count": args.min_accepted_count,
                "min_accepted_organizations": args.min_accepted_organizations,
                "required_roles": args.required_roles,
                "use_distribution_kit": True,
            },
        )
        result["acceptance_board_verification"] = board_verification
        result["acceptance_board_verification_summary"] = board_verification.get("summary", {})
    if args.acceptance_board_signoff_draft:
        result["acceptance_board_signoff_draft"] = acceptance_board_store.create_signoff_draft(args.center_id, {"source": "cli"})
    if args.acceptance_board_signoff:
        signoff = acceptance_board_store.signoff(args.center_id, {"signed_by": args.acceptance_board_signed_by, "reason": args.acceptance_board_signoff_reason})
        result["acceptance_board_signoff"] = signoff
        result["acceptance_board_summary"] = acceptance_board_store.summary(args.center_id)
    if args.acceptance_board_change_request_create:
        change = acceptance_board_store.create_change_request(args.center_id, {"reason": args.acceptance_board_signoff_reason, "requested_by": args.acceptance_board_signed_by})
        result["acceptance_board_change_request"] = change
    if args.acceptance_board_change_request_approve:
        if not args.acceptance_board_change_request_id:
            raise SystemExit("--acceptance-board-change-request-id is required with --acceptance-board-change-request-approve")
        change = acceptance_board_store.approve_change_request(args.center_id, args.acceptance_board_change_request_id, {"approved_by": args.acceptance_board_signed_by, "reason": args.acceptance_board_signoff_reason})
        result["acceptance_board_change_request"] = change
    if args.acceptance_board_reset_signoff:
        if not args.acceptance_board_change_request_id:
            raise SystemExit("--acceptance-board-change-request-id is required with --acceptance-board-reset-signoff")
        reset = acceptance_board_store.reset_signoff(args.center_id, {"change_request_id": args.acceptance_board_change_request_id, "reason": args.acceptance_board_signoff_reason})
        result["acceptance_board_signoff_reset"] = reset
        result["acceptance_board_summary"] = acceptance_board_store.summary(args.center_id)
    if args.acceptance_board_signoff_archive_export:
        result["acceptance_board_signoff_archive_manifest"] = acceptance_board_store.export_signoff_archive(args.center_id)
    if args.acceptance_board_signoff_archive_zip:
        result["acceptance_board_signoff_archive_zip"] = acceptance_board_store.build_signoff_archive_zip(args.center_id)
    if args.acceptance_board_signoff_archive_verify:
        archive_verification = acceptance_board_store.verify_signoff_archive_zip(
            args.center_id,
            {
                "strict": args.strict,
                "require_signed": True,
                "require_current": True,
                "require_ready": True,
                "use_board_zip": True,
                "use_board_verification": True,
                "use_distribution_kit": True,
                "use_accepted_evidence": True,
            },
        )
        result["acceptance_board_signoff_archive_verification"] = archive_verification
        result["acceptance_board_signoff_archive_verification_summary"] = archive_verification.get("summary", {})
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print_public_trust_center_result(result)
    raise SystemExit(0)

def handle_public_trust_center(argv: list[str]) -> None:
    _execute_public_trust_center(argv)

__all__ = ('_execute_public_trust_center', 'handle_public_trust_center')
