from __future__ import annotations

from typing import Any as _InterfaceType

from . import dependencies as _commands_trust_parts_dependencies

from .release_portfolio_governance_attestation import build_release_portfolio_governance_attestation_accepted_evidence_parser, build_release_portfolio_governance_attestation_transparency_acknowledgement_parser, build_release_portfolio_governance_attestation_transparency_parser

from .verify_trust_operations_assurance import build_public_trust_center_publication_parser

from .release_portfolio_governance_signoff import _build_public_trust_center_store, _build_release_portfolio_governance_attestation_portal_store, print_release_portfolio_governance_attestation_accepted_evidence_result, print_release_portfolio_governance_attestation_transparency_acknowledgement_result, print_release_portfolio_governance_attestation_transparency_result
Any, CommandSpec, DistributionStore, Path, ProviderConfig, ProviderError, PublicTrustCenterAcceptanceBoardStore, PublicTrustCenterAnchorRegistryStore, PublicTrustCenterAnchorTransparencyStore, PublicTrustCenterDistributionKitAcceptanceStore, PublicTrustCenterDistributionKitStore, PublicTrustCenterPublicationMonitoringStore, PublicTrustCenterPublicationStore, PublicTrustCenterStore, ReleaseOperationsAuditStore, ReleaseOperationsReviewerPackStore, ReleaseOperationsRunbookStore, ReleaseOperationsSignoffStore, ReleaseOperationsStore, ReleasePortfolioAuditStore, ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, ReleasePortfolioGovernanceAttestationPortalReviewStore, ReleasePortfolioGovernanceAttestationPortalStore, ReleasePortfolioGovernanceAttestationRegistryStore, ReleasePortfolioGovernanceAttestationStore, ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore, ReleasePortfolioGovernanceAttestationTransparencyStore, ReleasePortfolioGovernanceAuditStore, ReleasePortfolioGovernanceEvidenceVaultStore, ReleasePortfolioGovernanceFinalBoardStore, ReleasePortfolioGovernanceReviewerPackStore, ReleasePortfolioGovernanceSignoffStore, ReleasePortfolioGovernanceStore, ReleaseStore, SongRequest, SubmissionEvidenceStore, SubmissionStore, TrustOperationsAssuranceStore, TrustOperationsAssuranceWatchSignoffStore, TrustOperationsAssuranceWatchStore, TrustOperationsControlSignoffStore, TrustOperationsControlStore, TrustOperationsFinalReadinessStore, TrustOperationsHubRunbookStore, TrustOperationsHubStore, TrustOperationsIncidentKnowledgeStore, TrustOperationsIncidentStore, acknowledgement_summary, anchor_registry_summary, anchor_transparency_summary, argparse, base64, build_auth_config, distribution_kit_summary, generate_request, json, load_provider_config, monitoring_summary, os, portfolio_audit_summary, portfolio_governance_attestation_registry_summary, portfolio_governance_attestation_summary, portfolio_governance_audit_summary, portfolio_governance_evidence_vault_summary, portfolio_governance_final_board_summary, portfolio_governance_reviewer_pack_summary, print_public_trust_center_acceptance_board_signoff_archive_verification_report, print_public_trust_center_acceptance_board_verification_report, print_public_trust_center_anchor_registry_verification_report, print_public_trust_center_anchor_transparency_verification_report, print_public_trust_center_distribution_kit_accepted_evidence_verification_report, print_public_trust_center_distribution_kit_verification_report, print_public_trust_center_publication_monitoring_verification_report, print_public_trust_center_publication_verification_report, print_public_trust_center_verification_report, print_release_portfolio_audit_verification_report, print_release_portfolio_governance_archive_verification_report, print_release_portfolio_governance_attestation_accepted_evidence_verification_report, print_release_portfolio_governance_attestation_portal_response_verification_report, print_release_portfolio_governance_attestation_portal_review_pack_verification_report, print_release_portfolio_governance_attestation_portal_verification_report, print_release_portfolio_governance_attestation_registry_verification_report, print_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, print_release_portfolio_governance_attestation_transparency_verification_report, print_release_portfolio_governance_attestation_verification_report, print_release_portfolio_governance_audit_verification_report, print_release_portfolio_governance_evidence_vault_verification_report, print_release_portfolio_governance_final_board_verification_report, print_release_portfolio_governance_reviewer_pack_verification_report, print_release_portfolio_governance_verification_report, print_trust_operations_assurance_verification_report, print_trust_operations_assurance_watch_signoff_verification_report, print_trust_operations_assurance_watch_verification_report, print_trust_operations_control_signoff_verification_report, print_trust_operations_control_verification_report, print_trust_operations_final_handoff_verification_report, print_trust_operations_hub_incident_verification_report, print_trust_operations_hub_runbook_verification_report, print_trust_operations_hub_verification_report, print_trust_operations_incident_knowledge_verification_report, provider_configured, public_trust_center_acceptance_board_signoff_archive_verification_exit_code, public_trust_center_acceptance_board_verification_exit_code, public_trust_center_anchor_registry_verification_exit_code, public_trust_center_anchor_transparency_verification_exit_code, public_trust_center_distribution_kit_accepted_evidence_verification_exit_code, public_trust_center_distribution_kit_verification_exit_code, public_trust_center_publication_monitoring_verification_exit_code, public_trust_center_publication_verification_exit_code, public_trust_center_summary, public_trust_center_verification_exit_code, publication_summary, queue_summary, read_json, release_portfolio_audit_verification_exit_code, release_portfolio_audit_verification_summary, release_portfolio_governance_archive_verification_exit_code, release_portfolio_governance_archive_verification_summary, release_portfolio_governance_attestation_accepted_evidence_verification_exit_code, release_portfolio_governance_attestation_portal_response_summary, release_portfolio_governance_attestation_portal_review_pack_summary, release_portfolio_governance_attestation_portal_review_verification_exit_code, release_portfolio_governance_attestation_portal_summary, release_portfolio_governance_attestation_portal_verification_exit_code, release_portfolio_governance_attestation_portal_verification_summary, release_portfolio_governance_attestation_registry_verification_exit_code, release_portfolio_governance_attestation_registry_verification_summary, release_portfolio_governance_attestation_transparency_acknowledgement_verification_exit_code, release_portfolio_governance_attestation_transparency_verification_exit_code, release_portfolio_governance_attestation_verification_exit_code, release_portfolio_governance_attestation_verification_summary, release_portfolio_governance_audit_verification_exit_code, release_portfolio_governance_audit_verification_summary, release_portfolio_governance_evidence_vault_verification_exit_code, release_portfolio_governance_evidence_vault_verification_summary, release_portfolio_governance_final_board_verification_exit_code, release_portfolio_governance_final_board_verification_summary, release_portfolio_governance_reviewer_pack_verification_exit_code, release_portfolio_governance_reviewer_pack_verification_summary, release_portfolio_governance_verification_exit_code, release_portfolio_governance_verification_summary, sys, test_provider_config, transparency_summary, trust_operations_assurance_verification_exit_code, trust_operations_assurance_watch_signoff_verification_exit_code, trust_operations_assurance_watch_verification_exit_code, trust_operations_control_signoff_verification_exit_code, trust_operations_control_verification_exit_code, trust_operations_final_handoff_verification_exit_code, trust_operations_hub_incident_verification_exit_code, trust_operations_hub_runbook_verification_exit_code, trust_operations_hub_verification_exit_code, trust_operations_incident_knowledge_verification_exit_code, verify_public_trust_center_acceptance_board_package, verify_public_trust_center_acceptance_board_signoff_archive_package, verify_public_trust_center_anchor_registry_package, verify_public_trust_center_anchor_transparency_package, verify_public_trust_center_distribution_kit_accepted_evidence_package, verify_public_trust_center_distribution_kit_package, verify_public_trust_center_package, verify_public_trust_center_publication_mirror, verify_public_trust_center_publication_monitoring_package, verify_public_trust_center_publication_package, verify_release_portfolio_audit_package, verify_release_portfolio_governance_archive_package, verify_release_portfolio_governance_attestation, verify_release_portfolio_governance_attestation_accepted_evidence, verify_release_portfolio_governance_attestation_portal, verify_release_portfolio_governance_attestation_portal_response, verify_release_portfolio_governance_attestation_portal_review_pack, verify_release_portfolio_governance_attestation_registry, verify_release_portfolio_governance_attestation_transparency, verify_release_portfolio_governance_attestation_transparency_acknowledgement_package, verify_release_portfolio_governance_audit_package, verify_release_portfolio_governance_evidence_vault_package, verify_release_portfolio_governance_final_board_package, verify_release_portfolio_governance_package, verify_release_portfolio_governance_reviewer_pack, verify_trust_operations_assurance_package, verify_trust_operations_assurance_watch_package, verify_trust_operations_assurance_watch_signoff_archive_package, verify_trust_operations_control_package, verify_trust_operations_control_signoff_archive_package, verify_trust_operations_final_handoff_package, verify_trust_operations_hub_incident_package, verify_trust_operations_hub_package, verify_trust_operations_hub_runbook_package, verify_trust_operations_incident_knowledge_package, write_interface_document, write_json, write_public_trust_center_acceptance_board_signoff_archive_verification_report, write_public_trust_center_acceptance_board_verification_report, write_public_trust_center_anchor_registry_verification_report, write_public_trust_center_anchor_transparency_verification_report, write_public_trust_center_distribution_kit_accepted_evidence_verification_report, write_public_trust_center_distribution_kit_verification_report, write_public_trust_center_publication_monitoring_verification_report, write_public_trust_center_publication_verification_report, write_public_trust_center_verification_report, write_release_portfolio_audit_verification_report, write_release_portfolio_governance_archive_verification_report, write_release_portfolio_governance_attestation_accepted_evidence_verification_report, write_release_portfolio_governance_attestation_portal_response_verification_report, write_release_portfolio_governance_attestation_portal_review_pack_verification_report, write_release_portfolio_governance_attestation_portal_verification_report, write_release_portfolio_governance_attestation_registry_verification_report, write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, write_release_portfolio_governance_attestation_transparency_verification_report, write_release_portfolio_governance_attestation_verification_report, write_release_portfolio_governance_audit_verification_report, write_release_portfolio_governance_evidence_vault_verification_report, write_release_portfolio_governance_final_board_verification_report, write_release_portfolio_governance_reviewer_pack_verification_report, write_release_portfolio_governance_verification_report, write_trust_operations_assurance_verification_report, write_trust_operations_assurance_watch_signoff_verification_report, write_trust_operations_assurance_watch_verification_report, write_trust_operations_control_signoff_verification_report, write_trust_operations_control_verification_report, write_trust_operations_final_handoff_verification_report, write_trust_operations_hub_incident_verification_report, write_trust_operations_hub_runbook_verification_report, write_trust_operations_hub_verification_report, write_trust_operations_incident_knowledge_verification_report = _commands_trust_parts_dependencies.Any, _commands_trust_parts_dependencies.CommandSpec, _commands_trust_parts_dependencies.DistributionStore, _commands_trust_parts_dependencies.Path, _commands_trust_parts_dependencies.ProviderConfig, _commands_trust_parts_dependencies.ProviderError, _commands_trust_parts_dependencies.PublicTrustCenterAcceptanceBoardStore, _commands_trust_parts_dependencies.PublicTrustCenterAnchorRegistryStore, _commands_trust_parts_dependencies.PublicTrustCenterAnchorTransparencyStore, _commands_trust_parts_dependencies.PublicTrustCenterDistributionKitAcceptanceStore, _commands_trust_parts_dependencies.PublicTrustCenterDistributionKitStore, _commands_trust_parts_dependencies.PublicTrustCenterPublicationMonitoringStore, _commands_trust_parts_dependencies.PublicTrustCenterPublicationStore, _commands_trust_parts_dependencies.PublicTrustCenterStore, _commands_trust_parts_dependencies.ReleaseOperationsAuditStore, _commands_trust_parts_dependencies.ReleaseOperationsReviewerPackStore, _commands_trust_parts_dependencies.ReleaseOperationsRunbookStore, _commands_trust_parts_dependencies.ReleaseOperationsSignoffStore, _commands_trust_parts_dependencies.ReleaseOperationsStore, _commands_trust_parts_dependencies.ReleasePortfolioAuditStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationPortalReviewStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationPortalStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationRegistryStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationTransparencyStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAuditStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceEvidenceVaultStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceFinalBoardStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceReviewerPackStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceSignoffStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceStore, _commands_trust_parts_dependencies.ReleaseStore, _commands_trust_parts_dependencies.SongRequest, _commands_trust_parts_dependencies.SubmissionEvidenceStore, _commands_trust_parts_dependencies.SubmissionStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceWatchSignoffStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceWatchStore, _commands_trust_parts_dependencies.TrustOperationsControlSignoffStore, _commands_trust_parts_dependencies.TrustOperationsControlStore, _commands_trust_parts_dependencies.TrustOperationsFinalReadinessStore, _commands_trust_parts_dependencies.TrustOperationsHubRunbookStore, _commands_trust_parts_dependencies.TrustOperationsHubStore, _commands_trust_parts_dependencies.TrustOperationsIncidentKnowledgeStore, _commands_trust_parts_dependencies.TrustOperationsIncidentStore, _commands_trust_parts_dependencies.acknowledgement_summary, _commands_trust_parts_dependencies.anchor_registry_summary, _commands_trust_parts_dependencies.anchor_transparency_summary, _commands_trust_parts_dependencies.argparse, _commands_trust_parts_dependencies.base64, _commands_trust_parts_dependencies.build_auth_config, _commands_trust_parts_dependencies.distribution_kit_summary, _commands_trust_parts_dependencies.generate_request, _commands_trust_parts_dependencies.json, _commands_trust_parts_dependencies.load_provider_config, _commands_trust_parts_dependencies.monitoring_summary, _commands_trust_parts_dependencies.os, _commands_trust_parts_dependencies.portfolio_audit_summary, _commands_trust_parts_dependencies.portfolio_governance_attestation_registry_summary, _commands_trust_parts_dependencies.portfolio_governance_attestation_summary, _commands_trust_parts_dependencies.portfolio_governance_audit_summary, _commands_trust_parts_dependencies.portfolio_governance_evidence_vault_summary, _commands_trust_parts_dependencies.portfolio_governance_final_board_summary, _commands_trust_parts_dependencies.portfolio_governance_reviewer_pack_summary, _commands_trust_parts_dependencies.print_public_trust_center_acceptance_board_signoff_archive_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_acceptance_board_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_anchor_registry_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_anchor_transparency_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_distribution_kit_accepted_evidence_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_distribution_kit_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_publication_monitoring_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_publication_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_audit_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_archive_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_accepted_evidence_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_response_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_review_pack_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_registry_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_transparency_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_audit_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_evidence_vault_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_final_board_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_reviewer_pack_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_watch_signoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_watch_verification_report, _commands_trust_parts_dependencies.print_trust_operations_control_signoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_control_verification_report, _commands_trust_parts_dependencies.print_trust_operations_final_handoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_incident_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_runbook_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_verification_report, _commands_trust_parts_dependencies.print_trust_operations_incident_knowledge_verification_report, _commands_trust_parts_dependencies.provider_configured, _commands_trust_parts_dependencies.public_trust_center_acceptance_board_signoff_archive_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_acceptance_board_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_anchor_registry_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_anchor_transparency_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_distribution_kit_accepted_evidence_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_distribution_kit_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_publication_monitoring_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_publication_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_summary, _commands_trust_parts_dependencies.public_trust_center_verification_exit_code, _commands_trust_parts_dependencies.publication_summary, _commands_trust_parts_dependencies.queue_summary, _commands_trust_parts_dependencies.read_json, _commands_trust_parts_dependencies.release_portfolio_audit_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_audit_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_archive_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_archive_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_accepted_evidence_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_response_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_review_pack_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_review_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_registry_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_registry_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_transparency_acknowledgement_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_transparency_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_audit_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_audit_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_evidence_vault_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_evidence_vault_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_final_board_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_final_board_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_reviewer_pack_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_reviewer_pack_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_verification_summary, _commands_trust_parts_dependencies.sys, _commands_trust_parts_dependencies.test_provider_config, _commands_trust_parts_dependencies.transparency_summary, _commands_trust_parts_dependencies.trust_operations_assurance_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_assurance_watch_signoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_assurance_watch_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_control_signoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_control_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_final_handoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_incident_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_runbook_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_incident_knowledge_verification_exit_code, _commands_trust_parts_dependencies.verify_public_trust_center_acceptance_board_package, _commands_trust_parts_dependencies.verify_public_trust_center_acceptance_board_signoff_archive_package, _commands_trust_parts_dependencies.verify_public_trust_center_anchor_registry_package, _commands_trust_parts_dependencies.verify_public_trust_center_anchor_transparency_package, _commands_trust_parts_dependencies.verify_public_trust_center_distribution_kit_accepted_evidence_package, _commands_trust_parts_dependencies.verify_public_trust_center_distribution_kit_package, _commands_trust_parts_dependencies.verify_public_trust_center_package, _commands_trust_parts_dependencies.verify_public_trust_center_publication_mirror, _commands_trust_parts_dependencies.verify_public_trust_center_publication_monitoring_package, _commands_trust_parts_dependencies.verify_public_trust_center_publication_package, _commands_trust_parts_dependencies.verify_release_portfolio_audit_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_archive_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_accepted_evidence, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal_response, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal_review_pack, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_registry, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_transparency, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_transparency_acknowledgement_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_audit_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_evidence_vault_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_final_board_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_reviewer_pack, _commands_trust_parts_dependencies.verify_trust_operations_assurance_package, _commands_trust_parts_dependencies.verify_trust_operations_assurance_watch_package, _commands_trust_parts_dependencies.verify_trust_operations_assurance_watch_signoff_archive_package, _commands_trust_parts_dependencies.verify_trust_operations_control_package, _commands_trust_parts_dependencies.verify_trust_operations_control_signoff_archive_package, _commands_trust_parts_dependencies.verify_trust_operations_final_handoff_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_incident_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_runbook_package, _commands_trust_parts_dependencies.verify_trust_operations_incident_knowledge_package, _commands_trust_parts_dependencies.write_interface_document, _commands_trust_parts_dependencies.write_json, _commands_trust_parts_dependencies.write_public_trust_center_acceptance_board_signoff_archive_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_acceptance_board_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_anchor_registry_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_anchor_transparency_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_distribution_kit_accepted_evidence_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_distribution_kit_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_publication_monitoring_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_publication_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_audit_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_archive_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_accepted_evidence_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_response_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_review_pack_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_registry_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_transparency_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_audit_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_evidence_vault_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_final_board_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_reviewer_pack_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_watch_signoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_watch_verification_report, _commands_trust_parts_dependencies.write_trust_operations_control_signoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_control_verification_report, _commands_trust_parts_dependencies.write_trust_operations_final_handoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_incident_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_runbook_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_verification_report, _commands_trust_parts_dependencies.write_trust_operations_incident_knowledge_verification_report
def _execute_release_portfolio_governance_attestation_accepted_evidence(argv: list[str]) -> None:
    raw_args = ['release-portfolio-governance-attestation-accepted-evidence', *argv]
    from song_agent.domains.trust.release_portfolio_governance_attestation_accepted_evidence import ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, accepted_evidence_summary
    pass
    pass
    parser = build_release_portfolio_governance_attestation_accepted_evidence_parser()
    args = parser.parse_args(raw_args[1:])
    portal_store = _build_release_portfolio_governance_attestation_portal_store()
    review_store = ReleasePortfolioGovernanceAttestationPortalReviewStore(portal_store=portal_store)
    store = ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore(review_store=review_store)
    portfolio_id = args.portfolio_id
    result: dict[str, _InterfaceType] = {"ok": True, "portfolio_id": portfolio_id, "profile": args.profile}
    if args.refresh:
        payload = {"profile": args.profile}
        if args.response_id:
            payload["response_id"] = args.response_id
        evidence = store.refresh_evidence(portfolio_id, payload)
        result.update({"accepted_evidence": evidence, "summary": accepted_evidence_summary(evidence), "stale": False})
    else:
        evidence = store.read_evidence(portfolio_id, profile=args.profile, default={})
        summary = accepted_evidence_summary(evidence) if evidence else {"status": "missing", "external_review_status": "missing", "profile": args.profile}
        if evidence:
            summary["stale"] = store.evidence_is_stale(portfolio_id, evidence, profile=args.profile)
        result.update({"accepted_evidence": evidence, "summary": summary, "stale": summary.get("stale", False)})
    if args.export:
        result["manifest"] = store.export_evidence(portfolio_id, {"profile": args.profile})
    if args.zip:
        result["zip"] = store.build_zip(portfolio_id, {"profile": args.profile})
    if args.verify:
        verification = store.verify_evidence(portfolio_id, {"profile": args.profile, "strict": args.strict, "require_current": args.require_current})
        write_release_portfolio_governance_attestation_accepted_evidence_verification_report(verification, store.verification_report_path(portfolio_id, args.profile))
        result["verification"] = verification
    if args.archive:
        result["accepted_evidence"] = store.archive_evidence(portfolio_id, {"profile": args.profile, "reason": args.reason})
        result["summary"] = accepted_evidence_summary(result["accepted_evidence"])
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print_release_portfolio_governance_attestation_accepted_evidence_result(result)
    raise SystemExit(0)

def handle_release_portfolio_governance_attestation_accepted_evidence(argv: list[str]) -> None:
    _execute_release_portfolio_governance_attestation_accepted_evidence(argv)

def _execute_release_portfolio_governance_attestation_transparency(argv: list[str]) -> None:
    raw_args = ['release-portfolio-governance-attestation-transparency', *argv]
    pass
    pass
    pass
    pass
    parser = build_release_portfolio_governance_attestation_transparency_parser()
    args = parser.parse_args(raw_args[1:])
    portal_store = _build_release_portfolio_governance_attestation_portal_store()
    review_store = ReleasePortfolioGovernanceAttestationPortalReviewStore(portal_store=portal_store)
    accepted_store = ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore(review_store=review_store)
    store = ReleasePortfolioGovernanceAttestationTransparencyStore(
        attestation_store=portal_store.attestation_store,
        registry_store=portal_store.registry_store,
        portal_store=portal_store,
        accepted_evidence_store=accepted_store,
    )
    portfolio_id = args.portfolio_id
    result: dict[str, _InterfaceType] = {"ok": True, "portfolio_id": portfolio_id, "profile": args.profile}
    if args.refresh:
        feed = store.refresh_feed(portfolio_id, {"profile": args.profile, "require_accepted_evidence": args.require_accepted_evidence})
        result.update({"feed": feed, "summary": transparency_summary(feed), "stale": False})
    else:
        feed = store.read_feed(portfolio_id, profile=args.profile, default={})
        summary = transparency_summary(feed) if feed else {"status": "missing", "profile": args.profile}
        if feed:
            summary["stale"] = store.feed_is_stale(portfolio_id, feed, profile=args.profile)
        result.update({"feed": feed, "summary": summary, "stale": summary.get("stale", False)})
    if args.export:
        result["manifest"] = store.export_transparency(portfolio_id, {"profile": args.profile})
    if args.zip:
        result["zip"] = store.build_zip(portfolio_id, {"profile": args.profile})
    if args.verify:
        verification = store.verify_transparency(
            portfolio_id,
            {
                "profile": args.profile,
                "strict": args.strict,
                "require_current": args.require_current,
                "require_accepted_evidence": args.require_accepted_evidence,
                "require_no_revoked_current": args.require_no_revoked_current,
                "require_contiguous_chain": args.require_contiguous_chain,
            },
        )
        write_release_portfolio_governance_attestation_transparency_verification_report(verification, store.verification_report_path(portfolio_id, args.profile))
        result["verification"] = verification
    if args.notices:
        result["notices"] = store.list_notices(portfolio_id, profile=args.profile)
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print_release_portfolio_governance_attestation_transparency_result(result)
    raise SystemExit(0)

def handle_release_portfolio_governance_attestation_transparency(argv: list[str]) -> None:
    _execute_release_portfolio_governance_attestation_transparency(argv)

def _execute_release_portfolio_governance_attestation_transparency_acknowledgement(argv: list[str]) -> None:
    raw_args = ['release-portfolio-governance-attestation-transparency-acknowledgement', *argv]
    pass
    pass
    pass
    pass
    pass



    parser = build_release_portfolio_governance_attestation_transparency_acknowledgement_parser()
    args = parser.parse_args(raw_args[1:])
    portal_store = _build_release_portfolio_governance_attestation_portal_store()
    review_store = ReleasePortfolioGovernanceAttestationPortalReviewStore(portal_store=portal_store)
    accepted_store = ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore(review_store=review_store)
    transparency_store = ReleasePortfolioGovernanceAttestationTransparencyStore(
        attestation_store=portal_store.attestation_store,
        registry_store=portal_store.registry_store,
        portal_store=portal_store,
        accepted_evidence_store=accepted_store,
    )
    store = ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore(transparency_store=transparency_store)
    portfolio_id = args.portfolio_id
    result: dict[str, _InterfaceType] = {"ok": True, "portfolio_id": portfolio_id, "profile": args.profile}
    if args.refresh_pack:
        pack = store.refresh_pack(portfolio_id, {"profile": args.profile})
        result.update({"pack": pack, "summary": {"status": pack.get("status"), "pack_id": pack.get("pack_id"), "source_hash": pack.get("source_hash")}})
    else:
        pack = store.read_pack(portfolio_id, profile=args.profile, default={})
        result.update({"pack": pack, "summary": {"status": pack.get("status", "missing") if pack else "missing", "pack_id": pack.get("pack_id") if pack else None}})
    if args.export_pack:
        result["pack_manifest"] = store.export_pack(portfolio_id, {"profile": args.profile})
    if args.zip_pack:
        result["pack_zip"] = store.build_pack_zip(portfolio_id, {"profile": args.profile})
    if args.verify_pack:
        report = verify_release_portfolio_governance_attestation_transparency_acknowledgement_package(
            store.pack_zip_path(portfolio_id, args.profile),
            strict=args.strict,
            require_pack=True,
            require_transparency=args.require_transparency,
        )
        write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report(report, store.pack_verification_report_path(portfolio_id, args.profile))
        result["pack_verification"] = report
    if args.import_response:
        payload: dict[str, _InterfaceType] = {"profile": args.profile}
        if args.content_base64:
            payload["content_base64"] = args.content_base64
        imported = store.import_response(portfolio_id, payload)
        result.update(imported)
    if args.refresh_evidence:
        payload = {"profile": args.profile}
        if args.response_id:
            payload["response_id"] = args.response_id
        evidence = store.refresh_evidence(portfolio_id, payload)
        result.update({"acknowledgement_evidence": evidence, "evidence_summary": acknowledgement_summary(evidence)})
    if args.export_evidence:
        result["evidence_manifest"] = store.export_evidence(portfolio_id, {"profile": args.profile})
    if args.zip_evidence:
        result["evidence_zip"] = store.build_evidence_zip(portfolio_id, {"profile": args.profile})
    if args.verify_evidence:
        report = verify_release_portfolio_governance_attestation_transparency_acknowledgement_package(
            store.evidence_zip_path(portfolio_id, args.profile),
            strict=args.strict,
            require_response=True,
            require_accepted=args.require_accepted,
        )
        write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report(report, store.evidence_verification_report_path(portfolio_id, args.profile))
        result["evidence_verification"] = report
    if args.create_change_request:
        if not args.response_id:
            raise SystemExit("--response-id is required with --create-change-request")
        result["change_request"] = store.create_change_request(portfolio_id, args.response_id, {"profile": args.profile})
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print_release_portfolio_governance_attestation_transparency_acknowledgement_result(result)
    raise SystemExit(0)

def handle_release_portfolio_governance_attestation_transparency_acknowledgement(argv: list[str]) -> None:
    _execute_release_portfolio_governance_attestation_transparency_acknowledgement(argv)

def _execute_public_trust_center_publication(argv: list[str]) -> None:
    raw_args = ['public-trust-center-publication', *argv]
    pass
    pass


    parser = build_public_trust_center_publication_parser()
    args = parser.parse_args(raw_args[1:])
    trust_store = _build_public_trust_center_store()
    pass
    pass
    pass
    pass
    pass
    anchor_store = PublicTrustCenterAnchorRegistryStore(trust_center_store=trust_store)
    anchor_transparency_store = PublicTrustCenterAnchorTransparencyStore(anchor_registry_store=anchor_store)
    distribution_kit_store = PublicTrustCenterDistributionKitStore(trust_center_store=trust_store, anchor_registry_store=anchor_store, anchor_transparency_store=anchor_transparency_store)
    acceptance_store = PublicTrustCenterDistributionKitAcceptanceStore(distribution_kit_store=distribution_kit_store)
    board_store = PublicTrustCenterAcceptanceBoardStore(acceptance_store=acceptance_store)
    store = PublicTrustCenterPublicationStore(
        trust_center_store=trust_store,
        distribution_kit_store=distribution_kit_store,
        anchor_registry_store=anchor_store,
        anchor_transparency_store=anchor_transparency_store,
        acceptance_store=acceptance_store,
        acceptance_board_store=board_store,
    )
    result: dict[str, _InterfaceType] = {"ok": True, "center_id": args.center_id, "channel_id": args.channel_id}
    if args.create_channel:
        result["channel"] = store.create_channel(args.center_id, {"channel_id": args.channel_id, "name": args.channel_name, "channel_type": args.channel_type})
    else:
        try:
            result["channel"] = store.read_channel(args.center_id, args.channel_id)
        except Exception:
            result["channel"] = store.create_channel(args.center_id, {"channel_id": args.channel_id, "name": args.channel_name, "channel_type": args.channel_type})
    publication_id = args.publication_id
    if args.refresh:
        report = store.refresh_publication(args.center_id, args.channel_id)
        publication_id = str(report.get("publication_id") or publication_id or "")
        result["publication"] = report
        result["summary"] = publication_summary(report)
    if args.supersede:
        report = store.supersede_publication(args.center_id, args.channel_id, publication_id, {"reason": args.reason})
        publication_id = str(report.get("publication_id") or publication_id or "")
        result["publication"] = report
        result["summary"] = publication_summary(report)
    if args.revoke:
        if not publication_id:
            publication_id = store._current_publication_id(args.center_id, args.channel_id)
        report = store.revoke_publication(args.center_id, args.channel_id, publication_id, {"reason": args.reason})
        result["publication"] = report
        result["summary"] = publication_summary(report)
    if args.export:
        result["manifest"] = store.export_publication(args.center_id, args.channel_id, publication_id)
        publication_id = str(result["manifest"].get("publication_id") or publication_id or "")
    if args.zip:
        result["zip"] = store.build_publication_zip(args.center_id, args.channel_id, publication_id)
        publication_id = str(result["zip"].get("publication_id") or publication_id or "")
    if args.verify:
        verification = store.verify_publication_zip(
            args.center_id,
            args.channel_id,
            publication_id,
            {
                "strict": args.strict,
                "deep": args.deep,
                "require_ready": args.require_ready,
                "require_acceptance_board_signoff": args.require_acceptance_board_signoff,
                "require_anchor_current": args.require_anchor_current,
                "require_no_revoked": args.require_no_revoked,
                "publication_channel_state_path": args.publication_channel_state,
            },
        )
        result["verification"] = verification
        result["verification_summary"] = verification.get("summary", {})
    if args.verify_mirror:
        if not publication_id:
            publication_id = store._current_publication_id(args.center_id, args.channel_id)
        mirror_dir = args.mirror_dir or store.export_dir(args.center_id, args.channel_id, publication_id)
        verification = store.verify_mirror_directory(
            args.center_id,
            args.channel_id,
            publication_id,
            mirror_dir,
            {
                "strict": args.strict,
                "require_ready": args.require_ready,
                "require_acceptance_board_signoff": args.require_acceptance_board_signoff,
                "require_anchor_current": args.require_anchor_current,
                "require_no_revoked": args.require_no_revoked,
                "publication_channel_state_path": args.publication_channel_state,
            },
        )
        result["mirror_verification"] = verification
        result["mirror_verification_summary"] = verification.get("summary", {})
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        if "verification" in result:
            print_public_trust_center_publication_verification_report(result["verification"])
        elif "mirror_verification" in result:
            print_public_trust_center_publication_verification_report(result["mirror_verification"])
        else:
            print(json.dumps(result.get("summary") or {"status": "ok"}, ensure_ascii=False, indent=2))
    raise SystemExit(0)

def handle_public_trust_center_publication(argv: list[str]) -> None:
    _execute_public_trust_center_publication(argv)

__all__ = ('_execute_release_portfolio_governance_attestation_accepted_evidence', 'handle_release_portfolio_governance_attestation_accepted_evidence', '_execute_release_portfolio_governance_attestation_transparency', 'handle_release_portfolio_governance_attestation_transparency', '_execute_release_portfolio_governance_attestation_transparency_acknowledgement', 'handle_release_portfolio_governance_attestation_transparency_acknowledgement', '_execute_public_trust_center_publication', 'handle_public_trust_center_publication')
