from __future__ import annotations

from song_agent.platform.contracts import ImplementationDocument

from . import dependencies as _commands_trust_parts_dependencies

from .verify_trust_operations_assurance import build_trust_operations_assurance_parser, build_trust_operations_final_readiness_parser

from .trust_operations_control_signoff import _trust_operations_assurance_source_payload, _trust_operations_final_readiness_source_payload, build_trust_operations_control_signoff_parser, build_trust_operations_controls_parser, build_trust_operations_hub_runbook_parser
Any, CommandSpec, DistributionStore, Path, ProviderConfig, ProviderError, PublicTrustCenterAcceptanceBoardStore, PublicTrustCenterAnchorRegistryStore, PublicTrustCenterAnchorTransparencyStore, PublicTrustCenterDistributionKitAcceptanceStore, PublicTrustCenterDistributionKitStore, PublicTrustCenterPublicationMonitoringStore, PublicTrustCenterPublicationStore, PublicTrustCenterStore, ReleaseOperationsAuditStore, ReleaseOperationsReviewerPackStore, ReleaseOperationsRunbookStore, ReleaseOperationsSignoffStore, ReleaseOperationsStore, ReleasePortfolioAuditStore, ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, ReleasePortfolioGovernanceAttestationPortalReviewStore, ReleasePortfolioGovernanceAttestationPortalStore, ReleasePortfolioGovernanceAttestationRegistryStore, ReleasePortfolioGovernanceAttestationStore, ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore, ReleasePortfolioGovernanceAttestationTransparencyStore, ReleasePortfolioGovernanceAuditStore, ReleasePortfolioGovernanceEvidenceVaultStore, ReleasePortfolioGovernanceFinalBoardStore, ReleasePortfolioGovernanceReviewerPackStore, ReleasePortfolioGovernanceSignoffStore, ReleasePortfolioGovernanceStore, ReleaseStore, SongRequest, SubmissionEvidenceStore, SubmissionStore, TrustOperationsAssuranceStore, TrustOperationsAssuranceWatchSignoffStore, TrustOperationsAssuranceWatchStore, TrustOperationsControlSignoffStore, TrustOperationsControlStore, TrustOperationsFinalReadinessStore, TrustOperationsHubRunbookStore, TrustOperationsHubStore, TrustOperationsIncidentKnowledgeStore, TrustOperationsIncidentStore, acknowledgement_summary, anchor_registry_summary, anchor_transparency_summary, argparse, base64, build_auth_config, distribution_kit_summary, generate_request, json, load_provider_config, monitoring_summary, os, portfolio_audit_summary, portfolio_governance_attestation_registry_summary, portfolio_governance_attestation_summary, portfolio_governance_audit_summary, portfolio_governance_evidence_vault_summary, portfolio_governance_final_board_summary, portfolio_governance_reviewer_pack_summary, print_public_trust_center_acceptance_board_signoff_archive_verification_report, print_public_trust_center_acceptance_board_verification_report, print_public_trust_center_anchor_registry_verification_report, print_public_trust_center_anchor_transparency_verification_report, print_public_trust_center_distribution_kit_accepted_evidence_verification_report, print_public_trust_center_distribution_kit_verification_report, print_public_trust_center_publication_monitoring_verification_report, print_public_trust_center_publication_verification_report, print_public_trust_center_verification_report, print_release_portfolio_audit_verification_report, print_release_portfolio_governance_archive_verification_report, print_release_portfolio_governance_attestation_accepted_evidence_verification_report, print_release_portfolio_governance_attestation_portal_response_verification_report, print_release_portfolio_governance_attestation_portal_review_pack_verification_report, print_release_portfolio_governance_attestation_portal_verification_report, print_release_portfolio_governance_attestation_registry_verification_report, print_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, print_release_portfolio_governance_attestation_transparency_verification_report, print_release_portfolio_governance_attestation_verification_report, print_release_portfolio_governance_audit_verification_report, print_release_portfolio_governance_evidence_vault_verification_report, print_release_portfolio_governance_final_board_verification_report, print_release_portfolio_governance_reviewer_pack_verification_report, print_release_portfolio_governance_verification_report, print_trust_operations_assurance_verification_report, print_trust_operations_assurance_watch_signoff_verification_report, print_trust_operations_assurance_watch_verification_report, print_trust_operations_control_signoff_verification_report, print_trust_operations_control_verification_report, print_trust_operations_final_handoff_verification_report, print_trust_operations_hub_incident_verification_report, print_trust_operations_hub_runbook_verification_report, print_trust_operations_hub_verification_report, print_trust_operations_incident_knowledge_verification_report, provider_configured, public_trust_center_acceptance_board_signoff_archive_verification_exit_code, public_trust_center_acceptance_board_verification_exit_code, public_trust_center_anchor_registry_verification_exit_code, public_trust_center_anchor_transparency_verification_exit_code, public_trust_center_distribution_kit_accepted_evidence_verification_exit_code, public_trust_center_distribution_kit_verification_exit_code, public_trust_center_publication_monitoring_verification_exit_code, public_trust_center_publication_verification_exit_code, public_trust_center_summary, public_trust_center_verification_exit_code, publication_summary, queue_summary, read_json, release_portfolio_audit_verification_exit_code, release_portfolio_audit_verification_summary, release_portfolio_governance_archive_verification_exit_code, release_portfolio_governance_archive_verification_summary, release_portfolio_governance_attestation_accepted_evidence_verification_exit_code, release_portfolio_governance_attestation_portal_response_summary, release_portfolio_governance_attestation_portal_review_pack_summary, release_portfolio_governance_attestation_portal_review_verification_exit_code, release_portfolio_governance_attestation_portal_summary, release_portfolio_governance_attestation_portal_verification_exit_code, release_portfolio_governance_attestation_portal_verification_summary, release_portfolio_governance_attestation_registry_verification_exit_code, release_portfolio_governance_attestation_registry_verification_summary, release_portfolio_governance_attestation_transparency_acknowledgement_verification_exit_code, release_portfolio_governance_attestation_transparency_verification_exit_code, release_portfolio_governance_attestation_verification_exit_code, release_portfolio_governance_attestation_verification_summary, release_portfolio_governance_audit_verification_exit_code, release_portfolio_governance_audit_verification_summary, release_portfolio_governance_evidence_vault_verification_exit_code, release_portfolio_governance_evidence_vault_verification_summary, release_portfolio_governance_final_board_verification_exit_code, release_portfolio_governance_final_board_verification_summary, release_portfolio_governance_reviewer_pack_verification_exit_code, release_portfolio_governance_reviewer_pack_verification_summary, release_portfolio_governance_verification_exit_code, release_portfolio_governance_verification_summary, sys, test_provider_config, transparency_summary, trust_operations_assurance_verification_exit_code, trust_operations_assurance_watch_signoff_verification_exit_code, trust_operations_assurance_watch_verification_exit_code, trust_operations_control_signoff_verification_exit_code, trust_operations_control_verification_exit_code, trust_operations_final_handoff_verification_exit_code, trust_operations_hub_incident_verification_exit_code, trust_operations_hub_runbook_verification_exit_code, trust_operations_hub_verification_exit_code, trust_operations_incident_knowledge_verification_exit_code, verify_public_trust_center_acceptance_board_package, verify_public_trust_center_acceptance_board_signoff_archive_package, verify_public_trust_center_anchor_registry_package, verify_public_trust_center_anchor_transparency_package, verify_public_trust_center_distribution_kit_accepted_evidence_package, verify_public_trust_center_distribution_kit_package, verify_public_trust_center_package, verify_public_trust_center_publication_mirror, verify_public_trust_center_publication_monitoring_package, verify_public_trust_center_publication_package, verify_release_portfolio_audit_package, verify_release_portfolio_governance_archive_package, verify_release_portfolio_governance_attestation, verify_release_portfolio_governance_attestation_accepted_evidence, verify_release_portfolio_governance_attestation_portal, verify_release_portfolio_governance_attestation_portal_response, verify_release_portfolio_governance_attestation_portal_review_pack, verify_release_portfolio_governance_attestation_registry, verify_release_portfolio_governance_attestation_transparency, verify_release_portfolio_governance_attestation_transparency_acknowledgement_package, verify_release_portfolio_governance_audit_package, verify_release_portfolio_governance_evidence_vault_package, verify_release_portfolio_governance_final_board_package, verify_release_portfolio_governance_package, verify_release_portfolio_governance_reviewer_pack, verify_trust_operations_assurance_package, verify_trust_operations_assurance_watch_package, verify_trust_operations_assurance_watch_signoff_archive_package, verify_trust_operations_control_package, verify_trust_operations_control_signoff_archive_package, verify_trust_operations_final_handoff_package, verify_trust_operations_hub_incident_package, verify_trust_operations_hub_package, verify_trust_operations_hub_runbook_package, verify_trust_operations_incident_knowledge_package, write_interface_document, write_json, write_public_trust_center_acceptance_board_signoff_archive_verification_report, write_public_trust_center_acceptance_board_verification_report, write_public_trust_center_anchor_registry_verification_report, write_public_trust_center_anchor_transparency_verification_report, write_public_trust_center_distribution_kit_accepted_evidence_verification_report, write_public_trust_center_distribution_kit_verification_report, write_public_trust_center_publication_monitoring_verification_report, write_public_trust_center_publication_verification_report, write_public_trust_center_verification_report, write_release_portfolio_audit_verification_report, write_release_portfolio_governance_archive_verification_report, write_release_portfolio_governance_attestation_accepted_evidence_verification_report, write_release_portfolio_governance_attestation_portal_response_verification_report, write_release_portfolio_governance_attestation_portal_review_pack_verification_report, write_release_portfolio_governance_attestation_portal_verification_report, write_release_portfolio_governance_attestation_registry_verification_report, write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, write_release_portfolio_governance_attestation_transparency_verification_report, write_release_portfolio_governance_attestation_verification_report, write_release_portfolio_governance_audit_verification_report, write_release_portfolio_governance_evidence_vault_verification_report, write_release_portfolio_governance_final_board_verification_report, write_release_portfolio_governance_reviewer_pack_verification_report, write_release_portfolio_governance_verification_report, write_trust_operations_assurance_verification_report, write_trust_operations_assurance_watch_signoff_verification_report, write_trust_operations_assurance_watch_verification_report, write_trust_operations_control_signoff_verification_report, write_trust_operations_control_verification_report, write_trust_operations_final_handoff_verification_report, write_trust_operations_hub_incident_verification_report, write_trust_operations_hub_runbook_verification_report, write_trust_operations_hub_verification_report, write_trust_operations_incident_knowledge_verification_report = _commands_trust_parts_dependencies.Any, _commands_trust_parts_dependencies.CommandSpec, _commands_trust_parts_dependencies.DistributionStore, _commands_trust_parts_dependencies.Path, _commands_trust_parts_dependencies.ProviderConfig, _commands_trust_parts_dependencies.ProviderError, _commands_trust_parts_dependencies.PublicTrustCenterAcceptanceBoardStore, _commands_trust_parts_dependencies.PublicTrustCenterAnchorRegistryStore, _commands_trust_parts_dependencies.PublicTrustCenterAnchorTransparencyStore, _commands_trust_parts_dependencies.PublicTrustCenterDistributionKitAcceptanceStore, _commands_trust_parts_dependencies.PublicTrustCenterDistributionKitStore, _commands_trust_parts_dependencies.PublicTrustCenterPublicationMonitoringStore, _commands_trust_parts_dependencies.PublicTrustCenterPublicationStore, _commands_trust_parts_dependencies.PublicTrustCenterStore, _commands_trust_parts_dependencies.ReleaseOperationsAuditStore, _commands_trust_parts_dependencies.ReleaseOperationsReviewerPackStore, _commands_trust_parts_dependencies.ReleaseOperationsRunbookStore, _commands_trust_parts_dependencies.ReleaseOperationsSignoffStore, _commands_trust_parts_dependencies.ReleaseOperationsStore, _commands_trust_parts_dependencies.ReleasePortfolioAuditStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationPortalReviewStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationPortalStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationRegistryStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationTransparencyStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAuditStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceEvidenceVaultStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceFinalBoardStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceReviewerPackStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceSignoffStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceStore, _commands_trust_parts_dependencies.ReleaseStore, _commands_trust_parts_dependencies.SongRequest, _commands_trust_parts_dependencies.SubmissionEvidenceStore, _commands_trust_parts_dependencies.SubmissionStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceWatchSignoffStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceWatchStore, _commands_trust_parts_dependencies.TrustOperationsControlSignoffStore, _commands_trust_parts_dependencies.TrustOperationsControlStore, _commands_trust_parts_dependencies.TrustOperationsFinalReadinessStore, _commands_trust_parts_dependencies.TrustOperationsHubRunbookStore, _commands_trust_parts_dependencies.TrustOperationsHubStore, _commands_trust_parts_dependencies.TrustOperationsIncidentKnowledgeStore, _commands_trust_parts_dependencies.TrustOperationsIncidentStore, _commands_trust_parts_dependencies.acknowledgement_summary, _commands_trust_parts_dependencies.anchor_registry_summary, _commands_trust_parts_dependencies.anchor_transparency_summary, _commands_trust_parts_dependencies.argparse, _commands_trust_parts_dependencies.base64, _commands_trust_parts_dependencies.build_auth_config, _commands_trust_parts_dependencies.distribution_kit_summary, _commands_trust_parts_dependencies.generate_request, _commands_trust_parts_dependencies.json, _commands_trust_parts_dependencies.load_provider_config, _commands_trust_parts_dependencies.monitoring_summary, _commands_trust_parts_dependencies.os, _commands_trust_parts_dependencies.portfolio_audit_summary, _commands_trust_parts_dependencies.portfolio_governance_attestation_registry_summary, _commands_trust_parts_dependencies.portfolio_governance_attestation_summary, _commands_trust_parts_dependencies.portfolio_governance_audit_summary, _commands_trust_parts_dependencies.portfolio_governance_evidence_vault_summary, _commands_trust_parts_dependencies.portfolio_governance_final_board_summary, _commands_trust_parts_dependencies.portfolio_governance_reviewer_pack_summary, _commands_trust_parts_dependencies.print_public_trust_center_acceptance_board_signoff_archive_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_acceptance_board_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_anchor_registry_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_anchor_transparency_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_distribution_kit_accepted_evidence_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_distribution_kit_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_publication_monitoring_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_publication_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_audit_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_archive_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_accepted_evidence_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_response_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_review_pack_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_registry_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_transparency_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_audit_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_evidence_vault_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_final_board_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_reviewer_pack_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_watch_signoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_watch_verification_report, _commands_trust_parts_dependencies.print_trust_operations_control_signoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_control_verification_report, _commands_trust_parts_dependencies.print_trust_operations_final_handoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_incident_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_runbook_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_verification_report, _commands_trust_parts_dependencies.print_trust_operations_incident_knowledge_verification_report, _commands_trust_parts_dependencies.provider_configured, _commands_trust_parts_dependencies.public_trust_center_acceptance_board_signoff_archive_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_acceptance_board_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_anchor_registry_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_anchor_transparency_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_distribution_kit_accepted_evidence_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_distribution_kit_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_publication_monitoring_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_publication_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_summary, _commands_trust_parts_dependencies.public_trust_center_verification_exit_code, _commands_trust_parts_dependencies.publication_summary, _commands_trust_parts_dependencies.queue_summary, _commands_trust_parts_dependencies.read_json, _commands_trust_parts_dependencies.release_portfolio_audit_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_audit_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_archive_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_archive_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_accepted_evidence_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_response_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_review_pack_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_review_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_registry_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_registry_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_transparency_acknowledgement_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_transparency_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_audit_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_audit_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_evidence_vault_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_evidence_vault_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_final_board_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_final_board_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_reviewer_pack_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_reviewer_pack_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_verification_summary, _commands_trust_parts_dependencies.sys, _commands_trust_parts_dependencies.test_provider_config, _commands_trust_parts_dependencies.transparency_summary, _commands_trust_parts_dependencies.trust_operations_assurance_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_assurance_watch_signoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_assurance_watch_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_control_signoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_control_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_final_handoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_incident_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_runbook_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_incident_knowledge_verification_exit_code, _commands_trust_parts_dependencies.verify_public_trust_center_acceptance_board_package, _commands_trust_parts_dependencies.verify_public_trust_center_acceptance_board_signoff_archive_package, _commands_trust_parts_dependencies.verify_public_trust_center_anchor_registry_package, _commands_trust_parts_dependencies.verify_public_trust_center_anchor_transparency_package, _commands_trust_parts_dependencies.verify_public_trust_center_distribution_kit_accepted_evidence_package, _commands_trust_parts_dependencies.verify_public_trust_center_distribution_kit_package, _commands_trust_parts_dependencies.verify_public_trust_center_package, _commands_trust_parts_dependencies.verify_public_trust_center_publication_mirror, _commands_trust_parts_dependencies.verify_public_trust_center_publication_monitoring_package, _commands_trust_parts_dependencies.verify_public_trust_center_publication_package, _commands_trust_parts_dependencies.verify_release_portfolio_audit_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_archive_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_accepted_evidence, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal_response, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal_review_pack, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_registry, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_transparency, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_transparency_acknowledgement_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_audit_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_evidence_vault_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_final_board_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_reviewer_pack, _commands_trust_parts_dependencies.verify_trust_operations_assurance_package, _commands_trust_parts_dependencies.verify_trust_operations_assurance_watch_package, _commands_trust_parts_dependencies.verify_trust_operations_assurance_watch_signoff_archive_package, _commands_trust_parts_dependencies.verify_trust_operations_control_package, _commands_trust_parts_dependencies.verify_trust_operations_control_signoff_archive_package, _commands_trust_parts_dependencies.verify_trust_operations_final_handoff_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_incident_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_runbook_package, _commands_trust_parts_dependencies.verify_trust_operations_incident_knowledge_package, _commands_trust_parts_dependencies.write_interface_document, _commands_trust_parts_dependencies.write_json, _commands_trust_parts_dependencies.write_public_trust_center_acceptance_board_signoff_archive_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_acceptance_board_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_anchor_registry_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_anchor_transparency_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_distribution_kit_accepted_evidence_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_distribution_kit_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_publication_monitoring_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_publication_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_audit_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_archive_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_accepted_evidence_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_response_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_review_pack_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_registry_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_transparency_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_audit_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_evidence_vault_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_final_board_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_reviewer_pack_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_watch_signoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_watch_verification_report, _commands_trust_parts_dependencies.write_trust_operations_control_signoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_control_verification_report, _commands_trust_parts_dependencies.write_trust_operations_final_handoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_incident_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_runbook_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_verification_report, _commands_trust_parts_dependencies.write_trust_operations_incident_knowledge_verification_report
def _execute_trust_operations_final_readiness(argv: list[str]) -> None:
    raw_args = ['trust-operations-final-readiness', *argv]
    pass
    pass
    parser = build_trust_operations_final_readiness_parser()
    args = parser.parse_args(raw_args[1:])
    store = TrustOperationsFinalReadinessStore()
    result: ImplementationDocument = {"ok": True}
    source_payload = _trust_operations_final_readiness_source_payload(args)
    if args.refresh_report:
        result.update(store.refresh_report(source_payload))
    if args.create_certificate:
        result["certificate"] = store.create_certificate()
    if args.sign:
        result["signoff"] = store.sign({"signed_by": args.signed_by, "role": args.role, "reason": args.reason})
    if args.create_change_request:
        result["change_request"] = store.create_change_request({"reason": args.reason, "requested_by": args.signed_by})
    if args.approve_change_request:
        result["change_request"] = store.approve_change_request(args.approve_change_request, {"approved_by": args.signed_by})
    if args.reset_signoff:
        result["reset"] = store.reset_signoff(args.reset_signoff)
    if args.export:
        result["manifest"] = store.export_handoff(source_payload)
    if args.zip:
        result["zip"] = store.build_handoff_zip()
    if args.verify:
        verification = store.verify_handoff_zip({**source_payload, "strict": args.strict, "require_signed": args.require_signed, "require_current": args.require_current})
        result["verification"] = verification
        result["verification_summary"] = verification.get("summary", {})
    if not any([args.refresh_report, args.create_certificate, args.sign, args.create_change_request, args.approve_change_request, args.reset_signoff, args.export, args.zip, args.verify]):
        result["summary"] = store.summary()
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        if "verification" in result:
            print_trust_operations_final_handoff_verification_report(result["verification"])
        else:
            print(json.dumps(result.get("summary") or {"status": "ok"}, ensure_ascii=False, indent=2))
    raise SystemExit(0)

def handle_trust_operations_final_readiness(argv: list[str]) -> None:
    _execute_trust_operations_final_readiness(argv)

def _execute_trust_operations_controls(argv: list[str]) -> None:
    raw_args = ['trust-operations-controls', *argv]
    pass
    pass
    pass
    pass
    pass
    parser = build_trust_operations_controls_parser()
    args = parser.parse_args(raw_args[1:])
    hub_store = TrustOperationsHubStore()
    incident_store = TrustOperationsIncidentStore(hub_store=hub_store)
    knowledge_store = TrustOperationsIncidentKnowledgeStore(hub_store=hub_store, incident_store=incident_store)
    store = TrustOperationsControlStore(hub_store=hub_store, incident_store=incident_store, knowledge_store=knowledge_store)
    result: ImplementationDocument = {"ok": True, "hub_id": args.hub_id}
    source_payload = {
        "hub_package_path": args.hub_package,
        "hub_verification_report_path": args.hub_verification_report,
        "incident_board_package_path": args.incident_board_package,
        "incident_board_verification_report_path": args.incident_board_verification_report,
        "incident_knowledge_package_path": args.incident_knowledge_package,
        "incident_knowledge_verification_report_path": args.incident_knowledge_verification_report,
    }
    if args.refresh_catalog:
        result["catalog"] = store.refresh_catalog(args.hub_id, source_payload)
    if args.create_policy:
        policy = store.create_policy_bundle(args.hub_id, {"policy_id": args.policy_id, "name": args.policy_name})
        args.policy_id = str(policy.get("policy_id") or args.policy_id or "")
        result["policy"] = policy
    if args.assess:
        if not args.policy_id:
            policies = store.list_policies(args.hub_id)
            if not policies:
                raise ValueError("--policy-id is required when no policy exists.")
            args.policy_id = str(policies[0].get("policy_id") or "")
        assessed = store.assess_policy(args.hub_id, str(args.policy_id), {**source_payload, "assessment_id": args.assessment_id})
        args.assessment_id = str((assessed.get("assessment") or {}).get("assessment_id") or args.assessment_id or "")
        result.update(assessed)
    if not args.assessment_id and (args.export or args.zip or args.verify):
        assessments = sorted(store.assessments_dir(args.hub_id).glob("*/control-assessment-report.json")) if store.assessments_dir(args.hub_id).exists() else []
        if assessments:
            args.assessment_id = assessments[-1].parent.name
    if args.export:
        if not args.assessment_id:
            raise ValueError("--assessment-id is required for --export unless --assess was used.")
        result["manifest"] = store.export_controls(args.hub_id, str(args.assessment_id))
    if args.zip:
        if not args.assessment_id:
            raise ValueError("--assessment-id is required for --zip unless --assess was used.")
        result["zip"] = store.build_zip(args.hub_id, str(args.assessment_id))
    if args.verify:
        if not args.assessment_id:
            raise ValueError("--assessment-id is required for --verify unless --assess was used.")
        verification = store.verify_zip(args.hub_id, str(args.assessment_id), {**source_payload, "strict": args.strict, "require_policy_passed": args.require_policy_passed})
        result["verification"] = verification
        result["verification_summary"] = verification.get("summary", {})
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        if "verification" in result:
            print_trust_operations_control_verification_report(result["verification"])
        else:
            print(json.dumps(result.get("summary") or {"status": "ok", "hub_id": args.hub_id, "assessment_id": args.assessment_id}, ensure_ascii=False, indent=2))
    raise SystemExit(0)

def handle_trust_operations_controls(argv: list[str]) -> None:
    _execute_trust_operations_controls(argv)

def _execute_trust_operations_assurance(argv: list[str]) -> None:
    raw_args = ['trust-operations-assurance', *argv]
    pass
    pass
    pass
    parser = build_trust_operations_assurance_parser()
    args = parser.parse_args(raw_args[1:])
    hub_store = TrustOperationsHubStore()
    store = TrustOperationsAssuranceStore(hub_store=hub_store)
    result: ImplementationDocument = {"ok": True, "hub_id": args.hub_id}
    source_payload = _trust_operations_assurance_source_payload(args)
    if args.list:
        result["runs"] = store.list_runs(args.hub_id)
    if args.refresh:
        refreshed = store.refresh_run(args.hub_id, {**source_payload, "run_id": args.run_id}, policy_id=args.policy_id)
        result.update(refreshed)
        args.run_id = str((refreshed.get("run") or {}).get("run_id") or args.run_id or "")
    if args.export:
        if not args.run_id:
            raise ValueError("--run-id is required for --export unless --refresh was used.")
        result["manifest"] = store.export_archive(args.run_id, source_payload)
    if args.zip:
        if not args.run_id:
            raise ValueError("--run-id is required for --zip unless --refresh was used.")
        result["zip"] = store.build_archive_zip(args.run_id, source_payload)
    if args.verify:
        if not args.run_id:
            raise ValueError("--run-id is required for --verify unless --refresh was used.")
        verification = store.verify_archive_zip(args.run_id, {**source_payload, "strict": args.strict, "require_passed": args.require_passed, "require_current": args.require_current})
        result["verification"] = verification
        result["verification_summary"] = verification.get("summary", {})
    if not any([args.list, args.refresh, args.export, args.zip, args.verify]):
        if not args.run_id:
            result["runs"] = store.list_runs(args.hub_id)
        else:
            result["summary"] = store.summary(args.run_id)
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        if "verification" in result:
            print_trust_operations_assurance_verification_report(result["verification"])
        else:
            print(json.dumps(result.get("summary") or {"status": "ok", "hub_id": args.hub_id, "run_id": args.run_id}, ensure_ascii=False, indent=2))
    raise SystemExit(0)

def handle_trust_operations_assurance(argv: list[str]) -> None:
    _execute_trust_operations_assurance(argv)

def _execute_trust_operations_control_signoff(argv: list[str]) -> None:
    raw_args = ['trust-operations-control-signoff', *argv]
    pass
    pass
    pass
    pass
    pass
    pass
    parser = build_trust_operations_control_signoff_parser()
    args = parser.parse_args(raw_args[1:])
    hub_store = TrustOperationsHubStore()
    incident_store = TrustOperationsIncidentStore(hub_store=hub_store)
    knowledge_store = TrustOperationsIncidentKnowledgeStore(hub_store=hub_store, incident_store=incident_store)
    control_store = TrustOperationsControlStore(hub_store=hub_store, incident_store=incident_store, knowledge_store=knowledge_store)
    store = TrustOperationsControlSignoffStore(control_store=control_store, hub_store=hub_store, incident_store=incident_store, knowledge_store=knowledge_store)
    result: ImplementationDocument = {"ok": True, "hub_id": args.hub_id}
    source_payload = {
        "control_package_path": args.control_package,
        "control_verification_report_path": args.control_verification_report,
        "hub_package_path": args.hub_package,
        "hub_verification_report_path": args.hub_verification_report,
        "incident_board_package_path": args.incident_board_package,
        "incident_board_verification_report_path": args.incident_board_verification_report,
        "incident_knowledge_package_path": args.incident_knowledge_package,
        "incident_knowledge_verification_report_path": args.incident_knowledge_verification_report,
    }
    if args.sign:
        if not args.assessment_id:
            raise ValueError("--assessment-id is required for --sign.")
        result["signoff"] = store.sign(args.hub_id, str(args.assessment_id), {**source_payload, "signed_by": args.signed_by, "reason": args.reason})
    if args.request_exception:
        if not args.assessment_id or not args.control_id:
            raise ValueError("--assessment-id and --control-id are required for --request-exception.")
        result["exception"] = store.request_exception(args.hub_id, {"assessment_id": args.assessment_id, "control_id": args.control_id, "requested_by": args.requested_by, "reason": args.reason, "expires_at": args.expires_at, "mitigation": args.mitigation})
    if args.approve_exception:
        if not args.exception_id:
            raise ValueError("--exception-id is required for --approve-exception.")
        result["exception"] = store.approve_exception(args.hub_id, args.exception_id, {"approved_by": args.approved_by, "reason": args.reason})
    if args.reject_exception:
        if not args.exception_id:
            raise ValueError("--exception-id is required for --reject-exception.")
        result["exception"] = store.reject_exception(args.hub_id, args.exception_id, {"approved_by": args.approved_by, "reason": args.reason})
    if args.create_change_request:
        result["change_request"] = store.create_change_request(args.hub_id, {"reason": args.reason, "created_by": args.requested_by, "change_request_id": args.change_request_id})
    if args.approve_change_request:
        if not args.change_request_id:
            raise ValueError("--change-request-id is required for --approve-change-request.")
        result["change_request"] = store.approve_change_request(args.hub_id, args.change_request_id, {"approved_by": args.approved_by, "reason": args.reason})
    if args.reset:
        if not args.change_request_id:
            raise ValueError("--change-request-id is required for --reset.")
        result["reset"] = store.reset_signoff(args.hub_id, args.change_request_id)
    if args.export:
        result["manifest"] = store.export_archive(args.hub_id, source_payload)
    if args.zip:
        result["zip"] = store.build_archive_zip(args.hub_id)
    if args.verify:
        verification = store.verify_archive_zip(args.hub_id, {**source_payload, "strict": args.strict, "require_signed": args.require_signed, "require_current": args.require_current})
        result["verification"] = verification
        result["verification_summary"] = verification.get("summary", {})
    if not any([args.sign, args.request_exception, args.approve_exception, args.reject_exception, args.create_change_request, args.approve_change_request, args.reset, args.export, args.zip, args.verify]):
        result["summary"] = store.summary(args.hub_id)
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        if "verification" in result:
            print_trust_operations_control_signoff_verification_report(result["verification"])
        else:
            print(json.dumps(result.get("summary") or {"status": "ok", "hub_id": args.hub_id}, ensure_ascii=False, indent=2))
    raise SystemExit(0)

def handle_trust_operations_control_signoff(argv: list[str]) -> None:
    _execute_trust_operations_control_signoff(argv)

def _execute_trust_operations_hub_runbook(argv: list[str]) -> None:
    raw_args = ['trust-operations-hub-runbook', *argv]
    pass
    pass
    pass
    parser = build_trust_operations_hub_runbook_parser()
    args = parser.parse_args(raw_args[1:])
    hub_store = TrustOperationsHubStore()
    store = TrustOperationsHubRunbookStore(hub_store=hub_store)
    result: ImplementationDocument = {"ok": True, "hub_id": args.hub_id}
    report_id = args.report_id
    if not report_id:
        current = read_json(hub_store.current_report_path(args.hub_id)) if hub_store.current_report_path(args.hub_id).exists() else {}
        report_id = str(current.get("report_id") or "")
    runbook_id = args.runbook_id
    if args.create:
        if not report_id:
            raise ValueError("--report-id is required for --create unless a current Hub report exists.")
        runbook = store.create_runbook(args.hub_id, report_id, {"runbook_id": runbook_id})
        runbook_id = str(runbook.get("runbook_id") or runbook_id or "")
        result["runbook"] = runbook
    if not runbook_id:
        raise ValueError("--runbook-id is required unless --create was used.")
    if args.run_safe:
        result["result"] = store.run_safe_actions(args.hub_id, runbook_id)
    if args.export:
        result["manifest"] = store.export_runbook(args.hub_id, runbook_id)
    if args.zip:
        result["zip"] = store.build_zip(args.hub_id, runbook_id)
    if args.verify:
        verification = verify_trust_operations_hub_runbook_package(store.zip_path(args.hub_id, runbook_id), strict=args.strict, require_completed=args.require_completed, require_no_blocked=args.require_no_blocked)
        result["verification"] = verification
        result["verification_summary"] = verification.get("summary", {})
    if args.report_out is not None:
        write_interface_document(args.report_out, result)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        if "verification" in result:
            print_trust_operations_hub_runbook_verification_report(result["verification"])
        else:
            print(json.dumps(result.get("summary") or {"status": "ok", "hub_id": args.hub_id, "runbook_id": runbook_id}, ensure_ascii=False, indent=2))
    raise SystemExit(0)

def handle_trust_operations_hub_runbook(argv: list[str]) -> None:
    _execute_trust_operations_hub_runbook(argv)

__all__ = ('_execute_trust_operations_final_readiness', 'handle_trust_operations_final_readiness', '_execute_trust_operations_controls', 'handle_trust_operations_controls', '_execute_trust_operations_assurance', 'handle_trust_operations_assurance', '_execute_trust_operations_control_signoff', 'handle_trust_operations_control_signoff', '_execute_trust_operations_hub_runbook', 'handle_trust_operations_hub_runbook')
