from __future__ import annotations

from song_agent.platform.contracts.documents import ImplementationDocument

from . import dependencies as _commands_trust_parts_dependencies
Any, CommandSpec, DistributionStore, Path, ProviderConfig, ProviderError, PublicTrustCenterAcceptanceBoardStore, PublicTrustCenterAnchorRegistryStore, PublicTrustCenterAnchorTransparencyStore, PublicTrustCenterDistributionKitAcceptanceStore, PublicTrustCenterDistributionKitStore, PublicTrustCenterPublicationMonitoringStore, PublicTrustCenterPublicationStore, PublicTrustCenterStore, ReleaseOperationsAuditStore, ReleaseOperationsReviewerPackStore, ReleaseOperationsRunbookStore, ReleaseOperationsSignoffStore, ReleaseOperationsStore, ReleasePortfolioAuditStore, ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, ReleasePortfolioGovernanceAttestationPortalReviewStore, ReleasePortfolioGovernanceAttestationPortalStore, ReleasePortfolioGovernanceAttestationRegistryStore, ReleasePortfolioGovernanceAttestationStore, ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore, ReleasePortfolioGovernanceAttestationTransparencyStore, ReleasePortfolioGovernanceAuditStore, ReleasePortfolioGovernanceEvidenceVaultStore, ReleasePortfolioGovernanceFinalBoardStore, ReleasePortfolioGovernanceReviewerPackStore, ReleasePortfolioGovernanceSignoffStore, ReleasePortfolioGovernanceStore, ReleaseStore, SongRequest, SubmissionEvidenceStore, SubmissionStore, TrustOperationsAssuranceStore, TrustOperationsAssuranceWatchSignoffStore, TrustOperationsAssuranceWatchStore, TrustOperationsControlSignoffStore, TrustOperationsControlStore, TrustOperationsFinalReadinessStore, TrustOperationsHubRunbookStore, TrustOperationsHubStore, TrustOperationsIncidentKnowledgeStore, TrustOperationsIncidentStore, acknowledgement_summary, anchor_registry_summary, anchor_transparency_summary, argparse, base64, build_auth_config, distribution_kit_summary, generate_request, json, load_provider_config, monitoring_summary, os, portfolio_audit_summary, portfolio_governance_attestation_registry_summary, portfolio_governance_attestation_summary, portfolio_governance_audit_summary, portfolio_governance_evidence_vault_summary, portfolio_governance_final_board_summary, portfolio_governance_reviewer_pack_summary, print_public_trust_center_acceptance_board_signoff_archive_verification_report, print_public_trust_center_acceptance_board_verification_report, print_public_trust_center_anchor_registry_verification_report, print_public_trust_center_anchor_transparency_verification_report, print_public_trust_center_distribution_kit_accepted_evidence_verification_report, print_public_trust_center_distribution_kit_verification_report, print_public_trust_center_publication_monitoring_verification_report, print_public_trust_center_publication_verification_report, print_public_trust_center_verification_report, print_release_portfolio_audit_verification_report, print_release_portfolio_governance_archive_verification_report, print_release_portfolio_governance_attestation_accepted_evidence_verification_report, print_release_portfolio_governance_attestation_portal_response_verification_report, print_release_portfolio_governance_attestation_portal_review_pack_verification_report, print_release_portfolio_governance_attestation_portal_verification_report, print_release_portfolio_governance_attestation_registry_verification_report, print_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, print_release_portfolio_governance_attestation_transparency_verification_report, print_release_portfolio_governance_attestation_verification_report, print_release_portfolio_governance_audit_verification_report, print_release_portfolio_governance_evidence_vault_verification_report, print_release_portfolio_governance_final_board_verification_report, print_release_portfolio_governance_reviewer_pack_verification_report, print_release_portfolio_governance_verification_report, print_trust_operations_assurance_verification_report, print_trust_operations_assurance_watch_signoff_verification_report, print_trust_operations_assurance_watch_verification_report, print_trust_operations_control_signoff_verification_report, print_trust_operations_control_verification_report, print_trust_operations_final_handoff_verification_report, print_trust_operations_hub_incident_verification_report, print_trust_operations_hub_runbook_verification_report, print_trust_operations_hub_verification_report, print_trust_operations_incident_knowledge_verification_report, provider_configured, public_trust_center_acceptance_board_signoff_archive_verification_exit_code, public_trust_center_acceptance_board_verification_exit_code, public_trust_center_anchor_registry_verification_exit_code, public_trust_center_anchor_transparency_verification_exit_code, public_trust_center_distribution_kit_accepted_evidence_verification_exit_code, public_trust_center_distribution_kit_verification_exit_code, public_trust_center_publication_monitoring_verification_exit_code, public_trust_center_publication_verification_exit_code, public_trust_center_summary, public_trust_center_verification_exit_code, publication_summary, queue_summary, read_json, release_portfolio_audit_verification_exit_code, release_portfolio_audit_verification_summary, release_portfolio_governance_archive_verification_exit_code, release_portfolio_governance_archive_verification_summary, release_portfolio_governance_attestation_accepted_evidence_verification_exit_code, release_portfolio_governance_attestation_portal_response_summary, release_portfolio_governance_attestation_portal_review_pack_summary, release_portfolio_governance_attestation_portal_review_verification_exit_code, release_portfolio_governance_attestation_portal_summary, release_portfolio_governance_attestation_portal_verification_exit_code, release_portfolio_governance_attestation_portal_verification_summary, release_portfolio_governance_attestation_registry_verification_exit_code, release_portfolio_governance_attestation_registry_verification_summary, release_portfolio_governance_attestation_transparency_acknowledgement_verification_exit_code, release_portfolio_governance_attestation_transparency_verification_exit_code, release_portfolio_governance_attestation_verification_exit_code, release_portfolio_governance_attestation_verification_summary, release_portfolio_governance_audit_verification_exit_code, release_portfolio_governance_audit_verification_summary, release_portfolio_governance_evidence_vault_verification_exit_code, release_portfolio_governance_evidence_vault_verification_summary, release_portfolio_governance_final_board_verification_exit_code, release_portfolio_governance_final_board_verification_summary, release_portfolio_governance_reviewer_pack_verification_exit_code, release_portfolio_governance_reviewer_pack_verification_summary, release_portfolio_governance_verification_exit_code, release_portfolio_governance_verification_summary, sys, test_provider_config, transparency_summary, trust_operations_assurance_verification_exit_code, trust_operations_assurance_watch_signoff_verification_exit_code, trust_operations_assurance_watch_verification_exit_code, trust_operations_control_signoff_verification_exit_code, trust_operations_control_verification_exit_code, trust_operations_final_handoff_verification_exit_code, trust_operations_hub_incident_verification_exit_code, trust_operations_hub_runbook_verification_exit_code, trust_operations_hub_verification_exit_code, trust_operations_incident_knowledge_verification_exit_code, verify_public_trust_center_acceptance_board_package, verify_public_trust_center_acceptance_board_signoff_archive_package, verify_public_trust_center_anchor_registry_package, verify_public_trust_center_anchor_transparency_package, verify_public_trust_center_distribution_kit_accepted_evidence_package, verify_public_trust_center_distribution_kit_package, verify_public_trust_center_package, verify_public_trust_center_publication_mirror, verify_public_trust_center_publication_monitoring_package, verify_public_trust_center_publication_package, verify_release_portfolio_audit_package, verify_release_portfolio_governance_archive_package, verify_release_portfolio_governance_attestation, verify_release_portfolio_governance_attestation_accepted_evidence, verify_release_portfolio_governance_attestation_portal, verify_release_portfolio_governance_attestation_portal_response, verify_release_portfolio_governance_attestation_portal_review_pack, verify_release_portfolio_governance_attestation_registry, verify_release_portfolio_governance_attestation_transparency, verify_release_portfolio_governance_attestation_transparency_acknowledgement_package, verify_release_portfolio_governance_audit_package, verify_release_portfolio_governance_evidence_vault_package, verify_release_portfolio_governance_final_board_package, verify_release_portfolio_governance_package, verify_release_portfolio_governance_reviewer_pack, verify_trust_operations_assurance_package, verify_trust_operations_assurance_watch_package, verify_trust_operations_assurance_watch_signoff_archive_package, verify_trust_operations_control_package, verify_trust_operations_control_signoff_archive_package, verify_trust_operations_final_handoff_package, verify_trust_operations_hub_incident_package, verify_trust_operations_hub_package, verify_trust_operations_hub_runbook_package, verify_trust_operations_incident_knowledge_package, write_interface_document, write_json, write_public_trust_center_acceptance_board_signoff_archive_verification_report, write_public_trust_center_acceptance_board_verification_report, write_public_trust_center_anchor_registry_verification_report, write_public_trust_center_anchor_transparency_verification_report, write_public_trust_center_distribution_kit_accepted_evidence_verification_report, write_public_trust_center_distribution_kit_verification_report, write_public_trust_center_publication_monitoring_verification_report, write_public_trust_center_publication_verification_report, write_public_trust_center_verification_report, write_release_portfolio_audit_verification_report, write_release_portfolio_governance_archive_verification_report, write_release_portfolio_governance_attestation_accepted_evidence_verification_report, write_release_portfolio_governance_attestation_portal_response_verification_report, write_release_portfolio_governance_attestation_portal_review_pack_verification_report, write_release_portfolio_governance_attestation_portal_verification_report, write_release_portfolio_governance_attestation_registry_verification_report, write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, write_release_portfolio_governance_attestation_transparency_verification_report, write_release_portfolio_governance_attestation_verification_report, write_release_portfolio_governance_audit_verification_report, write_release_portfolio_governance_evidence_vault_verification_report, write_release_portfolio_governance_final_board_verification_report, write_release_portfolio_governance_reviewer_pack_verification_report, write_release_portfolio_governance_verification_report, write_trust_operations_assurance_verification_report, write_trust_operations_assurance_watch_signoff_verification_report, write_trust_operations_assurance_watch_verification_report, write_trust_operations_control_signoff_verification_report, write_trust_operations_control_verification_report, write_trust_operations_final_handoff_verification_report, write_trust_operations_hub_incident_verification_report, write_trust_operations_hub_runbook_verification_report, write_trust_operations_hub_verification_report, write_trust_operations_incident_knowledge_verification_report = _commands_trust_parts_dependencies.Any, _commands_trust_parts_dependencies.CommandSpec, _commands_trust_parts_dependencies.DistributionStore, _commands_trust_parts_dependencies.Path, _commands_trust_parts_dependencies.ProviderConfig, _commands_trust_parts_dependencies.ProviderError, _commands_trust_parts_dependencies.PublicTrustCenterAcceptanceBoardStore, _commands_trust_parts_dependencies.PublicTrustCenterAnchorRegistryStore, _commands_trust_parts_dependencies.PublicTrustCenterAnchorTransparencyStore, _commands_trust_parts_dependencies.PublicTrustCenterDistributionKitAcceptanceStore, _commands_trust_parts_dependencies.PublicTrustCenterDistributionKitStore, _commands_trust_parts_dependencies.PublicTrustCenterPublicationMonitoringStore, _commands_trust_parts_dependencies.PublicTrustCenterPublicationStore, _commands_trust_parts_dependencies.PublicTrustCenterStore, _commands_trust_parts_dependencies.ReleaseOperationsAuditStore, _commands_trust_parts_dependencies.ReleaseOperationsReviewerPackStore, _commands_trust_parts_dependencies.ReleaseOperationsRunbookStore, _commands_trust_parts_dependencies.ReleaseOperationsSignoffStore, _commands_trust_parts_dependencies.ReleaseOperationsStore, _commands_trust_parts_dependencies.ReleasePortfolioAuditStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationAcceptedEvidenceStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationPortalReviewStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationPortalStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationRegistryStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationTransparencyAcknowledgementStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAttestationTransparencyStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceAuditStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceEvidenceVaultStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceFinalBoardStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceReviewerPackStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceSignoffStore, _commands_trust_parts_dependencies.ReleasePortfolioGovernanceStore, _commands_trust_parts_dependencies.ReleaseStore, _commands_trust_parts_dependencies.SongRequest, _commands_trust_parts_dependencies.SubmissionEvidenceStore, _commands_trust_parts_dependencies.SubmissionStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceWatchSignoffStore, _commands_trust_parts_dependencies.TrustOperationsAssuranceWatchStore, _commands_trust_parts_dependencies.TrustOperationsControlSignoffStore, _commands_trust_parts_dependencies.TrustOperationsControlStore, _commands_trust_parts_dependencies.TrustOperationsFinalReadinessStore, _commands_trust_parts_dependencies.TrustOperationsHubRunbookStore, _commands_trust_parts_dependencies.TrustOperationsHubStore, _commands_trust_parts_dependencies.TrustOperationsIncidentKnowledgeStore, _commands_trust_parts_dependencies.TrustOperationsIncidentStore, _commands_trust_parts_dependencies.acknowledgement_summary, _commands_trust_parts_dependencies.anchor_registry_summary, _commands_trust_parts_dependencies.anchor_transparency_summary, _commands_trust_parts_dependencies.argparse, _commands_trust_parts_dependencies.base64, _commands_trust_parts_dependencies.build_auth_config, _commands_trust_parts_dependencies.distribution_kit_summary, _commands_trust_parts_dependencies.generate_request, _commands_trust_parts_dependencies.json, _commands_trust_parts_dependencies.load_provider_config, _commands_trust_parts_dependencies.monitoring_summary, _commands_trust_parts_dependencies.os, _commands_trust_parts_dependencies.portfolio_audit_summary, _commands_trust_parts_dependencies.portfolio_governance_attestation_registry_summary, _commands_trust_parts_dependencies.portfolio_governance_attestation_summary, _commands_trust_parts_dependencies.portfolio_governance_audit_summary, _commands_trust_parts_dependencies.portfolio_governance_evidence_vault_summary, _commands_trust_parts_dependencies.portfolio_governance_final_board_summary, _commands_trust_parts_dependencies.portfolio_governance_reviewer_pack_summary, _commands_trust_parts_dependencies.print_public_trust_center_acceptance_board_signoff_archive_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_acceptance_board_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_anchor_registry_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_anchor_transparency_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_distribution_kit_accepted_evidence_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_distribution_kit_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_publication_monitoring_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_publication_verification_report, _commands_trust_parts_dependencies.print_public_trust_center_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_audit_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_archive_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_accepted_evidence_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_response_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_review_pack_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_portal_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_registry_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_transparency_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_attestation_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_audit_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_evidence_vault_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_final_board_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_reviewer_pack_verification_report, _commands_trust_parts_dependencies.print_release_portfolio_governance_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_watch_signoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_assurance_watch_verification_report, _commands_trust_parts_dependencies.print_trust_operations_control_signoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_control_verification_report, _commands_trust_parts_dependencies.print_trust_operations_final_handoff_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_incident_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_runbook_verification_report, _commands_trust_parts_dependencies.print_trust_operations_hub_verification_report, _commands_trust_parts_dependencies.print_trust_operations_incident_knowledge_verification_report, _commands_trust_parts_dependencies.provider_configured, _commands_trust_parts_dependencies.public_trust_center_acceptance_board_signoff_archive_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_acceptance_board_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_anchor_registry_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_anchor_transparency_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_distribution_kit_accepted_evidence_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_distribution_kit_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_publication_monitoring_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_publication_verification_exit_code, _commands_trust_parts_dependencies.public_trust_center_summary, _commands_trust_parts_dependencies.public_trust_center_verification_exit_code, _commands_trust_parts_dependencies.publication_summary, _commands_trust_parts_dependencies.queue_summary, _commands_trust_parts_dependencies.read_json, _commands_trust_parts_dependencies.release_portfolio_audit_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_audit_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_archive_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_archive_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_accepted_evidence_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_response_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_review_pack_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_review_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_portal_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_registry_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_registry_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_transparency_acknowledgement_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_transparency_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_attestation_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_audit_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_audit_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_evidence_vault_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_evidence_vault_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_final_board_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_final_board_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_reviewer_pack_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_reviewer_pack_verification_summary, _commands_trust_parts_dependencies.release_portfolio_governance_verification_exit_code, _commands_trust_parts_dependencies.release_portfolio_governance_verification_summary, _commands_trust_parts_dependencies.sys, _commands_trust_parts_dependencies.test_provider_config, _commands_trust_parts_dependencies.transparency_summary, _commands_trust_parts_dependencies.trust_operations_assurance_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_assurance_watch_signoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_assurance_watch_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_control_signoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_control_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_final_handoff_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_incident_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_runbook_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_hub_verification_exit_code, _commands_trust_parts_dependencies.trust_operations_incident_knowledge_verification_exit_code, _commands_trust_parts_dependencies.verify_public_trust_center_acceptance_board_package, _commands_trust_parts_dependencies.verify_public_trust_center_acceptance_board_signoff_archive_package, _commands_trust_parts_dependencies.verify_public_trust_center_anchor_registry_package, _commands_trust_parts_dependencies.verify_public_trust_center_anchor_transparency_package, _commands_trust_parts_dependencies.verify_public_trust_center_distribution_kit_accepted_evidence_package, _commands_trust_parts_dependencies.verify_public_trust_center_distribution_kit_package, _commands_trust_parts_dependencies.verify_public_trust_center_package, _commands_trust_parts_dependencies.verify_public_trust_center_publication_mirror, _commands_trust_parts_dependencies.verify_public_trust_center_publication_monitoring_package, _commands_trust_parts_dependencies.verify_public_trust_center_publication_package, _commands_trust_parts_dependencies.verify_release_portfolio_audit_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_archive_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_accepted_evidence, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal_response, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_portal_review_pack, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_registry, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_transparency, _commands_trust_parts_dependencies.verify_release_portfolio_governance_attestation_transparency_acknowledgement_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_audit_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_evidence_vault_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_final_board_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_package, _commands_trust_parts_dependencies.verify_release_portfolio_governance_reviewer_pack, _commands_trust_parts_dependencies.verify_trust_operations_assurance_package, _commands_trust_parts_dependencies.verify_trust_operations_assurance_watch_package, _commands_trust_parts_dependencies.verify_trust_operations_assurance_watch_signoff_archive_package, _commands_trust_parts_dependencies.verify_trust_operations_control_package, _commands_trust_parts_dependencies.verify_trust_operations_control_signoff_archive_package, _commands_trust_parts_dependencies.verify_trust_operations_final_handoff_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_incident_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_package, _commands_trust_parts_dependencies.verify_trust_operations_hub_runbook_package, _commands_trust_parts_dependencies.verify_trust_operations_incident_knowledge_package, _commands_trust_parts_dependencies.write_interface_document, _commands_trust_parts_dependencies.write_json, _commands_trust_parts_dependencies.write_public_trust_center_acceptance_board_signoff_archive_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_acceptance_board_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_anchor_registry_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_anchor_transparency_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_distribution_kit_accepted_evidence_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_distribution_kit_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_publication_monitoring_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_publication_verification_report, _commands_trust_parts_dependencies.write_public_trust_center_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_audit_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_archive_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_accepted_evidence_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_response_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_review_pack_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_portal_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_registry_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_transparency_acknowledgement_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_transparency_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_attestation_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_audit_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_evidence_vault_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_final_board_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_reviewer_pack_verification_report, _commands_trust_parts_dependencies.write_release_portfolio_governance_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_watch_signoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_assurance_watch_verification_report, _commands_trust_parts_dependencies.write_trust_operations_control_signoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_control_verification_report, _commands_trust_parts_dependencies.write_trust_operations_final_handoff_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_incident_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_runbook_verification_report, _commands_trust_parts_dependencies.write_trust_operations_hub_verification_report, _commands_trust_parts_dependencies.write_trust_operations_incident_knowledge_verification_report
def build_trust_operations_control_signoff_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Sign, archive, and verify Trust Operations Controls.")
    parser.add_argument("--hub-id", default="hub", help="Trust Operations Hub id.")
    parser.add_argument("--assessment-id", default=None, help="Control assessment id.")
    parser.add_argument("--sign", action="store_true", help="Sign the current Control verification evidence.")
    parser.add_argument("--signed-by", default="local-reviewer", help="Signer name.")
    parser.add_argument("--reason", default="Trust Operations control signoff operation.", help="Reason for signoff/change request/exception.")
    parser.add_argument("--request-exception", action="store_true", help="Request a Control exception.")
    parser.add_argument("--approve-exception", action="store_true", help="Approve a Control exception.")
    parser.add_argument("--reject-exception", action="store_true", help="Reject a Control exception.")
    parser.add_argument("--exception-id", default=None, help="Control exception id.")
    parser.add_argument("--control-id", default=None, help="Control id for an exception.")
    parser.add_argument("--requested-by", default="local-operator", help="Exception requester.")
    parser.add_argument("--approved-by", default="local-reviewer", help="Exception or CR approver.")
    parser.add_argument("--expires-at", default=None, help="Exception expiry timestamp.")
    parser.add_argument("--mitigation", default="", help="Exception mitigation note.")
    parser.add_argument("--create-change-request", action="store_true", help="Create a Control Signoff change request.")
    parser.add_argument("--approve-change-request", action="store_true", help="Approve a Control Signoff change request.")
    parser.add_argument("--change-request-id", default=None, help="Change request id.")
    parser.add_argument("--reset", action="store_true", help="Reset Control Signoff with an approved change request.")
    parser.add_argument("--export", action="store_true", help="Export the Control Signoff archive directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Control Signoff archive ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the Control Signoff archive ZIP.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-signed", action="store_true", default=True, help="Verifier requires signed evidence.")
    parser.add_argument("--no-require-signed", dest="require_signed", action="store_false", help="Do not require signed evidence.")
    parser.add_argument("--require-current", action="store_true", default=True, help="Verifier requires current external evidence.")
    parser.add_argument("--no-require-current", dest="require_current", action="store_false", help="Do not require current external evidence.")
    parser.add_argument("--control-package", type=Path, default=None, help="External Trust Operations Control ZIP.")
    parser.add_argument("--control-verification-report", type=Path, default=None, help="External Trust Operations Control verification report.")
    parser.add_argument("--hub-package", type=Path, default=None, help="External Trust Operations Hub ZIP.")
    parser.add_argument("--hub-verification-report", type=Path, default=None, help="External Trust Operations Hub verification report.")
    parser.add_argument("--incident-board-package", type=Path, default=None, help="External Trust Operations Incident Board ZIP.")
    parser.add_argument("--incident-board-verification-report", type=Path, default=None, help="External Trust Operations Incident Board verification report.")
    parser.add_argument("--incident-knowledge-package", type=Path, default=None, help="External Trust Operations Incident Knowledge ZIP.")
    parser.add_argument("--incident-knowledge-verification-report", type=Path, default=None, help="External Trust Operations Incident Knowledge verification report.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_trust_operations_hub_runbook_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create, run, export, and verify Trust Operations Hub Runbooks.")
    parser.add_argument("--hub-id", default="hub", help="Trust Operations Hub id.")
    parser.add_argument("--report-id", default=None, help="Hub report id. Defaults to current report when possible.")
    parser.add_argument("--runbook-id", default=None, help="Runbook id. Defaults to current or new runbook.")
    parser.add_argument("--create", action="store_true", help="Create a runbook from the current Hub report.")
    parser.add_argument("--run-safe", action="store_true", help="Run only safe automated actions.")
    parser.add_argument("--export", action="store_true", help="Export the runbook package directory.")
    parser.add_argument("--zip", action="store_true", help="Build the runbook ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the runbook ZIP.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-completed", action="store_true", help="Verifier requires completed runbook results.")
    parser.add_argument("--require-no-blocked", action="store_true", help="Verifier requires no blocked safe action results.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_trust_operations_hub_incidents_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create, remediate, export, and verify Trust Operations Incidents.")
    parser.add_argument("--hub-id", default="hub", help="Trust Operations Hub id.")
    parser.add_argument("--report-id", default=None, help="Hub report id. Defaults to current report.")
    parser.add_argument("--incident-id", default=None, help="Incident id.")
    parser.add_argument("--refresh", action="store_true", help="Refresh Incident Board from Hub blockers.")
    parser.add_argument("--list", action="store_true", help="List incidents.")
    parser.add_argument("--triage", action="store_true", help="Triage an incident.")
    parser.add_argument("--severity", default=None, help="Incident severity.")
    parser.add_argument("--owner", default="local-user", help="Triage owner.")
    parser.add_argument("--notes", default="", help="Triage notes.")
    parser.add_argument("--create-plan", action="store_true", help="Create a remediation plan.")
    parser.add_argument("--add-evidence", action="store_true", help="Add JSON verification evidence.")
    parser.add_argument("--evidence-kind", default="external_verification_report", help="Evidence kind.")
    parser.add_argument("--component-type", default=None, help="Evidence component type.")
    parser.add_argument("--component-id", default=None, help="Evidence component id.")
    parser.add_argument("--content-base64", default=None, help="Base64 encoded evidence JSON.")
    parser.add_argument("--evidence-file", type=Path, default=None, help="Evidence JSON file to read and import.")
    parser.add_argument("--verify-fix", action="store_true", help="Verify incident fix evidence.")
    parser.add_argument("--close", action="store_true", help="Close an incident.")
    parser.add_argument("--closed-by", default="local-user", help="Closeout actor.")
    parser.add_argument("--reason", default="Trust Operations incident remediated.", help="Closeout reason.")
    parser.add_argument("--archive", action="store_true", help="Archive a closed incident.")
    parser.add_argument("--export", action="store_true", help="Export the Incident Board package directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Incident Board ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the Incident Board ZIP.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-no-open-critical", action="store_true", help="Verifier requires no open critical incidents.")
    parser.add_argument("--require-no-open-blocking", action="store_true", help="Verifier requires no open blocking incidents.")
    parser.add_argument("--require-current-hub", action="store_true", help="Verifier requires current Hub verification evidence.")
    parser.add_argument("--hub-verification-report", type=Path, default=None, help="External Trust Operations Hub verification report.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_trust_operations_incident_knowledge_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create, run, export, and verify Trust Operations Incident Knowledge regression guards.")
    parser.add_argument("--hub-id", default="hub", help="Trust Operations Hub id.")
    parser.add_argument("--refresh", action="store_true", help="Refresh Knowledge entries from closed incidents.")
    parser.add_argument("--list-entries", action="store_true", help="List Knowledge entries.")
    parser.add_argument("--entry-id", default=None, help="Knowledge entry id.")
    parser.add_argument("--hide-entry", action="store_true", help="Hide a Knowledge entry.")
    parser.add_argument("--unhide-entry", action="store_true", help="Unhide a Knowledge entry.")
    parser.add_argument("--create-guard", action="store_true", help="Create a regression guard for a Knowledge entry.")
    parser.add_argument("--guard-id", default=None, help="Regression guard id.")
    parser.add_argument("--guard-type", default=None, help="Regression guard type.")
    parser.add_argument("--run-guard", action="store_true", help="Run a single regression guard.")
    parser.add_argument("--run-all-guards", action="store_true", help="Run all regression guards.")
    parser.add_argument("--refresh-recurrence", action="store_true", help="Refresh incident recurrence report.")
    parser.add_argument("--export", action="store_true", help="Export the Knowledge package directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Knowledge ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the Knowledge ZIP.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-guards-passed", action="store_true", help="Verifier requires passed guard runs.")
    parser.add_argument("--require-no-open-recurrence", action="store_true", help="Verifier requires no open recurrence.")
    parser.add_argument("--incident-board-package", type=Path, default=None, help="External Trust Operations Incident Board ZIP.")
    parser.add_argument("--incident-board-verification-report", type=Path, default=None, help="External Trust Operations Incident Board verification report.")
    parser.add_argument("--hub-verification-report", type=Path, default=None, help="External Trust Operations Hub verification report.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_trust_operations_controls_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create, assess, export, and verify Trust Operations Controls.")
    parser.add_argument("--hub-id", default="hub", help="Trust Operations Hub id.")
    parser.add_argument("--policy-id", default=None, help="Control policy id.")
    parser.add_argument("--assessment-id", default=None, help="Control assessment id.")
    parser.add_argument("--refresh-catalog", action="store_true", help="Refresh the Control Catalog.")
    parser.add_argument("--create-policy", action="store_true", help="Create a Control Policy Bundle.")
    parser.add_argument("--policy-name", default="Default Trust Operations Controls", help="Control policy display name.")
    parser.add_argument("--assess", action="store_true", help="Assess a Control Policy Bundle.")
    parser.add_argument("--export", action="store_true", help="Export the Control package directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Control ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the Control ZIP.")
    parser.add_argument("--hub-package", type=Path, default=None, help="External Trust Operations Hub ZIP.")
    parser.add_argument("--hub-verification-report", type=Path, default=None, help="External Trust Operations Hub verification report.")
    parser.add_argument("--incident-board-package", type=Path, default=None, help="External Trust Operations Incident Board ZIP.")
    parser.add_argument("--incident-board-verification-report", type=Path, default=None, help="External Trust Operations Incident Board verification report.")
    parser.add_argument("--incident-knowledge-package", type=Path, default=None, help="External Trust Operations Incident Knowledge ZIP.")
    parser.add_argument("--incident-knowledge-verification-report", type=Path, default=None, help="External Trust Operations Incident Knowledge verification report.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-policy-passed", action="store_true", help="Verifier requires the control policy assessment to pass.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def build_public_trust_center_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build local MusicForge Public Trust Center reports and packages.")
    parser.add_argument("--center-id", default="ptc-default", help="Public Trust Center id.")
    parser.add_argument("--name", default=None, help="Display name.")
    parser.add_argument("--release-id", action="append", dest="release_ids", default=[], help="Release id to include. Can be repeated.")
    parser.add_argument("--portfolio-id", action="append", dest="portfolio_ids", default=[], help="Portfolio id to include. Can be repeated.")
    parser.add_argument("--profile", default="public_summary", help="Attestation profile.")
    parser.add_argument("--refresh", action="store_true", help="Refresh the Public Trust Center report.")
    parser.add_argument("--export", action="store_true", help="Build the static Trust Center export directory.")
    parser.add_argument("--zip", action="store_true", help="Build the Public Trust Center ZIP.")
    parser.add_argument("--verify", action="store_true", help="Verify the Public Trust Center ZIP.")
    parser.add_argument("--archive", action="store_true", help="Append an archive event for the current ZIP.")
    parser.add_argument("--anchor-register", action="store_true", help="Register the current delivery anchor in the Anchor Registry.")
    parser.add_argument("--anchor-publish", action="store_true", help="Publish the current Anchor Registry entry.")
    parser.add_argument("--anchor-revoke", default=None, help="Revoke an Anchor Registry entry id.")
    parser.add_argument("--anchor-export", action="store_true", help="Export the Anchor Registry package directory.")
    parser.add_argument("--anchor-zip", action="store_true", help="Build the Anchor Registry ZIP.")
    parser.add_argument("--anchor-verify", action="store_true", help="Verify the Anchor Registry ZIP.")
    parser.add_argument("--anchor-reason", default="Public Trust Center anchor registry operation", help="Reason for Anchor Registry state changes.")
    parser.add_argument("--anchor-transparency-refresh", action="store_true", help="Refresh the Anchor Transparency ledger/report.")
    parser.add_argument("--anchor-checkpoint-create", action="store_true", help="Create the current Anchor Transparency checkpoint.")
    parser.add_argument("--anchor-transparency-export", action="store_true", help="Export the Anchor Transparency package directory.")
    parser.add_argument("--anchor-transparency-zip", action="store_true", help="Build the Anchor Transparency ZIP.")
    parser.add_argument("--anchor-transparency-verify", action="store_true", help="Verify the Anchor Transparency ZIP.")
    parser.add_argument("--distribution-kit-refresh", action="store_true", help="Refresh the Public Trust Center Distribution Kit report.")
    parser.add_argument("--distribution-kit-export", action="store_true", help="Export the Public Trust Center Distribution Kit directory.")
    parser.add_argument("--distribution-kit-zip", action="store_true", help="Build the Public Trust Center Distribution Kit ZIP.")
    parser.add_argument("--distribution-kit-verify", action="store_true", help="Verify the Public Trust Center Distribution Kit ZIP.")
    parser.add_argument("--distribution-kit-acceptance-template", action="store_true", help="Create a Distribution Kit external acceptance response template.")
    parser.add_argument("--distribution-kit-acceptance-response-file", type=Path, default=None, help="Import a Distribution Kit acceptance response JSON file.")
    parser.add_argument("--distribution-kit-acceptance-response-base64", default=None, help="Import a base64-encoded Distribution Kit acceptance response.")
    parser.add_argument("--distribution-kit-acceptance-response-id", default=None, help="Distribution Kit acceptance response id.")
    parser.add_argument("--distribution-kit-acceptance-verify-response", action="store_true", help="Verify an imported Distribution Kit acceptance response.")
    parser.add_argument("--distribution-kit-accepted-evidence-export", action="store_true", help="Export accepted Distribution Kit evidence for the response.")
    parser.add_argument("--distribution-kit-accepted-evidence-zip", action="store_true", help="Build accepted Distribution Kit evidence ZIP for the response.")
    parser.add_argument("--distribution-kit-accepted-evidence-verify", action="store_true", help="Verify the accepted Distribution Kit evidence ZIP.")
    parser.add_argument("--distribution-kit-acceptance-change-request", action="store_true", help="Create a draft follow-up from a needs_changes/rejected Distribution Kit response.")
    parser.add_argument("--acceptance-board-policy-save", type=Path, default=None, help="Save Acceptance Board policy from a JSON file.")
    parser.add_argument("--acceptance-board-refresh", action="store_true", help="Refresh the Acceptance Board report.")
    parser.add_argument("--acceptance-board-export", action="store_true", help="Export the Acceptance Board directory.")
    parser.add_argument("--acceptance-board-zip", action="store_true", help="Build the Acceptance Board ZIP.")
    parser.add_argument("--acceptance-board-verify", action="store_true", help="Verify the Acceptance Board ZIP.")
    parser.add_argument("--acceptance-board-signoff-draft", action="store_true", help="Create an Acceptance Board signoff draft.")
    parser.add_argument("--acceptance-board-signoff", action="store_true", help="Sign the current ready Acceptance Board.")
    parser.add_argument("--acceptance-board-signed-by", default="MusicForge Operator", help="Signer name for Acceptance Board signoff.")
    parser.add_argument("--acceptance-board-signoff-reason", default="Acceptance Board ready for public release.", help="Reason for Acceptance Board signoff.")
    parser.add_argument("--acceptance-board-change-request-create", action="store_true", help="Create an Acceptance Board signoff Change Request.")
    parser.add_argument("--acceptance-board-change-request-approve", action="store_true", help="Approve an Acceptance Board signoff Change Request.")
    parser.add_argument("--acceptance-board-change-request-id", default=None, help="Acceptance Board Change Request id.")
    parser.add_argument("--acceptance-board-reset-signoff", action="store_true", help="Reset Acceptance Board signoff using an approved Change Request.")
    parser.add_argument("--acceptance-board-signoff-archive-export", action="store_true", help="Export the Acceptance Board signoff archive directory.")
    parser.add_argument("--acceptance-board-signoff-archive-zip", action="store_true", help="Build the Acceptance Board signoff archive ZIP.")
    parser.add_argument("--acceptance-board-signoff-archive-verify", action="store_true", help="Verify the Acceptance Board signoff archive ZIP.")
    parser.add_argument("--strict", action="store_true", help="Use strict verifier mode.")
    parser.add_argument("--require-ready", action="store_true", help="Verifier requires ready board/package state.")
    parser.add_argument("--require-quorum", action="store_true", help="Verifier requires board quorum.")
    parser.add_argument("--require-no-conflicts", action="store_true", help="Verifier requires no board conflicts.")
    parser.add_argument("--min-accepted-count", type=int, default=0, help="Minimum accepted evidence count required by the verifier.")
    parser.add_argument("--min-accepted-organizations", type=int, default=0, help="Minimum accepted organization count required by the verifier.")
    parser.add_argument("--required-role", action="append", dest="required_roles", default=[], help="Required Acceptance Board role. Can be repeated.")
    parser.add_argument("--require-registry-current", action="store_true", help="Require current Registry evidence.")
    parser.add_argument("--require-portal-current", action="store_true", help="Require current Portal evidence.")
    parser.add_argument("--require-transparency-current", action="store_true", help="Require current Transparency evidence.")
    parser.add_argument("--require-acknowledgement-current", action="store_true", help="Require current accepted acknowledgement evidence.")
    parser.add_argument("--include-delivery", dest="include_delivery", action="store_true", default=True, help="Include delivery chain summaries.")
    parser.add_argument("--no-include-delivery", dest="include_delivery", action="store_false", help="Do not include delivery chain summaries.")
    parser.add_argument("--include-distribution", dest="include_distribution", action="store_true", default=True, help="Include Distribution target summaries.")
    parser.add_argument("--no-include-distribution", dest="include_distribution", action="store_false", help="Do not include Distribution target summaries.")
    parser.add_argument("--include-submission", dest="include_submission", action="store_true", default=True, help="Include Submission batch summaries.")
    parser.add_argument("--no-include-submission", dest="include_submission", action="store_false", help="Do not include Submission batch summaries.")
    parser.add_argument("--include-submission-evidence", dest="include_submission_evidence", action="store_true", default=True, help="Include Submission Evidence summaries.")
    parser.add_argument("--no-include-submission-evidence", dest="include_submission_evidence", action="store_false", help="Do not include Submission Evidence summaries.")
    parser.add_argument("--include-operations", dest="include_operations", action="store_true", default=True, help="Include Release Operations summaries.")
    parser.add_argument("--no-include-operations", dest="include_operations", action="store_false", help="Do not include Release Operations summaries.")
    parser.add_argument("--require-release-signoff", dest="require_release_signoff", action="store_true", default=True, help="Require Release Signoff in the Trust Center report.")
    parser.add_argument("--no-require-release-signoff", dest="require_release_signoff", action="store_false", help="Do not require Release Signoff in the Trust Center report.")
    parser.add_argument("--require-distribution-signed", action="store_true", help="Require signed and verified Distribution packages in the report.")
    parser.add_argument("--require-submission-accepted", action="store_true", help="Require accepted Submission batches in the report.")
    parser.add_argument("--require-submission-evidence-signed", action="store_true", help="Require signed Submission Evidence packages in the report.")
    parser.add_argument("--require-operations-signed", action="store_true", help="Require Release Operations Signoff in the report.")
    parser.add_argument("--require-operations-audit-verified", action="store_true", help="Require verified Release Operations Audit evidence in the report.")
    parser.add_argument("--require-operations-reviewer-pack-verified", action="store_true", help="Require verified Release Operations Reviewer Pack evidence in the report.")
    parser.add_argument("--require-release-readiness", action="store_true", help="Verifier requires selected releases to be ready.")
    parser.add_argument("--require-delivery-readiness", action="store_true", help="Verifier requires delivery readiness.")
    parser.add_argument("--require-distribution-ready", action="store_true", help="Verifier requires distribution readiness.")
    parser.add_argument("--require-submission-evidence", action="store_true", help="Verifier requires submission evidence.")
    parser.add_argument("--require-operations-audit", action="store_true", help="Verifier requires operations audit evidence.")
    parser.add_argument("--require-operations-reviewer-pack", action="store_true", help="Verifier requires operations reviewer pack evidence.")
    parser.add_argument("--require-anchor-registry-current", action="store_true", help="Verifier requires current Anchor Registry evidence.")
    parser.add_argument("--require-anchor-published", action="store_true", help="Verifier requires a published Anchor Registry current entry.")
    parser.add_argument("--require-anchor-not-revoked", action="store_true", help="Verifier requires the Anchor Registry current entry not to be revoked.")
    parser.add_argument("--require-anchor-transparency-current", action="store_true", help="Verifier requires current Anchor Transparency evidence.")
    parser.add_argument("--require-anchor-checkpoint", action="store_true", help="Verifier requires an external Anchor Transparency checkpoint.")
    parser.add_argument("--json", action="store_true", help="Print JSON output.")
    parser.add_argument("--report-out", type=Path, default=None, help="Write command result to this JSON file.")
    return parser

def _trust_operations_assurance_source_payload(args: argparse.Namespace) -> ImplementationDocument:
    return {
        "hub_package_path": getattr(args, "hub_package", None),
        "hub_verification_report_path": getattr(args, "hub_verification_report", None),
        "control_signoff_archive_path": getattr(args, "control_signoff_archive", None),
        "control_signoff_verification_report_path": getattr(args, "control_signoff_verification_report", None),
        "control_package_path": getattr(args, "control_package", None),
        "control_verification_report_path": getattr(args, "control_verification_report", None),
        "incident_board_package_path": getattr(args, "incident_board_package", None),
        "incident_board_verification_report_path": getattr(args, "incident_board_verification_report", None),
        "incident_knowledge_package_path": getattr(args, "incident_knowledge_package", None),
        "incident_knowledge_verification_report_path": getattr(args, "incident_knowledge_verification_report", None),
        "release_verification_paths": getattr(args, "release_verification", []),
        "distribution_verification_paths": getattr(args, "distribution_verification", []),
        "submission_verification_paths": getattr(args, "submission_verification", []),
        "submission_evidence_verification_paths": getattr(args, "submission_evidence_verification", []),
        "release_operations_verification_paths": getattr(args, "release_operations_verification", []),
    }

def _trust_operations_assurance_watch_source_payload(args: argparse.Namespace) -> ImplementationDocument:
    return {
        "assurance_archive_path": getattr(args, "assurance_archive", None),
        "assurance_verification_report_path": getattr(args, "assurance_verification_report", None),
        "hub_package_path": getattr(args, "hub_package", None),
        "hub_verification_report_path": getattr(args, "hub_verification_report", None),
    }

def _trust_operations_final_readiness_source_payload(args: argparse.Namespace) -> ImplementationDocument:
    payload = _trust_operations_assurance_source_payload(args)
    payload.update(
        {
            "continuous_assurance_archive_path": getattr(args, "continuous_assurance_archive", None),
            "continuous_assurance_verification_report_path": getattr(args, "continuous_assurance_verification_report", None),
            "assurance_watch_package_path": getattr(args, "assurance_watch_package", None),
            "assurance_watch_verification_report_path": getattr(args, "assurance_watch_verification_report", None),
            "assurance_watch_signoff_archive_path": getattr(args, "assurance_watch_signoff_archive", None),
            "assurance_watch_signoff_verification_report_path": getattr(args, "assurance_watch_signoff_verification_report", None),
        }
    )
    return payload

def print_release_portfolio_audit_result(result: dict[str, Any]) -> None:
    summary = result.get("summary") if isinstance(result.get("summary"), dict) else {}
    verification = result.get("verification_summary") if isinstance(result.get("verification_summary"), dict) else {}
    portfolio = result.get("portfolio") if isinstance(result.get("portfolio"), dict) else {}
    print("MusicForge release-portfolio-audit")
    print(f"portfolio: {result.get('portfolio_id') or portfolio.get('portfolio_id') or '-'}")
    print(f"status: {summary.get('status') or portfolio.get('status') or '-'}")
    print(f"releases: {summary.get('release_count', 0)}")
    print(f"risk_score: {summary.get('risk_score') if summary.get('risk_score') is not None else '-'}")
    print(f"blockers: {summary.get('blocker_count', 0)}")
    print(f"warnings: {summary.get('warning_count', 0)}")
    if result.get("portfolios") is not None:
        print(f"portfolios: {len(result.get('portfolios') or [])}")
    if result.get("zip"):
        print(f"zip: {(result.get('zip') or {}).get('filename')}")
    if verification:
        print(f"verify: {verification.get('status')}")

def print_release_portfolio_governance_result(result: dict[str, Any]) -> None:
    summary = result.get("summary") if isinstance(result.get("summary"), dict) else {}
    verification = result.get("verification_summary") if isinstance(result.get("verification_summary"), dict) else {}
    queue = result.get("queue") if isinstance(result.get("queue"), dict) else {}
    print("MusicForge release-portfolio-governance-queue")
    print(f"queue: {result.get('queue_id') or queue.get('queue_id') or '-'}")
    print(f"portfolio: {queue.get('portfolio_id') or '-'}")
    print(f"status: {summary.get('status') or queue.get('status') or '-'}")
    print(f"items: {summary.get('total_items', 0)}")
    print(f"safe_completed: {summary.get('safe_completed', 0)}")
    print(f"manual_required: {summary.get('manual_required', 0)}")
    print(f"blocked: {summary.get('blocked', 0)}")
    print(f"failed: {summary.get('failed', 0)}")
    if result.get("queues") is not None:
        print(f"queues: {len(result.get('queues') or [])}")
    if result.get("zip"):
        print(f"zip: {(result.get('zip') or {}).get('filename')}")
    if verification:
        print(f"verify: {verification.get('status')}")

__all__ = ('build_trust_operations_control_signoff_parser', 'build_trust_operations_hub_runbook_parser', 'build_trust_operations_hub_incidents_parser', 'build_trust_operations_incident_knowledge_parser', 'build_trust_operations_controls_parser', 'build_public_trust_center_parser', '_trust_operations_assurance_source_payload', '_trust_operations_assurance_watch_source_payload', '_trust_operations_final_readiness_source_payload', 'print_release_portfolio_audit_result', 'print_release_portfolio_governance_result')
