"""Project application-facing composition over the domain repository."""

from song_agent.domains.studio.project_repository import JobLike as JobLike, PROJECT_ROOT as PROJECT_ROOT, PROJECT_STATUSES as PROJECT_STATUSES, ProjectState as ProjectState, ProjectSummaryProvider as ProjectSummaryProvider, ProjectVersion as ProjectVersion, Protocol as Protocol, QUALITY_GATE_STATUSES as QUALITY_GATE_STATUSES, SongPlan as SongPlan, VARIANT_TYPES as VARIANT_TYPES, VERSION_STATUSES as VERSION_STATUSES, _artifact_exists as _artifact_exists, _artifact_flags as _artifact_flags, _average_velocity as _average_velocity, _clean as _clean, _collect_project_asset_refs as _collect_project_asset_refs, _collect_project_context_packs as _collect_project_context_packs, _collect_project_reference_refs as _collect_project_reference_refs, _diff_dict as _diff_dict, _diff_optional as _diff_optional, _edit_info as _edit_info, _empty_project_summary as _empty_project_summary, _find_version as _find_version, _lineage_info as _lineage_info, _mix_info as _mix_info, _optional_int as _optional_int, _optional_str as _optional_str, _optional_version_id as _optional_version_id, _section_info as _section_info, _track_info as _track_info, _validate_project_id as _validate_project_id, _validate_variant_type as _validate_variant_type, _validate_version_id as _validate_version_id, _version_index as _version_index, _version_or_none as _version_or_none, _version_ref as _version_ref, _version_song_plan as _version_song_plan, analyze_song_quality as analyze_song_quality, dataclass as dataclass, field as field, now_iso as now_iso, quality_score_for_run as quality_score_for_run, shutil as shutil, slugify as slugify, threading as threading, write_json as write_json
from song_agent.domains.studio.project_export_enrichment import Any as Any, BLOCKED_ASSET_METADATA_KEYS as BLOCKED_ASSET_METADATA_KEYS, Path as Path, ProjectDocument as ProjectDocument, _collect_project_acceptance_fix_plan_review_summary as _collect_project_acceptance_fix_plan_review_summary, _collect_project_acceptance_fix_plan_summary as _collect_project_acceptance_fix_plan_summary, _collect_project_acceptance_fix_sprint_summary as _collect_project_acceptance_fix_sprint_summary, _collect_project_acceptance_kb_summary as _collect_project_acceptance_kb_summary, _collect_project_delivery_qa_summary as _collect_project_delivery_qa_summary, _collect_project_delivery_signoff_summary as _collect_project_delivery_signoff_summary, _collect_project_planning_rule_governance_summary as _collect_project_planning_rule_governance_summary, _collect_project_planning_rule_impact_summary as _collect_project_planning_rule_impact_summary, _collect_project_planning_rule_simulation_summary as _collect_project_planning_rule_simulation_summary, _collect_project_review_metrics_summary as _collect_project_review_metrics_summary, _collect_project_review_sprints as _collect_project_review_sprints, _collect_project_review_tasks as _collect_project_review_tasks, _project_version_song_plan as _project_version_song_plan, _sanitize_asset_metadata as _sanitize_asset_metadata, annotations as annotations, build_project_summary as build_project_summary, collect_planning_rule_governance_summary as collect_planning_rule_governance_summary, collect_planning_rule_impact_summary as collect_planning_rule_impact_summary, collect_planning_rule_simulation_summary as collect_planning_rule_simulation_summary, json as json, read_json as read_json, sanitize_metadata as sanitize_metadata
from song_agent.domains.studio.project_repository import ProjectStore as _RepositoryProjectStore


class ProjectStore(_RepositoryProjectStore):
    def __init__(self, root: Path | str = PROJECT_ROOT):
        super().__init__(root, summary_provider=build_project_summary)


__all__ = ('Any', 'BLOCKED_ASSET_METADATA_KEYS', 'JobLike', 'PROJECT_ROOT', 'PROJECT_STATUSES', 'Path', 'ProjectDocument', 'ProjectState', 'ProjectSummaryProvider', 'ProjectVersion', 'Protocol', 'QUALITY_GATE_STATUSES', 'SongPlan', 'VARIANT_TYPES', 'VERSION_STATUSES', '_artifact_exists', '_artifact_flags', '_average_velocity', '_clean', '_collect_project_acceptance_fix_plan_review_summary', '_collect_project_acceptance_fix_plan_summary', '_collect_project_acceptance_fix_sprint_summary', '_collect_project_acceptance_kb_summary', '_collect_project_asset_refs', '_collect_project_context_packs', '_collect_project_delivery_qa_summary', '_collect_project_delivery_signoff_summary', '_collect_project_planning_rule_governance_summary', '_collect_project_planning_rule_impact_summary', '_collect_project_planning_rule_simulation_summary', '_collect_project_reference_refs', '_collect_project_review_metrics_summary', '_collect_project_review_sprints', '_collect_project_review_tasks', '_diff_dict', '_diff_optional', '_edit_info', '_empty_project_summary', '_find_version', '_lineage_info', '_mix_info', '_optional_int', '_optional_str', '_optional_version_id', '_project_version_song_plan', '_sanitize_asset_metadata', '_section_info', '_track_info', '_validate_project_id', '_validate_variant_type', '_validate_version_id', '_version_index', '_version_or_none', '_version_ref', '_version_song_plan', 'analyze_song_quality', 'annotations', 'build_project_summary', 'collect_planning_rule_governance_summary', 'collect_planning_rule_impact_summary', 'collect_planning_rule_simulation_summary', 'dataclass', 'field', 'json', 'now_iso', 'quality_score_for_run', 'read_json', 'sanitize_metadata', 'shutil', 'slugify', 'threading', 'write_json', 'ProjectStore')
