"""Project application-facing composition over the domain repository."""

from song_agent.domains.studio.project_repository import Any, BLOCKED_ASSET_METADATA_KEYS, JobLike, PROJECT_ROOT, PROJECT_STATUSES, Path, ProjectDocument, ProjectState, ProjectSummaryProvider, ProjectVersion, Protocol, QUALITY_GATE_STATUSES, SongPlan, VARIANT_TYPES, VERSION_STATUSES, _artifact_exists, _artifact_flags, _average_velocity, _clean, _collect_project_asset_refs, _collect_project_context_packs, _collect_project_reference_refs, _diff_dict, _diff_optional, _edit_info, _empty_project_summary, _find_version, _lineage_info, _mix_info, _optional_int, _optional_str, _optional_version_id, _sanitize_asset_metadata, _section_info, _track_info, _validate_project_id, _validate_variant_type, _validate_version_id, _version_index, _version_or_none, _version_ref, _version_song_plan, analyze_song_quality, annotations, dataclass, field, json, now_iso, quality_score_for_run, read_json, sanitize_metadata, shutil, slugify, threading, write_json
from song_agent.domains.studio.project_export_enrichment import Any, BLOCKED_ASSET_METADATA_KEYS, Path, ProjectDocument, _collect_project_acceptance_fix_plan_review_summary, _collect_project_acceptance_fix_plan_summary, _collect_project_acceptance_fix_sprint_summary, _collect_project_acceptance_kb_summary, _collect_project_delivery_qa_summary, _collect_project_delivery_signoff_summary, _collect_project_planning_rule_governance_summary, _collect_project_planning_rule_impact_summary, _collect_project_planning_rule_simulation_summary, _collect_project_review_metrics_summary, _collect_project_review_sprints, _collect_project_review_tasks, _project_version_song_plan, _sanitize_asset_metadata, annotations, build_project_summary, collect_planning_rule_governance_summary, collect_planning_rule_impact_summary, collect_planning_rule_simulation_summary, json, read_json, sanitize_metadata
from song_agent.domains.studio.project_repository import ProjectStore as _RepositoryProjectStore


class ProjectStore(_RepositoryProjectStore):
    def __init__(self, root: Path | str = PROJECT_ROOT):
        super().__init__(root, summary_provider=build_project_summary)


__all__ = ('Any', 'BLOCKED_ASSET_METADATA_KEYS', 'JobLike', 'PROJECT_ROOT', 'PROJECT_STATUSES', 'Path', 'ProjectDocument', 'ProjectState', 'ProjectSummaryProvider', 'ProjectVersion', 'Protocol', 'QUALITY_GATE_STATUSES', 'SongPlan', 'VARIANT_TYPES', 'VERSION_STATUSES', '_artifact_exists', '_artifact_flags', '_average_velocity', '_clean', '_collect_project_acceptance_fix_plan_review_summary', '_collect_project_acceptance_fix_plan_summary', '_collect_project_acceptance_fix_sprint_summary', '_collect_project_acceptance_kb_summary', '_collect_project_asset_refs', '_collect_project_context_packs', '_collect_project_delivery_qa_summary', '_collect_project_delivery_signoff_summary', '_collect_project_planning_rule_governance_summary', '_collect_project_planning_rule_impact_summary', '_collect_project_planning_rule_simulation_summary', '_collect_project_reference_refs', '_collect_project_review_metrics_summary', '_collect_project_review_sprints', '_collect_project_review_tasks', '_diff_dict', '_diff_optional', '_edit_info', '_empty_project_summary', '_find_version', '_lineage_info', '_mix_info', '_optional_int', '_optional_str', '_optional_version_id', '_project_version_song_plan', '_sanitize_asset_metadata', '_section_info', '_track_info', '_validate_project_id', '_validate_variant_type', '_validate_version_id', '_version_index', '_version_or_none', '_version_ref', '_version_song_plan', 'analyze_song_quality', 'annotations', 'build_project_summary', 'collect_planning_rule_governance_summary', 'collect_planning_rule_impact_summary', 'collect_planning_rule_simulation_summary', 'dataclass', 'field', 'json', 'now_iso', 'quality_score_for_run', 'read_json', 'sanitize_metadata', 'shutil', 'slugify', 'threading', 'write_json', 'ProjectStore')
