"""Explicit active API route manifest; generated from the v13.4 compatibility dispatcher."""

ACTIVE_ROUTE_ROWS = (
    ('*', '/api/acceptance/analytics', '_handle_acceptance_analytics_root', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/analytics/refresh', '_handle_acceptance_analytics_refresh', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/fix-plan-reviews', '_handle_acceptance_fix_plan_reviews_root', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/fix-plans', '_handle_acceptance_fix_plans_root', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/fix-plans/recommend', '_handle_acceptance_fix_plans_recommend', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/fix-sprints', '_handle_acceptance_fix_sprints_root', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/kb', '_handle_acceptance_kb_root', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/kb/entries', '_handle_acceptance_kb_entries', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/kb/recommend', '_handle_acceptance_kb_recommend', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/kb/refresh', '_handle_acceptance_kb_refresh', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/kb/search', '_handle_acceptance_kb_search', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/planning-rule-governance/active', '_handle_planning_rule_governance_active', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/planning-rule-governance/events', '_handle_planning_rule_governance_events', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/planning-rule-governance/promotions', '_handle_planning_rule_governance_promotions', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/planning-rule-governance/rollback', '_handle_planning_rule_governance_rollback', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/planning-rule-governance/versions', '_handle_planning_rule_governance_versions', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/planning-rule-impact/latest', '_handle_planning_rule_impact_latest', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/planning-rule-impact/reports', '_handle_planning_rule_impact_reports', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/planning-rulesets', '_handle_planning_rulesets_root', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/planning-simulations', '_handle_planning_simulations_root', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/acceptance/suites', '_handle_acceptance_suites_root', 'configured', 'acceptance-request-v1', 'acceptance-response-v1'),
    ('*', '/api/assets', '_handle_assets_root', 'configured', 'assets-request-v1', 'assets-response-v1'),
    ('*', '/api/assets/extract/from-candidate', '_handle_asset_extract_from_candidate', 'configured', 'assets-request-v1', 'assets-response-v1'),
    ('*', '/api/assets/extract/from-job', '_handle_asset_extract_from_job', 'configured', 'assets-request-v1', 'assets-response-v1'),
    ('*', '/api/assets/extract/from-project-version', '_handle_asset_extract_from_project_version', 'configured', 'assets-request-v1', 'assets-response-v1'),
    ('GET', '/assets/musicforge/{path}', 'web_script', 'public', 'web-asset-request-v1', 'javascript-module-v1'),
    ('*', '/api/audio-baselines', '_handle_audio_baselines_route', 'configured', 'audio-baselines-request-v1', 'audio-baselines-response-v1'),
    ('*', '/api/audio-baselines/', '_handle_audio_baselines_route', 'configured', 'audio-baselines-request-v1', 'audio-baselines-response-v1'),
    ('*', '/api/audio-campaigns', '_handle_audio_campaign_route', 'configured', 'audio-campaigns-request-v1', 'audio-campaigns-response-v1'),
    ('*', '/api/audio-campaigns/', '_handle_audio_campaign_route', 'configured', 'audio-campaigns-request-v1', 'audio-campaigns-response-v1'),
    ('*', '/api/audio-encoding/config', '_handle_audio_encoding_route', 'configured', 'audio-encoding-request-v1', 'audio-encoding-response-v1'),
    ('*', '/api/audio-encoding/config/', '_handle_audio_encoding_route', 'configured', 'audio-encoding-request-v1', 'audio-encoding-response-v1'),
    ('*', '/api/audio-encoding/profiles', '_handle_audio_encoding_route', 'configured', 'audio-encoding-request-v1', 'audio-encoding-response-v1'),
    ('*', '/api/audio-encoding/profiles/', '_handle_audio_encoding_route', 'configured', 'audio-encoding-request-v1', 'audio-encoding-response-v1'),
    ('*', '/api/audio-fix-sprints', '_handle_audio_fix_sprint_route', 'configured', 'audio-fix-sprints-request-v1', 'audio-fix-sprints-response-v1'),
    ('*', '/api/audio-fix-sprints/', '_handle_audio_fix_sprint_route', 'configured', 'audio-fix-sprints-request-v1', 'audio-fix-sprints-response-v1'),
    ('*', '/api/audio-lab', '_handle_audio_lab_route', 'configured', 'audio-lab-request-v1', 'audio-lab-response-v1'),
    ('*', '/api/audio-lab/', '_handle_audio_lab_route', 'configured', 'audio-lab-request-v1', 'audio-lab-response-v1'),
    ('*', '/api/audio-quality-actions', '_handle_audio_quality_actions_route', 'configured', 'audio-quality-actions-request-v1', 'audio-quality-actions-response-v1'),
    ('*', '/api/audio-quality-actions/', '_handle_audio_quality_actions_route', 'configured', 'audio-quality-actions-request-v1', 'audio-quality-actions-response-v1'),
    ('*', '/api/audio-quality-observatories', '_handle_audio_quality_observatories_route', 'configured', 'audio-quality-observatories-request-v1', 'audio-quality-observatories-response-v1'),
    ('*', '/api/audio-quality-observatories/', '_handle_audio_quality_observatories_route', 'configured', 'audio-quality-observatories-request-v1', 'audio-quality-observatories-response-v1'),
    ('*', '/api/audio/profiles', '_handle_audio_profiles_route', 'configured', 'audio-request-v1', 'audio-response-v1'),
    ('*', '/api/audio/profiles/', '_handle_audio_profiles_route', 'configured', 'audio-request-v1', 'audio-response-v1'),
    ('*', '/api/context-packs', '_handle_context_packs_root', 'configured', 'context-packs-request-v1', 'context-packs-response-v1'),
    ('*', '/api/distribution/profiles', '_handle_distribution_profiles_root', 'configured', 'distribution-request-v1', 'distribution-response-v1'),
    ('*', '/api/distribution/template-packs', '_handle_distribution_templates_root', 'configured', 'distribution-request-v1', 'distribution-response-v1'),
    ('*', '/api/distribution/template-packs/import', '_handle_distribution_template_import', 'configured', 'distribution-request-v1', 'distribution-response-v1'),
    ('*', '/api/docs/index', '_handle_docs_index_route', 'configured', 'docs-request-v1', 'docs-response-v1'),
    ('*', '/api/edit-presets', '_handle_edit_presets_root', 'configured', 'edit-presets-request-v1', 'edit-presets-response-v1'),
    ('*', '/api/edit-presets/reset', '_handle_edit_presets_reset', 'configured', 'edit-presets-request-v1', 'edit-presets-response-v1'),
    ('*', '/api/editor-templates', '_handle_editor_templates_root', 'configured', 'editor-templates-request-v1', 'editor-templates-response-v1'),
    ('*', '/api/ga', '_handle_ga_route', 'configured', 'ga-request-v1', 'ga-response-v1'),
    ('*', '/api/ga/check', '_handle_ga_check_route', 'configured', 'ga-request-v1', 'ga-response-v1'),
    ('*', '/api/library/index', '_handle_library_index', 'configured', 'library-request-v1', 'library-response-v1'),
    ('*', '/api/library/rebuild', '_handle_library_rebuild', 'configured', 'library-request-v1', 'library-response-v1'),
    ('*', '/api/library/recommend', '_handle_library_recommend', 'configured', 'library-request-v1', 'library-response-v1'),
    ('*', '/api/library/search', '_handle_library_search', 'configured', 'library-request-v1', 'library-response-v1'),
    ('*', '/api/maintenance/', '_handle_maintenance_route', 'configured', 'maintenance-request-v1', 'maintenance-response-v1'),
    ('*', '/api/maintenance/status', '_handle_maintenance_route', 'configured', 'maintenance-request-v1', 'maintenance-response-v1'),
    ('*', '/api/mastering/profiles', '_handle_mastering_profiles_route', 'configured', 'mastering-request-v1', 'mastering-response-v1'),
    ('*', '/api/mastering/profiles/', '_handle_mastering_profiles_route', 'configured', 'mastering-request-v1', 'mastering-response-v1'),
    ('*', '/api/projects', '_handle_projects_root', 'configured', 'projects-request-v1', 'projects-response-v1'),
    ('*', '/api/prompt-templates', '_handle_prompt_templates_root', 'configured', 'prompt-templates-request-v1', 'prompt-templates-response-v1'),
    ('*', '/api/prompt-templates/reset', '_handle_prompt_templates_reset', 'configured', 'prompt-templates-request-v1', 'prompt-templates-response-v1'),
    ('*', '/api/provider', '_handle_provider_route', 'configured', 'provider-request-v1', 'provider-response-v1'),
    ('*', '/api/provider/reset', '_handle_provider_reset', 'configured', 'provider-request-v1', 'provider-response-v1'),
    ('*', '/api/provider/test', '_handle_provider_test', 'configured', 'provider-request-v1', 'provider-response-v1'),
    ('*', '/api/public-trust-centers', '_handle_public_trust_centers', 'configured', 'public-trust-centers-request-v1', 'public-trust-centers-response-v1'),
    ('*', '/api/public-trust-centers/', '_handle_public_trust_centers', 'configured', 'public-trust-centers-request-v1', 'public-trust-centers-response-v1'),
    ('*', '/api/references', '_handle_references_root', 'configured', 'references-request-v1', 'references-response-v1'),
    ('*', '/api/references/import', '_handle_reference_import', 'configured', 'references-request-v1', 'references-response-v1'),
    ('*', '/api/release-portfolio-audits', '_handle_release_portfolio_audits', 'configured', 'release-portfolio-audits-request-v1', 'release-portfolio-audits-response-v1'),
    ('*', '/api/release-portfolio-audits/', '_handle_release_portfolio_audits', 'configured', 'release-portfolio-audits-request-v1', 'release-portfolio-audits-response-v1'),
    ('*', '/api/release-portfolio-governance-queues', '_handle_release_portfolio_governance_queues', 'configured', 'release-portfolio-governance-queues-request-v1', 'release-portfolio-governance-queues-response-v1'),
    ('*', '/api/release-portfolio-governance-queues/', '_handle_release_portfolio_governance_queues', 'configured', 'release-portfolio-governance-queues-request-v1', 'release-portfolio-governance-queues-response-v1'),
    ('*', '/api/releases', '_handle_releases_root', 'configured', 'releases-request-v1', 'releases-response-v1'),
    ('*', '/api/renderer', '_handle_renderer_route', 'configured', 'renderer-request-v1', 'renderer-response-v1'),
    ('*', '/api/renderer/reset', '_handle_renderer_reset', 'configured', 'renderer-request-v1', 'renderer-response-v1'),
    ('*', '/api/renderer/test', '_handle_renderer_test', 'configured', 'renderer-request-v1', 'renderer-response-v1'),
    ('*', '/api/trust-operations', '_handle_trust_operations', 'configured', 'trust-operations-request-v1', 'trust-operations-response-v1'),
    ('*', '/api/trust-operations/', '_handle_trust_operations', 'configured', 'trust-operations-request-v1', 'trust-operations-response-v1'),
    ('*', '/api/unified-command-center-release-trains', '_handle_unified_command_center_release_trains_route', 'configured', 'unified-command-center-release-trains-request-v1', 'unified-command-center-release-trains-response-v1'),
    ('*', '/api/unified-command-center-release-trains/', '_handle_unified_command_center_release_trains_route', 'configured', 'unified-command-center-release-trains-request-v1', 'unified-command-center-release-trains-response-v1'),
    ('*', '/api/unified-command-centers', '_handle_unified_command_centers_route', 'configured', 'unified-command-centers-request-v1', 'unified-command-centers-response-v1'),
    ('*', '/api/unified-command-centers/', '_handle_unified_command_centers_route', 'configured', 'unified-command-centers-request-v1', 'unified-command-centers-response-v1'),
    ('*', '/api/usage/provider', '_handle_provider_usage_root', 'configured', 'usage-request-v1', 'usage-response-v1'),
    ('*', 'matcher:_match_acceptance_analytics_recommendation_route', '_handle_acceptance_analytics_recommendation', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_acceptance_analytics_report_route', '_handle_acceptance_analytics_report', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_acceptance_fix_plan_review_route', '_handle_acceptance_fix_plan_review_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_acceptance_fix_plan_route', '_handle_acceptance_fix_plan_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_acceptance_fix_sprint_route', '_handle_acceptance_fix_sprint_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_acceptance_kb_entry_route', '_handle_acceptance_kb_entry_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_acceptance_kb_report_route', '_handle_acceptance_kb_report', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_acceptance_route', '_handle_acceptance_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_asset_route', '_handle_asset_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_batch_route', '_handle_batch_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_context_pack_route', '_handle_context_pack_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_distribution_profile_route', '_handle_distribution_profile_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_distribution_template_route', '_handle_distribution_template_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_edit_preset_route', '_handle_edit_preset_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_editor_template_route', '_handle_editor_template_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_job_route', '_handle_job_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_planning_rule_governance_promotion_route', '_handle_planning_rule_governance_promotion_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_planning_rule_governance_version_route', '_handle_planning_rule_governance_version_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_planning_rule_impact_report_route', '_handle_planning_rule_impact_report_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_planning_ruleset_route', '_handle_planning_ruleset_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_planning_simulation_route', '_handle_planning_simulation_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_project_route', '_handle_project_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_prompt_template_route', '_handle_prompt_template_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_reference_route', '_handle_reference_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('*', 'matcher:_match_release_route', '_handle_release_route', 'configured', 'api-request-v1', 'api-response-v1'),
    ('DELETE', '/api/unified-release-programs/{path}', 'program_application.dispatch_http', 'configured', 'program-command-v1', 'program-result-v1'),
    ('GET', '/api/unified-release-programs/{path}', 'program_application.dispatch_http', 'configured', 'program-command-v1', 'program-result-v1'),
    ('PATCH', '/api/unified-release-programs/{path}', 'program_application.dispatch_http', 'configured', 'program-command-v1', 'program-result-v1'),
    ('POST', '/api/unified-release-programs/{path}', 'program_application.dispatch_http', 'configured', 'program-command-v1', 'program-result-v1'),
    ('PUT', '/api/unified-release-programs/{path}', 'program_application.dispatch_http', 'configured', 'program-command-v1', 'program-result-v1'),
)

ACTIVE_DISPATCH_HANDLERS = (
    '_dispatch_studio_system',
    '_dispatch_studio_jobs',
    '_dispatch_studio_resources',
    '_dispatch_studio_acceptance_routes',
    '_dispatch_studio_acceptance_items',
    '_dispatch_studio_distribution',
    '_dispatch_studio_library',
    '_dispatch_studio_dynamic',
)
