from __future__ import annotations
from collections.abc import Mapping
from inspect import getsourcefile
from pathlib import Path
from types import ModuleType
from song_agent.domains.program import unified_release_program_continuity_acceptance_change_verifier as acceptance_change_verifier, unified_release_program_continuity_acceptance_verifier as acceptance_verifier, unified_release_program_continuity_command_center_acceptance_change_verifier as receiver_change_verifier, unified_release_program_continuity_command_center_acceptance_verifier as receiver_verifier, unified_release_program_continuity_command_center_signoff_verifier as command_signoff_verifier, unified_release_program_continuity_command_center_verifier as command_center_verifier, unified_release_program_continuity_distribution_verifier as distribution_verifier, unified_release_program_continuity_verifier as continuity_verifier, unified_release_program_handoff_verifier as handoff_verifier, unified_release_program_operations_verifier as operations_verifier, unified_release_program_vault_operations_verifier as vault_operations_verifier, unified_release_program_vault_verifier as vault_verifier, unified_release_program_verifier as program_verifier
from song_agent.platform.verification.registry import VerifierCapability, VerifierCapabilityRegistry

def _verifier_capability(component_type: str, module: ModuleType, verifier: str, package_type_attr: str, verification_type_attr: str, check_prefix: str, required_entries_attr: str, optional_entries_attr: str='', allowed_entry_patterns: tuple[str, ...]=(), nested_zip_policy: str='deny', allowed_nested_entries_attr: str='', allowed_nested_entries: tuple[str, ...]=(), allowed_nested_patterns: tuple[str, ...]=(), required_proofs: tuple[str, ...]=(), lifecycle_bindings: tuple[str, ...]=()) -> VerifierCapability:
    verifier_callable = getattr(module, verifier)
    if not callable(verifier_callable):
        raise TypeError(f'Program verifier is not callable: {module.__name__}.{verifier}')

    def invoke(package_path: Path, arguments: Mapping[str, object]) -> Mapping[str, object]:
        return verifier_callable(package_path, **arguments)
    nested_entries = frozenset(allowed_nested_entries)
    if allowed_nested_entries_attr:
        nested_entries = nested_entries.union((str(value) for value in getattr(module, allowed_nested_entries_attr)))
    return VerifierCapability(capability_id=f'program.{component_type}', component_type=component_type, module=module.__name__, function=verifier, verifier=invoke, source_path=Path(getsourcefile(verifier_callable) or ''), archive_type=str(getattr(module, package_type_attr)), verification_report_type=str(getattr(module, verification_type_attr)), check_prefix=check_prefix, required_entries=frozenset((str(value) for value in getattr(module, required_entries_attr))), optional_entries=frozenset((str(value) for value in getattr(module, optional_entries_attr))) if optional_entries_attr else frozenset(), allowed_entry_patterns=allowed_entry_patterns, nested_zip_policy='allowlisted' if nested_zip_policy == 'allowlisted' else 'deny', allowed_nested_entries=nested_entries, allowed_nested_patterns=allowed_nested_patterns, required_proofs=required_proofs, lifecycle_bindings=lifecycle_bindings)
ACTIVE_VERIFIER_CAPABILITIES = (
    _verifier_capability('unified_release_program', program_verifier, 'verify_unified_release_program_package', 'UNIFIED_RELEASE_PROGRAM_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_VERIFICATION_PACKAGE_TYPE', 'urp_kernel', 'BASE_REQUIRED_ENTRIES', optional_entries_attr='SIGNED_ENTRIES', required_proofs=('external_evidence_manifest_path', 'program_signoff_binding_path'), lifecycle_bindings=('current_external_evidence', 'signoff_binding', 'history_chain')),
    _verifier_capability('unified_release_program_operations', operations_verifier, 'verify_unified_release_program_operations_package', 'UNIFIED_RELEASE_PROGRAM_OPERATIONS_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_OPERATIONS_VERIFICATION_PACKAGE_TYPE', 'urp_ops_kernel', 'REQUIRED_ENTRIES', required_proofs=('program_zip_path', 'program_verification_report_path', 'program_signoff_binding_path', 'external_evidence_manifest_path'), lifecycle_bindings=('current_program', 'signoff_binding', 'change_request')),
    _verifier_capability('unified_release_program_handoff', handoff_verifier, 'verify_unified_release_program_handoff_package', 'UNIFIED_RELEASE_PROGRAM_HANDOFF_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_HANDOFF_VERIFICATION_PACKAGE_TYPE', 'urph_kernel', 'HANDOFF_REQUIRED_ENTRIES', required_proofs=('external_evidence_manifest_path', 'handoff_signoff_binding_path'), lifecycle_bindings=('accepted_evidence', 'signoff_binding', 'history_chain')),
    _verifier_capability('unified_release_program_vault', vault_verifier, 'verify_unified_release_program_vault_package', 'UNIFIED_RELEASE_PROGRAM_VAULT_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_VAULT_VERIFICATION_PACKAGE_TYPE', 'urpv_kernel', 'STATIC_REQUIRED_ENTRIES', allowed_entry_patterns=('packages/accepted-evidence/[A-Za-z0-9_.-]+\\.zip', 'proofs/accepted-evidence/[A-Za-z0-9_.-]+-(?:verification-report|response-verification-report|response-binding-summary)\\.json'), nested_zip_policy='allowlisted', allowed_nested_entries=('packages/unified-release-program.zip', 'packages/unified-release-program-operations.zip', 'packages/unified-release-program-handoff.zip'), allowed_nested_patterns=('packages/accepted-evidence/[A-Za-z0-9_.-]+\\.zip',), required_proofs=('vault_anchor_path',), lifecycle_bindings=('external_anchor', 'nested_runtime_verification')),
    _verifier_capability('unified_release_program_vault_operations', vault_operations_verifier, 'verify_unified_release_program_vault_operations_package', 'UNIFIED_RELEASE_PROGRAM_VAULT_OPERATIONS_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_VAULT_OPERATIONS_VERIFICATION_PACKAGE_TYPE', 'urpvo_kernel', 'REQUIRED_ENTRIES', nested_zip_policy='allowlisted', allowed_nested_entries=('packages/current-vault.zip',), required_proofs=('signoff_binding_path',), lifecycle_bindings=('current_vault', 'signoff_binding', 'custody_history')),
    _verifier_capability('unified_release_program_continuity', continuity_verifier, 'verify_unified_release_program_continuity_package', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_VERIFICATION_PACKAGE_TYPE', 'urpc_kernel', 'REQUIRED_ENTRIES', required_proofs=('signoff_binding_path', 'vault_operations_archive_path', 'vault_operations_verification_report_path', 'vault_operations_signoff_binding_path'), lifecycle_bindings=('current_vault_operations', 'signoff_binding', 'recovery_drill')),
    _verifier_capability('unified_release_program_continuity_kit', distribution_verifier, 'verify_unified_release_program_continuity_distribution_package', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_DISTRIBUTION_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_DISTRIBUTION_VERIFICATION_PACKAGE_TYPE', 'urpcdk_kernel', 'REQUIRED_ENTRIES', nested_zip_policy='allowlisted', allowed_nested_entries_attr='NESTED_ZIP_ENTRIES', required_proofs=('kit_verification_report_path',), lifecycle_bindings=('nested_runtime_verification', 'receiver_receipt_binding')),
    _verifier_capability('unified_release_program_continuity_acceptance', acceptance_verifier, 'verify_unified_release_program_continuity_acceptance_package', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_ACCEPTANCE_ARCHIVE_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_ACCEPTANCE_VERIFICATION_PACKAGE_TYPE', 'urpca_kernel', 'FIXED_ARCHIVE_ENTRIES', allowed_entry_patterns=('responses/[A-Za-z0-9_.-]+\\.json', 'responses/[A-Za-z0-9_.-]+-(?:binding-summary|verification-report)\\.json', 'accepted-evidence/[A-Za-z0-9_.-]+/(?:accepted-evidence|evidence-report|original-response-public|response-binding-summary|response-verification-summary)\\.json'), required_proofs=('continuity_kit_path', 'continuity_kit_verification_report_path', 'signoff_binding_path'), lifecycle_bindings=('current_kit', 'external_response_proofs', 'signoff_binding')),
    _verifier_capability('unified_release_program_continuity_acceptance_change', acceptance_change_verifier, 'verify_unified_release_program_continuity_acceptance_change_package', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_ACCEPTANCE_CHANGE_ARCHIVE_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_ACCEPTANCE_CHANGE_VERIFICATION_PACKAGE_TYPE', 'urpca_cc_kernel', 'FIXED_ARCHIVE_ENTRIES', allowed_entry_patterns=('cr/[A-Za-z0-9_.-]+/(?:request|binding|approval)\\.json', 'rp/[A-Za-z0-9_.-]+/(?:proof|binding)\\.json', 'gen/g[0-9]{6}/(?:verification|signoff-binding|source)\\.json'), required_proofs=('acceptance_archive_path', 'acceptance_verification_report_path', 'acceptance_signoff_binding_path'), lifecycle_bindings=('current_acceptance', 'change_request', 'reset_proof', 'generation_chain')),
    _verifier_capability('unified_release_program_continuity_command_center', command_center_verifier, 'verify_unified_release_program_continuity_command_center_package', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_COMMAND_CENTER_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_COMMAND_CENTER_VERIFICATION_PACKAGE_TYPE', 'urpccc_kernel', 'REQUIRED_ENTRIES', required_proofs=('evidence_manifest_path',), lifecycle_bindings=('runtime_evidence_manifest', 'current_generation')),
    _verifier_capability('unified_release_program_continuity_command_center_signoff', command_signoff_verifier, 'verify_unified_release_program_continuity_command_center_signoff_package', 'COMMAND_CENTER_SIGNOFF_ARCHIVE_PACKAGE_TYPE', 'COMMAND_CENTER_SIGNOFF_ARCHIVE_VERIFICATION_PACKAGE_TYPE', 'urpcccs_kernel', 'ARCHIVE_REQUIRED_ENTRIES', required_proofs=('signoff_binding_path', 'command_center_zip_path', 'command_center_verification_report_path', 'command_center_external_evidence_manifest_path'), lifecycle_bindings=('current_command_center', 'signoff_binding', 'history_chain', 'change_request')),
    _verifier_capability('unified_release_program_receiver_acceptance', receiver_verifier, 'verify_unified_release_program_continuity_command_center_acceptance_package', 'ARCHIVE_PACKAGE_TYPE', 'ARCHIVE_VERIFICATION_PACKAGE_TYPE', 'urpccca_kernel', 'ARCHIVE_ENTRIES', required_proofs=('signoff_binding_path', 'review_pack_path', 'review_pack_verification_report_path'), lifecycle_bindings=('current_handoff', 'external_response_proofs', 'signoff_binding', 'history_chain')),
    _verifier_capability('unified_release_program_receiver_acceptance_change', receiver_change_verifier, 'verify_unified_release_program_continuity_command_center_acceptance_change_package', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_COMMAND_CENTER_ACCEPTANCE_CHANGE_ARCHIVE_PACKAGE_TYPE', 'UNIFIED_RELEASE_PROGRAM_CONTINUITY_COMMAND_CENTER_ACCEPTANCE_CHANGE_VERIFICATION_PACKAGE_TYPE', 'urpcccacc_kernel', 'FIXED_ARCHIVE_ENTRIES', allowed_entry_patterns=('cr/[A-Za-z0-9_.-]+/(?:request|binding|approval)\\.json', 'rp/[A-Za-z0-9_.-]+/(?:proof|binding)\\.json', 'gen/g[0-9]{6}/(?:verification|signoff-binding|source)\\.json'), required_proofs=('acceptance_archive_path', 'acceptance_verification_report_path', 'acceptance_signoff_binding_path', 'previous_acceptance_root'), lifecycle_bindings=('current_acceptance', 'previous_acceptance_root', 'change_request', 'reset_proof', 'generation_chain')),
)
active_verifier_registry = VerifierCapabilityRegistry(ACTIVE_VERIFIER_CAPABILITIES)
__all__ = ['ACTIVE_VERIFIER_CAPABILITIES', 'active_verifier_registry']
