from __future__ import annotations
from song_agent.interfaces.cli.registry import CommandSpec
from song_agent.interfaces.cli.commands.quality_parts.acceptance_fix_plan import _run_audio_lab_command, build_acceptance_fix_plan_parser, build_acceptance_kb_parser, build_planning_rule_governance_parser, build_planning_rule_impact_parser, build_planning_ruleset_parser, build_planning_simulation_parser
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint import build_audio_campaign_parser, build_audio_fix_sprint_parser, build_release_audio_certification_parser, build_verify_audio_campaign_archive_parser, build_verify_audio_campaign_parser, build_verify_audio_campaign_remediation_parser
from song_agent.interfaces.cli.commands.quality_parts.audio_fix_sprint_command import _run_audio_campaign_command, _run_audio_fix_sprint_command, _run_release_audio_certification_command, _run_release_audio_timeline_command
from song_agent.interfaces.cli.commands.quality_parts.audio_lab_parser_and_adapters import build_audio_lab_parser
from song_agent.interfaces.cli.commands.quality_parts.planning_rule_governance import handle_acceptance_kb, handle_planning_rule_governance, handle_planning_rule_impact
from song_agent.interfaces.cli.commands.quality_parts.planning_ruleset import _acceptance_analytics_fail_on, handle_audio_campaign, handle_audio_fix_sprint, handle_audio_lab, handle_release_audio_baseline, handle_release_audio_certification, handle_release_audio_command_center, handle_release_audio_quality_actions, handle_release_audio_quality_observatory, handle_release_audio_regression, handle_release_audio_regression_response, handle_release_audio_timeline, handle_verify_release_audio_baseline_registry_package, handle_verify_release_audio_regression_response_package, print_acceptance_kb_result, print_planning_rule_governance_result, print_planning_rule_impact_result, print_planning_ruleset_result, print_planning_simulation_result
from song_agent.interfaces.cli.commands.quality_parts.release_audio_command_center_command import _command_center_acceptance_payload, _print_audio_campaign_result, _print_audio_fix_sprint_result, _print_audio_lab_result, _print_release_audio_certification_result, _run_release_audio_command_center_command, print_acceptance_analytics_report, print_acceptance_check_report, print_acceptance_diff_report, print_acceptance_fix_plan_result, print_acceptance_fix_sprint_result, print_release_audio_review_result, run_acceptance_check
from song_agent.interfaces.cli.commands.quality_parts.release_audio_quality_actions import _add_command_center_acceptance_source_args, _add_release_audio_command_center_evidence_args, build_acceptance_analytics_parser, build_acceptance_check_parser, build_acceptance_diff_parser, build_acceptance_fix_sprint_parser, build_audio_health_parser, build_audio_profile_parser, build_encoded_audio_acceptance_parser, build_format_decision_parser, build_release_audio_command_center_parser, build_release_audio_quality_actions_parser, build_release_audio_review_parser, build_verify_release_audio_command_center_parser, build_verify_release_audio_quality_action_queue_parser, build_verify_release_audio_quality_action_queue_signoff_archive_parser
from song_agent.interfaces.cli.commands.quality_parts.release_audio_regression_command import _release_audio_command_center_evidence_from_args, _run_release_audio_baseline_command, _run_release_audio_quality_actions_command, _run_release_audio_quality_observatory_command, _run_release_audio_regression_command, _run_release_audio_regression_response_command
from song_agent.interfaces.cli.commands.quality_parts.release_audio_review import handle_acceptance_analytics, handle_acceptance_diff, handle_acceptance_fix_plan, handle_acceptance_fix_sprint, handle_encoded_audio_acceptance, handle_format_decision, handle_planning_ruleset, handle_planning_simulation, handle_release_audio_review
from song_agent.interfaces.cli.commands.quality_parts.verify_audio_campaign import handle_acceptance_check, handle_audio_health, handle_audio_profile, handle_verify_audio_campaign_archive_package, handle_verify_audio_campaign_package, handle_verify_audio_campaign_remediation_package, handle_verify_release_audio_certification_package, handle_verify_release_audio_regression_package, handle_verify_release_audio_timeline_package
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_certification import _add_release_audio_baseline_external_args, _add_release_audio_regression_external_args, build_release_audio_baseline_parser, build_release_audio_quality_observatory_parser, build_release_audio_regression_parser, build_release_audio_regression_response_parser, build_release_audio_timeline_parser, build_verify_release_audio_baseline_registry_parser, build_verify_release_audio_certification_parser, build_verify_release_audio_quality_observatory_parser, build_verify_release_audio_regression_parser, build_verify_release_audio_regression_response_parser, build_verify_release_audio_timeline_parser
from song_agent.interfaces.cli.commands.quality_parts.verify_release_audio_quality_observatory import handle_verify_release_audio_command_center_package, handle_verify_release_audio_quality_action_queue_package, handle_verify_release_audio_quality_action_queue_signoff_archive_package, handle_verify_release_audio_quality_observatory_package, handle_verify_unified_command_center_evidence_review_acceptance_package, handle_verify_unified_release_program_continuity_acceptance_change_package, handle_verify_unified_release_program_continuity_acceptance_package, handle_verify_unified_release_program_continuity_command_center_acceptance_change_package, handle_verify_unified_release_program_continuity_command_center_acceptance_package

__all__ = [ 'SPECS', '_acceptance_analytics_fail_on', '_add_command_center_acceptance_source_args', '_add_release_audio_baseline_external_args', '_add_release_audio_command_center_evidence_args', '_add_release_audio_regression_external_args', '_command_center_acceptance_payload', '_print_audio_campaign_result', '_print_audio_fix_sprint_result', '_print_audio_lab_result', '_print_release_audio_certification_result', '_release_audio_command_center_evidence_from_args', '_run_audio_campaign_command', '_run_audio_fix_sprint_command', '_run_audio_lab_command', '_run_release_audio_baseline_command', '_run_release_audio_certification_command', '_run_release_audio_command_center_command', '_run_release_audio_quality_actions_command', '_run_release_audio_quality_observatory_command', '_run_release_audio_regression_command', '_run_release_audio_regression_response_command', '_run_release_audio_timeline_command', 'build_acceptance_analytics_parser', 'build_acceptance_check_parser', 'build_acceptance_diff_parser', 'build_acceptance_fix_plan_parser', 'build_acceptance_fix_sprint_parser', 'build_acceptance_kb_parser', 'build_audio_campaign_parser', 'build_audio_fix_sprint_parser', 'build_audio_health_parser', 'build_audio_lab_parser', 'build_audio_profile_parser', 'build_encoded_audio_acceptance_parser', 'build_format_decision_parser', 'build_planning_rule_governance_parser', 'build_planning_rule_impact_parser', 'build_planning_ruleset_parser', 'build_planning_simulation_parser', 'build_release_audio_baseline_parser', 'build_release_audio_certification_parser', 'build_release_audio_command_center_parser', 'build_release_audio_quality_actions_parser', 'build_release_audio_quality_observatory_parser', 'build_release_audio_regression_parser', 'build_release_audio_regression_response_parser', 'build_release_audio_review_parser', 'build_release_audio_timeline_parser', 'build_verify_audio_campaign_archive_parser', 'build_verify_audio_campaign_parser', 'build_verify_audio_campaign_remediation_parser', 'build_verify_release_audio_baseline_registry_parser', 'build_verify_release_audio_certification_parser', 'build_verify_release_audio_command_center_parser', 'build_verify_release_audio_quality_action_queue_parser', 'build_verify_release_audio_quality_action_queue_signoff_archive_parser', 'build_verify_release_audio_quality_observatory_parser', 'build_verify_release_audio_regression_parser', 'build_verify_release_audio_regression_response_parser', 'build_verify_release_audio_timeline_parser', 'print_acceptance_analytics_report', 'print_acceptance_check_report', 'print_acceptance_diff_report', 'print_acceptance_fix_plan_result', 'print_acceptance_fix_sprint_result', 'print_acceptance_kb_result', 'print_planning_rule_governance_result', 'print_planning_rule_impact_result', 'print_planning_ruleset_result', 'print_planning_simulation_result', 'print_release_audio_review_result', 'run_acceptance_check', ]

SPECS = (
    CommandSpec(name='audio-lab', parser=build_acceptance_analytics_parser, handler=handle_audio_lab, help='Audio Lab', group='quality'),
    CommandSpec(name='audio-fix-sprint', parser=build_acceptance_analytics_parser, handler=handle_audio_fix_sprint, help='Audio Fix Sprint', group='quality'),
    CommandSpec(name='audio-campaign', parser=build_acceptance_analytics_parser, handler=handle_audio_campaign, help='Audio Campaign', group='quality'),
    CommandSpec(name='release-audio-certification', parser=build_acceptance_analytics_parser, handler=handle_release_audio_certification, help='Release Audio Certification', group='quality'),
    CommandSpec(name='release-audio-timeline', parser=build_acceptance_analytics_parser, handler=handle_release_audio_timeline, help='Release Audio Timeline', group='quality'),
    CommandSpec(name='release-audio-regression', parser=build_acceptance_analytics_parser, handler=handle_release_audio_regression, help='Release Audio Regression', group='quality'),
    CommandSpec(name='release-audio-baseline', parser=build_acceptance_analytics_parser, handler=handle_release_audio_baseline, help='Release Audio Baseline', group='quality'),
    CommandSpec(name='release-audio-regression-response', parser=build_acceptance_analytics_parser, handler=handle_release_audio_regression_response, help='Release Audio Regression Response', group='quality'),
    CommandSpec(name='release-audio-quality-observatory', parser=build_acceptance_analytics_parser, handler=handle_release_audio_quality_observatory, help='Release Audio Quality Observatory', group='quality'),
    CommandSpec(name='release-audio-quality-actions', parser=build_acceptance_analytics_parser, handler=handle_release_audio_quality_actions, help='Release Audio Quality Actions', group='quality'),
    CommandSpec(name='release-audio-command-center', parser=build_acceptance_analytics_parser, handler=handle_release_audio_command_center, help='Release Audio Command Center', group='quality'),
    CommandSpec(name='verify-release-audio-baseline-registry-package', parser=build_acceptance_analytics_parser, handler=handle_verify_release_audio_baseline_registry_package, help='Verify Release Audio Baseline Registry Package', group='quality'),
    CommandSpec(name='verify-release-audio-regression-response-package', parser=build_acceptance_analytics_parser, handler=handle_verify_release_audio_regression_response_package, help='Verify Release Audio Regression Response Package', group='quality'),
    CommandSpec(name='verify-release-audio-quality-observatory-package', parser=build_acceptance_analytics_parser, handler=handle_verify_release_audio_quality_observatory_package, help='Verify Release Audio Quality Observatory Package', group='quality'),
    CommandSpec(name='verify-release-audio-quality-action-queue-package', parser=build_acceptance_analytics_parser, handler=handle_verify_release_audio_quality_action_queue_package, help='Verify Release Audio Quality Action Queue Package', group='quality'),
    CommandSpec(name='verify-release-audio-quality-action-queue-signoff-archive-package', parser=build_acceptance_analytics_parser, handler=handle_verify_release_audio_quality_action_queue_signoff_archive_package, help='Verify Release Audio Quality Action Queue Signoff Archive Package', group='quality'),
    CommandSpec(name='verify-release-audio-command-center-package', parser=build_acceptance_analytics_parser, handler=handle_verify_release_audio_command_center_package, help='Verify Release Audio Command Center Package', group='quality'),
    CommandSpec(name='verify-unified-command-center-evidence-review-acceptance-package', parser=build_acceptance_analytics_parser, handler=handle_verify_unified_command_center_evidence_review_acceptance_package, help='Verify Unified Command Center Evidence Review Acceptance Package', group='quality'),
    CommandSpec(name='verify-unified-release-program-continuity-acceptance-package', parser=build_acceptance_analytics_parser, handler=handle_verify_unified_release_program_continuity_acceptance_package, help='Verify Unified Release Program Continuity Acceptance Package', group='quality'),
    CommandSpec(name='verify-unified-release-program-continuity-acceptance-change-package', parser=build_acceptance_analytics_parser, handler=handle_verify_unified_release_program_continuity_acceptance_change_package, help='Verify Unified Release Program Continuity Acceptance Change Package', group='quality'),
    CommandSpec(name='verify-unified-release-program-continuity-command-center-acceptance-package', parser=build_acceptance_analytics_parser, handler=handle_verify_unified_release_program_continuity_command_center_acceptance_package, help='Verify Unified Release Program Continuity Command Center Acceptance Package', group='quality'),
    CommandSpec(name='verify-unified-release-program-continuity-command-center-acceptance-change-package', parser=build_acceptance_analytics_parser, handler=handle_verify_unified_release_program_continuity_command_center_acceptance_change_package, help='Verify Unified Release Program Continuity Command Center Acceptance Change Package', group='quality'),
    CommandSpec(name='verify-audio-campaign-package', parser=build_acceptance_analytics_parser, handler=handle_verify_audio_campaign_package, help='Verify Audio Campaign Package', group='quality'),
    CommandSpec(name='verify-audio-campaign-archive-package', parser=build_acceptance_analytics_parser, handler=handle_verify_audio_campaign_archive_package, help='Verify Audio Campaign Archive Package', group='quality'),
    CommandSpec(name='verify-audio-campaign-remediation-package', parser=build_acceptance_analytics_parser, handler=handle_verify_audio_campaign_remediation_package, help='Verify Audio Campaign Remediation Package', group='quality'),
    CommandSpec(name='verify-release-audio-certification-package', parser=build_acceptance_analytics_parser, handler=handle_verify_release_audio_certification_package, help='Verify Release Audio Certification Package', group='quality'),
    CommandSpec(name='verify-release-audio-timeline-package', parser=build_acceptance_analytics_parser, handler=handle_verify_release_audio_timeline_package, help='Verify Release Audio Timeline Package', group='quality'),
    CommandSpec(name='verify-release-audio-regression-package', parser=build_acceptance_analytics_parser, handler=handle_verify_release_audio_regression_package, help='Verify Release Audio Regression Package', group='quality'),
    CommandSpec(name='acceptance-check', parser=build_acceptance_analytics_parser, handler=handle_acceptance_check, help='Acceptance Check', group='quality'),
    CommandSpec(name='audio-health', parser=build_acceptance_analytics_parser, handler=handle_audio_health, help='Audio Health', group='quality'),
    CommandSpec(name='audio-profile', parser=build_acceptance_analytics_parser, handler=handle_audio_profile, help='Audio Profile', group='quality'),
    CommandSpec(name='release-audio-review', parser=build_acceptance_analytics_parser, handler=handle_release_audio_review, help='Release Audio Review', group='quality'),
    CommandSpec(name='encoded-audio-acceptance', parser=build_acceptance_analytics_parser, handler=handle_encoded_audio_acceptance, help='Encoded Audio Acceptance', group='quality'),
    CommandSpec(name='format-decision', parser=build_acceptance_analytics_parser, handler=handle_format_decision, help='Format Decision', group='quality'),
    CommandSpec(name='acceptance-diff', parser=build_acceptance_analytics_parser, handler=handle_acceptance_diff, help='Acceptance Diff', group='quality'),
    CommandSpec(name='acceptance-analytics', parser=build_acceptance_analytics_parser, handler=handle_acceptance_analytics, help='Acceptance Analytics', group='quality'),
    CommandSpec(name='acceptance-fix-sprint', parser=build_acceptance_fix_plan_parser, handler=handle_acceptance_fix_sprint, help='Acceptance Fix Sprint', group='quality'),
    CommandSpec(name='acceptance-fix-plan', parser=build_acceptance_fix_plan_parser, handler=handle_acceptance_fix_plan, help='Acceptance Fix Plan', group='quality'),
    CommandSpec(name='planning-ruleset', parser=build_acceptance_kb_parser, handler=handle_planning_ruleset, help='Planning Ruleset', group='quality'),
    CommandSpec(name='planning-simulation', parser=build_acceptance_kb_parser, handler=handle_planning_simulation, help='Planning Simulation', group='quality'),
    CommandSpec(name='planning-rule-governance', parser=build_acceptance_kb_parser, handler=handle_planning_rule_governance, help='Planning Rule Governance', group='quality'),
    CommandSpec(name='planning-rule-impact', parser=build_acceptance_kb_parser, handler=handle_planning_rule_impact, help='Planning Rule Impact', group='quality'),
    CommandSpec(name='acceptance-kb', parser=build_acceptance_kb_parser, handler=handle_acceptance_kb, help='Acceptance Kb', group='quality'),
)
